### ISSUE TITLE
Facebook oauth

### ISSUE THREAD

**Issue by Reminouche** [Azure/azure-mobile-apps-net-client#102]
Facebook policies (https://developers.facebook.com/docs/facebook-login/checklist) clearly states that native iOS and Android apps are REQUIRED to use the native SDK for login.

Azure mobile app xamarin client uses Xamarin.auth and it's not accepted by fb (app review).

> Mobile Apps
---
Mobile apps (iOS, Android, and Windows) must use the latest Facebook SDK. Mobile apps developed with Unity should upload a dummy build and include a screencast of the integration.

**Comment by mattchenderson** [comment]
Correct. The guidance should be to use the Facebook SDK where possible, and we do support flows using the Facebook SDK. The documentation here is lacking, though. I'll track that elsewhere, as I don't believe there is any action required for the client SDK.
