### ISSUE TITLE
Allow specification of TableName in strongly-typed GetTable calls

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-mobile-apps-net-client#105]
Right now there's no way to override the values specified on the type that is used by GetTable<>. In order to allow us to specify a table name that did not derive from the type name, we had to do some nasty private reflection in our WebJob extension: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/93b9e96f8a9617034471ca461abb5214eae9cda2/src/WebJobs.Extensions.EasyTables/Extensions/IMobileServiceClientExtensions.cs#L21

**Comment by lindydonna** [comment]
@brettsam Isn't there a [TableName] attribute for the data class?

**Comment by elamalani** [comment]
@brettsam Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us to prioritize this work in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
