### ISSUE TITLE
Offer sync calls to SyncTables instead of async only

### ISSUE THREAD

**Issue by isamllr** [Azure/azure-mobile-apps-net-client#108]
I know that there are probably design decisions behind this, but it would make ones life easier when integrating Mobile Apps in older applications.

**Comment by fabiocav** [comment]
@isamllr , thank you for the suggestion! We will not consider adding synchronous API alternatives as using them would negatively impact the types of applications the SDK is designed for and their use would often mask a design issue that, if corrected, would allow you to work with the async APIs the SDK currently exposes. 
I'll be closing this issue, but if you'd like us to look at additional aspects to support your request, please feel free to reopen it, providing examples and additional information as to why you believe this is needed.
