### ISSUE TITLE
Filtering by UTC DateTimeOffset causing issues in SyncTable 

### ISSUE THREAD

**Issue by dillondrobena** [Azure/azure-mobile-apps-net-client#117]
For brevity please refer to this [discussion](http://stackoverflow.com/questions/36440150/difference-between-these-2-linq-queries-using-azure-mobile-client)

Essentially a simple conditional filter on a query doesn't seem to be working at all. If I have this particular query
 `allMessages = await
                        MobileServiceInstance.GetSyncTable<Messages>()
                            .OrderByDescending(key => key.SentDate)
                            .Take(50)
                            .ToListAsync();`

I should expect the last 50 messages in the SyncTable. Now if I take the result of this query and want to get all the items whos `SentDate` property is less than a particular item's `SentDate` I should be able to do this 
`filteredMessages = await
                        MobileServiceInstance.GetSyncTable<Messages>()
                            .OrderByDescending(key => key.SentDate)
                            .Take(50)
                            .Where(p => p.SentDate < allMessages[24].SentDate)
                            .ToListAsync();`

Note that the `SentDate` property is a `DateTimeOffset` datatype. The above variable should be a list of 25 items. However the result is 0 when I run it.

You can reference the stackoverflow discussion for all the tests we performed, but I'm starting to come to the conclusion that it is a bug.

**Comment by ltaljaard** [comment]
I think I had a similar issue before and I ended up switching over from DateTimeOffset to DateTime in my client side models. This may be a bug that needs to be fixed, but maybe you can get by using DateTime in the mean time.

**Comment by elamalani** [comment]
@dillondrobena Thanks for using Azure Mobile Apps. Since this issue is over 2 years old, I'll close it for now but feel free to ask us questions if you have any. Also, please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps).
