### ISSUE TITLE
Xamarin.Auth is not working under Android anymore

### ISSUE THREAD

**Issue by ltaljaard** [Azure/azure-mobile-apps-net-client#119]
I'm aware that this is not strictly a bug in the Azure Mobile Apps client but the bottom line is that many (if not most) developers targeting Azure Mobile are using Xamarin.Auth to handle the login from a Xamarin app. So I believe this must be impacting a large user base. That's where one gets your Zumo token from to use with the Azure Mobile client after all. Logging in involves a custom page renderer for iOS and Android respectively. The Xamarin.Auth code that is called from the Android custom page renderer is no longer working and it seems that the Xamarin.Auth solution has been stagnant for a long time and nobody is responding to the developers' queries over there. Could you kindly escalate this to the relevant authority to get things going on the Xamarin.Auth side of things again please?

The latest update on the Xamarin.Auth component ( https://components.xamarin.com/view/xamarin.auth ) was 12 Jan 2015. And similarly the last update to the master branch on github ( https://github.com/xamarin/Xamarin.Auth ) was a year ago as well. there are very few responses to the developers' issues that they log over there as well.

I have described the Android issue in detail on the project's github page here: https://github.com/xamarin/Xamarin.Auth/issues/109

**Comment by ltaljaard** [comment]
Update: This bug is not restricted to Xamarin.Auth. It also affects the LogicAsync() method within Azure Mobile Apps. But it only occurs when you upgrade your Xamarin.Forms version from the current stable version 2.1.0.6529 to the pre-release version  2.2.0.5-pre2. nd it only occurs under Android. More info here: https://github.com/xamarin/Xamarin.Auth/issues/109

**Comment by jamesmontemagno** [comment]
I would recommend taking a look at how I do it in my CoffeeCups app: https://github.com/jamesmontemagno/app-coffeecups

Specifically https://github.com/jamesmontemagno/app-coffeecups/blob/master/Droid/Helpers/Authentication.cs

This method does not require a page renderer and works pretty great for me.

**Comment by ltaljaard** [comment]
Thanks @jamesmontemagno that is exactly what I'm changing my app to now - based on the guidelines specified here: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-users/

But please note that the Xamarin.Forms pre-release bug (version 2.2.0.5-pre2) occurs even with this new approach. At the moment I've had to switch back to version 2.1.0.6529 just so that I can carry on. Someone should still fix this "blank screen" bug in the pre-release version.

PS: I know this is not the best forum for a question but I'm completely stuck now with this new approach so hoping you can shed some light on it: the initial LoginAsync() that gets called from the Authenticate method in MainActivity.cs (from the Droid project) - i.e. the LoginAsync() that is platform-specific and shows the login screen - works like a charm. BUT then later on, let's say when the user comes back to the app later, I'm trying to do a LoginAsync() from the Shared code i.e. the non-platform-specific version of LoginAsync() which doesn't have a UI and therefore needs a Zumo token to be passed to it - the one which is defined as "LoginAsync(MobileServiceAuthenticationProvider provider, JObject token)" in MobileServiceClient.cs.
I'm passing in MobileServiceAuthenticationProvider.Facebook as the provider and a JObject that looks like this as the token: {{"access_token":"&lt;e00454AiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdGFibGVfc2lkIjoic2lkOmYxODBiMjdkYzllNTg0ODkyN2JmMTI4YzAxYjJiNTk0Iiwic3ViIjoic2lkOjJiNzhlYjU3YzkyZjdjYWRiYTI1MjMxNDE3MzEyZWY0IiwiaWRwIjoiZmFjZWJre2siLCJ2ZXIiOiIzIiwiaXNzIjoiaHR0cHM6Ly9pbWF2YWlsLmF6dXJld2Vic2l0ZXMubmV0LyIsImF1ZCI6Imh0dOQzOi8vaW1hdmFpbC5henVyZXdlYnNpdGVzLm5ldC8iLCJleHAiOjE0NjYzNjc1NTEsIm5iZiI5MTQ2MTE5MDQ5N30.HL4VCGca4HClNmUWJ8idHjaG_ngi5yG740k31xDnDWt&gt;"}}
But the call to the shared project version of LoginAsync() fails with a 401: Unauthorized. I've tried passing the zumo token with and without the surrounding &lt; and &gt; tags which is mentioned in the comments above the method in MobileServiceClient.cs but to no avail. I can't see why the Unauthorized would occur and can't find any help on how to fix this on google either. Any ideas on this one?

**Comment by jamesmontemagno** [comment]
I'll try to update my app and see what happens and talk to the team about
it as there is now a pre3 out.

**Comment by ltaljaard** [comment]
@jamesmontemagno the newly released pre4 version seems to have fixed it.
