### ISSUE TITLE
Push: NH Templates

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-apps-net-client#12]
Review whether to make a better first class API for generating a Installation template when using the NH register methods (https://msdn.microsoft.com/en-us/library/azure/mt621153.aspx)

**Comment by phvannor** [comment]
iOS: https://github.com/Azure/azure-mobile-apps-ios-client/issues/9
.Net: https://github.com/Azure/azure-mobile-apps-net-client/issues/12
JS: https://github.com/Azure/azure-mobile-apps-js-client/issues/22
Android: <pending seperate repo>

**Comment by adrianhall** [comment]
Dup of #247
