### ISSUE TITLE
Add the Authentication provider token to the return value of the LoginAsync() method for retrieving additional user information

### ISSUE THREAD

**Issue by ltaljaard** [Azure/azure-mobile-apps-net-client#123]
At the moment the "official way" to retrieve additional user info like the user's email address/name/etc from the authentication provider (Facebook/Google/etc) seems to be to create a custom backend API that should be called directly after LoginAsync() was called from the client. This is because the auth provider's token is only available on the server-side. an example of such an implementation can be found here: https://azure.microsoft.com/en-us/blog/custom-login-scopes-single-sign-on-new-asp-net-web-api-updates-to-the-azure-mobile-services-net-backend/

This seems wasteful. If the authentication provider's token can simply be returned from LoginAsync() then the client can request the info that it required directly from the authentication provider instead of having to request it through the Azure "middle-man" custom API.

Kindly look into adding something along these lines to LoginAsync().

**Comment by eestein** [comment]
+1 This is really needed!

**Comment by geraldons** [comment]
Extremamente necessário. Inacreditável que até hoje não fizeram.

**Comment by aline-almeida** [comment]
Have you tried invoking the built-in endpoint "/.auth/me" ? 
I'm using it with AD.

**Comment by adrianhall** [comment]
Agreed - adding extra claims to the token is not required as the information is in the /.auth/me endpoint.  We have open tasks for creating an API for easily accessing the claims.
