### ISSUE TITLE
MobileServiceClient does not contain a definition for 'GetPush'

### ISSUE THREAD

**Issue by JohannTIM** [Azure/azure-mobile-apps-net-client#128]
I have Wp8.1 Silverlight app that works with WNS on the old MobileService.

I have now upgraded the server to App Service - Mobile App.

Adding this new package through NuGet (2.0.1), there is the issue that the Microsoft.WindowsAzure.Mobile.Ext does not contain the 'GetPush' extension. It seems like it is missing, looking to WP8, it only registers to MPNS ? 

Could you elaborate about this subject?

**Comment by pragnagopa** [comment]
We did not add support for WNS push in Windows Phone 8.1 Silverlight apps.

**Comment by JohannTIM** [comment]
Why not? Silverlight wp8.1 supports wns. So why not? Especially now that mobileservices will be discontinued. Is this something that will come, because people now with older apps also will move to app service?

**Comment by lindydonna** [comment]
@JohannTIM If you migrate your service from Mobile Services to Mobile Apps, you don't need to change your client SDK. In fact, you shouldn't, unless you upgrade your server code as well. See https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-migrating-from-mobile-services/#what-does-migration-do.

**Comment by JohannTIM** [comment]
You are of course right but there are quite some benefits by having the updated server (which I hvad done). But the issue is the push notification http://stackoverflow.com/questions/37011339/notificationhub-push-notification-returns-the-token-obtained-from-the-token-pr which is why I also have tried on stackpverflow.

**Comment by pragnagopa** [comment]
Azure NotificationHubs does not support WNS on Phone 8.1 Silverlight apps. Please see: https://github.com/Azure/azure-notificationhubs-samples/tree/master/PushToSLPhoneApp for a workaround

**Comment by JohannTIM** [comment]
But that is incorrect I have done it. Many people has done it https://www.bing.com/search?q=wp81+silverlight+wns+support&FORM=EDGENA

Even here on msdn where the upgrade information from wp8 to wp8.1 silverlight https://msdn.microsoft.com/en-us/library/windows/apps/dn642081(v=vs.105).aspx states you can choose.

The code I show in the stackoverflow question retrieves a channeluri for wns, and on the server it can register for wns. Please see the link before. 

So I should interpreted it as: We will not do it? Because it is certainly possible?

**Comment by JohannTIM** [comment]
Also the link you provided, with the registration done using the hub, it automatically assumes the registration should be mpns, that is why I needed to do it on the server. But I still do not understand why this function is not available.

**Comment by adrianhall** [comment]
The GetPush() method is a wrapper around the Notification Hubs SDK, so support for it is tied to the Notification Hubs support matrix.  If NH does not support a platform, then - just by that virtue - neither does Azure Mobile Apps.  You can find the NH support matrix here: https://azure.microsoft.com/en-us/documentation/articles/notification-hubs-faq/#design-amp-development
