### ISSUE TITLE
Two or more UWP Apps using one Mobile App Easy Table with authentication

### ISSUE THREAD

**Issue by WinInsider** [Azure/azure-mobile-apps-net-client#129]
**Scenario**: Two UWP apps to share data stored in one table in Azure SQL via Mobile Apps Easy Tables with authentication

**Problem**: User_ID/ID/SID for same Microsoft Account is different among Azure Mobile Apps; which prevents user from sharing data between two apps.  Seems like a key scenario.  Below are my steps; perhaps I got it wrong.

**Setup**:
- Two UWP apps (already associated with two App Store names) 
- Using SSO via OnlineIdAuthenticator class (JWT)... gets Access_Token; then calls mobileService.LoginWithMicrosoftAccountAsync(access_token) to get UserID and AuthenticationToken
- Two Client IDs (from My applications ... account.live.com) 
- pointing to two Azure Mobile Apps (in order Target Domain and Redirect URL to be correctly configured)
- One Azure database/table
- Azure Mobile App **A** setup to use UWP Client ID **A**; Azure Mobile App **B** setup to use UWP Client ID **B**; both with Microsoft Account for authentication
- both Azure Mobile Apps "Easy Tables" configured for authenticated access

Mike

**Comment by adrianhall** [comment]
You are getting it wrong.  The SID for each user will be different when the client ID is different.  Use one mobile app with one client ID / secret for both apps.

**Comment by WinInsider** [comment]
@adrianhall need bit more clarification... my understanding is that each Windows Store App gets its own (unique) Client ID... then Windows Store App gets connected to Azure Mobile App via apps.dev.microsoft.com... and it enforces policy were ...

1 UWP app => 1 Client ID / secret => 1 Azure Mobile App (policy is enforced by unique "Target Domain" url on apps.dev.microsoft.com)

... "Target Domain" url is the value passed to MobileServiceClient constructor

**Comment by adrianhall** [comment]
Ah - I see where you are going.  You will need to use "something else" for the user ID in this case.  We normally use the SID (which comes across as the NameIdentifier) - you could use email address, for example, or something else common to the API.  Once you have one app logged in, check in /.auth/me for the claims - you can use anything in there.
