### ISSUE TITLE
401 (Unauthorized) even after successful login.

### ISSUE THREAD

**Issue by Bosch571** [Azure/azure-mobile-apps-net-client#130]
Hello,

I'm using custom authentication with facebook to let my users login to the app service. Unfortunately I'm getting the following error when calling "InvokeApiAsync"

```Microsoft.WindowsAzure.MobileServices.MobileServiceInvalidOperationException: The request could not be completed.  (Unauthorized)```

I;m using the following code that worked with the 1.x.x branch of the NuGet package
```C#
Newtonsoft.Json.Linq.JObject jToken = new Newtonsoft.Json.Linq.JObject();
jToken.Add("access_token", token);

var user = await mobileService.LoginAsync(MobileServiceAuthenticationProvider.Facebook, jToken);
                    
var result= await _mobileService.InvokeApiAsync<GetContactListRequest, GetContactListResponse>("GetContactList", new GetContactListRequest());
```

```C#
var user = await _mobileService.LoginAsync(MobileServiceAuthenticationProvider.Facebook, jToken);
```
Works and the user variable contains an user  with a token (_mobileService.CurrentUser does as well). It's when I call "InvokeApiAsync that i get the Unauthorized error.

The mobile service
```C#
 [Authorize]
    public class GetContactListController : ApiController
    {
        // POST api/CustomRegistration
        public HttpResponseMessage Post(GetContactListRequest request)
        {
            try
            {
                return this.Request.CreateResponse(HttpStatusCode.OK, new GetContactListResponse());
            }
            catch (Exception ex)
            {
                return this.Request.CreateResponse(HttpStatusCode.InternalServerError, ex.Message);
            }
        }    
    }
```

Any pointers?

**Comment by ltaljaard** [comment]
See https://azure.microsoft.com/en-us/documentation/learning-paths/appservice-mobileapps/ <https://azure.microsoft.com/en-us/documentation/learning-paths/appservice-mobileapps/> -> Monitor -> Enable diagnostic logging & Troubleshoot with Visual Studio. You can choose between switching on logging on the Azure side or remotely debug the Azure app or run the backend app locally while your’e developing/testing (the latter is not covered there but that’s my preference). In the last two options you can see what’s happening from the Output (Debug) window within Visual Studio. Put a breakpoint in your controller, if it is reached you can see what’s going on inside your controller and if it doesn’t get to the breakpoint it’s likely to do with the app config or the HTTP/s calls to your controller. Hope that helps.

**Comment by ltaljaard** [comment]
You may also need the [MobileAppController] tag above your class declaration and maybe also an [HttpPost] tag above your method declaration. And check your app config as per https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-how-to-use-server-sdk/

**Comment by lindydonna** [comment]
@Bosch571 We you haven't posted any updates, and it is very likely the issue was caused by not adding the `[MobileAppController]` attribute to your ApiController. If you have more issues, please post on the [MSDN Forums](http://social.msdn.microsoft.com/Forums/en-US/azuremobile/) or the StackOverflow tag [azure-mobile-services](http://stackoverflow.com/questions/tagged/azure-mobile-services), or post a reproducible bug as an issue.
