### ISSUE TITLE
DateTime handling in client sqlite

### ISSUE THREAD

**Issue by jmichas** [Azure/azure-mobile-apps-net-client#131]
Can someone confirm for me whether datetimes that are kind local are automatically converted to utc on insert to sqlite? It appears that the opposite is true as well and in my initial testing utc dates inserted via InsertAsync get converted to local.

I upgraded from the mobile services client and now my dates have gone all wonky. In mobile service client the utc dates came out of the local db as local datetimes but they were actually the utc values, so I changed the DateTime.Kind without changing the value so that using .ToLocal would work properly when displaying to the end users.

Before I go rework my code I want to make sure I understand how DateTime is treated.

Thanks.

**Comment by jmichas** [comment]
Ok, to follow up with what I was asking and maybe to partially answer my own question I ran this code on iOS in a Xam.Forms app:

```
 var testDates = new TestDatesModel
 {
	 Id = "1",
	 DateTimeUtc = DateTime.UtcNow,
	 DateTimeLocal = DateTime.Now
 };
 Debug.WriteLine("Saving Records====================");
 Debug.WriteLine("Before Being Saved::");
 Debug.WriteLine("UTC = " + testDates.DateTimeUtc + " : " + testDates.DateTimeUtc.Kind);
 Debug.WriteLine("Local = " + testDates.DateTimeLocal + " : " + testDates.DateTimeLocal.Kind);

 await App.Current.MobileServiceClient.GetSyncTable<TestDatesModel>().InsertAsync(testDates);

 Debug.WriteLine("After Being Saved::");
 Debug.WriteLine("UTC = " + testDates.DateTimeUtc + " : " + testDates.DateTimeUtc.Kind);
 Debug.WriteLine("Local = " + testDates.DateTimeLocal + " : " + testDates.DateTimeLocal.Kind);


 Debug.WriteLine("Retrieving Records===================");

var testDatesOut = await App.Current.MobileServiceClient.GetSyncTable<TestDatesModel>().Where(s=>s.Id == "1").ToListAsync();
var testDateOut = testDatesOut.First();

 Debug.WriteLine("UTC = " + testDateOut.DateTimeUtc + " : " + testDateOut.DateTimeUtc.Kind);
 Debug.WriteLine("Local = " + testDateOut.DateTimeLocal + " : " + testDateOut.DateTimeLocal.Kind);

 testDateOut.DateTimeUtc = testDateOut.DateTimeUtc.EnsureUniversal();

 Debug.WriteLine("Converted UTC Date From Local to UTC::");
 Debug.WriteLine("Converted UTC = " + testDateOut.DateTimeUtc + " : " + testDateOut.DateTimeUtc.Kind);

 await App.Current.MobileServiceClient.GetSyncTable<TestDatesModel>().UpdateAsync(testDateOut);

 Debug.WriteLine("After Being Updated in Db::");
 Debug.WriteLine("UTC = " + testDateOut.DateTimeUtc + " : " + testDateOut.DateTimeUtc.Kind);
 Debug.WriteLine("Local = " + testDateOut.DateTimeLocal + " : " + testDateOut.DateTimeLocal.Kind);

 testDatesOut = await App.Current.MobileServiceClient.GetSyncTable<TestDatesModel>().Where(s => s.Id == "1").ToListAsync();
 testDateOut = testDatesOut.First();

 Debug.WriteLine("After Being Updated in Db with converted UTC then Read Again::");
 Debug.WriteLine("UTC = " + testDateOut.DateTimeUtc + " : " + testDateOut.DateTimeUtc.Kind);
 Debug.WriteLine("Local = " + testDateOut.DateTimeLocal + " : " + testDateOut.DateTimeLocal.Kind);
```

Which yields this output:
```
[0:] Saving Records====================
[0:] Before Being Saved::
[0:] UTC = 5/8/2016 2:16:44 PM : Utc
[0:] Local = 5/8/2016 10:16:44 AM : Local
[0:] After Being Saved::
[0:] UTC = 5/8/2016 10:16:44 AM : Local
[0:] Local = 5/8/2016 10:16:44 AM : Local
[0:] Retrieving Records===================
[0:] UTC = 5/8/2016 10:16:44 AM : Local
[0:] Local = 5/8/2016 10:16:44 AM : Local
[0:] Converted UTC Date From Local to UTC::
[0:] Converted UTC = 5/8/2016 2:16:44 PM : Utc
[0:] After Being Updated in Db::
[0:] UTC = 5/8/2016 2:16:44 PM : Utc
[0:] Local = 5/8/2016 10:16:44 AM : Local
[0:] After Being Updated in Db with converted UTC then Read Again::
[0:] UTC = 5/8/2016 10:16:44 AM : Local
[0:] Local = 5/8/2016 10:16:44 AM : Local
```
You can see that when you Insert a record the UTC date is converted to a Local DateTime value, but when you Update the UTC date is not and gives you the same UTC value back.

Shouldn't this behavior be consistent?

**Comment by shrishrirang** [comment]
The problem here is the API semantics.

`MobileServiceSyncTable.InsertAsync()` inserts an item and returns the inserted value (the inserted value will have the ID property set to a GUID string if it was not set already). Note that the API will not modify the parameter passed to it.

However, `MobileServiceSyncTable<T>.InsertAsync()` inserts an item but does not return the inserted value. It instead modifies the item passed to it (parameter) to reflect the changes made to it while inserting.

As can be seen, the 2 `InsertAsync()` APIs above behave differently. Ideally, both variants of `InsertAsync()` should return the inserted value and leave the value passed to it as parameter untouched.

On the other hand, `UpdateAsync()` neither modifies the item passed to it nor does it return anything. This is as expected.

**Comment by duizer** [comment]
The DateTime handling also causes issues when saving a timestamp in the ambiguous hour when changing from daylight savings to standard time: http://stackoverflow.com/questions/39890764/azure-mobile-apps-saves-incorrect-datetime-in-sqlite-database

**Comment by jamesmontemagno** [comment]
If I look at how Frank does it in sqlite-net he does:
```
if (value is DateTime) {
					if (storeDateTimeAsTicks) {
						SQLite3.BindInt64 (stmt, index, ((DateTime)value).Ticks);
					}
					else {
						SQLite3.BindText (stmt, index, ((DateTime)value).ToString (DateTimeExactStoreFormat, System.Globalization.CultureInfo.InvariantCulture), -1, NegativePointer);
					}
```
Always good to store UTC :) and as ticks
