### ISSUE TITLE
MobileServiceClient.LoginAsync() call from PCL project fails for Google auth provider: "'authorization_code' field is required"

### ISSUE THREAD

**Issue by ltaljaard** [Azure/azure-mobile-apps-net-client#133]
This is a known issue as can bee seen in post https://disqus.com/home/discussion/thewindowsazureblog/expanding_app_service_authenticationauthorization/

Quoting Matt Henderson: "for Google, you actually need an authorization code and an ID token, both of which can be obtained using specific scopes (something like "audience:server:client_id:9414861317621.apps.g..." for ID token and "oauth2:server:client_id:9414861317621.apps.g...:api_scope:resource-1 resource-2" for authorization code). A Google access token isn't accepted for this flow right now. We're working on expanding the support and getting better documentation in place for this."

We have been following the "add authentication to your Xamarin.Forms app" tutorial when we came across this issue: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-users/

The article makes no mention of the additional "authorization_code" field that is required by the Google auth provider. Granted that this article only deals with the initial platform-specific UI-based version of LoginAsync(). But this is the beginning of the authentication flow that one gets "locked into" when you go down this path. Then, later, once you've received the auth token, stored it, and then want to use it to login again, you then need to call the PCL-based (non-UI) version of MobileServiceClient.LoginAsync(), using your stored token. It is at this point that it simply fails with the message "'authorization_code' field is required".

I have not come across any documentation that tells me how to get this working for Google from a Xamarin.Forms app, either as a temporary workaround or as the final solution.

Once the user has been authenticated we have created a server-side API to retrieve additional user information from the auth provider like email address etc - the API calls ((IPrincipal)ApiController.User).GetAppServiceIdentityAsync<GoogleCredentials>(). If it's possible to add code in our API to retrieve the "authorization_code" that could be a potential solution - please advise on the feasibility of this. The guidelines we followed to retrieve the additional info can be seen here: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-how-to-use-server-sdk/#user-info

Another issue similar to this one has been logged under the mobile apps server project but his has been closed (prematurely in my opinion) and the suggested resolution there did not address the issue above i.e. how to get this working from a Xamarin.Forms PCL project. Here's a link to that issue: https://github.com/Azure/azure-mobile-apps-net-server/issues/63

This seems like a big gap in the solution. Please advise on the timelines that you are looking at to provide proper support for the Google auth provider using the flow described in https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-users/

And if it's going to be a while please advise on a workaround in the mean time.

And lastly if you could kindly leave this issue open until it has been properly resolved and documented, for tracking purposes. Except if there is already an issue tracking this specific "authorization_code" problem for the non-UI version of LoginAsync(), but I have not seen one.

**Comment by adrianhall** [comment]
I'm closing this because you are mixing client-flow and server-flow logic.  If you want to use authorization_code, re-login, refresh, etc., then you need to move wholeheartedly to client-flow, where all this "works".  If you want to use "server-flow" (i.e. the UI version), then you will need to get your users to log in each and every time.
