### ISSUE TITLE
Allow specifying the $expand attribute on the client

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-net-client#141]
Avoids the hacky server-side approach such as https://github.com/paulbatum/FieldEngineerLite/blob/master/FieldEngineerLite.Service/Helpers/ExpandPropertyAttribute.cs

**Comment by elamalani** [comment]
Hi there, please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK. Thanks!
