### ISSUE TITLE
Detecting Changes on PullAsync request

### ISSUE THREAD

**Issue by jefftaynton** [Azure/azure-mobile-apps-net-client#144]
It would be nice to know when executing PullAsync if any new changes were downloaded or received  (and count) if there are specific events you want to fire off at that time but only if new changes were downloaded.

**Comment by lindydonna** [comment]
We already have this support, but it's not documented yet. There is an EventManager property on MobileServiceClient that lets you subscribe to events for changes on the local store. 

To set up: https://github.com/Azure-Samples/app-service-mobile-dotnet-todo-list-files/blob/master/src/client/MobileAppsFilesSample/TodoItemManager.cs#L42

Code that uses it: https://github.com/Azure-Samples/app-service-mobile-dotnet-todo-list-files/blob/master/src/client/MobileAppsFilesSample/ViewModels/TodoListViewModel.cs#L87

You can also use the event manager for your own events, as you subscribe to events using a type filter.
