### ISSUE TITLE
WP8.1 Silverlight Support

### ISSUE THREAD

**Issue by jieverson** [Azure/azure-mobile-apps-net-client#151]
I have an WP8.1 Silverlight App that I'm keeping support, and I would like to migrate to the new Azure App Service. I could not find an API (all the Nugget API seens to be for Universal Apps or Xamarin).
Will I have to use REST API or do you guys have any unreleased code for this?

**Comment by lindydonna** [comment]
I'm not sure why it's not working for you, it could be that one of dependencies doesn't work on WP8.1. We support the following portable profile: **portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10**

**Comment by lindydonna** [comment]
I realized I do still have Phone 8.1 tools installed on my machine, and I just tested that this works fine. I created a new Phone Silverlight 8.1 project in VS 2013 and successfully added both the NuGet package for Microsoft.Azure.Mobile.Client. and .SQLiteStore. Here's what I have in packages.config:

    <package id="Microsoft.Azure.Mobile.Client" version="2.0.1" targetFramework="wp81" />
    <package id="Microsoft.Azure.Mobile.Client.SQLiteStore" version="2.0.1" targetFramework="wp81" />
