### ISSUE TITLE
Issue caused by AssemblyFileVersion use in MobileServiceHttpClient when Xamarin linker is enabled

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-mobile-apps-net-client#16]
Copy of https://github.com/Azure/azure-mobile-services/issues/855

**Comment by fabiocav** [comment]
Connect #9

**Comment by SecretService** [comment]
Consistent crash on AzureClient initialization during push notification arrival on Android Nougat, Nexus 5X device:

[Service]
public class PushHandlerService : GcmServiceBase
{
protected override async void OnRegistered(Context context, string registrationId)
{
MobileServiceClient client = ServiceLocator.Instance.Resolve()?.Client as MobileServiceClient;
}
...
}

caused.PlatformInformation()
System.Object.__icall_wrapper_mono_throw_method_access(intptr, intptr)(wrapper managed-to-native)
Microsoft.WindowsAzure.MobileServices.PlatformInformation.get_Version():0
Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient.GetUserAgentHeader():0
Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient.MobileServiceHttpClient(IEnumerable handlers, Uri applicationUri, string installationId):0
Microsoft.WindowsAzure.MobileServices.MobileServiceClient.MobileServiceClient(Uri mobileAppUri, HttpMessageHandler[] handlers):0
Microsoft.WindowsAzure.MobileServices.MobileServiceClient.MobileServiceClient(string mobileAppUri, HttpMessageHandler[] handlers):0
Kudizmo.AzureClient.AzureClient.CreateClient()<560e234b5b734c69b5334a0d1ca1a685>:0
Kudizmo.AzureClient.AzureClient.get_Client()<560e234b5b734c69b5334a0d1ca1a685>:0
Kudizmo.Droid.Helpers.PushHandlerService.d__8.MoveNext()<08cf2cefecb84c4eb3e93013d29dca3a>:0
System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(object state)<4b972182e4df431898b1377813260900>:0
System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)<4b972182e4df431898b1377813260900>:0
System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)<4b972182e4df431898b1377813260900>:0
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()<4b972182e4df431898b1377813260900>:0
System.Threading.ThreadPoolWorkQueue.Dispatch()<4b972182e4df431898b1377813260900>:0
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()<4b972182e4df431898b1377813260900>:0
