### ISSUE TITLE
Add a PurgeAsync overload that clears all incremental sync metadata

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-net-client#164]
Currently, if you're using incremental sync, you need to purge incremental sync metadata by providing the query name. It would be helpful to have an overload that purges all queries for that table. (In fact, won't it result in bugs if it isn't purging the metadata, since there's no way to get the old records?)

We could either add an overload to the per-table version and/or add an overload to the sync context. The latter would be helpful if you need to clear the database on app logout.

**Comment by aline-almeida** [comment]
This would be very important! 
Consider the case where a record "fits in" two queries, each one with different query ids (let's say queries A and B). If I perform a purge on query A, the record is removed from the table, but query B's metadata  remains the same and therefore will not attempt to pull that record from server the next time it runs....

**Comment by elamalani** [comment]
Hi there, please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK. Thanks!
