### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-mobile-apps-net-client#175]
The link in the main readme for the nugget link to the managed SDK refers to the depreciated version of the nuget package. It would be better if the link to the 2.x package was linked as well.

Also, please can Version 2.1.0 be pushed to nuget.

**Comment by dhei** [comment]
@networkfusion Thanks for your feedback, we plan to publish version 2.1.0 to nuget.org very soon.

**Comment by lindydonna** [comment]
Thanks for the report about the readme, updated in dfe2490.
