### ISSUE TITLE
Xamarin iOS projects get System.Threading.Tasks dependency error when using Microsoft.Azure.Mobile.Client

### ISSUE THREAD

**Issue by idg10** [Azure/azure-mobile-apps-net-client#176]
In version 2.0.1 of the Microsoft.Azure.Mobile.Client NuGet package, the `Microsoft.WindowsAzure.Mobile.dll` file in the package's `lib\Xamarin.iOS10` folder refers to two different versions of `System.Threading.Tasks`! It has a reference to 4.0.0.0 (which is, as far as I know, the normal way to refer to this component), but also to 1.5.11.0. You can see this from running ILDASM on the DLL. If you open up the MANIFEST you'll see:

    .assembly extern System.Threading.Tasks
    {
      .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )
      .ver 4:0:0:0
    }

but also, later on, this:

    .assembly extern System.Threading.Tasks as System.Threading.Tasks_17
    {
      .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )
      .ver 1:5:11:0
    }

This causes build warnings - if you create a brand new iPhone Xamarin app in Visual Studio 2015 (update 3), add a reference to Microsoft.Azure.Mobile.Client v2.0.1 and then build (while connected to a Mac build agent), you'll get a warning: 'MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190'

I've tried adding a `<AutoGenerateBindingRedirects>true<AutoGenerateBindingRedirects>` to my project file as suggested, but it does not help - the error still appears. Also, adding an assembly binding redirect to the `app.config` does not help. Perhaps these techniques that usually work are defeated by the really strange situation of having two references to different versions of the same assembly from a single DLL.

It appears to pick up this dependency via `System.Net.Http` - it depends on version 1.5.0.0 of that, which it seems to get from Microsoft.Net.Http v2.2.28. Support for Xamarin wasn't introduced until 2.2.29 as far as I know, so perhaps the root cause of this problem is this dependency on an old pre-Xaramin version of Microsoft.Net.Http?

**Comment by lindydonna** [comment]
@dhei Could you take a look?  I think @fabiocav tried to update the System.Net.Http dependencies a few months back, but ran into all kinds of issues.

**Comment by idg10** [comment]
Heh - at some point in the 14 hours since I posted this, I see that v2.1.0 became available on NuGet. This does appear to depend directly on v2.2.29 of Microsoft.Net.Http, and it no longer has the funky dependencies on multiple versions of System.Threading.Tasks - it now just depends on v4.0.0.0 of that.

And I'm now able to get warning-free builds. Thanks!
