### ISSUE TITLE
Add a generic PullAsync overload that accepts query parameters

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-net-client#181]
The only way to pass custom query parameters to PullAsync is to use an overload that takes a string query. We should add an overload that takes IMobileServiceTableQuery. 

In https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices/Extensions/MobileServiceSyncTableExtensions.cs#L119:

`public static Task PullAsync(this IMobileServiceSyncTable table, string queryId, string query, IDictionary<string, string> parameters, CancellationToken cancellationToken)`

We should also add an overload that takes `IMobileServiceTableQuery`, such as:

`public static Task PullAsync<T, U>(this IMobileServiceSyncTable<T> table, string queryId, IMobileServiceTableQuery<U> query, IDictionary<string, string> parameters, CancellationToken cancellationToken)`

**Comment by danderson00** [comment]
Not sure I agree. Users will shoot themselves in the foot by issuing different queries for the same table - this will screw up the local store.

**Comment by lindydonna** [comment]
You can already do this, and you can even do this with the existing overload. :)  Our docs say that customers should use different query IDs for each unique query for a table. See https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-offline-data-sync/#how-sync-works.

This issue is about making it possible to add custom query parameters on Pull when using a LINQ query. Currently, you can only pass these parameters if you use an OData query string.

**Comment by danderson00** [comment]
Sorry, really I meant different queries against the same *queryId* - that's what will put the local store out of sync. What is the scenario that this change supports? We should make it hard for customers to shoot themselves in the foot.

**Comment by lindydonna** [comment]
Yes, different queries against the same queryId is bad, but I think that is orthongonal to this issue. The proposed overload also takes a queryId parameter, and customers need to make sure they set it correctly.

The scenario for this is that you might support custom queries on the server, such as in this SO question: http://stackoverflow.com/questions/38319858/querying-azure-mobile-app-tablecontroller. 

A simple example is that you might have a custom query parameter of "daysToSync" on your table controller, which your server code then expands to an EF LINQ query with date ranges. 

And, if there are multiple queries against the same table, you would need to incorporate all query parameters into the query ID, including custom ones specified in the query params dictionary.

**Comment by lindydonna** [comment]
It turns out that there's an extension method WithParameters() on IMobileServiceTableQuery that covers this exact case: https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices/Table/Query/Linq/IMobileServiceTableQuery.cs#L197
