### ISSUE TITLE
Add extension method ToODataString for IMobileServiceTableQuery

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-net-client#182]
There is a public method `ToODataString` in `MobileServiceTableQueryDescription` (see https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices/Table/Query/MobileServiceTableQueryDescription.cs#L125), but there is no way to get a query description from a query since the class `MobileServiceTableQueryProvider` is internal.

We should add an extension method for `IMobileServiceTableQuery` to get an OData query from a LINQ query.

**Comment by elamalani** [comment]
Hi there, please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK. Thanks!
