### ISSUE TITLE
Support nested property filters for child objects in PullAsync

### ISSUE THREAD

**Issue by drungrin** [Azure/azure-mobile-apps-net-client#183]
The Mobile Queries don't support nested properties.

http://stackoverflow.com/questions/16570779/odata-filter-by-nested-property

It is useful to reduce the amount out data being synced, when we need to sync the order items on a customer sync, instead of making multiple requests for each order.

**Comment by lindydonna** [comment]
Right, this is not supported when using LINQ queries. FYI you can use the overload that takes a string OData query to do this kind of filter.

**Comment by drungrin** [comment]
Sure?

There is only

```
public static Task PullAsync<T, U>(this IMobileServiceSyncTable<T> table, string queryId, IMobileServiceTableQuery<U> query, CancellationToken cancellationToken)
public static Task PullAsync<T, U>(this IMobileServiceSyncTable<T> table, string queryId, IMobileServiceTableQuery<U> query, CancellationToken cancellationToken, PullOptions pullOptions)
public static Task PullAsync<T, U>(this IMobileServiceSyncTable<T> table, string queryId, IMobileServiceTableQuery<U> query)
public static Task PullAsync<T, U>(this IMobileServiceSyncTable<T> table, string queryId, IMobileServiceTableQuery<U> query, PullOptions pullOptions)
public static Task PullAsync<T, U>(this IMobileServiceSyncTable<T> table, string queryId,
            IMobileServiceTableQuery<U> query, bool pushOtherTables, CancellationToken cancellationToken)
public static Task PurgeAsync<T, U>(this IMobileServiceSyncTable<T> table, IMobileServiceTableQuery<U> query)        
```

available, all with IMobileServiceTableQuery. Can you point me which overload to use?

There are overloads to the untyped IMobileServiceSyncTable, but it is better to wait/implement than mess with my code.
I made 2 patches to make the correct request, but I need to implement server side. Since the data is small, I'm planning to do that later, since I can live with that for now.

ODataExpressionVisitor.cs

```
public override QueryNode Visit(MemberAccessNode nodeIn)
        {
			if (nodeIn.Instance != null)
			{
				nodeIn.Instance.Accept(this);
				this.Expression.Append("/");
			}
			this.Expression.Append(nodeIn.MemberName);
            return nodeIn;
        }
```

```
FilterBuildingExpressionVisitor.cs

public static string GetTableMemberName(Expression expression,
                                                  MobileServiceContractResolver contractResolver)
        {
            Debug.Assert(expression != null);
            Debug.Assert(contractResolver != null);

            // Only parameter references are valid in a query (any other
            // references should have been partially evaluated away)
            MemberExpression member = expression as MemberExpression;
            if (member != null &&
                member.Expression != null &&
			    member.Expression.NodeType == ExpressionType.Parameter &&
                member.Member != null)
            {
                // Lookup the Mobile Services name of the member and use that
                JsonProperty property = contractResolver.ResolveProperty(member.Member);
                return property.PropertyName;
            }

			if (member != null &&
				member.Expression != null &&
			    member.Expression.NodeType == ExpressionType.MemberAccess &&
				member.Member != null)
			{
				// Lookup the Mobile Services name and table name of the member and use that
				var tableName = contractResolver.ResolveTableName(member.Expression.Type);
				JsonProperty property = contractResolver.ResolveProperty(member.Member);
				return string.Format("{0}/{1}", tableName, property.PropertyName);
			}


			// Otherwise return null
			return null;
        }
```

Regards,

**Comment by lindydonna** [comment]
Yes, I was referring to the untyped sync table methods. They will still insert into your generic sync table just fine, as they are extension methods.

In your client data model, do you include the child objects as a nested object, or are you using separate sync tables for them?  This feature would be pretty hard to do when there are separate sync tables, since the parent would not have a child object as a member, just a foreign key.

**Comment by drungrin** [comment]
Sorry about the delay.

```
    public class GrandFather : EntityData
    {
        [JsonIgnore]
        public ICollection<Father> Fathers { get; set; }
    }

    public class Father : EntityData
    {
        [JsonIgnore]
        public ICollection<Kid> Kids { get; set; }

        [JsonIgnore]
        public GrandFather GrandFather { get; set; }

        public string GrandFatherId { get; set; }

    }

    public class Kid : EntityData
    {
        [JsonIgnore]
        public Father Father { get; set; }

        public string FatherId { get; set; }
    }
```
I need to pull only the data relative to a specific grandfather.

```
			var fathers = client.GetSyncTable<Father>();
			fathers.PullAsync("some query id", fathers.CreateQuery().Where(f => f.GrandFatherId == "someid")); // OK

			var kids = client.GetSyncTable<Kid>();
			kids.PullAsync("some query id", kids.CreateQuery().Where(k => k.Father.GrandFatherId == "someid")); // This is what I need

```

(that reminded me that EntityTable should be in a PCL so we can share the models)

**Comment by lindydonna** [comment]
@drungrin And what does your client data model look like?  Is it identical?

**Comment by drungrin** [comment]
Yes, identical.





On Thu, Jul 28, 2016 at 4:15 PM -0300, "Donna Malayeri" <notifications@github.com> wrote:












@drungrin And what does your client data model look like?  Is it identical?

**Comment by drungrin** [comment]
I have a "basemodel" on client side as base, with the same properties as EntityData.

**Comment by lindydonna** [comment]
In that case, I think you're actually asking for relationship support in offline sync. Related to https://github.com/Azure/azure-mobile-apps/issues/6.

**Comment by drungrin** [comment]
No. There are other models related to GrandFather that I don't need to include. It is a nested property filter only.

**Comment by lindydonna** [comment]
@drungrin Right, but the nested property filter has to do with the fact that "kids" is a separate table that can change independently. So, it still seems related to relationship support. Perhaps it is only partial relationship support?

**Comment by drungrin** [comment]
I think indirect relationship support fits better.

Kids don't have a direct relationship with GrandFather.

It should work also if you have a Toys table.

toys.Where(t => t.Kid.Father.GrandFatherId == "some")

(not my case, my schema stop on the Kid :D)

**Comment by adrianhall** [comment]
I'm still going to call this "relationship support", and I agree, it's very much needed.  I've got other issues open that require full relationship support, so I'm closing this one to keep things tidy.
