### ISSUE TITLE
Improve doccoments: add class summary and exception list

### ISSUE THREAD

**Issue by migig** [Azure/azure-mobile-apps-net-client#184]
There is very little documentation for the SDK - _in xml doc comments in particular_.

If this is not a priority item right now, then at least provide the basics:
1. Describe each class and interface, in the topmost `/// <summary>`. So at least we know what a `SomethingOrOtherService` actually does. This would also give us Intellisense.
2. Important, even moreso than (1): specify WHICH EXCEPTIONS ARE THROWN by the various methods, i.e. `/// <exception cref="SomeException">Thrown when blah.</exception>`. We're tired of our code blowing up because of unseen problems. :sob:

The lack of (2) is a giving us endless problems. And resorting to a failsafe catch of `Exception` everywhere is the sure sign of bad API design. It means we don't really know what is going on, and the design contract between API supplier (you) and consumer (us) is tenuous at best.

The SDK is rock solid, no doubt, and performs as promised, when you are doing the right things. But without at least the above it is incomplete. **Tutorials, articles, blogs and sample code projects - though appreciated, do not qualify as documentation, they are supplementary.**

Sorry for the rant, because we love where Azure is headed, but if this SDK is intended as a way for us to buy into a professional paid-for service, then the reference documentation must be improved.

**EDIT:** PS, before getting upset with me, please know that this is a very widely reported problem on StackOverflow, for Azure in particular. Which is unfortunate as the underlying .NET platform is _very_ well documented. Amazon AWS don't release new services without extensive docs.

**Comment by lindydonna** [comment]
To help prioritize the updates, could you give examples of the cases where this would be most helpful, for both the summary and exception list?

**Comment by migig** [comment]
Yes good idea I'll try build a list of the most improtant ones.

**Comment by migig** [comment]
I've been trying to make a list. What I've found is that as I expected (2) is worse than (1).

There are many undocumented items (missing a `/// <summary>`) but the SDK uses clear and sensible naming, so we figured out most of what we need. I'll nonetheless post a list of such missing items as I find them while I'm working (from what I can tell, it's the interfaces which are the main culprit). It's annoying, but isn't a priority because it's unlikely you'll change a class' core behavior.

BUT, (2) is a problematic area. I've yet to find anything annotated with exceptions. I mainly use the various storage classes, but some of my colleagues are working on "offline sync" and "authorization" (etc.) and they've complained about the same thing.

We actually wrote a little console app, to simulate various operations when interacting with Azure, so that we can find out which exceptions are thrown where. It helps, but of course it's anecdotal as it can change. We also began to look into the source (who'd have thought that a few years ago, on an MS product???!!! :smile:) to find out what's being thrown, but likewise if it's not officially documented then we're essentially relying on side effects.

Our problem is that a failsafe `catch (Exception err) { }` hides various problems and we can't deal with them. So for example we can't tell the difference between "network down", "not found / 404", "invalid request", etc. All we can tell is "something bad happened". :cry:

If you'll scan through almost any class related to the above, you'll see what I mean. The xml doc comments are missing exception documentation. We've worked around it for now, but I hope one day we can refactor what we've done so it's more robust. :beers:

**Comment by adrianhall** [comment]
Closing this as it's been dead for 6 months.  If you have specific situations where the documentation is bad, please let us know the class/method that needs improving as a new issue, and I'll prioritize that work.  (Example: I just updated docs and added exception handling for the PurgeAsync and PullAsync methods in the SyncTable)
