### ISSUE TITLE
Serialization bug in offline sync operations table in UWP Release mode

### ISSUE THREAD

**Issue by pglazkov** [Azure/azure-mobile-apps-net-client#185]
This happens only in Release builds of Windows 10 universal apps (compiled with .NET Native). 

**Steps to reproduce (or use a test - see below):**
1. Compile a Universal Windows app that uses the offline storage in Release;
2. Add a record to the local storage;
3. Update the added record in the local storage;
4. Push the changes to the remote table. 

**Expected result:**
Record is added to the remote table in Azure.

**Actual result:**
The push operation succeeds, but the the record is not saved to the remote table.  

After examining the local SQLite database I can see that the `__operations `table contains a record for the newly added data. After debugging the source code of the SDK, it turned out that the value of the `sequence `column in the `__operations `table gets overwritten with "0" after updating the record before Push (step 3). Therefore the record in the `__operations `table never gets picked up for execution during Push. 
After some more debugging, I could narrow down the issue to the **`MobileServiceTableOperation.Deserialize`** method that doesn't deserialize the JSON data correctly - the `sequence `value is always deserialized as "0". 

The issue can be reproduced by adding the following test to the **`OfflineTests`** class in the **`UWP.E2ETest`** project and running it in Release:

```
        [TestMethod]
        public void TableOperationDeserializeInRelease() {
            var serializedOperation = JObject.Parse(@"
                {""id"":""70cf6cc2-5981-4a32-ae6c-249572917a46"",
                ""kind"": 2,
                ""tableName"":""test"",
                ""itemId"":""abc"",
                ""version"":123,
                ""state"":null,
                ""item"":""{\""id\"":\""abc\"",\""text\"":\""example\""}"",
                ""createdAt"":""2014-03-11T20:37:10.3366689Z"",
                ""sequence"":1
                }");

            var operation = MobileServiceTableOperation.Deserialize(serializedOperation);
            Assert.AreEqual((long)1, operation.Sequence);
        }
```

**Comment by shrishrirang** [comment]
You seem to be running into a bug in the compiler as reported in issue https://github.com/Azure/azure-mobile-services/issues/890. Comment https://github.com/Azure/azure-mobile-services/issues/890#issuecomment-230610187 explains a workaround you can use till the bug is fixed.

**Comment by SapanGhafuri** [comment]
Many thanks @pglazkov . It worked perfectly!

**Comment by fcyy** [comment]
I'm still encountering this issue on the latest stable release (3.1.0).  Is there a fix for this?   It's a pretty nasty bug.     also, the above links to issue 890 under the old azure-moble-services are dead.   Is there any way to access those issues?   I just want to find out more about this compiler bug.   Thanks.

**Comment by tobber72** [comment]
I also encountered this problem last summer (and asked for help in issue 890, and in some other forums) and after much troubleshooting, and with the help of @MattWhilden, came up with the workaround refered to above :-).

Maybe you can ask the .NET Native runtime and compiler team (dotnetnative@microsoft.com) if there has been any progress in resolving "the root cause" to this in the .NET Native Tools Chain.

(I am also curious to know why they removed issue 890.)

**Comment by fcyy** [comment]
Thanks, @tobber72.   I should have mentioned that I've also successfully used the workaround mentioned above.    When I've gathered enough observations I'll post to StackOverflow.   Perhaps I'll get more answers from the MS people who thankfully are active in that site.

**Comment by afmicc** [comment]
I try to used the workaround mentioned above but it's not run for me. When I build the uwp project I have this error: 
`F:\XXX\XXX.XX\XXX.XX.UWP\Properties\Default.rd.xml(35,13): error : The element 'Directives' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' cannot contain text. List of possible elements expected: 'Library' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata'.`

The Default.rd.xml file:

```
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <Assembly Name="*Application*" Dynamic="Required All" />
  </Application>
  <Library Name="Newtonsoft.Json">
    <Assembly Name="Newtonsoft.Json" DoNotOptimize="true" />
  </Library>​
</Directives>
```

What is it wrong?
