### ISSUE TITLE
SyncTable Where not working with enums

### ISSUE THREAD

**Issue by ceichin** [Azure/azure-mobile-apps-net-client#188]
I have table Friendhship: 

`table = client.GetSyncTable<Friendhship> ();`

When I retrieve all:

```
result = await table.ToListAsync ();
// result: One Friendhsip with status FriendStatus.Pending
```

But when I query:

```
result1 = await table.Where (f => f.Status == FriendStatus.Pending).ToListAsync ();
result2 = await table.Where (f => f.Status == (int)FriendStatus.Pending).ToListAsync ();
result3 = await table.Where (f => (int)f.Status == (int)FriendStatus.Pending).ToListAsync ();
result4 = await table.Where (f => f.Status.ToString ().ToLower () == FriendStatus.Pending.ToString ().ToLower ()).ToListAsync ();

// all results: Empty lists
```

If I query something without enums it works well. I'm using Xamarin.iOS. 

I hope someone can help me, thanks!

**Comment by shrishrirang** [comment]
Are you using custom serializer settings - `MobileServiceClient.SerializerSettings`?

**Comment by ceichin** [comment]
I'm adding a converter:

`client.SerializerSettings.Converters.Add (new AppJsonConverter ());`

Where AppJsonConverter is like this: http://stackoverflow.com/a/34931110/3481904

I just noticed that when I save a Friendship locally, the enum is saved as the string name (eg. "Pending"). When I pull from server it is saved as an int.

I'm sure the custom added converter is the issue, how could I fix this also using my custom AppJsonConverter converter?

Thanks!

**Comment by ltaljaard** [comment]
Same issue here. Enums are not supported on the server side. For now I've used int as the data type on both the client and client and server tables. Then I'm casting back to the enum type before using the retrieved values. It would be nice if it could be fixed so that enums are properly supported.

**Comment by shrishrirang** [comment]
@ceichin - ok, that explains. Local inserts and querying should work unless you remove one of the default converters.

https://github.com/Azure/azure-mobile-services/issues/759 talks about the enum issue on server.
