### ISSUE TITLE
Android N does not support loading sqlite dll from the platform

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-mobile-apps-net-client#191]
MobileServiceSQLiteStore depends on [SQLitePCL](https://sqlitepcl.codeplex.com/) which uses the sqlite3 library that is part of Android platform. [Android N previews now only allow linking to NDK-provided native libraries](https://developer.android.com/preview/behavior-changes.html#ndk) and does not allow loading platform's sqlite3 library.

Options to fix this issue:
1. Point customers to include their own sqlite3 library as part of the application. Binaries can be downloaded from [SQLite Downloads](https://www.sqlite.org/download.html)
2. Include sqlite3 in Microsoft.WindowsAzure.Mobile.SQLiteStore nuget package
3. Update SDK to use [SQLite-net-pcl](https://www.nuget.org/packages/SQLite.Net-PCL/). This package includes sqlite library.

**Comment by mamaso** [comment]
In good news, this won't break with Android N release (api v 23) and will throw logcat errors.  It seems that things will break with 24.

I think that we need to choose one of 2 or 3, asking customers to include their own sqlite3 lib is too much.

Also, took a look at 3, it doesn't seem like they've fixed the library yet https://github.com/oysteinkrog/SQLite.Net-PCL/issues/311

**Comment by pragnagopa** [comment]
Investigating moving to [SQLitePCL.raw](https://github.com/ericsink/SQLitePCL.raw)

**Comment by pragnagopa** [comment]
For Windows Phone Silverlight apps, need to install nuget package:  SQLitePCL.native.sqlite3.v110_wp80
