### ISSUE TITLE
Surface incremental sync dictionary, or provide validator

### ISSUE THREAD

**Issue by migig** [Azure/azure-mobile-apps-net-client#192]
When performing an *incremental sync*, the "query id" must be unique (to prevent incorrect results from being pulled), conform to a regex, and have length of 25 (or 50, if you look at the source :wink:). The recommendation is to use the table name and [some extra bits of info](http://azure.microsoft.com/en-gb/documentation/articles/app-service-mobile-offline-data-sync/#how-sync-works), like "AllCustomers", "FilteredCustomersOutstandingPayment", "Customer3", etc.

We need to integrate our current systems, and some table names are *loooong*. We wrapped some complexity in views, and those have names which are *loooong*. So, a `typeof(Foo).Name` results in strings of length `>25`, and that's even before adding the "extra bits of info". So we shorten them using a `foo.Substring(0, 25)`.

The problem is that for a sufficiently large/complex system, such shortening may (probably will) cause key collisions in the query id dictionary, which means incorrect query results.

If that dictionary were public I would first check for a collision, then throw an exception. But right now I have no way of knowing if this problem is even taking place.

Please consider surfacing that dictionary, or if you feel that's a bad idea, then provide some function which allows me to check whether a query id is already in use. Maybe something like `public bool IsQueryIdUnique(string queryId);`.

(Or let me know if there's a better way I haven't thought of! :smile:)

**Comment by migig** [comment]
PS: allowing a longer key is probably not a great solution, as it'll just mask the problem... There should be a simple mechanism to ensure uniqueness.

**Comment by lindydonna** [comment]
The documentation might be a bit misleading, since it includes table names. In fact, the query ID just needs to be unique for that particular table, since the table name is used as part of the index. So, you just need to use the "extra bit of info" such as "All" rather than "AllCustomers".

Does that resolve the issue?  How many different queries do you have for a particular table?

**Comment by migig** [comment]
@lindydonna Ahhh I didn't know that!! :grinning: 

But does that mean that I must satisfy:

    length(tablename) + length(discriminator) <= 25 chars

**Comment by lindydonna** [comment]
It's just length(discriminator) that needs to be less than 50 characters. It turns out that the query ID length was changed from 25 to 50 characters, but the doccoment wasn't updated. I'll file a new issue to update it and I'll close this one.

**Comment by migig** [comment]
@lindydonna Thanks!

PS:

We have a fairly heavy table with over 30 unique queries (products, filtered products on various criteria, filtered products by time, by customer, by sales performance, etc.). So I gave this much thought

I concluded that that providing us with a validation function won't help after all - how is some function supposed to know that it caused the collision, or whether some other function did? :anguished: And surfacing the dictionary is messy and doesn't answer the question either.

*So there is an implicit race condition here*. Even if my code detects the collision, there is no easy way to deal with it (which I can think of).

So unfortunately, the only way to deal with this, is to make the keyspace BIGGER. Much bigger, not 25, or even 50. Let's say 1000. It's running on the client device, and so the longer string won't have any perf impact.

Something to think about.

**Comment by lindydonna** [comment]
@migig The restriction was put in place to improve performance, since it is still an index lookup. 1000 characters seems like it would impact performance substantially, but we could increase this to something like 255 characters. If that will help your use case, then please file another issue.

**Comment by migig** [comment]
@lindydonna Okay that is a good idea! I'll do that... :+1:
