### ISSUE TITLE
Update PullAsync doccomments to reflect current restrictions on queryId

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-net-client#193]
The doccomments for PullAsync say that the queryId has to be less than 25 characters and conform to a particular regex (e.g. https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices/Extensions/MobileServiceSyncTableExtensions.cs#L34). However, the query ID length was increased to 50 characters, and the regex was changed to just disallow the pipe character (see https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/MobileServiceSyncTable.cs#L18). 

We should change all of the doccomments that reference queryId limitations to say that it has to conform to the regex "^[^|]{0,50}$" instead.

Change queryId comment to:

> Must be 50 characters or less and cannot contain the pipe ('|') character" 

and exception comment to:

> Thrown when <paramref name="queryId"/> does not match the regular expression <value>[^|]{0,50}</value>.

**Comment by migig** [comment]
Interesting edge case regarding [the `queryID` length](https://github.com/Azure/azure-mobile-apps-net-client/issues/192#issuecomment-236133071). We've worked around it by hardcoding strings (I know, I know, gross!), but someone else might encounter the problem at some point.

**Comment by pvbchak** [comment]
Fixed by #272
