### ISSUE TITLE
Expose MobileServiceHttpClient on MobileServiceClient and Methods to inheritance

### ISSUE THREAD

**Issue by angusbreno** [Azure/azure-mobile-apps-net-client#197]
**The ZUMO SDK it's awesome!** We all know that.

But i believe we can leverage options to extend that.

Right now i already have some things built on top of it and to get it better the access to the MobileServiceHttpClient is needed. At my point of view making it protected don't break anything in the original SDK. I'm not telling to make it public (maybe?) but making it protected do the jobs.

Why need access to it? Today it's not supported make a call to an non"api/x" endpoint and in some environments it's needed.

**See, this is not a Issue,** way from it. It's an question about if we can make this awesome SDK more flexible to us... And with this we can create more cool things on top of it.

Makes sense?

**Comment by adrianhall** [comment]
So, the requirement is really to be able to call non-ZUMO endpoints within the same app?

**Comment by angusbreno** [comment]
If look it in this way, yes... 

We can have another things in the services that we can put together with service client. That's why is an extension. If the dev use just ZUMO on client and server nice, he would note the difference, but in many cases we have a lot of other things in services that could centered to one place... And this place could be a diferent clients built on top of actual ZUMO. 

Don't agree?

**Comment by adrianhall** [comment]
I'm not sure of the benefit (aside from authentication/authorization) of not just doing a new HttpClient() instead.   I can see the composition argument, but it's trivial to just new up a new HttpClient()

**Comment by angusbreno** [comment]
@adrianhall Yourself write the benefit. 

Why create a brand new HttpClient if we already have a client that have: Endpoint information setting, Serialization, Serialization Settings, HttpHandlers, User and so many others features? 

The goal here it's use the MobileServiceClient patterns and behaviors working together with other service stuff.

See, changing some access will leave this extensions options to the developer who want, but they don't change anything to actual use of MobileServiceClient. 

I was about to create PR demonstrating but i was afraid that u guys have any other ideas to make it extensible.

What is the concern exposing those prop and some methods to protected?

**Comment by adrianhall** [comment]
@angusbreno Feel free to file a PR - seems reasonable to me.

**Comment by elamalani** [comment]
@angusbreno  Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us to prioritize this work in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
