### ISSUE TITLE
Project names (namespaces) and structure do not match folder locations

### ISSUE THREAD

**Issue by goblinfactory** [Azure/azure-mobile-apps-net-client#201]
Project names (namespaces) and structure do not match folder locations; for example;
`Microsoft.WindowsAzure.Mobile.Test` project resides in subfolder `Microsoft.WindowsAzure.MobileServices.Test`.

Rationale; this impacts the `scannability` of the code; how quickly someone new to the project can get a good grasp of what's going on, and what are all the moving pieces. Newcomers will have to create a mental map in their mind, of When the code says X here, this actually means Y.

**Comment by adrianhall** [comment]
As much as I would like to do a mass rename, reality is that it isn't going to get fixed - there are just too many moving parts at this point.  Closing this as a result.
