### ISSUE TITLE
Nuget package names should match the solution and project structure

### ISSUE THREAD

**Issue by goblinfactory** [Azure/azure-mobile-apps-net-client#202]
The primary nuget package artifact (deliverable) for the sdk, (I might be wrong here, so please excuse if I am), appears to be `Microsoft.Azure.Mobile.Client`.

The project name for the core assembly, located in folder `src\Microsoft.WindowsAzure.MobileServices`  is named `Microsoft.WindowsAzure.Mobile (Portable)`. This does not match, see earlier issue.

The nuget package that gets generated and published to Nuget, is named, `Microsoft.Azure.Mobile.Client`; In my opinion, the project should be named to match, and the folder structure should be changed to match the name of the projects as well. 

If this is not the case, then perhaps place a clear note in the primary `readme.md` explaining the rationale?

**Comment by adrianhall** [comment]
I'm going to close this as we have a bigger composability project in the works.  The idea, basically, is that you have a core class (let's call this Microsoft.Azure.Mobile.Client) and then dependent packages for each feature (.Tables, .Auth, .PushRegistration) and further dependent packages (.Auth.Google, .Auth.Facebook, etc.)  - we'll be completely re-doing the SDK at that point.  I take your point and will ensure this gets in.

This SDK won't be changed per your suggestion as too much backwards compatible code would need to change.
