### ISSUE TITLE
Readme does not explain which nuget packages you need for the platform .Ext.nnn assemblies

### ISSUE THREAD

**Issue by goblinfactory** [Azure/azure-mobile-apps-net-client#204]
Readme does not explain which nuget packages you need for the platform .Ext.nnn assemblies.

As far as I can tell, if you include the main nuget package, you still need to somewhere in your code call `CurrentPlatform.Init()`. I may be wrong, (new to all this), however it looks like this is only possible if you have referenced the appropriate `.Ext.Net45` or `Ext.{your-platform}` assembly. 

The only way I can find to get these platform specific assemblies is to build the project myself from source. This seems to defeat the purpose of having a nuget package? I'm sure I've misunderstood how it all works, however, if I'm right, then it means the Nuget package should include the assemblies, and doesn't, or doesnt in a way that means you can easily use it. Or, a the platform versions should be made available as nuget packages, and named exactly the same as the readme notes refer to it, i.e. `Microsoft.WindowsAzure.Mobile.Ext.<Platform>`. 

Aside;
This is somewhat related to #202 and #201 ie synchronising the names of the nuget packages, the folder structure and the project and solution names. (apologies, would link to the issue directly, but they're all been submitted at the same time.)

**Comment by lindydonna** [comment]
The NuGet does include the .Ext assemblies that you need, you definitely don't need to go building from source yourself. The call to CurrentPlatform.Init is only needed for Xamarin.iOS projects, because of the way that the Xamarin linker works for iOS projects. That method does not in other platforms by design.

The details of what is included in the Ext for each platform isn't immediately obvious without digging into the details of the project structure, but as a consumer of the library, you shouldn't need to have to learn all of that. We do definitely welcome suggestions on making it easier to contribute to the library, of course.

Does that clear up this issue?  If so, please close it.

**Comment by goblinfactory** [comment]
yes it does, thank you.

**Comment by goblinfactory** [comment]
just a quick update; I've referenced the nuget package; and when I run my project I initially recieved the error;

>  `d. Ensure that the current project references both Microsoft.WindowsAzure.Mobile
>  and the following platform-specific assembly: Microsoft.WindowsAzure.Mobile.Ext
> .`. If you google that error you find references to try `CurrentPlatform.Init()`.  
> 

After reading your reply, I did a `grepwin` for any matching assembly and eventually found the assembly referred to in the readme in : `packages\Microsoft.Azure.Mobile.Client.2.1.1\lib\net45` folder of my solution. 

So yes, it `is` included, but perhaps the notes could be more guiding and explain that you will need to manually link the appropriate dll, together with an example? (i.e. it will be a different location depending on your platform. ) 

For many developers not used to writing different platform code, the concept of a `dll` being in either place A or place B is foreign; especially if you're wanting to use this library for simple windows development. The fact that it can be used in cross platform should be irellevant. 

Perhaps the nuget package should have a `ps` script that references the appropriate assembly automatically?

Lastly; possibly the notes could be updated to be more helpful to beginners as to where exactly you'll find the .Ext , and what the .Ext actually is, and how to reference it? 

I'm leaving this as closed, as my comments are merely here for clarification. Feedback is helpful as I'm totally new to seeing how these projects work and would like to be able to contribute. Thanks again, A

**Comment by lindydonna** [comment]
Could you explain the steps you took to add the NuGet reference?  You're right that it's supposed to be added automatically. What kind of project are you working with?  I.e., Android, UWP, etc.  It could be that there's a package bug that only manifests on console apps, for instance.

**Comment by goblinfactory** [comment]
Hi Lindy; unrelated note; just watched an old video on https://channel9.msdn.com/Shows/Cloud+Cover/Episode-155-Offline-Storage-with-Donna-Malayeri ( great video! ) do you have any later videos?

re: what steps did I take? below is my readme from the spike project I created; 

** Alan's azure-mobile-sandbox **
Sandbox for experimenting with building xamarin android mobile apps with azure backend, with the least amount of dependancies possible, and the simplest and quickest (lightest) means of (automated?) testing of libs.

##Getting started projects and packages

- A) Lib project
 - Class Library (Portable for iOS, Android and Windows)
 - packages
 ```

    install-package Newtonsoft.Json -version 6.0.4
	install-package Microsoft.Bcl -version 1.1.10
	install-package Microsoft.Bcl.Build -version 1.0.21
	install-package Microsoft.Net.Http -version 2.2.29
	install-package Newtonsoft.Json -version 6.0.4
	install-package Microsoft.Azure.Mobile.Client -version 2.1.1
	install-package Microsoft.Azure.Mobile.Client.SQLiteStore -version 2.1.1
	
```

- B) Console app
 - net45 class library
 - packages
```
	// https://github.com/Azure/azure-mobile-apps-net-client
    install-package Microsoft.Azure.Mobile.Client -version 2.1.1 
	install-package Microsoft.Azure.Mobile.Client.SQLiteStore -version 2.1.1

```
- after installing the Mobile.Client, you will need to manually add a reference to `Microsoft.WindowsAzure.Mobile.Ext.dll`, which will be in the packages folder. In my project, this was in `packages\Microsoft.Azure.Mobile.Client.2.1.1\lib\net45\Microsoft.WindowsAzure.Mobile.Ext.dll`

```

**Comment by goblinfactory** [comment]
me again; 

I've only just notice in the log output (visible in the package console window) from NUGET when installing the package, the log contains these two lines;

```
If your PCL Project is part of another NuGet Package, you should add this NuGet package as a dependency.
If your PCL Project is referenced from other platform specific projects, you should install this NuGet package on each of these projects.

```
doh! That explains it perfectly. (ok, in my defense, who really reads the verbose output from builds, when there's no errors? ) he he. Perhaps we can include these two lines in the readme notes, I think that would be very helpful?

regards,

Alan

**Comment by lindydonna** [comment]
Thanks for the feedback!  Since this is more of a troubleshooting item, and our tutorials walk through the right steps, I've created a wiki page that outlines the basics. Feel free to suggest any information that might be missing: https://github.com/Azure/azure-mobile-apps-net-client/wiki/Portable-libraries-and-platform-specific-.ext-assemblies
