### ISSUE TITLE
Allow marking properties to be persisted locally but not sent to the server

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-net-client#207]
To prevent properties in a data model from being sent to the server, you use the [JsonIgnore] attribute. Unfortunately, this also prevents the properties from being persisted in offline sync, since the object is JSON serialized before being saved. There should be an attribute that marks fields as being "local store only," so that they are persisted to the local store, but not sent the server.

**Comment by ltaljaard** [comment]
That would be nice. At the moment I have a workaround to accomplish this in my sync handler (which is based on IMobileServiceSyncHandler). If the table is marked as local only (my own attribute) then I return null from ExecuteTableOperationAsync() which makes it think that the sync was successful and the pending operations are then removed from the queue.

**Comment by ceichin** [comment]
It would be great to have. I take the opportunity to make reference to a related forum question: https://social.msdn.microsoft.com/Forums/azure/en-US/8568a8b1-36e6-4174-819d-7e60cd80fef7/client-only-properties?forum=azuremobile

**Comment by ceichin** [comment]
Some considerations to have when implementing this:
- Do not send these attributes to the server, but save them into the local store
- When doing a pull, do not "override" these attributes (the object server will not have these attributes, so when doing upsert in the local store these attributes are overwritten to null, but they should stay the same)
- Do not track sync changes when I only modify these attributes (for sync table)

**Comment by elamalani** [comment]
Hi there, please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK. Thanks!
