### ISSUE TITLE
RegisterMultipleAsync causes flakiness in E2E push tests

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-net-client#21]
Removing this test from the E2E suite allows the push functional tests to pass reliably. Adding the test back in causes flakiness. The test itself passes but causes subsequent tests to fail.

We should investigate if the same behavior is observed when executing tests against the .NET backend. If so, the issue likely exists in Notification Hubs itself. If not, I will investigate the cause in when running against the Node backend.

**Comment by paulbatum** [comment]
Resolved by #41
