### ISSUE TITLE
NuGet package should declare System.Net.Http as a framework assembly

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-mobile-apps-net-client#210]
When using the Mobile Apps client SDK on platforms that have System.Net.Http available (such as Xamarin.iOS, Xamarin.Android, .NET 4.5 console apps, etc), the user must manually add a reference to this framework assembly. If they do not, they encounter this error:

`The type 'HttpMessageHandler' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Net.Http'.`

However if we take advantage of the [framework assembly feature of NuGet](https://docs.nuget.org/create/nuspec-reference#specifying-framework-assembly-references-(gac)), we can ensure that this reference is automatically added when required.

**Comment by kallisto** [comment]
We want to add that this impacts the new connected services work shipping for connect. The sooner we can get this change the better.

**Comment by paulbatum** [comment]
I looked at this some more. The problem seems to be that Microsoft.Net.Http adds the system.net.http reference when installed into an android application but the same is not true for iOS. However the fix I discussed above is still applicable.

**Comment by dhei** [comment]
Fixed in 3.0.0 release of [Microsoft.Azure.Mobile.Client.SQLiteStore](https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client.SQLiteStore/3.0.0)

**Comment by dhei** [comment]
We update [Microsoft.Azure.Mobile.Client.SQLiteStore](https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client.SQLiteStore/3.0.0) package to 3.0.0. [Microsoft.Azure.Mobile.Client](https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client/2.1.1) package is still on 2.1.1. We will release the 3.0.0 version of Microsoft.Azure.Mobile.Client which includes a fix for this issue. I will update this thread once it is done.

**Comment by demali** [comment]
Thanks @dhei  for re-activating and updating the issue.

**Comment by dhei** [comment]
@demali 3.0.1 is released and this issue should be fixed.
