### ISSUE TITLE
Inconsistent formatting of Guid primary keys

### ISSUE THREAD

**Issue by migig** [Azure/azure-mobile-apps-net-client#215]
[On the server](https://github.com/Azure/azure-mobile-apps-net-server/blob/master/src/Microsoft.Azure.Mobile.Server.Entity/EntityDomainManager.cs#L120), a PK is created as such:

```
Guid.NewGuid().ToString("N");
```

[On the client](https://github.com/Azure/azure-mobile-services/blob/master/sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/MobileServiceSyncTable.cs#L70), a PK is created as such:

```
Guid.NewGuid().ToString();
```

So it may, or may not, have hyphens.

I'm not a database expert, but common sense tells me the hyphens would slow down a query over a very large table.

And even if not so, this has caused us some problems when we deal with PKs in our system, we need to first clean them.

Unless this is because of some weird implementation detail that I don't understand, please consider fixing it so it is consistent. Preferably without hyphens.

**Comment by artemious7** [comment]
Hmm now when I upgraded my client to v3.1.0, it broke logic in my local app, which converts string id's to GUID's. And even no release notes for 3.1.0 at all to notify me of that!
Now some of the records in my local database have id's with hypens, but new records have id's without hyphens! How can I fix that?

**Comment by adrianhall** [comment]
The non-hyphenated versions were always there.  The ID is a string - not a GUID.  We just use string representations of GUIDs.  Stop assuming you are working with GUIDs.  You aren't - you are working with strings.
