### ISSUE TITLE
Mobile App in ClassLibrary is not supported.

### ISSUE THREAD

**Issue by sureshja** [Azure/azure-mobile-apps-net-client#216]
Tried creating a ClassLib project in VS and added Mobile App reference to it. Referencing the ClassLib from a Console Application throws run time errors. The first issue was that the platform specific .Ext assembly was not copied by VS to the Console Application bin/debug folder. After fixing this manually I see the following error - 
Could not load file or assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I think using Mobile App in a classlib is a valid scenario. Can we have this fixed?

**Comment by adrianhall** [comment]
The ClassLibrary is not going to be a supported instance of the service.   If you want to use Mobile Apps tables in a class library, then use an OData.v3 library adjusted for the ZUMO-API-VERSION
