### ISSUE TITLE
PullAsync bug in query

### ISSUE THREAD

**Issue by airedwin** [Azure/azure-mobile-apps-net-client#220]
my query as string
(((((latitude sub " + location.Latitude.ToString() + ") mul (latitude sub " + location.Latitude.ToString() + ")) add ((longitude sub " + location.Longitude.ToString() + ") mul (longitude sub " + location.Longitude.ToString() + "))) mul 3280.8399) le 50.0)"
is not working

and as LINQ Query
var pullQuery = messageTable.Where(u => (((u.Latitude - location.Latitude) \* (u.Latitude - location.Latitude) + (u.Longitude - location.Longitude) \* (u.Longitude - location.Longitude)) \* 3280.8399 <= radius));

the translator is changing the + operand to an OData "and" instead of  OData "add"

**Comment by airedwin** [comment]
GET /tables/Message?$filter=(((((latitude%20sub%2038.8879886269569)%20mul%20(latitude%20sub%2038.8879886269569))%20and%20((longitude%20sub%20-77.42908171378)%20mul%20(longitude%20sub%20-77.42908171378)))%20mul%203280.8399)%20le%2050.0)&$skip=0&$top=50&__includeDeleted=true HTTP/1.1

is the resulting GET, there is an "and" where "add" should be

**Comment by airedwin** [comment]
it is wierd because the purgeasync works fine with same query, it does the 'add' normally

**Comment by adrianhall** [comment]
Can you give us the client-side and server-side models you are using?

**Comment by airedwin** [comment]
public class Message {
        string id;
        string text;
        bool done;
        double latitude;
        double longitude;
        string userid;
        string username;
        string fullname;
        int duration;
        int radius;
        string parentmessageid;
        int replycount;
        DateTime created;

        [JsonProperty(PropertyName = "id")]
        public string Id {
            get {
                return id;
            }
            set {
                id = value;
            }
        }

        [JsonProperty(PropertyName = "text")]
        public string BodyText {
            get {
                return text;
            }
            set {
                text = value;
            }
        }

        [JsonProperty(PropertyName = "complete")]
        public bool Done {
            get {
                return done;
            }
            set {
                done = value;
            }
        }

        [JsonProperty(PropertyName = "latitude")]
        public double Latitude {

            get {
                return latitude;
            }

            set {
                latitude = value;
            }
        }

        [JsonProperty(PropertyName = "longitude")]
        public double Longitude {

            get {
                return longitude;
            }

            set {
                longitude = value;
            }
        }

        [JsonProperty(PropertyName = "userID")]
        public string UserID {

            get {
                return userid;
            }

            set {
                userid = value;
            }
        }

        [JsonProperty(PropertyName = "userName")]
        public string Username {

            get {
                return username;
            }

            set {
                username = value;
            }
        }

        [JsonProperty(PropertyName = "name")]
        public string Name {
            get {
                return fullname;
            }
            set {
                fullname = value;
            }
        }

        [JsonProperty(PropertyName = "radius")]
        public int Radius {

            get {
                return radius;
            }

            set {
                radius = value;
            }
        }

        [JsonProperty(PropertyName = "duration")]
        public int Duration {

            get {
                return duration;
            }

            set {
                duration = value;
            }
        }

        [JsonProperty(PropertyName = "parentID")]
        public string ParentMessageID {

            get {
                return parentmessageid;
            }
            set {

                parentmessageid = value;

            }
        }

        [JsonProperty(PropertyName = "replyCount")]
        public int ReplyCount {
            get {
                return replycount;
            }
            set {
                replycount = value;
            }
        }

        [JsonProperty(PropertyName = "createdAt")]
        public DateTime Created {
            get {
                return created;
            }
            set {
                created = value;
            }
        }
        [Version]
        public string Version {
            get; set;
        }
}

**Comment by airedwin** [comment]
public class Message : EntityData {
        public string Text {
            get; set;
        }

        public bool Complete {
            get; set;
        }

        public DbGeography Location {
            get; set;
        }

        public string UserID {
            get; set;
        }

        //public string UserName { get; set; }

        public int Radius {
            get; set;
        }

        public int Duration {
            get; set;
        }
        public string ParentID {
            get; set;
        }
        public Message ParentMessage {
            get; set;
        }
        public virtual ICollection<Message> Replies {
            get; set;
        }

        public User User {
            get; set;
        }

    }

public class MessageDTO : EntityData {
        private string parentid;

        public string Text {
            get; set;
        }

        public bool Complete {
            get; set;
        }

        public double? Latitude {
            get; set;
        }

        public double? Longitude {
            get; set;
        }

        public string UserID {
            get; set;
        }

        public string UserName {
            get; set;
        }

        public string Name {
            get; set;
        }

        public int Radius {
            get; set;
        }

        public int Duration {
            get; set;
        }

        public string ParentID {
            get;
            set;
        }

        private int replycount;
        public int ReplyCount {
            get {

                return replycount;
            }
            set {
                replycount = value;
            }
        }
    }

**Comment by adrianhall** [comment]
I could not reproduce this activity.  

I added the following test (in `unittest/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/Query/ZumoQuery.Test.cs`):

```
        [TestMethod]
        public void Issue220()
        {
            MobileServiceTableQueryDescription query = Compile<Product, Product>(table =>
                table.Where(u => (((u.Latitude - 10.0) * (u.Latitude - 10.0) + (u.Longitude - 10.0) * (u.Longitude - 10.0)) * 3280.8399 <= 10.0))
            );
            AssertFilter(query.Filter, "(((((Latitude sub 10.0) mul (Latitude sub 10.0)) add ((Longitude sub 10.0) mul (Longitude sub 10.0))) mul 3280.8399) le 10.0)");
        }
```

This unit test passes, meaning that the + is being translated to add. 

As a result, we will need both a backend and frontend minimal repro from you to continue this.  Please produce a GitHub project with a suitable backend and frontend UWP project in it that allows us to validate the issue.  It should be as minimal as possible.  Post the GitHub repo to this thread.

**Comment by adrianhall** [comment]
Based on lack of response and a valid test query, closing.  Please re-open if you have a github project that can repro so we can see what is going on.
