### ISSUE TITLE
Incorrect query filter string generated when JsonPropertyAttribute is used to rename properties of the data model

### ISSUE THREAD

**Issue by BioTurboNick** [Azure/azure-mobile-apps-net-client#226]
The below code produces the following filter query string for the Transactions table:
`(accountid eq '0f33d5d0-3063-4a03-835e-0e1c1fbce8a7')`

The column name is lowercase when it should be PascalCase. The latter value is a sample account id.

Meanwhile, the select query string is generated correctly:
`AccountId,Amount,Id,Version,CreatedAt,UpdatedAt,Deleted`

This is occurring because I have set `[JsonProperty(PropertyName = "accountid")]` on the AccountId property of the Transaction data model. Changing the attribute to "AccountId" produces the correct filter query string and allows the application to operate properly.

The use of JsonProperty to map property names to lowercase for Json serialization is demonstrated as proper in the TodoItem sample application.

I've included sample code below, stripped down and largely simplified to the most relevant parts.

```
public class AccountViewModel
{
    protected Account Model { get; }

    public static implicit operator T(AccountViewModel viewModel) { return viewModel.Model; }

    public MobileServiceCollection<Transaction, TransactionViewModel> Transactions;

    public AccountViewModel(Account model = null)
    {
        Model = (model == null) ? new Account() : model;
    }

    public async void LoadData()
    {
        Transactions = new MobileServiceCollection<Transaction, TransactionViewModel>(transactionsTable.Where((x) => x.AccountId == Model.Id), (x) => new TransactionViewModel(x));
        await Transactions.LoadMoreItemsAsync();
    }
}
```

```
    public class Transaction
    {
        public string Id { get; set; }

        [JsonProperty(PropertyName = "accountid")]
        public string AccountId { get; set; }

        [JsonProperty(PropertyName = "amount")]
        public decimal Amount { get; set; }
    }
```

```
public class TransactionViewModel
{
    protected Transaction Model { get; }

    public static implicit operator T(TransactionViewModel viewModel) { return viewModel.Model; }

    public TransactionViewModel(Transaction model = null)
    {
        Model = (model == null) ? new Transaction() : model;
    }
}
```

This was seen in Version 2.1.1

**Comment by BioTurboNick** [comment]
Confirmed in 3.0.1.

**Comment by elamalani** [comment]
@BioTurboNick Thanks for using Azure Mobile Apps. This bug was opened more than a year back. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps).  At this point, we are not fixing any bugs in the product unless it's a critical issue.

I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!

**Comment by BioTurboNick** [comment]
@elamalani  Okay, though the text you linked to does not specify criticality of bug fixes. Suggest changing that for clarity.

**Comment by elamalani** [comment]
@BioTurboNick Thanks for the feedback. We are looking to fix critical bugs that completely breaks the functionality and behavior of currently supported features.

**Comment by JoshuaWeber** [comment]
@BioTurboNick To build on what Ela mentioned. Please work with us to make sure we are categorizing correctly. Let us know if something we do doesn't seem right. Criticality is a hard thing to calculate. :)
