### ISSUE TITLE
Question: Is CurrentPlatform.Init(); still required?

### ISSUE THREAD

**Issue by jamesmontemagno** [Azure/azure-mobile-apps-net-client#230]
With the update to use SQLite.raw we no longer need to init for iOS, but what about Microsoft.WindowsAzure.MobileServices.CurrentPlatform.Init(); for iOS/Android?

**Comment by jamesmontemagno** [comment]
nm it is :)

**Comment by cheahengsoon** [comment]
How about for Xamarin Forms?

**Comment by adrianhall** [comment]
Ditto for Xamarin Forms.

**Comment by xtianus79** [comment]
+1 from Xamarin.Forms
