### ISSUE TITLE
Documenation -> Updating from 2.x to 3.0

### ISSUE THREAD

**Issue by jamesmontemagno** [Azure/azure-mobile-apps-net-client#231]
Seeing a bunch of questions come in on this. Would be nifty.

Such as: http://motzcod.es/post/150988588867/updating-azure-mobile-sqlitestore-to-30

**Comment by adrianhall** [comment]
THanks James - working on Docs now.

**Comment by adrianhall** [comment]
Fixed for the v3.0.2 release - will push the updates as soon as the release goes out.
