### ISSUE TITLE
How to provide tags using push.RegisterAsync(string RegiId, JObject templates)

### ISSUE THREAD

**Issue by mbharodia** [Azure/azure-mobile-apps-net-client#234]
I am not able to find any sample which, shows how to provide tags while registering a device using above method. If this is possible, the please let me know. If not, then I guess I need to handle it by writing my own API. Please let me know.

**Comment by mbharodia** [comment]
When I looked into GitHub to check the source to figure out the problem, I was able to locate the correct format of templates object.

push.RegisterAsync(.., ..) method eventually calls the following controller

https://github.com/Azure/azure-mobile-apps-net-server/blob/master/src/Microsoft.Azure.Mobile.Server.Notifications/Controllers/NotificationInstallationsController.cs

This controller has two parameters. One of them is an object of the following class

https://github.com/Azure/azure-mobile-apps-net-server/blob/master/src/Microsoft.Azure.Mobile.Server.Notifications/NotificationInstallation.cs

So, to provide tags correctly, a client must provide a valid instance to NotificationInstallation. You may want use the public property named "Tags" here and provide a list of tags. However, this would still not work because of the following bug. I have created this issue within project  Microsoft.Azure.Mobile.Server.Notifications on GitHub. I am yet to hear something from the project moderator or members. So I don't know whether what I have proposed is correct or not.

https://github.com/Azure/azure-mobile-apps-net-server/issues/162

However, I needed to complete my work so I implemented my own version of NotificationInstallationsController to fix the issue. It works for me indeed. So I think that what I have proposed should be correct.

I am adding this explanation here, in case, if some one is having the same problem and looking for any solution, then this would help. If you need further information, please let me know.

**Comment by adrianhall** [comment]
This is an old problem.  The answer is to use the new "App Service Push", which has replaced the old push blade.  Use of this push blade allows you to define tags that you allow.  Alternately, you can generate a custom API with your own logic that drives the Notification Hub.  Either way will work.

See also #247 that talks about an update to the client SDK that allows you to specify tags and templates.

**Comment by mbharodia** [comment]
Ok. Thanks a lot for your help!
