### ISSUE TITLE
System.TypeInitializationException with Version 3.0.1

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#235]
I just updated to v. 3.0.1 and get that. Any idea?

10-03 12:27:21.181 D/Mono (26453): Assembly Ref addref Microsoft.WindowsAzure.Mobile.SQLiteStore[0x5aec1fa0] -> System.Runtime.Extensions[0x5af51e68]: 5
10-03 12:27:21.191 D/Mono (26453): Assembly Ref addref Microsoft.WindowsAzure.Mobile.SQLiteStore[0x5aec1fa0] -> SQLitePCLRaw.batteries_green[0x5aed27f8]: 2
10-03 12:27:21.191 D/Mono (26453): Assembly Ref addref SQLitePCLRaw.batteries_green[0x5aed27f8] -> SQLitePCLRaw.provider.e_sqlite3[0x5aed5060]: 2
10-03 12:27:21.191 D/Mono (26453): Assembly Ref addref SQLitePCLRaw.provider.e_sqlite3[0x5aed5060] -> SQLitePCLRaw.core[0x5aed3530]: 3
10-03 12:27:21.201 D/Mono (26453): Assembly Ref addref SQLitePCLRaw.batteries_green[0x5aed27f8] -> SQLitePCLRaw.core[0x5aed3530]: 4
10-03 12:27:21.211 D/Mono (26453): DllImport attempting to load: 'e_sqlite3'.
10-03 12:27:21.211 D/Mono (26453): DllImport error loading library './libe_sqlite3': 'Cannot load library: load_library[1093]: Library '/data/data/com.xamarin.sample.mobile_rolsped/lib/./libe_sqlite3' not found'.
10-03 12:27:21.221 D/Mono (26453): DllImport loaded library './libe_sqlite3.so'.
10-03 12:27:21.221 D/Mono (26453): DllImport searching in: 'e_sqlite3' ('./libe_sqlite3.so').
10-03 12:27:21.221 D/Mono (26453): Searching for 'sqlite3_libversion_number'.
10-03 12:27:21.221 D/Mono (26453): Probing 'sqlite3_libversion_number'.
10-03 12:27:21.221 D/Mono (26453): Found as 'sqlite3_libversion_number'.
10-03 12:27:21.231 D/Mono (26453): DllImport searching in: 'e_sqlite3' ('./libe_sqlite3.so').
10-03 12:27:21.231 D/Mono (26453): Searching for 'sqlite3_open'.
10-03 12:27:21.231 D/Mono (26453): Probing 'sqlite3_open'.
10-03 12:27:21.231 D/Mono (26453): Found as 'sqlite3_open'.
10-03 12:27:21.241 D/Mono (26453): DllImport searching in: 'e_sqlite3' ('./libe_sqlite3.so').
10-03 12:27:21.241 D/Mono (26453): Searching for 'sqlite3_close'.
10-03 12:27:21.241 D/Mono (26453): Probing 'sqlite3_close'.
10-03 12:27:21.241 D/Mono (26453): Found as 'sqlite3_close'.
10-03 12:27:21.281 D/Mono (26453): DllImport searching in: 'e_sqlite3' ('./libe_sqlite3.so').
10-03 12:27:21.281 D/Mono (26453): Searching for 'sqlite3_errmsg'.
10-03 12:27:21.281 D/Mono (26453): Probing 'sqlite3_errmsg'.
10-03 12:27:21.281 D/Mono (26453): Found as 'sqlite3_errmsg'.
Unhandled Exception:

System.TypeInitializationException: The type initializer for 'mobile_rolsped.TodoItemManager' threw an exception.

**Comment by ericsink** [comment]
I can't be sure, but it looks like the call to sqlite3_open() in SqlitePCLRawHelpers.GetSqliteConnection() is returning an error.  The most likely reason for this is something wrong with the filename passed in, but I can't tell for sure where that filename might have come from.

@ericbrunner Are you saying that your code was working fine with the previous version, then you updated to 3.0.1, and there were no other changes to your code or the project, and this error happened?

**Comment by ericsink** [comment]
I wonder if this is related to issue #233

**Comment by jamesmontemagno** [comment]
@ericbrunner how are you initializing the file path?

**Comment by ericbrunner** [comment]
@ericsink 
right, no code changes. only update to 3.0.1. 
@jamesmontemagno
exactly like described here: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-offline-data/

**Comment by ericbrunner** [comment]
I just downloaded the quickstart xamarin.forms xaml PCL project from my Azure Mobile Apps backend

**Comment by jamesmontemagno** [comment]
I am not sure if they have updated that quick start yet...

You may need to manually update it via my upgrade guide:
http://motzcod.es/post/150988588867/updating-azure-mobile-sqlitestore-to-30

Essentially there is a little bit of work to set it up different on Android for the file location. Windows/iOS should be alright.

**Comment by jamesmontemagno** [comment]
They are slowly updating all the docs and there is already an issue specific for Xamarin.Forms quick start: https://github.com/Azure/azure-mobile-apps-quickstarts/issues/78

**Comment by adrianhall** [comment]
Fixed in cf9e640
