### ISSUE TITLE
Call SQLitePCL.Batteries.Init() only once

### ISSUE THREAD

**Issue by ericsink** [Azure/azure-mobile-apps-net-client#236]
In GetSqliteConnection(), it looks like Batteries.Init() is being called every time a SQLite connection is opened.

It would be better to call this function only one time, such as in a static constructor.

**Comment by jamesmontemagno** [comment]
I was under the assumption that the developer has to actually call this... is this not the case?

If the library is calling Init() then that is great :)

**Comment by adrianhall** [comment]
Fixed in 641c88e
