### ISSUE TITLE
VerifySQLiteResponse might call sqlite3_errmsg() with a null connection handle

### ISSUE THREAD

**Issue by ericsink** [Azure/azure-mobile-apps-net-client#237]
In GetSqliteConnection(), VerifySQLiteResponse() is called to check the result of sqlite3_open.  However, if the open fails, the connection will be null, and that connection handle will be passed to sqlite3_errmsg(), which I don't think is allowed.  In this case, you would want to instead call sqlite3_errstr() with the return code from sqlite3_open().

**Comment by dhei** [comment]
this should be fixed by #252

**Comment by adrianhall** [comment]
Closing - this will be released in the next release.
