### ISSUE TITLE
API to reset delta tokens of sync table

### ISSUE THREAD

**Issue by ceichin** [Azure/azure-mobile-apps-net-client#238]
When user logs out I purge all data using `await table.PurgeAsync (true);` for every table, but delta tokens that contain the last datetime of last pulls for each query id are not deleted. This makes in next login to pull only new data, but old data is missing. I considered to purge specifying the queryId, but I can have N queryIds depending on objects Id (for example queryId="websiteArticles-{websiteId}").

For now I'm using the following code as a workaround, but it should be implemented better:

```
var configs = await store.ReadAsync (new MobileServiceTableQueryDescription ("__config"));
var toDelete = new List<string> ();
foreach (var config in configs)
{
   var id = config ["id"];
   if (id != null)
   {
      string idString = id.ToString ();
      //if (idString.Contains ($"deltaToken|{typeof (T).Name}|")) // For especific table
      if (idString.Contains ($"deltaToken|")) // All delta tokens across all tables
      {
          toDelete.Add (idString);
      }
   }
}
await store.DeleteAsync ("__config", toDelete);
```

It would be nice to have an API to do this easily!

Reference: 
https://social.msdn.microsoft.com/Forums/azure/en-US/29122a1f-0126-41a0-a7c0-312694c65e42/reset-delta-tokens-of-sync-table?forum=azuremobile

**Comment by ceichin** [comment]
The code I provided does not work completely as values are cached, as shown here: https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/MobileServiceSyncSettingsManager.cs#L46

**Comment by aline-almeida** [comment]
I'm developing a UWP app and also came across this issue. This would be very helpful!

**Comment by adrianhall** [comment]
Dup of #164
