### ISSUE TITLE
Query related objects

### ISSUE THREAD

**Issue by maxsieben** [Azure/azure-mobile-apps-net-client#239]
I'm sorry if this is the wrong place to ask questions.

I'm having two models on my Xamarin client app, where the Test Model has the id value of the Project Model:

```
public class Test : BaseModel
{
 ...
  [JsonProperty(PropertyName = "name")]
  public string Name { get; set; }
  [JsonProperty(PropertyName = "project_id")]
  public string Project_Id { get; set; }
}

public class Project : BaseModel
{
  [JsonProperty(PropertyName = "name")]
  public string Name { get; set; }
}
```
Now my question: I'm getting all my Test Models with the where query:
`await testTable.Where(some_condition_to_get_test_models)`
This yields me a list of Test objects, now I can do things like testObj.Name .

Is there a possibility to get the related Project in one query, so that I can call sth. like testObj.Project.Name to get the Projects Name for a Test Object?

Or do I have to do sth. like projectTable.LookupAsync(testObj.Project_Id) to get the related Project?

**Comment by adrianhall** [comment]
I'd recommend reading the data chapter (chapter 3) of my book, which covers relationships.  The link is http://aka.ms/zumobook
