### ISSUE TITLE
Exception if not specifying full path

### ISSUE THREAD

**Issue by jamesmontemagno** [Azure/azure-mobile-apps-net-client#244]
In 3.0.2:

Haven't been able to test iOS yet, but this code works:

```
var path = "syncstore.db";
path = Path.Combine(MobileServiceClient.DefaultDatabasePath, path);
//setup our local sqlite store and intialize our table
var store = new MobileServiceSQLiteStore(path);
```
This code fails:
```
var path = "syncstore.db";

//setup our local sqlite store and intialize our table
var store = new MobileServiceSQLiteStore(path);
```

Browsing through the code it makes no sense unless for some reason the android part isn't being called due to something weird. Not sure. 

You can test this in: https://github.com/jamesmontemagno/app-coffeecups

**Comment by dhei** [comment]
v3.0.3 is released. Close this.

https://github.com/Azure/azure-mobile-apps-net-client/releases/tag/3.0.3
