### ISSUE TITLE
SQLLiteStore Version 3.0.1 Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceTableOperationError

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#246]
Hi,

I struggle currently with a curious error. I use Microsoft.Azure.Mobile.Client.SQLiteStore Version 3.0.1 in my Azure Xamarin.Forms Mobile App. When I have Internet Connection in the Android Emulator I can Read, Update or Delete records. I checked it in my backend in the MS SQL Server.

I wanted to test Offline Sync. Therefore I switched to Airplain Mode in the emulator to simulate a disconnection from the web. Then I did an update in my App and changed one field. I saw the change in the App. So far so good. Then I reconnection (Airplain mode off). I use Xam.Plugin.Connectivity. The ConnectityEvent was fired and now I was connected. Within the Eventhandler I do a complete Resync (PullAsync with implicite Push).

At the first PullAsync with a pending Change I get an exception.

Detailed error description: [Stackoverflow](http://stackoverflow.com/questions/39995322/sqllitestore-version-3-0-1-microsoft-windowsazure-mobileservices-sync-mobileservl)

I just saw that a new Version is available. After updating to Version 3.0.2 it seems to work in my described Case but I had to fully uninstall previous Version of my App on Phones and additionally clear all Cache and App data (incl. Database) on the Phone.

I just got it running with new Version but wanted to Report the bug here, too.

Thanks for any further advice. Currently I am not certain if it is really working for 100%.

Eric

**Comment by dhei** [comment]
v3.0.3 is released.
