### ISSUE TITLE
push should have method that takes in Installation

### ISSUE THREAD

**Issue by ysxu** [Azure/azure-mobile-apps-net-client#247]
Current push methods take in two forms:
- register(token)
- register(token, templates)

We need an additional:
- register(Installation)

that reflects https://msdn.microsoft.com/en-us/library/azure/microsoft.azure.notificationhubs.notificationhubclient.createorupdateinstallation.aspx.

There's no way for customers to pass tags in from the client side currently, hence they won't be able to take advantage of the app service push endpoint tags feature.

Chat with me when this is started. I'm trying to convince NH to release an Installation object PCL for convenience.

**Comment by elamalani** [comment]
Hi there, please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK. Thanks!
