### ISSUE TITLE
NotSupportedException in Offline Sync Mode v. 3.0.3

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#249]
Hi,

I have a curious issue. In the official Xamarin.Froms TodoItems sample from the Azure site I have even in Offline enabled mode a query on the table like that:

`var items = await todoTable
                    .Where(todoItem => !todoItem.Done)
                    .ToEnumerableAsync();`

No problem it works. That sample has Verison 2.1.1 of Client/SQLiteStore.

In my current project I am on Version 3.0.3 of Client / SQLLiteStore and a query like that throws a NotSupportedException:

`IEnumerable<TruckFahrer> items = 
                    await OfflineSyncStoreManager.Instance.TruckFahrerTable
                    .Where(fahrerinfo => fahrerinfo.Imei.Equals(imei)) //TODO: Why does that throw an exception???
                    .ToEnumerableAsync();`

I posted a more detailed description on: [SO](http://stackoverflow.com/questions/40073288/azure-mobile-apps-offline-client-throws-notsupportedexception-on-query)

What am I doing wrong?
thanks,
Eric

**Comment by dhei** [comment]
@ericbrunner You just use `.Where(fahrerinfo => fahrerinfo.Imei == imei).ToEnumerableAsync()` instead of .Equals(), right?

**Comment by ericbrunner** [comment]
@dhei I use `.Where(fahrerinfo => fahrerinfo.Imei.Equals(imei))` Why does that throw an exception???

**Comment by ericbrunner** [comment]
@dhei I have one query where it is working. The only difference is that the `imei` is of type `string` and the `selectedAuftragTruckAppId `is of type `int`:

` IEnumerable<TruckAuftragLauf> items = await OfflineSyncStoreManager.Instance.TruckAuftragLaufTable
                    .Where(auftraglauf => auftraglauf.TruckAppId == selectedAuftragTruckAppId)
                    .OrderBy(auftraglauf => auftraglauf.Sortierzahl)
                    .ToEnumerableAsync()
                    .ConfigureAwait(false);`

That query works fine.

**Comment by adrianhall** [comment]
@ericbrunner Did you try @dhei comment to use == instead?  The where clauses are parsed, and not all functions are available, so that may just make the difference.

**Comment by ericbrunner** [comment]
@adrianhall yes, works

**Comment by adrianhall** [comment]
Ok.  I can see why it doesn't work.  We parse the Where clauses and there is only a subset of functions.  Because we support ==, we don't support .Equals().
