### ISSUE TITLE
Sync times increasing drastically over time

### ISSUE THREAD

**Issue by ashbrandfour** [Azure/azure-mobile-apps-net-client#251]
We've implemented the sync functionality in to a large enterprise solution and found that over time the Sync times are increasing as it appears to by trying to sync every row of the local database with the every row of the remote one for each sync. At the moment we are pulling latest and then pushing the changes.

Is there a way to update only the rows that have been updated since the last pull and push?

**Comment by williamsrz** [comment]
We have the same trouble here, this is a excellent question.

**Comment by shrishrirang** [comment]
https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-offline-data-sync/#how-sync-works explains how to use _incremental sync_ to pull server changes since the last pull.
