### ISSUE TITLE
Azure MobileServices - background sync with foreground updates = Busy errors

### ISSUE THREAD

**Issue by Hangarspace** [Azure/azure-mobile-apps-net-client#253]
In simple terms, with a background thread performing PushAsync and PullAsync's, any foreground database inserts (or updates) can result in 'Busy' errors if the timing happens to clash.  

We are writing a Xamarin Forms UWP app and using the Azure Mobile Services to pull data into a SQLite db (IMobileServiceSyncTable), work offline and push changes back and in general this works really well.

However, more extensive testing is throwing up some SQLite 'Busy' errors when a background sync is in progress and we try to update or insert new records in response to actions on the UI ie the user edits a record. 

All actions are performed on the IMobileServiceSyncTable, all the same context etc so should all be using the same connection underneath. I know what the busy message means but was hoping that by doing everything thru the same context that the locking would somehow be better.

At first it seems like we just neeed to implement our own locking between the updating and sync processess, but this isn't really practical and in the real world where a sync process could take several minutes due to many factors then it's not really practical to leave the user hanging whilst it waits.

We are using Microsoft.Azure.Mobile.Client version 2.0.1. Previously we have written similar apps using the Microsoft Sync Framework with SQLite on the client for offline access, background syncs and foreground updates and didn't get this problem.

**Comment by adrianhall** [comment]
We are no longer working on Mobile.Client v2.0.1.  Can you retry on the latest version.  If it is still happening, then please reopen.  

It would also be helpful to see a minimal repro project.  We've had problems in the past reproducing threading issues (which is obnoxious), so if you have one you can share, all the better.

Closing this for now, as later versions fixed many threading issues.
