### ISSUE TITLE
PullAsync: Failed to read the item from local store

### ISSUE THREAD

**Issue by jasonccliu** [Azure/azure-mobile-apps-net-client#255]
I want to update LocalDB record to Azure and it has failed.

There are few steps in my testing plan.

1. First Sync LocalDB & AzureDB. 
2. Update 'PhoneCallHistory' item record in LocalDB by UI
3. Manually update 'PhoneCallHistory' item record on Azure
4. Try to Sync data and force overwrite LocalDB record to Azure

In step 4 got the error as follows.

> Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceLocalStoreException: Failed to read the item from local store. 
System.InvalidOperationException: Table with name 'PhoneCallHistory' is not defined.

How could I catch those conflict items at MobileServicePushFailedException event?

p.s. using Microsoft.Azure.Mobile.Client version 3.0.3

**Comment by adrianhall** [comment]
The error would indicate that your local offline sync store is not set up properly.  What does your store initialization code look like?

For conflict resolution, see the docs at https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#a-nameofflinesyncawork-with-offline-tables

**Comment by jasonccliu** [comment]
Hi, 

Here are my code snippet.
Each action will call  Initialize(); to make sure the DB has been initiated.

I got this issue when I made actions (delete, update or insert) more than twice.

`
    
    public class AzureDataManager<T> : IAzureDataManager<T> where T : IAzureEntity
    {
        public IMobileServiceSyncTable<T> SyncTable { get; set; }
        public MobileServiceClient client { get; set; } = null;
        private const string defaultQueryId = "alldata";
        private string queryId;
        private IMobileServiceTableQuery<T> customQuery;
        public Func<T, bool> customQueryLocal;

        public async Task Initialize()
        {
            if (client?.SyncContext?.IsInitialized ?? false)
                return;
            this.client = new MobileServiceClient(AppSettings.AzureMobileAPPUrl);

            var path = AppSettings.SQLiteDBName;

            path = Path.Combine(MobileServiceClient.DefaultDatabasePath, path);

            var store = new MobileServiceSQLiteStore(path);

            store.DefineTable<T>();

            await this.client.SyncContext.InitializeAsync(store, new MobileServiceSyncHandler());

            this.SyncTable = client.GetSyncTable<T>();
        }

        public async Task SaveTaskAsync(T item)
        {

            var saveableEntity = item as IAzureEntity;
            if (saveableEntity == null)
                throw new ArgumentException("item should be of type IAzureEntity");

            await Initialize();

            if (saveableEntity.Id == null)
            {
                await SyncTable.InsertAsync(item);
            }
            else
            {
                try
                {
                    await SyncTable.UpdateAsync(item);
                }
                catch (MobileServicePreconditionFailedException<T> ex)
                {
                    Debug.WriteLine(ex.ToString());
                    //local item first
                    item.Version = ex.Item.Version;
                    await SaveTaskAsync(item);
                }
                catch (MobileServiceInvalidOperationException ex)
                {
                    // ...push failed
                    // ...do manual conflict resolution
                    Debug.WriteLine(ex.ToString());
                }
            }
        }

        public async Task<ObservableCollection<T>> GetTasksAsync(bool syncItems = false)
        {
            try
            {
                await Initialize();

                if (syncItems)
                {
                    await this.SyncAsync();
                }

                var items = await SyncTable.ToEnumerableAsync();

                if (customQueryLocal != null)
                {
                    items = items.Where(customQueryLocal);
                }

                return new ObservableCollection<T>(items);
            }
            catch (MobileServiceInvalidOperationException msioe)
            {
                Debug.WriteLine(@"INVALID {0}", msioe.Message);
            }
            catch (Exception e)
            {
                Debug.WriteLine(@"ERROR {0}", e.Message);
            }
            return null;
        }

        public async Task DeleteTaskAsync(T item)
        {
            try
            {
                await Initialize();
                await SyncTable.DeleteAsync(item);
            }
            catch (MobileServiceInvalidOperationException msioe)
            {
                Debug.WriteLine(@"INVALID {0}", msioe.Message);
            }
            catch (Exception e)
            {
                Debug.WriteLine(@"ERROR {0}", e.Message);
            }
        }

        public virtual async Task SyncAsync()
        {
            ReadOnlyCollection<MobileServiceTableOperationError> syncErrors = null;
            try
            {
                if (!(await CrossConnectivity.Current.IsRemoteReachable(client.MobileAppUri.Host, 443)))
                {
                    Debug.WriteLine($"Cannot connect to {client.MobileAppUri} right now - offline");
                    return;
                }

                await Initialize();

                await this.client.SyncContext.PushAsync();

                if (string.IsNullOrEmpty(queryId) && customQuery == null)
                    await SyncTable.PullAsync(defaultQueryId, SyncTable.CreateQuery());
                else
                    await SyncTable.PullAsync(queryId, customQuery);

            }
            catch (MobileServicePushFailedException exc)
            {
                Debug.WriteLine(exc.Message);
                //For the offline case, the code would look like this:
                if (exc.PushResult != null)
                {
                    syncErrors = exc.PushResult.Errors;
                }
            }
            catch (MobileServicePreconditionFailedException<T> exp)
            {
                Debug.WriteLine(exp.Message);

            }
            catch (MobileServiceConflictException cex)
            {
                Debug.WriteLine(cex.Message);
                throw;
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                throw;
            }

            await HandleSyncErrors(syncErrors);
        }

        public virtual async Task HandleSyncErrors(ReadOnlyCollection<MobileServiceTableOperationError> syncErrors)
        {
            // Simple error/conflict handling. A real application would handle the various errors like network conditions,
            // server conflicts and others via the IMobileServiceSyncHandler.
            if (syncErrors != null)
            {
                foreach (var error in syncErrors)
                {
                    if (error.OperationKind == MobileServiceTableOperationKind.Update && error.Result != null)
                    {
                        //Update failed, reverting to server's copy.
                        await error.CancelAndUpdateItemAsync(error.Result);
                    }
                    else
                    {
                        // Discard local change.
                        await error.CancelAndDiscardItemAsync();
                    }
                }
            }
        }

        public void SetQuery(string queryId, IMobileServiceTableQuery<T> query)
        {
            customQuery = query;
            this.queryId = queryId;
        }


`

**Android Project**
`

-- MainActivity.cs
protected override void OnCreate(Bundle bundle)
{
            base.OnCreate(bundle);
            Microsoft.WindowsAzure.MobileServices.CurrentPlatform.Init();
            global::Xamarin.Forms.Forms.Init(this, bundle);
            LoadApplication(new App());
}


`

**Comment by adrianhall** [comment]
Do you have an azuredatamanager per table?  If so, you are going to run into problems.  The MobileServiceClient is meant to be global, and you will bump into issues with multiple tables, as you are re-initializing the table each time.

**Comment by jasonccliu** [comment]
Yes, I already know this issue.
I will try to fix my code and refer to "[TaskList](https://github.com/adrianhall/develop-mobile-apps-with-csharp-and-azure/tree/master/Chapter3/TaskList/TaskList/Services
)" sample code.

Thanks for your help.

**Comment by adrianhall** [comment]
Great - glad you found this issue.  I'll leave this open for another 2 weeks.  If you have more issues beyond that one, then please add on some detail.  If not, feel free to close, or I will in 2 weeks time.
