### ISSUE TITLE
Updating from 2.01 to 3.0.3 - LookupAsync returns null while the data IS there

### ISSUE THREAD

**Issue by FrancoisM** [Azure/azure-mobile-apps-net-client#256]
As I was encoutering that [issue](https://github.com/Azure/azure-mobile-apps-net-client/issues/186#issuecomment-258223747), I tried to update from 2.0.1 to 3.0.3 (latest available).
However, the following line was returning null while, FOR SURE, the data was there:
`var user = await userTable.LookupAsync(userId);`
As I'm running out of schedule on my project, I didn't try to understand the issue further and reverted to 2.0.1.

**Comment by adrianhall** [comment]
To clarify:
1) You are using SQLiteStore - useTable is retrieved using client.GetSyncTable<T>()?
2) Your userId is the Id field of the user record exactly.

Do you have a repro that demonstrates the issue?

**Comment by FrancoisM** [comment]
0) Same line works on 2.01. It broke when running on iOS. I haven't even tried UWP or Android. It could be a sqlite issue as I had errors about missing libraries (pclrawcore and pclblend or something) that I had to install from nuget. With 2.0.1 I have PCLRaw_Basic. Unfortunately I didn't keep any track of that upgrade to give you more details.

1) Yes

2) Yes

Repro: nope. I haven't spent time on that. I'm fine with 2.01 except for that other [issue](https://github.com/Azure/azure-mobile-apps-net-client/issues/186#issuecomment-258223747). I upgraded to 3.0.3, got that problem and went back to 2.0.1.

**Comment by adrianhall** [comment]
ok - thanks - we'll take a look at the upgrade issue.

**Comment by FrancoisM** [comment]
I've tried to upgrade once more from 2.1.1 to 3.0.3 trying to solve that other [issue](https://github.com/Azure/azure-mobile-apps-net-client/issues/264) but it didn't.

Back to the missing data.
Here are my steps:

1°) Upgrade from 2.1.1 to 3.0.3 => doesn't build and complains that SQLitePCLRaw.core is missing.
2°) Install SQLitePCLRaw.core => doesn't build and complains that SQLitePCLRaw.batteries_green is missing.
3) Install SQLitePCLRaw.bundle_green and uninstall SQLitePCL.raw_basic. I still have SQLitePCL 3.8.7.2, do I need it? => builds on iOS but COMPILETODALVIK error on Android.

Now I have a line of code _userTable.LookupAsync(id) that systematically returns null WHILE I can see that the row is there in the open db (after the upgrade I noticed it move to within the .app folder)!

**Comment by FrancoisM** [comment]
I'm sure my two issues are related.
I don't get null because the data is not there (it is lol) but because of multithreading.
I can see from logs that the line failing on one thread while on another thread the same id is pulled from the backend:        https:\\blabla\tables\User?filter=((Id eq 'the id'....
When I add some locks in order not to lookup and pull the same id, it now works.

**Comment by FrancoisM** [comment]
Managed to build android after setting the heap size in Android Options.
However, it doesn't run:
Microsoft.WindowsAzure.MobileServices.SQLiteStore.SQLiteException: Error executing SQLite command: 'unable to open database file'.

**Comment by adrianhall** [comment]
Hi @FrancoisM  - I'm still unable to repro this.  Just checked in a fix to #264 though.  If you have time, please re-validate this bug.  Build the library from the master branch and use that.  If you can't repro this, then please close.  

If we don't get a test case that can reproduce this, then I'm going to have to close it as unreproducable.

**Comment by FrancoisM** [comment]
Hi @adrianhall ,

I think it's fine to close it as no one else reported the issue and as far as I'm concerned I'm running a custom version of the library derived from version 2.
I really wish I could find the time to look further into it to help you help me (true for many issues I raise actually) but as a lone dev I'm already drowning :-( 

Tks a lot for the great work though.
