### ISSUE TITLE
Can't create a local sync database in WPF application.

### ISSUE THREAD

**Issue by WiteCastle** [Azure/azure-mobile-apps-net-client#257]
I can't create a local sync database in a WPF app (tested in .NET 4.5.2 and 4.6) on the first run because it can't open the SQLite file. If I navigate to the folder where I try to create the SQLite file I can see that it has been created but it's only 0kb in size. If I rerun my app it is able to open the file just fine. But trying it on the first run never works. I tried recreating the issue with a simple WPF application and the following code:

```
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            var client = new MobileServiceClient(@"http://dev-mobile-app.azurewebsites.net/");

            var syncDbFilePath = Path.Combine(MobileServiceClient.DefaultDatabasePath,
                @"WPF\App\Folder\testdb.db");

            var store = new MobileServiceSQLiteStore(syncDbFilePath);
        }
    }

```
And the error is very cryptic...

`Additional information: Error executing SQLite command: 'unable to open database file'.`

I tried to open the file in the same code with a simple File.Open(syncDbFilePath) but I get an error that another process is using the file. I used the Resource Monitor to see what apps were accessing the file while running and it shows that my app is the only process accessing that file. However, if I close and rerun the app the code works fine... I've updated to MobileServiceClient 3.0.3 and am using SQLitePCLRaw 1.0.0. Updating SQLitePCLRaw to 1.1.0 didn't help either.

**Comment by jamesmontemagno** [comment]
I don't believe the Mobile SDK supports WPF:

Supported platforms

Xamarin Android releases for API 19 through 24 (KitKat through Nougat)
Xamarin iOS releases for iOS versions 8.0 through 10.0
Universal Windows Platform
Windows Phone 8.1
Windows Phone 8.0

from the readme.

**Comment by WiteCastle** [comment]
Thanks for the quick response. I thought the listed platforms might've been an oversight since Microsoft has said they haven't given up on WPF yet. But is the Mobile Apps team really not going to support WPF? It used to work fine with Mobile Services and I believe SQLitePCLRaw works on WPF so shouldn't it work here as well?

If the Mobile Apps team has no plans to support WPF than I believe this issue can be closed.

**Comment by adrianhall** [comment]
WPF is not a platform that we test on or have any coverage on.  If it worked before, it was accidental.  Our recommendation is to use UWP, which we do support.

**Comment by ferrydeboer** [comment]
I was trying to write integration tests for my app that then go all the way down the database but do reroute sync calls. So just as the above example this is a regular .net class library. I considered this an easier scenario than mocking out a layer. Though it's apparently not supported, everything seems to be working fine as soon as the database does in fact exist.

What are the possibilities to get this supported? Submit a PR?

**Comment by adrianhall** [comment]
We are happy to review a PR for this.  However, please be aware that our direction is towards .NET Standard 1.6 compatibility and leaving the older platforms behind.

**Comment by WiteCastle** [comment]
@ferrydeboer Nice find, did you have a chance to create a PR for this?
