### ISSUE TITLE
[Managed] Local store encryption with SQLite Cipher

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-mobile-apps-net-client#26]
Managed: SQLite Cipher for secure offline - waiting for SqliteCipher PCL

**Comment by adrianhall** [comment]
@pragnagopa released the SQLite Encryption blog post, so I don't see this as an issue any more.  Due to export restrictions, we are not going to be producing any package for this.

**Comment by seanfisher** [comment]
@adrianhall @pragnagopa I think [this is the post you are referring to](https://azure.microsoft.com/en-in/documentation/samples/app-service-mobile-dotnet-offline-encryption/), which demonstrates using SQLite Encryption Extension. Is there an example for using SQLCipher somewhere?

**Comment by adrianhall** [comment]
No, there is not.  We felt demonstrating the technique for encryption was enough, especially as encryption code generally has restrictions for release.
