### ISSUE TITLE
Setup for Microsoft.Azure.Mobile.Client.SQLiteStore v3.0.3 in Xamarin.Forms.Droid + Xamarin.Forms.iOS

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#260]
Hi,

What do I have to setup in the Mainactivty (Droid) and AppDelegate(iOS) for current v.3.0.3?

Currently I have that:

**Droid:**

    `// See: http://motzcod.es/post/150988588867/updating-azure-mobile-sqlitestore-to-30
	Constants.SqliteStorePath =
		Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal),
			Constants.SqliteStorePath);

	if (!File.Exists(Constants.SqliteStorePath))
	{
		// Create SQLite Store file 
		File.Create(Constants.SqliteStorePath).Dispose();
	}

	Microsoft.WindowsAzure.MobileServices.CurrentPlatform.Init();

	//Call this in each platform before intializing your Mobile Client
	SQLitePCL.Batteries.Init();

	DroidApplication = new App();
	LoadApplication(DroidApplication);`

**iOS:**

    `//TODO Same MobileServiceClient.DefaultDatabasePath in Droid App ???

	Helper.Constants.SqliteStorePath = Path.Combine(MobileServiceClient.DefaultDatabasePath,
				Helper.Constants.SqliteStorePath);

	MobileServiceClient.EnsureFileExists(Helper.Constants.SqliteStorePath);

	Microsoft.WindowsAzure.MobileServices.CurrentPlatform.Init();

	//Call this in each platform before intializing your Mobile Client
	SQLitePCL.Batteries.Init();

	LoadApplication (new App ());

	return base.FinishedLaunching (app, options);`

thanks,
Eric

**Comment by jamesmontemagno** [comment]
The only thing that you need I believe is


Microsoft.WindowsAzure.MobileServices.CurrentPlatform.Init();

**Comment by ericbrunner** [comment]
Thanks for your reply but I use Azure Offline Sync and I have to delete the Database file in scenarios when my backend SQL Server had a schema change.

**Comment by jamesmontemagno** [comment]
Your code looks fine.

I do not think you need SQLitePCL.Batteries.Init(); anymore as they call it for you.

**Comment by adrianhall** [comment]
Correct - your code is actually overkill now since we work out the appropriate path based on the platform.  You don't need the SQLitePCL.Batteries.Init() any more.
