### ISSUE TITLE
push.RegisterAsync(registrationId) no longer works

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-net-client#261]
The push endpoint now takes an Installation.  The RegisterAsync() method does not produce a correct installation object.  Specifically, it is missing the InstallationId.

**Comment by adrianhall** [comment]
Closing - this is a problem in the backend, not the frontend.

**Comment by ericbrunner** [comment]
Related to [https://github.com/Azure/azure-mobile-apps-net-server/issues/170](url)
