### ISSUE TITLE
Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceLocalStoreException: Failed to perform operation on local store. ---> System.FormatException: String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#265]
Hi,

I get that exception only on my Lenovo Tablet (APILEVEL 19). On phones like a HTC Desire 510 in APILEVE 19 the same code works.

> Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceLocalStoreException: Failed to perform operation on local store. ---> System.FormatException: String was not recognized as a valid DateTime.
>   at System.DateTimeParse.Parse (System.String s, System.Globalization.DateTimeFormatInfo dtfi, System.Globalization.DateTimeStyles styles) [0x00026] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/globalization/datetimeparse.cs:2282 
>   at System.DateTime.Parse (System.String s, System.IFormatProvider provider) [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/datetime.cs:1032 
>   at System.Convert.ToDateTime (System.String value, System.IFormatProvider provider) [0x0000e] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/convert.cs:1733 
>   at System.String.System.IConvertible.ToDateTime (System.IFormatProvider provider) [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/string.cs:3397 
>   at System.Convert.ToDateTime (System.Object value, System.IFormatProvider provider) [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/convert.cs:1721 
>   at Newtonsoft.Json.Linq.JToken.op_Explicit (Newtonsoft.Json.Linq.JToken value) [0x0005f] in <2781d1b198634655944cdefb18b3309b>:0 
>   at Newtonsoft.Json.Linq.JToken.ToObject (System.Type objectType) [0x0027e] in <2781d1b198634655944cdefb18b3309b>:0 
>   at Newtonsoft.Json.Linq.JToken.ToObject[T] () [0x00000] in <2781d1b198634655944cdefb18b3309b>:0 
>   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.SqlHelpers.SerializeDateTime (Newtonsoft.Json.Linq.JToken value) [0x00000] in <294b68c809824838a8d1375e83943bc8>:0 
>   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.SqlHelpers.SerializeAsNumber (Newtonsoft.Json.Linq.JToken value, Newtonsoft.Json.Linq.JTokenType columnType) [0x00005] in <294b68c809824838a8d1375e83943bc8>:0 
>   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.SqlHelpers.SerializeValue (Newtonsoft.Json.Linq.JToken value, System.String storeType, Newtonsoft.Json.Linq.JTokenType columnType) [0x0003c] in <294b68c809824838a8d1375e83943bc8>:0 
>   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore.AddParameter (Newtonsoft.Json.Linq.JObject item, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, Microsoft.WindowsAzure.MobileServices.SQLiteStore.ColumnDefinition column) [0x00019] in <294b68c809824838a8d1375e83943bc8>:0 
>   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore.BatchUpdate (System.String tableName, System.Collections.Generic.IEnumerable`1[T] items, System.Collections.Generic.List`1[T] columns) [0x000c7] in <294b68c809824838a8d1375e83943bc8>:0 
>   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore+<>c__DisplayClass10_0.<UpsertAsyncInternal>b__0 (System.Threading.Tasks.Task t) [0x0005d] in <294b68c809824838a8d1375e83943bc8>:0 
>   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke () [0x00027] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:63 

This is the custom JSON Serializer/Deserializer:

```
public class CustomDateTimeConverter : DateTimeConverterBase
    {
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteValue(((DateTime)value).ToString());
        }
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            DateTime? date = (DateTime?)reader.Value;
            // NOTE: The default JSON deserializer assumes the received date is UTC time and adds 2 hours to our local time.
            // Which is wrong. That cast solves the problem to get the date we received and not some formatted that from JSON.NET
            return date;
        }
    }
```

That is the Property where I apply the serializer:

		[JsonConverter(typeof(CustomDateTimeConverter))]
		public DateTime? DatumAnkunftIst { get; set; }

and here the code where it happens at the UpdateAsync call:

            storeTruckAuftragLauf.StatusId = workflowItem.NewTruckAuftragLaufStatusId;
            storeTruckAuftragLauf.DatumAnkunftIst = DateTime.Now;

            storeTruckAuftragLauf.UpdatedAtMobileApp = true;

            await OfflineSyncStoreManager.Instance.TruckAuftragLaufTable.UpdateAsync(storeTruckAuftragLauf);

TruckAuftragLaufTable is a Offlinesync table:

        public readonly IMobileServiceSyncTable<TruckAuftragLauf> TruckAuftragLaufTable;

Hope someone can give me a hint why that happens.
thanks
Eric

**Comment by ericbrunner** [comment]
Modified to CultureInfo.InvariantCulture in the `CustomDateTimeConverter `solved that issue:

`writer.WriteValue(((DateTime)value).ToString(CultureInfo.InvariantCulture));`

**Comment by adrianhall** [comment]
Since this was fixed in the custom date/time converter, closing.
