### ISSUE TITLE
Xamarin.iOS: A Microsoft Azure Mobile Services assembly for the current platform was not found

### ISSUE THREAD

**Issue by strillo** [Azure/azure-mobile-apps-net-client#271]
Hi, 
I'm trying to add MobileServiceClient to a Xamarin.iOS project but keep getting the exception above.
As soon as the code calls

_client = new MobileServiceClient( mobileServiceUri );

I get the "A Microsoft Azure Mobile Services assembly for the current platform was not found. Ensure that the current project references both Microsoft.WindowsAzure.Mobile and the following platform-specific assembly: Microsoft.WindowsAzure.Mobile.Ext."

I am using Microsoft.Azure.Mobile.Client 3.0.3 from NuGet, and the Microsoft.WindowsAzure.Mobile & Microsoft.WindowsAzure.Mobil.Ext dlls are referenced in the project references.

I've tried changing the iOS target versions, as well as manually adding references from the lib/monotouch folder (as opposed to lib/Xamarin.iOS10) but to no avail.

Any ideas?

Thansk!
Marco

**Comment by adrianhall** [comment]
Do you have a project we can look at that exhibits this behavior?  Also, are you building this on Mac (if so, Xamarin Studio or VS for Mac and version of the build?) or PC (in which case, VS version and Xamarin version is needed, plus the Xamarin version on your connected Mac).

**Comment by strillo** [comment]
Hi Adrian, thanks for the prompt response!

Attached is a test project, which is basically a vanilla iPhone app + the Microsoft.Azure.Mobile.Client package. The error occurs when trying to initialise MobileServiceClient inside AppDelegate.FinishedLaunching.

I am working on Xamarin Studio on Mac. Details below:

=== Xamarin Studio Indie ===

Version 6.1.2 (build 44)
Installation UUID: 8b7332c0-48f1-4e69-80d9-a81413af849c
Runtime:
	Mono 4.6.2 (mono-4.6.0-branch/08fd525) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 406020007

=== NuGet ===

Version: 3.4.3.0

=== Xamarin.Profiler ===

Not Installed

=== Apple Developer Tools ===

Xcode 8.1 (11544)
Build 8B62

=== Xamarin.Mac ===

Version: 2.10.0.113 (Xamarin Indie)

=== Xamarin.Android ===

Version: 7.0.2.37 (Xamarin Indie)
Android SDK: /Users/marco/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.1   (API level 16)
		4.2   (API level 17)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)

SDK Tools Version: 25.1.6
SDK Platform Tools Version: 24.0.0
SDK Build Tools Version: 23.0.2

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Android Player ===

Not Installed

=== Xamarin.iOS ===

Version: 10.2.1.5 (Xamarin Indie)
Hash: 44931ae
Branch: xcode8.1
Build date: 2016-11-01 20:52:28-0400

=== Xamarin Inspector ===

Version: 1.0.0.0
Hash: 1f3067d
Branch: master
Build date: 15/11/2016 21:13:59

=== Build Information ===

Release ID: 601020044
Git revision: 0ccfcd52b95305ebd5b7eca0d88c1017035910ae
Build date: 2016-10-28 15:12:43-04
Xamarin addins: a39a869d8a78d87bdc6775f696c13a4cc9024501
Build lane: monodevelop-lion-cycle8

=== Operating System ===

Mac OS X 10.12.1
Darwin MacBook-Pro-6.local 16.1.0 Darwin Kernel Version 16.1.0
    Thu Oct 13 21:26:57 PDT 2016
    root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

NuGet Package Management Extensions 0.11
Xamarin Inspector 1.0.0.0


[Test.zip](https://github.com/Azure/azure-mobile-apps-net-client/files/646940/Test.zip)

**Comment by strillo** [comment]
I have also tried compiling the package myself but keep getting the same error. Looks like Microsoft.WindowsAzure.Mobile.Ext.dll fails to load at runtime due to some missing dependency. No idea which one though, all the relevant dlls should be linked and available.

**Comment by marcostae** [comment]
I had the same problem recently but with Android, and apparently it was happening because I had installed WindowsAzure.MobileServices package through NuGet and it was somehow interfering with Microsoft.Azure.Mobile.Client. So the only way I could make it to work again was to rollback the project to a state before the WindowsAzure.MobileServices was installed and installed just the Microsoft.Azure.Mobile.Client package. I hope this helps!

**Comment by adrianhall** [comment]
I just compiled your project with no problems from my PC with a connected Mac doing the build.  Does the error occur during build or running?

**Comment by strillo** [comment]
Hi Adrian,
Compilation is fine. The error occurs at runtime. 
Marco

Get Outlook for iOS

		_____________________________

**Comment by adrianhall** [comment]
You are missing a CurrentPlatform.Init() call.  Adding that before your MobileServiceClient fixed the problem.

A good example is our TodoItem samples, available at azure/azure-mobile-apps-quickstarts

**Comment by strillo** [comment]
Wonderful it worked! 
Thanks, I wasn't using the pre-built samples and hadn't seen that line anywhere in the documentation. The call to Init seems to fix the issue. 👍

**Comment by adrianhall** [comment]
I'll get the docs updated.
