### ISSUE TITLE
IncludeTotalCount/TotalCount not working when compiled with .Net Native tool chain + Optimize code

### ISSUE THREAD

**Issue by RamonLR** [Azure/azure-mobile-apps-net-client#278]
We are getting allways -1 as result of property **TotalCount** in **IQueryResultEnumerable**<T>.
This issue only happens when we compile our app with .NET Native tool chain and code optimization.
It works properly in any other compilation mode.
This is the code we are using:

        public async Task<int> GetItemCountAsync<T>(Expression<Func<T, bool>> predicate = null) where T : BaseModel
        {
            var table = SyncService.MobileService.GetSyncTable<T>();
            IMobileServiceTableQuery<T> query = table.IncludeTotalCount();
            if (predicate != null)
                query = query.Where(predicate);
            query = query.Take(0);

            var results = await query.ToEnumerableAsync();
            return (int)((IQueryResultEnumerable<T>)results).TotalCount;
        }

**Comment by adrianhall** [comment]
@RamonLR - do you have a specific repro test that gets this?  I've been unable to reproduce this one.

**Comment by RamonLR** [comment]
Hi Adrian. 
I have writen a little test Project in VS 2015 but before sending it to you I have given it a try with VS 2017 
I turns out that the issue is solved in **Microsoft.NETCore.UniversalWindowsPlatform 5.3.0**

**Comment by RamonLR** [comment]
Hi @adrianhall.
I have writen a little test Project in VS 2015 but before sending it to you I have given it a try with VS 2017
I turns out that the issue is solved in **Microsoft.NETCore.UniversalWindowsPlatform 5.3.0**

**Comment by adrianhall** [comment]
Glad to hear it is solved with tooling.  I as never able to reproduce.
