### ISSUE TITLE
DateTimeOffsets lose precision

### ISSUE THREAD

**Issue by gcrockenberg** [Azure/azure-mobile-apps-net-client#279]
DateTimeOffset values lose their precision after serialization to SQLite.  Viewing inbound and outbound data through Request.Content in a custom AuthenticationHandler shows roundtripkind DateTimeOffset values are pushed back as Zulu time.

"2017-01-12T21:46:29.4511230+00:00"
is pushed back as
"2017-01-12T21:46:29.451Z"

**Comment by adrianhall** [comment]
Can you please provide a unit test that shows this off?  Also, what is the impact to your code specifically?

**Comment by gcrockenberg** [comment]
My app generates transactions quickly and I use DateTimeOffsets to time stamp them.  The order of transactions are important so I want to retain as much precision as possible.   

Was able to retain precision when pushing to Azure by overriding JsonConvert.DefaultSettings in my Xamarin Forms app.

            JsonConvert.DefaultSettings = () =>
            {
                return new JsonSerializerSettings
                {
                    DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK",
                    DateParseHandling = DateParseHandling.None,
                    DateTimeZoneHandling = Newtonsoft.Json.DateTimeZoneHandling.RoundtripKind,
                    Converters = new List<JsonConverter>
                    {
                        new MyIsoDateTimeConverter(),
                        new MobileServicePrecisionCheckConverter()
                    }
                };
            };
