### ISSUE TITLE
MobileServiceClient.get_DefaultDatabasePath not found

### ISSUE THREAD

**Issue by DumDumin** [Azure/azure-mobile-apps-net-client#281]
Hey guys,

I have trouble getting sqlite running with azure-mobile-service on android (uwp is running fine and I havent tried ios yet)

In the Android project I added:
- Microsoft.WindowsAzure.Mobile
- Microsoft.WindowsAzure.Mobile.Ext
- Microsoft.WindowsAzure.Mobile.SQLiteStore

And I call this at the application start in the Android project:

`Microsoft.WindowsAzure.MobileServices.CurrentPlatform.Init();`

In my PCL I added:
- Microsoft.WindowsAzure.Mobile
- Microsoft.WindowsAzure.Mobile.SQLiteStore

To get the database going I call this:

            try
            {
                _client = new MobileServiceClient(mobileServiceConnection);

                _sqLiteStore = new MobileServiceSQLiteStore(localDb);
                _sqLiteStore.DefineTable<PositionData>();
                
                await Client.SyncContext.InitializeAsync(_sqLiteStore);
                _offlineTable = Client.GetSyncTable<PositionData>();
            }
            catch (Exception ex)
            {
            }

"System.MissingMethodException: Method 'Microsoft.WindowsAzure.MobileServices.MobileServiceClient.get_DefaultDatabasePath' not found…"

Same goes for a call to 
`EnsureFileExist(localDb);`

System.MissingMethodException: Method 'Microsoft.WindowsAzure.MobileServices.MobileServiceClient.EnsureFileExists' not found.

It seems like the CurrentPlatform.Init() call doesnt do its job.
I also found in your library, that both calls go to Platform.Instance.., which is initilized with this:

```
// create if not yet created
                if (current == null)
                {
                    //assume the platform assembly has the same key, same version and same culture
                    // as the assembly where the IPlatformProvider interface lives.
                    var provider = typeof(IPlatform);
                    var asm = new AssemblyName(provider.GetTypeInfo().Assembly.FullName);
                    //change name to the specified name
                    asm.Name = PlatformAssemblyName;
                    var name = PlatformTypeFullName + ", " + asm.FullName;

                    //look for the type information but do not throw if not found
                    var type = Type.GetType(name, false);
                    if (type != null)
                    {
                        // create type
                        // since we are the only one implementing this interface
                        // this cast is safe.
                        current = (IPlatform)Activator.CreateInstance(type);
                    }
                    else
                    {
                        // throw
                        ThrowForMissingPlatformAssembly();
                    }
                }

return current;
```

I dont know how to understand this, or how to ensure it:
```
//assume the platform assembly has the same key, same version and same culture
// as the assembly where the IPlatformProvider interface lives.
```

Thanks for any help!

**Comment by adrianhall** [comment]
What versions of the libraries are you using?

**Comment by DumDumin** [comment]
I fixed it this morning.. 
The assembly android::label didnt match to the PCL assembly name where the SQLiteStore is created..
So your comments in the code helped me finding the error, but you should have a section in your README for this, because not everyone uses the default assembly names ;)
