### ISSUE TITLE
Incremental sync not working at all

### ISSUE THREAD

**Issue by rusty21** [Azure/azure-mobile-apps-net-client#282]
I've read through the documentation found here
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-offline-data-sync#how-sync-works

Something tells me I'm doing something wrong though.

My pull async looks like
`await Results.PullAsync ("Results", Results.CreateQuery());`

The records in the results table have a "meaningful" value. As far as I know that means a not null value of `DateTimeOffset.UtcNow`

It seems that none of the records are synced when I try to use incremental sync. If I pass in `null`
as the queryId then I get the records to come down from the server. Is there something I'm missing or is this a bug?

**Comment by adrianhall** [comment]
We need more information - offline sync is verified working in our tests, so it's likely something in your code.  What does your model look like?  What about the initializer?  Have you changed the model in the interim?  More code is required.

**Comment by adrianhall** [comment]
No response, so closing.

**Comment by rusty21** [comment]
Sorry I we've been busy and implementing incremental sync hasn't been a priority, but I'd still like to get this working at some point. Is there an example you can point me to that has this working so I can see if my code differs in a significant way?

**Comment by adrianhall** [comment]
Plenty of examples in the book - http://aka.ms/zumobook

**Comment by nareshy-menlo** [comment]
I am facing the same issue in iOS

```
[self.syncTable pullWithQuery:query queryId:nil completion:^(NSError *error) {
}];
```
This function can get all the records from the server. But when i used the queryId like

```
[self.syncTable pullWithQuery:query queryId:@"AllRecords" completion:^(NSError *error) {
}];
```
Its getting partial data from the server. Any help here?

**Comment by hashmurali** [comment]
Did anyone manage to resolve the issue?
