### ISSUE TITLE
Add AlternatePushUrl setting for local development

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-net-client#283]
Handle the case when development of the server is happening locally, but App Service Push is being used.

Set client.AlternatePushUrl
If not set, use client.AlternateLoginUrl (if set)
If still not set, don't worry about it

If set to the URL of the remote backend, send the push requests there instead of localhost.

**Comment by elamalani** [comment]
Hi there, please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK. Thanks!
