### ISSUE TITLE
InsertAll support

### ISSUE THREAD

**Issue by ertay** [Azure/azure-mobile-apps-net-client#285]
Right now the only way to insert multiple items to a table is looping through them and inserting them one by one. It would be great if there was a way to do this in one go.

**Comment by mjo151** [comment]
This is painful when inserting a large number of items. The SDK posts one item at a time to the mobile app server, which is very inefficient and slow.

**Comment by elamalani** [comment]
@ertay Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us to prioritize this work in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
