### ISSUE TITLE
InvalidOperationException : The operation has been updated and cannot be updated again

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#289]
Hi,

Today I got that exception and currently scratch my head because I can't find an error in my code. Hope you can help me.

Microsoft.Azure.Mobile.Client: v.3.1.0
Microsoft.Azure.Mobile.Client.SQLiteStore: v.3.1.0

Type: InvalidOperationException 
Message The operation has been updated and cannot be updated again

Stacktrace:

> at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext+<TryUpdateOperation>d__38.MoveNext () [0x0009c] in <42e24ce875d34485ad11c4f8aebb904a>:0 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext+<>c__DisplayClass37_0+<<UpdateOperationAsync>b__0>d.MoveNext () [0x00085] in <42e24ce875d34485ad11c4f8aebb904a>:0 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext+<ExecuteOperationSafeAsync>d__44.MoveNext () [0x0027f] in <42e24ce875d34485ad11c4f8aebb904a>:0 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceTableOperationError+<UpdateOperationAsync>d__46.MoveNext () [0x00084] in <42e24ce875d34485ad11c4f8aebb904a>:0 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at trucker_rolsped.StoreManager.OfflineSyncStoreManager+<HandleConflictResolutionOfLocalTablePushAttemptAsync>d__39.MoveNext () [0x0078c] in <83128fa36e514d9aa8d72b6818c53c68>:0 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at trucker_rolsped.StoreManager.OfflineSyncStoreManager+<PushAsync>d__48.MoveNext () [0x002ad] in <83128fa36e514d9aa8d72b6818c53c68>:0 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <89f0138272a14db2a1c42fdf1f9746a2>:0 
>   at trucker_rolsped.Workflow.WorkflowTaskCommandFactory+<>c__DisplayClass35_0+<<Task70ActionAsync>b__0>d.MoveNext () [0x002cf] in <83128fa36e514d9aa8d72b6818c53c68>:0

Code for **PushAsync**:

        public async Task PushAsync(string contextName)
        {
            bool isConnected = await IsRemoteBackendReachable();
            // Sync is only enabled in Connected Mode. What should I sync in offline mode. There is not connection to the remote-db
            // When it is online then a sync from the local-db with the remote-db is possible.
            if (!isConnected)
            {
                return;
            }

            const int maxAttempts = 5;
            int currentAttempts = 0;
            MobileServicePushFailedException mobileServicePushFailedException = null;

            while (OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations > 0 && (currentAttempts < maxAttempts))
            {
                ReadOnlyCollection<MobileServiceTableOperationError> syncErrors = null;

                try
                {
                    System.Diagnostics.Debug.WriteLine($"Pending Ops before PUSH: {OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations}");

                    // PUSH all local.db changes to the remote.db (changes of all tables are pushed to achieve referential integrity)
                    await OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PushAsync();

                    System.Diagnostics.Debug.WriteLine($"Pending Ops after PUSH: {OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations}");
                }
                catch (MobileServicePushFailedException e)
                {
                    isConnected = await IsRemoteBackendReachable();

                    if (isConnected)
                    {
                        mobileServicePushFailedException = e;

                        if (e.PushResult != null)
                        {
                            syncErrors = e.PushResult.Errors;
                        }

                        if (syncErrors != null)
                        {
                            System.Diagnostics.Debug.WriteLine($"Pending Ops before CONFLICT HANDLER: {OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations}");
                            await HandleConflictResolutionOfLocalTablePushAttemptAsync(syncErrors);
                            System.Diagnostics.Debug.WriteLine($"Pending Ops after CONFLICT HANDLER: {OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations}");
                        }

                        currentAttempts++;
                    }
                    else
                    {
                        await MetricsManagerHelper.Instance.SendInfoToApplicationInsightsAsync("Internet Connection lost while data sync. Data sync not done.");
                        break;
                    }
                }
                catch (Exception e)
                {
                    isConnected = await IsRemoteBackendReachable();

                    if (isConnected)
                    {
                        await MetricsManagerHelper.Instance.SendExceptionToApplicationInsightsAsync(e);
                    }
                    else
                    {
                        await MetricsManagerHelper.Instance.SendInfoToApplicationInsightsAsync("Internet Connection lost while data sync. Data sync not done.");
                    }
                }
            }

            if (isConnected && OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations > 0)
            {
                if (mobileServicePushFailedException != null)
                    await MetricsManagerHelper.Instance.SendExceptionToApplicationInsightsAsync(mobileServicePushFailedException);

                await MetricsManagerHelper.Instance.SendInfoToApplicationInsightsAsync("Internet Connection lost while data sync. Data sync not done.");
            }
        }

Code to **handle conflicts**:

    private async Task   HandleConflictResolutionOfLocalTablePushAttemptAsync(ReadOnlyCollection<MobileServiceTableOperationError> syncErrors)
        {
            /*
             * * Handling Conflict Resolution
                         
             * * see :https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter3/client/#handling-conflict-resolution
             * * */

            // Simple error/conflict handling. A real application would handle the various errors like network conditions,
            // server conflicts and others via the IMobileServiceSyncHandler.
            if (syncErrors != null)
            {
                foreach (var error in syncErrors)
                {
                    var localItem = error.Item;
                    var serverItem = error.Result;

                    if (error.OperationKind == MobileServiceTableOperationKind.Update && error.Result != null)
                    {
                        var localVersion = localItem?[MobileServiceSystemColumns.Version];
                        var serverVersion = serverItem?[MobileServiceSystemColumns.Version];

                        if (localVersion == null)
                        {
                            if (await IsRemoteBackendReachable())
                            {
                                await MetricsManagerHelper.Instance
                                    .SendErrorToApplicationInsightsAsync($"Operation: {error.OperationKind} LocalVersion == NULL." +
                                                                         "Action: Reverting to remote-db server's copy\r\n" +
                                                                         $"Table: {error.TableName} Record Id: {localItem?[MobileServiceSystemColumns.Id]}\r\n" +
                                                                         $"Local: {localItem}\r\n" +
                                                                         $"Server: {serverItem}");

                                //Update failed, reverting to server's copy.
                                await error.CancelAndUpdateItemAsync(serverItem);
                            }
                            else
                            {
                                await MetricsManagerHelper.Instance.SendInfoToApplicationInsightsAsync($"Operation: {error.OperationKind} LocalVersion == NULL." +
                                                                                                       "Internet Connection lost while data sync. Data sync not done.");
                            }

                            continue;
                        }

                        if (serverVersion == null)
                        {
                            if (await IsRemoteBackendReachable())
                            {
                                await MetricsManagerHelper.Instance
                                    .SendErrorToApplicationInsightsAsync($"Operation: {error.OperationKind} ServerVersion == NULL.\r\n" +
                                                                         "Action: Reverting to remote-db server's copy\r\n" +
                                                                         $"Table: {error.TableName} Record Id: {localItem?[MobileServiceSystemColumns.Id]}\r\n" +
                                                                         $"Local: {localItem}\r\n" +
                                                                         $"Server: {serverItem}");

                                //Update failed, reverting to server's copy.
                                await error.CancelAndUpdateItemAsync(serverItem);
                            }
                            else
                            {
                                await MetricsManagerHelper.Instance.SendInfoToApplicationInsightsAsync($"Operation: {error.OperationKind} ServerVersion == NULL." +
                                                                                                       "Internet Connection lost while data sync. Data sync not done.");
                            }

                            continue;
                        }

                        // Set Local version to Server Version an Update again. PendingOpertation is set to new updated localItem and in outer loop a PushAsync is attempted again.
                        localItem[MobileServiceSystemColumns.Version] = serverItem[MobileServiceSystemColumns.Version];

                        if (await IsRemoteBackendReachable())
                        {
                            await error.UpdateOperationAsync(JObject.FromObject(localItem));
                        }
                        else
                        {
                            await MetricsManagerHelper.Instance.SendInfoToApplicationInsightsAsync($"Operation: {error.OperationKind} LocalVersion older than (<) ServerVersion." +
                                                                                                   "Internet Connection lost while data sync. Data sync not done.");
                        }
                    }
                    else
                    {
                        if (await IsRemoteBackendReachable())
                        {
                            await MetricsManagerHelper.Instance
                                .SendErrorToApplicationInsightsAsync($"Operation: {error.OperationKind} PUSH failed.\r\n" +
                                                                     "Action: Discard local-db change.\r\n" +
                                                                     $"Table: {error.TableName} Record Id: {localItem?[MobileServiceSystemColumns.Id]}\r\n" +
                                                                     $"Local: {localItem}\r\n" +
                                                                     $"Server: {serverItem}");

                            // Discard local change.
                            await error.CancelAndDiscardItemAsync();
                        }
                        else
                        {
                            await MetricsManagerHelper.Instance.SendInfoToApplicationInsightsAsync($"Operation: {error.OperationKind} PUSH failed." +
                                                                                                   "Internet Connection lost while data sync. Data sync not done.");
                        }
                    }
                }
            }
        }

Thanks in advance for pointing me in the right direction

Eric

**Comment by adrianhall** [comment]
Thanks - we will take a look.  Off the top of my head, I don't see anything obviously wrong with the code.

I'm not seeing which actual operation is causing the error.  Perhaps you can clarify by stepping through the code?

**Comment by ericbrunner** [comment]
It was a multithreading problem. I called `PushAsync `from different threads. After modification with a `SemaphorSlim `lock it never appeared again:

        //Instantiate a Singleton of the Semaphore with a value of 1. This means that only 1 thread can be granted access at a time.
        private readonly SemaphoreSlim _mutex = new SemaphoreSlim(1, 1);

        public async Task PushAsync(string contextName)
        {
            if (_mutex.CurrentCount == 0)
            {
                await MetricsManagerHelper.Instance.SendGenericMessageToApplicationInsightsAsync("SyncLock-PushAsync", "No further threads can enter critical section.");
            }
            //Asynchronously wait to enter the Semaphore. If no-one has been granted access to the Semaphore, 
            //code execution will proceed, otherwise this thread waits here until the semaphore is released
            await _mutex.WaitAsync();

            try
            {
                bool isConnected = await IsRemoteBackendReachable();
                // Sync is only enabled in Connected Mode. What should I sync in offline mode. There is not connection to the remote-db
                // When it is online then a sync from the local-db with the remote-db is possible.
                if (!isConnected)
                {
                    return;
                }

                const int maxAttempts = 5;
                int currentAttempts = 0;
                MobileServicePushFailedException mobileServicePushFailedException = null;


                while (OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations > 0 && (currentAttempts < maxAttempts))
                {
                    ReadOnlyCollection<MobileServiceTableOperationError> syncErrors = null;

                    try
                    {
                        System.Diagnostics.Debug.WriteLine($"Pending Ops before PUSH: {OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations}");

                        // PUSH all local.db changes to the remote.db (changes of all tables are pushed to achieve referential integrity)
                        await OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PushAsync();

                        System.Diagnostics.Debug.WriteLine($"Pending Ops after PUSH: {OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations}");
                    }
                    catch (MobileServicePushFailedException e)
                    {
                        isConnected = await IsRemoteBackendReachable();

                        if (isConnected)
                        {
                            mobileServicePushFailedException = e;

                            if (e.PushResult != null)
                            {
                                syncErrors = e.PushResult.Errors;
                            }

                            if (syncErrors != null)
                            {
                                System.Diagnostics.Debug.WriteLine($"Pending Ops before CONFLICT HANDLER: {OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations}");
                                await HandleConflictResolutionOfLocalTablePushAttemptAsync(syncErrors);
                                System.Diagnostics.Debug.WriteLine($"Pending Ops after CONFLICT HANDLER: {OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations}");
                            }

                            currentAttempts++;
                        }
                        else
                        {
                            await MetricsManagerHelper.Instance.SendInfoToApplicationInsightsAsync("Internet Connection lost while data sync. Data sync not done.");
                            break;
                        }
                    }
                    catch (Exception e)
                    {
                        isConnected = await IsRemoteBackendReachable();

                        if (isConnected)
                        {
                            await MetricsManagerHelper.Instance.SendExceptionToApplicationInsightsAsync(e);
                        }
                        else
                        {
                            await MetricsManagerHelper.Instance.SendInfoToApplicationInsightsAsync("Internet Connection lost while data sync. Data sync not done.");
                        }
                    }
                }


                if (isConnected && OfflineSyncStoreManager.Instance.MobileAppClient.SyncContext.PendingOperations > 0)
                {
                    if (mobileServicePushFailedException != null)
                        await MetricsManagerHelper.Instance.SendExceptionToApplicationInsightsAsync(mobileServicePushFailedException);

                    await MetricsManagerHelper.Instance.SendInfoToApplicationInsightsAsync("Internet Connection lost while data sync. Data sync not done.");
                }
            }
            catch (Exception e)
            {
                await MetricsManagerHelper.Instance.SendExceptionToApplicationInsightsAsync(e);
            }
            finally
            {
                // When the task is ready, release the semaphore.It is vital to ALWAYS release the semaphore when we are ready, or else we will end up with a Semaphore that is forever locked.
                //This is why it is important to do the Release within a try...finally clause; program execution may crash or take a different path, this way you are guaranteed execution
                _mutex.Release();
            }
        }

**Comment by adrianhall** [comment]
Good to know - there is another discussion in #264 which probably will fix your case as well.  I am going to do a PR there.  If that doesn't fix your issue when we release that, then feel free to re-open this.
