### ISSUE TITLE
The request could not be completed.  (Bad Request) on PullAsync

### ISSUE THREAD

**Issue by myokeeh** [Azure/azure-mobile-apps-net-client#292]
I'm trying to do something pretty basic, but I keep getting a "The request could not be completed.  (Bad Request)" error (Status Code 400). Is this a bug? Available doc seems outdated: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-offline-data-sync#how-sync-works

`await myTable.PullAsync("someid", myTable.Where(we => we.personId != somePersonId), false, new CancellationToken(), new PullOptions());`

**Comment by adrianhall** [comment]
The error code 400 is from the backend.  Can you please use a Fiddler trace and post the result from that - explicitly, what URI is being requested?

As an aside, is there a reason why you are not doing this filtering on the server side?

**Comment by myokeeh** [comment]
From the sample code and documentation provided, I assumed this is how it's done.

The thought behind is to sync only the relevant data for the person in context. ~20 records per person vs. ~20,000 records in the table. Primarily, this is to save time.

Per your suggestion to use Fiddler, I was able to make this work by adding an attribute 


HTTP/1.1 400 Bad Request
Content-Length: 151
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/8.0
X-Powered-By: ASP.NET
Date: Fri, 10 Mar 2017 03:36:28 GMT

{"message":"The query specified in the URI is not valid. Could not find a property named 'PersonId' on type 'Backend.DataObjects.PersonStringChange'."}

GET https://XXXX.azurewebsites.net/tables/SomeTable?$filter=((personId%20ne%20'9494ed6ddd21424394521ed00befe083')%20and%20(updatedAt%20ge%20datetimeoffset'1970-01-01T00%3A00%3A00.0000000%2B00%3A00'))&$orderby=updatedAt&$skip=0&$top=50&__includeDeleted=true

**Comment by adrianhall** [comment]
Nice that it is telling you what is wrong.  It's definitely that PersonId field that is causing the issue.  Generally, Entity Framework and the Newtonsoft.Json serializer do wierd things - EF requires upper case first letter, but JSON expects a lower-case first letter.  Thus we have these differing mechanisms.

This seems to be in the heart of EF that you are having the problem.  I'd start by attaching the VS debugger to the backend service and stepping throuhg your controllers GetAllItems() method.

**Comment by adrianhall** [comment]
Closing based on no update.
