### ISSUE TITLE
TaskCanceledException on PullAsync

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#294]
Azure Mobile Client SDK: **v3.1.0**

Sometimes after a internet reconnect in the Xamarin.Forms Android App when I Pull my table data I get a TaskCanceledException. Hope someone can explain me why and how to overcome that.

Code ran into `if` branch of the Exception `try-catch` block So the Remote Mobile Apps backend was reachable. I guess I run into a kind of default PullAsync TaskCancellation Timeout. Right? 

```
catch (Exception e)
            {
                isConnected = await IsRemoteBackendReachable();

                if (isConnected)
                {
                    await MetricsManagerHelper.Instance.SendExceptionToApplicationInsightsAsync(e);
                }
            }

```
Code:

```
 public async Task SyncTagSpracheTableInLocalStoreAsync()
        {
            bool isConnected = await IsRemoteBackendReachable();
            // Sync is only enabled in Connected Mode. What should I sync in offline mode. There is not connection to the remote-db
            // When it is online then a sync from the local-db with the remote-db is possible.
            if (!isConnected)
            {
                return;
            }

            ReadOnlyCollection<MobileServiceTableOperationError> syncErrors = null;

            try
            {
                // see: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter3/client/
                // see: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter3/dataconcepts/#offline-synchronization
                // Implict PUSH local-db changes to remote-db. Then PULL the remote-db data into local-db tables
                await OfflineSyncStoreManager.Instance.TagSpracheTable.PullAsync(TagSpracheQueryAll, _tagSpracheTableQuery);
                await OfflineSyncStoreManager.Instance.TagSpracheStore.InitLocalStoreCacheAsync();
            }
            catch (MobileServicePushFailedException e)
            {
                isConnected = await IsRemoteBackendReachable();

                if (isConnected)
                {
                    await MetricsManagerHelper.Instance.SendExceptionToApplicationInsightsAsync(e);

                    if (e.PushResult != null)
                    {
                        syncErrors = e.PushResult.Errors;
                    }
                }
            }
            catch (Exception e)
            {
                isConnected = await IsRemoteBackendReachable();

                if (isConnected)
                {
                    await MetricsManagerHelper.Instance.SendExceptionToApplicationInsightsAsync(e);
                }
            }

            if (await IsRemoteBackendReachable() && syncErrors != null)
            {
                try
                {
                    await HandleConflictResolutionOfLocalTablePushAttemptAsync(syncErrors);
                }
                catch (Exception e)
                {
                    await MetricsManagerHelper.Instance.SendExceptionToApplicationInsightsAsync(e);
                }
            }
        }
```

**Type**
`TaskCanceledException`

**Message**
`A task was canceled.`

**Source**
`mscorlib`

**Stacktrace**

see that gist: https://gist.github.com/ericbrunner/579011390e9554724c29ac14d553c4a0

**Comment by ericbrunner** [comment]
Is the LocalStore Table preserved in it's previous state on such exception or is it corrupted?

**Comment by adrianhall** [comment]
The LocalStore table should always be in a reasonable state - it should never be corrupted.  That being said, there is always a chance that something bad happened.

**Comment by ericbrunner** [comment]
In the last few weeks I received again several `TaskCanceledException` exceptions from the app deployed to our in-field clients. No disconnection to internet happened.

When exactly those `PullAsync` throw a `TaskCanceledException` and how can I overcome that?

Obviously I run into a kind of timeout.

**Comment by stefvanhooijdonk** [comment]
You say, this is happening in the field also, could you indicate what type connections (speed/conditions) this is happening on?

**Comment by ericbrunner** [comment]
@stefvanhooijdonk It happens in the field when the connection is poor or a disconnection happens while data sync (which is the root cause). I catch the excpetion and on re-connect I attempt to sync again which works fine.

**Comment by rneeft** [comment]
@ericbrunner hi Eric, I've raised this issue: [Unable to synchronise on a slow connection (TaskCanceledException)](https://github.com/Azure/azure-mobile-apps-net-client/issues/323) It is kind of releated to yours. We are unable to sync at all, even after a re-connect.

**Comment by ericbrunner** [comment]
@rneeft Hello , I put my Offline Sync Store Manager implementation as gist here: [https://gist.github.com/ericbrunner/44fe9d0aeb82227ebc38d2b3b53a32c6](https://gist.github.com/ericbrunner/44fe9d0aeb82227ebc38d2b3b53a32c6)

I use Xamarin.Plugin.ConnectionManager (I guess you to). When for example my method `PushPurgePullOfAllTablesInLocalStoreAsync()` (line: 1157) fails for some some reason (almost on a poor connection or a disconnection while sync attempt) that method gets incoked again on reconnect in the Connection Event Handler of the above mentioned plugin (see line 297).

`await OfflineSyncStoreManager.Instance.PushPurgePullOfAllTablesInLocalStoreAsync();`

I have several fail safe mechnaismn in error and conflict handlnig implemented there. Also notice the use of SemaphoreSlim locks. That is used to ensure that only one thread at a time can enter the critical section. I use Push Messages and her it can heappen that a Push Message arrives , the associated push command tries to invoked the `PushPurgePullOfAllTablesInLocalStoreAsync` method while the Connectivity Event handler wants to do the same and in addition the user in the UI tries to save something. Well a lot to synchronize.

I hope I helped you out a bit, feel free to take out of the code what you need if it fits to your business case.

From my experience in my business case it is the best to PUSH all pending changes from local.db (Xamarin App) to remote.db (Azure Mobile REST API Backend) , the purg ethe whole local.db to get a clean fresh local.db and then extablish a full pull from remote.db into local.db. Well we don't havbe tousends of records so that approach is ok. But on an App you seldomly have so much records. Of cource it could be tweaked to be more optimized but it works well , stable and the response time is within a few secodns on a push, purge, pull. In our case that is fine, despite the fact that on slow connections the best database sync impl. can't help you running faster ;-)

best
Eric
