### ISSUE TITLE
ODataExpressionParser Incorrectly Flags "Any" Operation on $filter with Parse Error

### ISSUE THREAD

**Issue by lthib** [Azure/azure-mobile-apps-net-client#297]
Since my Azure SDK endpoint is backed by Entity Framework and fully supports navigation properties, I've been doing a bit of custom pull processing that allows for more complex strategies on the filter with the use of `Task MobileServiceSyncTableExtensions.PullAsync(this IMobileServiceSyncTable table, string queryId, string query, IDictionary<string, string> parameters, CancellationToken cancellationToken)`. I've generated a $filter string that runs effortlessly on the table endpoint if requested in Postman, but the query parser balks at the query's `NavigationCollection/any(x1:...)` syntax with `MobileServiceODataException: The specified odata query has syntax errors`.

I don't expect support for navigation properties from the SDK, as I've built out my own framework for expanding navigation properties and supporting them in locally executed Where clauses, but please don't artificially limit my code's capability to leverage the full range of OData filter syntax on pull.

**Comment by lthib** [comment]
After investigating it would appear this behavior is more wide-spread than I anticipated, as the parser does more than validation and seemingly rewrites my entire query string to remove nav property accesses. This seems like overly aggressive defensive behavior by the code.

**Comment by adrianhall** [comment]
We have a very opinionated OData spec - it's better to assume it isn't OData since we don't support full OData.
