### ISSUE TITLE
Bulk table operation support

### ISSUE THREAD

**Issue by shirazamin** [Azure/azure-mobile-apps-net-client#299]
I am developing an application that needs to collect a lot of data offline and then needs to sync that back to the server, and in certain cases even do bulk operations on the local database. 

Doing this in the current implementation is very time consuming, especially pushing the data to the server.

I have already forked both the Client and Server implementations to begin adding this functionality. I was wondering if this implementation will be added in a future version and if so, has there been discussion on how this would be implemented?

I am basing my implementation around creating a Bulk Operations that encapsulation the Insert/Update/DeleteOperations and instead of inserting one operation at time into the queue, use some of the already defined bulk operation methods to process them. This implementation still keeps each operation as individual operation in OperationQueue, and does not break any existing implementations for single operations, if I am not wrong.

**Comment by adrianhall** [comment]
Dup of #285
