### ISSUE TITLE
Error on Facebook Authentication

### ISSUE THREAD

**Issue by bossvellore** [Azure/azure-mobile-apps-net-client#301]
when try to authenticate with Facebook, 
It opens facebook login screen, once login I get this error message.

Invalid Scopes: page_manage_leads. This message is only shown to developers. User of your app will ignore these permissions if present. Please read the documentation for valid permissions at https"//developer.facebook.com/docs/facebook-login/permissions

**Comment by adrianhall** [comment]
This is an issue with Azure App Service.  It is not a bug with Azure Mobile Apps.

**Comment by vitimm144** [comment]
That happened to me. I selected all the permissions that were in the azure. To fix it I had to remove all permissions and just select the permissions that facebook released me from the beginning.
