### ISSUE TITLE
NetStandard Package

### ISSUE THREAD

**Issue by dansiegel** [Azure/azure-mobile-apps-net-client#302]
I'm not sure what special tooling I need to build the repo in it's current state, but I've been unable to get this to properly build and/or pack. I have the problem on both Mac and PC. Naturally on Mac I have to first remove the net45 and UWP targets... but I'm getting an error that it cannot find the target for MonoAndroid44. 

I'm not sure if there is a MyGet feed that would contain a build of the NetStandard version of the packages but it would be super helpful for my project.

**Comment by pvbchak** [comment]
We released alpha version of [4.0.0](https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client/4.0.0-alpha-001) today, which contains .Net Standard binaries. We are in the process of validating all tests & updating all quickstarts and will release final version soon.

**Comment by dansiegel** [comment]
Looks like this completely breaks support for existing PCL's. The `Microsoft.Azure.Mobile.Client` installs just fine for a PCL using Profile 111, however `Microsoft.Azure.Mobile.Client.SQLiteStore` will not install.
