### ISSUE TITLE
Handling scenario when MSA sign in is down

### ISSUE THREAD

**Issue by myokeeh** [Azure/azure-mobile-apps-net-client#309]
Looking back to a week or two ago when MSA was down.

Do we have guidance on properly (gracefully) handling the situation when MSA sign-in is down?

**Comment by adrianhall** [comment]
The advice is

a) Use the approved Microsoft Account SDK (OneDrive / Live SDK) for authentication.
b) Use the client-flow version of LoginAsync() to validate the token.

If MSA is down, the MSA SDK will be used to handle the error, and you can handle it in their approved way.  There is not much you can do when a provider is down on the server-flow side.
