### ISSUE TITLE
When will Android 7.1 API 25 be supported?

### ISSUE THREAD

**Issue by kdawg1406** [Azure/azure-mobile-apps-net-client#314]
Hi,

When will Android 7.1 API 25 be supported?

This page states only API 24 and below are supported.

https://github.com/Azure/azure-mobile-apps-net-client

Best,

Karl

**Comment by adrianhall** [comment]
API 25, on my testing, works fine.  We don't support it because we haven't run the end-to-end tests on API 25.  If it works for you, then great.  If you find a problem, let us know.
