### ISSUE TITLE
When I try to dotnet pack in TeamCity I get an error about MonoAndroid44 missing

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps-net-client#317]
[17:33:12][Step 7/7] C:\Users\TCUser\.nuget\packages\msbuild.sdk.extras\1.0.0\build\netstandard1.0\MSbuildSdkExtras.Common.targets(116,5): error : The specified language targets for MonoAndroid44 is missing. Ensure correct tooling is installed.\r\nMissing File: C:\Program Files\dotnet\sdk\1.0.3\Xamarin\Android\Xamarin.Android.CSharp.targets [C:\TeamCity\buildAgent\work\1b384cbcb583432\src\Microsoft.Azure.Mobile.Client\Microsoft.Azure.Mobile.Client.csproj]

Any idea how I can resolve this? Thanks in advance.

**Comment by tofutim** [comment]
Outside of TeamCity I have the same issue:

`D:\Loqu8\Db\azure-mobile-apps-net-client\src\Microsoft.Azure.Mobile.Client>dotnet pack Microsoft.Azure.Mobile.Client.csp
roj

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://ak
a.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include c
ommand-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shel
l.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access.
 This command will take up to a minute to complete and will only happen once.
Decompressing 100% 7733 ms
Expanding 100% 83508 ms
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft.Azure.Mobile.Client -> D:\Loqu8\Db\azure-mobile-apps-net-client\src\Microsoft.Azure.Mobile.Client\bin\Debug\
netstandard1.4\Microsoft.Azure.Mobile.Client.dll
  Microsoft.Azure.Mobile.Client -> D:\Loqu8\Db\azure-mobile-apps-net-client\src\Microsoft.Azure.Mobile.Client\bin\Debug\
netstandard1.1\Microsoft.Azure.Mobile.Client.dll
  Microsoft.Azure.Mobile.Client -> D:\Loqu8\Db\azure-mobile-apps-net-client\src\Microsoft.Azure.Mobile.Client\bin\Debug\
net45\Microsoft.Azure.Mobile.Client.dll
C:\Users\tim\.nuget\packages\msbuild.sdk.extras\1.0.0\build\netstandard1.0\MSbuildSdkExtras.Common.targets(116,5): error
 : The specified language targets for MonoAndroid44 is missing. Ensure correct tooling is installed.\r\nMissing File: C:
\Program Files\dotnet\sdk\1.0.3\Xamarin\Android\Xamarin.Android.CSharp.targets [D:\Loqu8\Db\azure-mobile-apps-net-client
\src\Microsoft.Azure.Mobile.Client\Microsoft.Azure.Mobile.Client.csproj]`

**Comment by adrianhall** [comment]
Azure Mobile Apps does not work with dotNet core.  Please read the README for supported platforms.

**Comment by tofutim** [comment]
But wait, so how do you end up packing the nupkg? Do you use nuget? msbuild pack?

**Comment by tofutim** [comment]
I had to use msbuild /t:pack

**Comment by adrianhall** [comment]
You use the regular .NET Framework tooling - not the .NET Core tooling.  That's the key difference here.

**Comment by tofutim** [comment]
Thank you Adrian, I got confused because 'nuget pack' gave an error.

**Comment by tofutim** [comment]
Any idea how I can direct the msbuild /t:pack output to go to ../../output?

**Comment by tofutim** [comment]
I have discovered /p:OutputPath=..\..\output - works! :)
