### ISSUE TITLE
File Syncing SDK Missing

### ISSUE THREAD

**Issue by acastr7** [Azure/azure-mobile-apps-net-client#318]
It appears the File Syncing SDK has been removed or hidden. The repo use to be available here https://github.com/Azure/azure-mobile-apps-net-files-client/. It also looks like the nuget was unlisted https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client.Files. Is there any indication on why this happened?

**Comment by ceichin** [comment]
Check this thread: https://social.msdn.microsoft.com/Forums/azure/en-US/2556d05a-5b2c-4eec-9551-2a55209643b4/windowsazuremobileapps-files-has-been-delisted-from-nuget?forum=azuremobile
