### ISSUE TITLE
Google Authentication now that web-views/embedded browsers are out

### ISSUE THREAD

**Issue by JeffDalby** [Azure/azure-mobile-apps-net-client#319]
I apologize if this is addressed somewhere, but I've been searching everywhere I can think of and can't find an answer.  Does the current release support authenticating to Google now that they no longer allow an embedded window (which from what I can tell is how the azure mobile apps client has functioned so far)?  If so what (if any) changes do we need to make this work?  Is there any documentation on how this should now be implemented?  It appears the existing documentation has not been updated.  My guess is I'm just not coming up with the right terms to search because I would have thought this change would put everyone in a panic.  Or do I simply not really understand how it worked before and was it not using an embedded window?

If there isn't a fix for this any suggestions on what we are supposed to do now? I've somehow missed this in all the other work we are doing, since we haven't touched our auth code in many months.  Now we've got an app out there living on borrowed time.

I should add that we are using the Azure Mobile Apps client, and this is a Xamarin Forms application.  We haven't used the Xamarin Auth Component up to this point because, well, we need the functionality of the Azure Mobile Apps client since our backend is an Azure Mobile App.

**Comment by dsandraz** [comment]
Same problem here, hoping for some guidance.

**Comment by williamsrz** [comment]
@JeffDalby I think that you should use the native authentication from google (using Xamarin Component for Google Play Services Client Library https://www.nuget.org/packages/Xamarin.GooglePlayServices.Auth), to authenticate the user and after that send the token to Azure App Service to auth with backend.

**Comment by dsandraz** [comment]
Ok, thanks. 
I thought Azure Mobile Client v3.1.0 was suppose to work and avoid the problem, I guess I was wrong..

**Comment by dengere** [comment]
@dsandraz, 
We use Xamarin.Auth lib. Yesterday suddenly stopped with same issue. We couldn't find any solution yet (Xamarin.Aut author also). We try to find "a way", change code with Azure Mobile Client. 
Before starting to change codes,  I saw your noted. 
Did you try that is work or not? Your answer will be very very useful guide to us to decide that we run with Azure Mobile Client or try to find another way?

**Comment by dsandraz** [comment]
I used the authentication through Microsoft Azure Mobile Client, because it does handle it for the provider I needed. It worked fine until now. I have not updated the code to yet as suggested by williamsrz. I am still checking if anyone fixed the issue using the Azure Mobile client. I'll add an update here is I find anything useful.

**Comment by JeffDalby** [comment]
@williamsrz  That's the path I'm currently going down.  Frustrating to add yet another component, but if I can make it work that'll be fine.  The problem is Xamarin Auth isn't ready for this either...I'll see what I can do to work with them to help get something going.

**Comment by dsandraz** [comment]
Isn't Azure Mobile using Xamarin Auth?

**Comment by dsandraz** [comment]
FYI, on iOS the workaround listed here: https://forums.xamarin.com/discussion/86415/google-auth-error-disallowed-useragent
does work. 

Not for Android though.

**Comment by williamsrz** [comment]
@JeffDalby agree. It is cumbersome to use a lot of libraries but I think is better for (user perspective). 

@dsandraz No, they have their own implementation.

**Comment by Clancey** [comment]
@williamsrz were you able to get this too work? I just get 401, unauthorized:

```cs
var jobject = new JObject ();
jobject.Add ("access_token", authToken);
var usr = await AzureService.Instance.Client.LoginAsync (MobileServiceAuthenticationProvider.Google, jobject);
```

**Comment by FetFrumos** [comment]
Hello, Azure Team.When is update  available in NuGet?

**Comment by DanAnzelmi** [comment]
I am little bit confuse here. Should I use Xamarin.Auth component or should I wait for Azure SDK?

**Comment by JeffDalby** [comment]
If you need it now, go with Xamarin Auth...it currently works.

**Comment by dengere** [comment]
@JeffDalby  which component do you talk about? Xamarin.Auth doesn't support new google login. (They told yes it is but please check issues about it. how many packages published in a week.)

**Comment by JeffDalby** [comment]
It definitely works, I've got it running on our published iOS and Google Xamarin Forms, and it's been working fine for a couple weeks.  They've had some issues with Xamarin Forms on UWP, but my understanding is that is worked out now...could be wrong about that though.  

If you have questions about Xamarin Auth the best place to do is go get help from the Slack channel.  Here's the info for that:

Xamarin Chat - Community Slack Team (xamarin-auth-social room)

For those that need real-time help (hand-in-hand leading through implementation) the best option is to use community slack channel. There are numerous people that have implemented Xamarin.Auth with Native UI and maintainers/developers of the library.

https://xamarinchat.slack.com/messages/C4TD1NHPT/

For those without Xamarin Chat account please visit this page and generate self-invitation:

https://xamarinchat.herokuapp.com/

**Comment by DanAnzelmi** [comment]
Thanks @JeffDalby. I'll start playing with that then.
