### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by dansiegel** [Azure/azure-mobile-apps-net-client#322]
Since the main library is cross compiled, support should be added for macOS since Xamarin Forms has macOS support start with 2.3.5.

**Comment by kdawg1406** [comment]
Very much agree

**Comment by tofutim** [comment]
Me three.

**Comment by elamalani** [comment]
@dansiegel This is a good suggestion, but we have no plans to support Xamarin macOS for Azure Mobile Apps.

**Comment by ltaljaard** [comment]
Definitely, this should go right to the top of the list in my opinion. It would be silly for everyone out there to have to code their own custom sync engine (a Mobile Services substitute) just for your MacOS app. Please don't close this issue!

**Comment by dansiegel** [comment]
@elamalani I very much agree with @ltaljaard. With Xamarin Forms supporting Mac OS development, I believe we are going to see a boom of development for Mac as it greatly reduces the difficulty in making out existing applications work as native Mac apps. I understand that other features may be higher priority to the team, but supporting Mac should be considered a must add...

**Comment by elamalani** [comment]
@dansiegel Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us to prioritize this work in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
