### ISSUE TITLE
Unable to synchronise on a slow connection (TaskCanceledException)

### ISSUE THREAD

**Issue by rneeft** [Azure/azure-mobile-apps-net-client#323]
Hi, 

We have a big issue with clients running on a slow connection. The synchronisation does not happen and result in an application crash with the following message: *System.Threading.Tasks.TaskCanceledException: A task was canceled.* Catching that exception result in no items. 

I'm able to reproduce the issue with the Android emulator by setting the network settings to **2G** and the signal strength to **Poor**. The data that I tried to sync were 25 todo items with a GUID as text. 

I have attach the Android code that I used to test the application. This is, however, connected to my own Azure environments. [chramspoc.zip](https://github.com/Azure/azure-mobile-apps-net-client/files/1010336/chramspoc.zip)

The create the application yourself please execute the following steps: 

Reproduction:
- Create, in Azure, a new Mobile App.
- Go to the quick start section and choose for Xamarin.Android
- Create the database
- Set the backend language to C# 
- Download and publish the backend service
- Download the Android application
- Open the solution
- In the ToDoActivity.cs file enable OFFLINE_SYNC.
- (optional) add the following code in the SyncAsync method:
```
catch (TaskCanceledException ex)
{
    CreateAndShowDialog(ex, "TaskCanceledException");
}
```
- Start the Android emulator
- In the network section of the emulator setting, make sure the Cellular settings are set to 2G and signal strength to Poor.
- Run the app and let it sync. 

If it work the first time try to add some todo items - let it sync - delete the app and run it again. 

*Azure Mobile Client SDK: v3.1.0*

**Comment by elamalani** [comment]
@rneeft Thanks for using Azure Mobile Apps. This issue was opened almost a year back - were you able to resolve it? Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps).  At this point, we are not fixing any bugs in the product unless it's a critical issue.

I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!

**Comment by Bejasc** [comment]
@elamalani Is this not a critical issue, that it throws a TaskCancelled exception for a poor network connection? 

Why is there no resolution for this issue?

**Comment by elamalani** [comment]
@Bejasc Sorry that you are running into this exception but we are not doing any active development in this product. Unfortunately, we don't plan to fix this issue in the SDK. Please feel free to fork this open source repository and fix the exception if you'd like.
