### ISSUE TITLE
Options for Working with Legacy DateTime Fields?

### ISSUE THREAD

**Issue by lthib** [Azure/azure-mobile-apps-net-client#324]
I am working completely with offline tables. The current usage of **Newtonsoft.Json** between client and server SDKs tries its best to be helpful, but ultimately ends up creating issues for working with our legacy data that unfortunately uses `DateTime` fields instead of `DateTimeOffset`.  My issue is that when saving the data to the server, the base behavior of the SDK is to assume the `DateTimeKind` of the object is `Local` and express the value in terms of UTC on request serialization. I have attempted to modify my `MobileServiceClient.SerializerSettings.DateTimeZoneHandling` value to `DateTimeZoneHandling.Unspecified` but don't see any changes in behavior.

What are my options for producing some kind of behavior that doesn't try to compensate for time zones and simply passes the values around as they are? I could likely use some guidance on the server SDK as well, as both modifying `HttpConfiguration.Formatters.JsonFormatter.SerializerSettings.DateTimeZoneHandling` globally and in a custom `ITableControllerConfigProvider` didn't produce any results.

**Comment by lthib** [comment]
Solved this by removing `IsoDateTimeConverter` in the per-controller config on the server-side and setting the top-level settings object's `DateFormatString`, added a custom implementation of `MobileServiceDateTimeConverter` on the client side, and set `DateTimeZoneHandling` on both to `Unspecified`. I think it might be ideal if the SDK had some way to stop it from compensating for what it assumes to be the meaning of the DateTime columns the app needs to communicate. Was pretty hard to both locate and revise the behavior.

**Comment by elamalani** [comment]
@lthib Thanks for your suggestion but unfortunately, we are not looking to modify the SDK with this change.
