### ISSUE TITLE
Clarification on netstandard14 vs platform-specific

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps-net-client#327]
Hi, I am working on a multi-platform project that has a netstandard core and platform-specific apps (via mvvmcross). If I add this library to the netstandard core, should I add it also to the platform-specific apps? Since there are platform specific compilations will there be issues?

**Comment by dhei** [comment]
Hi @tofutim, do you still have concern on this? What exactly do you mean by "multi-platform"? Is it a Xamarin or Xamarim.Forms project? Is it PCL project? Azure Mobile Apps SDK supports .netstandard1.4 in v4.0.1, so .netstandard should work. Note that PCL projects are currently not supported in v4.0.1 and PCL will be supported in soon-to-be-released v4.0.2.

Thanks

**Comment by elamalani** [comment]
@tofutim We haven't heard back from you. I am closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
