### ISSUE TITLE
Lost Connection Throws Exception

### ISSUE THREAD

**Issue by jscharmann** [Azure/azure-mobile-apps-net-client#329]
When switching between wifi and cellular service our implementation of the Mobile Services throws one of the below exceptions depending on whether we just started syncing data or if data transfer is in progress.

Just started -
06-05 12:55:26.102 I/MonoDroid( 1638): UNHANDLED EXCEPTION:
06-05 12:55:26.108 I/MonoDroid( 1638): Microsoft.WindowsAzure.MobileServices.SQLiteStore.SQLiteException: Error executing SQLite command: 'library routine called out of sequence'.
06-05 12:55:26.108 I/MonoDroid( 1638):   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.SQLitePCLRawHelpers.VerifySQLiteResponse (System.Int32 result, System.Int32 expectedResult, SQLitePCL.sqlite3 db) [0x0002f] in <0704a9dba7694cd39d856894695adffc>:0 
06-05 12:55:26.108 I/MonoDroid( 1638):   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.SQLitePCLRawHelpers.GetSqliteStatement (System.String sql, SQLitePCL.sqlite3 db) [0x00009] in <0704a9dba7694cd39d856894695adffc>:0 
06-05 12:55:26.108 I/MonoDroid( 1638):   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore.ExecuteQueryInternal (Microsoft.WindowsAzure.MobileServices.SQLiteStore.TableDefinition table, System.String sql, System.Collections.Generic.IDictionary`2[TKey,TValue] parameters) [0x0001e] in <0704a9dba7694cd39d856894695adffc>:0 
06-05 12:55:26.108 I/MonoDroid( 1638):   at Kpa.Mko.Mobile.Client.Data.Stores.MobileServiceSQLiteLoggingStore.ExecuteQueryInternal (Microsoft.WindowsAzure.MobileServices.SQLiteStore.TableDefinition table, System.String sql, System.Collections.Generic.IDictionary`2[TKey,TValue] parameters) [0x00025] in C:\Users\james.scharmann\git\MobileApps\Source\Client\Kpa.Mko.Mobile.Client.Data\Stores\MobileServiceSQLiteLoggingStore.cs:59 
06-05 12:55:26.108 I/MonoDroid( 1638):   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore.ExecuteQueryInternal (System.String tableName, System.String sql, System.Collections.Generic.IDictionary`2[TKey,TValue] parameters) [0x00008] in <0704a9dba7694cd39d856894695adffc>:0 
06-05 12:55:26.108 I/MonoDroid( 1638):   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore+<>c__DisplayClass8_0.<ReadAsync>b__0 (System.Threading.Tasks.Task t) [0x00022] in <0704a9dba7694cd39d856894695adffc>:0 
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:111 
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 
06-05 12:55:26.108 I/MonoDroid( 1638): --- End of stack trace from previous location where exception was thrown ---
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 
06-05 12:55:26.108 I/MonoDroid( 1638):   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceLocalStoreExtensions+<QueryAsync>d__4.MoveNext () [0x00066] in <42e24ce875d34485ad11c4f8aebb904a>:0 
06-05 12:55:26.108 I/MonoDroid( 1638): --- End of stack trace from previous location where exception was thrown ---
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
06-05 12:55:26.108 I/MonoDroid( 1638):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 
06-05 12:55:26.108 I/MonoDroid( 1638):   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceLocalStoreExtensions+<CountAsync>d__3.MoveNext () [0x00083] in <42e24ce875d34485ad11c4f8aebb904a>:0 
06-05 12:55:26.108 I/MonoDroid( 1638): --- End of stack trace from previous location where exception was thrown ---

In transfer -
06-05 12:50:30.853 I/MonoDroid( 1325): UNHANDLED EXCEPTION:
06-05 12:50:30.858 I/MonoDroid( 1325): System.NullReferenceException: Object reference not set to an instance of an object.
06-05 12:50:30.858 I/MonoDroid( 1325):   at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient+<SendRequestAsync>d__26.MoveNext () [0x00011] in <42e24ce875d34485ad11c4f8aebb904a>:0 
06-05 12:50:30.858 I/MonoDroid( 1325): --- End of stack trace from previous location where exception was thrown ---
06-05 12:50:30.858 I/MonoDroid( 1325):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
06-05 12:50:30.858 I/MonoDroid( 1325):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
06-05 12:50:30.858 I/MonoDroid( 1325):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
06-05 12:50:30.858 I/MonoDroid( 1325):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
06-05 12:50:30.858 I/MonoDroid( 1325):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 
06-05 12:50:30.858 I/MonoDroid( 1325):   at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient+<RequestAsync>d__18.MoveNext () [0x000fa] in <42e24ce875d34485ad11c4f8aebb904a>:0 
06-05 12:50:30.858 I/MonoDroid( 1325): --- End of stack trace from previous location where exception was thrown ---
06-05 12:50:30.858 I/MonoDroid( 1325):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
06-05 12:50:30.858 I/MonoDroid( 1325):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
06-05 12:50:30.858 I/MonoDroid( 1325):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
06-05 12:50:30.858 I/MonoDroid( 1325):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
06-05 12:50:30.858 I/MonoDroid( 1325):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 
06-05 12:50:30.858 I/MonoDroid( 1325):   at Microsoft.WindowsAzure.MobileServices.MobileServiceTable+<ReadAsync>d__20.MoveNext () [0x000a3] in <42e24ce875d34485ad11c4f8aebb904a>:0 

In both cases, the connection with Mobile Services is somehow being disposed/lost. Any help with this issue would be greatly appreciated.

**Comment by MatkovIvan** [comment]
Hi @jscharmann 

After investigation, my main version why it happens is multiple actions run at the same time. I've managed to get the same errors only in this condition. Furthermore, this is confirmed by [sqlite error description](https://www.sqlite.org/cvstrac/wiki?p=LibraryRoutineCalledOutOfSequence) where listed one of the possible reasons:
>Trying to use the same database connection at the same instant in time from two or more threads.

Let me explain how this might happen from my point of view.
When you switching between wifi and cellular, current operation freezing at HTTP system call that canceled only by timeout. It happens in the background thread and this is why the application doesn't freeze.
Your application starts the second operation in parallel (without waiting for the completion of the current operation). It causing `Error executing SQLite command: 'library routine called out of sequence'` and other problems.
So, please make sure that you don't run operations while previous doesn't complete.
If my guess is wrong could you please check that it happens on sample app which can be shared as reproduction sample.

Thanks,
Ivan

**Comment by elamalani** [comment]
@jscharmann We haven't heard back from you. I am closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
