### ISSUE TITLE
Ability to build Code

### ISSUE THREAD

**Issue by Cairn23** [Azure/azure-mobile-apps-net-client#342]
I have downloaded the latest code via a zip download, after resolving the nuget packages and building I get 19 errors, which cross relate to 2 errors. 'Auth' does not exist in the namespace 'Xamarin, file MobileServiceUIAuthentication line 6 and another error on line 20 'WebAuthenticator' could not be found. How can this be resolved as I want to trial a change to the SDK before submitting

**Comment by MatkovIvan** [comment]
Hi @Cairn23!

Github zip download don't contains submodules. Please use `git clone` or download https://github.com/Azure/azure-mobile-services-xamarin-auth to `src/External/Xamarin.Auth` manually.
