### ISSUE TITLE
Cannot reference Xamarin.Auth and Microsoft.Azure.Mobile.Client in the same Xamarin.iOS Project

### ISSUE THREAD

**Issue by mjo151** [Azure/azure-mobile-apps-net-client#343]
With the latest version (4.0.0) of the Azure Mobile SDK, I can no longer build my project. I'm also referencing Xamarin.Auth, and here's the error that occurs when I try to build for a physical device:

Error MT4116: Could not register the assembly 'Xamarin.Auth': error MT4118: Cannot register two managed types ('Xamarin.Controls.ProgressLabel, Xamarin.Auth' and 'Xamarin.Controls.ProgressLabel, Microsoft.Azure.Mobile.Client') with the same native name ('Xamarin_Controls_ProgressLabel'). (MT4116)

**Comment by MatkovIvan** [comment]
Hi @mjo151!

Thanks for reporting. Actually, on my test app it is just a warning, but I see that this should be fixed. I created [PR](https://github.com/Azure/azure-mobile-services-xamarin-auth/pull/9) to resolve this issue.

**Comment by mjo151** [comment]
Thanks!

**Comment by ericbrunner** [comment]
@MatkovIvan Is a pre release / release version available? When I only use the AccountStore from Xamarin.Auth, can I use that from the Azure MobileService Client and kick the Xamarin.Auth package out? Wha t can I do instead, revert to v.3.1.0? Don't know if I would not run in other issues in XF utilizing a .NET Standard,Version=1.4 library......

**Comment by MatkovIvan** [comment]
Hi @ericbrunner. We plan to nuget release with these changes at this week. We include `Xamarin.Auth` as `internal`, so if you need anything from it you should use it directly.

**Comment by ericbrunner** [comment]
@MatkovIvan Sounds good. Thank you for your reply.
