### ISSUE TITLE
Add / Remove files

### ISSUE THREAD

**Issue by Cairn23** [Azure/azure-mobile-apps-net-client#346]
In previous versions of the mobile SDK, you could add and remove files etc. the url for the files no longer works https://github.com/Azure/azure-mobile-apps-net-files-client, and I cannot see anything in the current code base to deal with files /blobs etc.
Is it the case the URl is broken, or has the functionality been removed from the SDK

**Comment by dhei** [comment]
@Cairn23, yes the package is delisted, please see [this](https://social.msdn.microsoft.com/Forums/azure/en-US/2556d05a-5b2c-4eec-9551-2a55209643b4/windowsazuremobileapps-files-has-been-delisted-from-nuget?forum=azuremobile) answer on azure forum.

**Comment by fileman** [comment]
#347

**Comment by dhei** [comment]
@Cairn23 @fileman Please see the source code in azure-mobile-apps-net-files-client-1.0.0.beta2.zip. This is the last release of Microsoft.Azure.Mobile.Client.Files before it was delisted.


[azure-mobile-apps-net-files-client-1.0.0.beta2.zip](https://github.com/Azure/azure-mobile-apps-net-client/files/1089123/azure-mobile-apps-net-files-client-1.0.0.beta2.zip)
