### ISSUE TITLE
v4.0.0 Incompatible with Xamarin.Forms v2.3.4 & v2.3.5: `java.lang.IllegalArgumentException`

### ISSUE THREAD

**Issue by brminnick** [Azure/azure-mobile-apps-net-client#348]
Microsoft.Azure.Mobile.Client v4.0.0 is incompatible for Android builds with the current version of Xamarin.Forms, v2.3.4.247. It is also incompatible with the next version of Xamarin.Forms, v2.3.5.239-pre3.

Microsoft.Azure.Mobile.Client v4.0.0 is [dependent on Xamarin.Android.Support.CustomTabs v25.3.1](https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.Azure.Mobile.Client/Microsoft.Azure.Mobile.Client.csproj#L92), but the current version of Xamarin.Forms, v2.3.4.247, [requires v23.3.0 of the Xamarin.Android Support Libraries](https://www.nuget.org/packages/Xamarin.Forms/2.3.4.247).

### Reproduction

1. [Download the reproduction sample](https://github.com/brminnick/FormsIllegalArgumentReproduction) 
2. Open `FormsIllegalArgument.sln` in Visual Studio of Visual Studio for Mac
3. Build `FormsIllegalArgument.Droid`

### Build Error
>/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error: java.lang.IllegalArgumentException: already added :  Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat; (dihei_empty_node.Droid)

### Work-Around
Update the `Xamarin.Android.Support.v4` NuGet Package to v25.3.1. 

Note: This will eliminate the `java.lang.IllegalArgumentException` error, but it may cause run-time crashes in your Xamarin.Forms Android App, because Xamarin.Forms does not yet support any Xamarin.Android.Support library above v23.3.0

**Comment by fileman** [comment]
MonoAndroid 7.0 support >=23.3.0 I'm running 4.0.0 client since from preview and no issue with 25.* 
I think for this issue a better title could be 4.0.0 client incompatible with Xamarin.Android.* 23.3.0

**Comment by MatkovIvan** [comment]
Hi @brminnick!

Why do you think that `Xamarin.Forms` does not support `Xamarin.Android.Support.*` library above `v23.3.0`?
From your link https://www.nuget.org/packages/Xamarin.Forms/2.3.4.247 :
> MonoAndroid 7.0
>    Xamarin.Android.Support.v4 (>= 23.3.0)

`25.3.1` >= `23.3.0`

**Comment by dhei** [comment]
Hi @brminnick, I agree with what @MatkovIvan has said. `Microsoft.Azure.Mobile.Client` v4.0.0 depends on`Xamarin.Android.Support.*` v25.3.1. If you upgrade `Xamarin.Android.Support.v4` to 25.3.1 in your `FormsIllegalArgument.Droid` project, the build error should disappear.

**Comment by brminnick** [comment]
@dhei @MatkovIvan 
Will `Microsoft.Azure.Mobile.Client` work with Xamarin.Android.Support.CustomTabs v23.3.0? If it does, we should lower the NuGet Dependancy to "Xamarin.Android.Support.CustomTabs (>= 23.3.0)".

It is a poor user experience to create a File -> New Xamarin.Forms app, add the `Microsoft.Azure.Mobile.Client` NuGet package, compile, then get a compilation error. 

We have many customers who are still using older versions of Xamarin.Forms who cannot now update their `Microsoft.Azure.Mobile.Client` to v4.0.0. Xamarin.Forms only recently introduced support for the Xamarin.Android.Support Libraries above 23.3.0 in Xamarin.Forms v2.3.4 on March 29th 2017.

**Comment by MatkovIvan** [comment]
@brminnick [A little earlier (February 1, 2017)](https://www.nuget.org/packages/Xamarin.Forms/2.3.3.193) ;)
But this doesn't change the meaning of your words

**Comment by brminnick** [comment]
Haha - whoops! Good catch!

**Comment by BioTurboNick** [comment]
Just noticed this issue. The downgrade breaks LoginAsync.

**Comment by renzska** [comment]
I ran into the same issue on a different third party library, but it was a matter of configuration to get it working. Hopefully it works for this as well.

First, you must have Android SDK for API 25 installed. Next, you need to go into your Android project settings and under General/Build make sure you select Android 7.0 or newer and then go into your Manifest and set the Target to 25, as well.

**As long as you Target API 25 and build against Android 7.0 or newer, you can update the support libraries to 25.3.1 with Xamarin Forms v2.3.4.247.**

If you don’t do this you will see an error when trying to install the Android NuGet that you aren’t targeting the correct version of Android. After doing this, you should no longer get this error.

**Comment by elamalani** [comment]
Closing this issue as its fixed in v4.0.1.

**Comment by Suryakalai** [comment]
a

**Comment by Suryakalai** [comment]
I am trying to install geolocator plugin in xamarin form nuget package. bt i getting the error like 
Error: java.lang.IllegalArgumentException: already added :  Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat

pls someone hlp me
