### ISSUE TITLE
Upgrade from v3.1.0 to v4.0.0 not possible in PCL Profile=259

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#350]
Hi,
My Xamarin.Forms App targets Profile=259. Today I tried to update the **Microsoft.Azure.Mobile.Client** and got that message:

> Could not install package 'Microsoft.Azure.Mobile.Client 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

The same for the **Microsoft.Azure.Mobile.Client.SQLiteStore**

> Could not install package 'Microsoft.Azure.Mobile.Client.SQLiteStore 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I don't want to convert my whole project to .NET Standard only because of that change. BTW I don't know how to retarget the PCL to NET Standard.

best
Eric

**Comment by fileman** [comment]
You need to create new library project and import manually all file. For VS2017 project follow [this](https://xamarinhelp.com/visual-studio-2017-net-standard-xamarin/) in same blog you can find VS2015 version

**Comment by ericbrunner** [comment]
@fileman Thanks for your reply. I already tried that but as mention in that migration guide it is not working https://bugzilla.xamarin.com/show_bug.cgi?id=53060

**Comment by fileman** [comment]
I've v4 running in PCL without problem with "Xamarin.Forms" Version="2.3.4.247" and this profile
`<PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
    <PackageTargetFallback>portable-net45+win8+wpa81+wp8</PackageTargetFallback>
    <DebugType>full</DebugType>
  </PropertyGroup>`

**Comment by ericbrunner** [comment]
Wow.. I got into hell. I will try that to create a brand new .NET Standard library, add your config , re-add all packages from the old PCL  into the new .NET Standard library and hope it works. I am a bit concerned if the project will build in VSTS but that is written on another page.

**Comment by elamalani** [comment]
@ericbrunner We are going to support PCL in .NET SDK for Mobile Apps. I don't have a timeline yet but it will take us a few weeks to release the new SDK.

**Comment by elamalani** [comment]
@ericbrunner We released the latest version of Zumo .NET client SDK v4.0.2 today where we support PCL based Xamarin.Forms project, please find more information [here](https://github.com/Azure/azure-mobile-apps-net-client/releases/tag/4.0.2).
