### ISSUE TITLE
LoginAsync

### ISSUE THREAD

**Issue by myokeeh** [Azure/azure-mobile-apps-net-client#351]
I'm using this on a Template 10 UWP app, but isn't working. using Microsoft accounts for login. Is there something I need to change in the Application Registration Portal (https://apps.dev.microsoft.com)?

I tried adding the redirect URL: `myprotocollinktext://easyauth.callback` but doesn't work.

`mobileServiceClient.CurrentUser = await mobileServiceClient.LoginAsync(MobileServiceAuthenticationProvider.MicrosoftAccount, "myprotocollinktext");`

The browser pops up saying this, and it doesn't Activate the app: 

![image](https://user-images.githubusercontent.com/3663297/27774101-4fd7d198-5f3f-11e7-948e-14e218e0975c.png)

Added to .appxmanifest file
```
<uap:Extension Category="windows.protocol">
    <uap:Protocol Name="myprotocollinktext">
        <uap:DisplayName>myprotocollinktext</uap:DisplayName>
    </uap:Protocol>
</uap:Extension>
```

Overriding `OnStartAsync`:
```
public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
{
    if (startKind == StartKind.Activate)
    {
        var wefwe = args as ProtocolActivatedEventArgs;
        mobileServiceClient.ResumeWithURL(wefwe.Uri);
    }
}
```
Referencing #341 #344 #326

**Comment by BioTurboNick** [comment]
I got that too when trying the server authentication flow, even without adding a protocol, when following the documentation.

**Comment by RobbyRobbyRobby** [comment]
I get this same problem when trying to login with the provider and SingleSignOn set to true.

**Comment by BioTurboNick** [comment]
I think the idea is that we should be following in essence the Android instructions, based on some other posts here. (Even though they are dated the same?) In the Android instructions, you pass your app's Uri scheme to the mobile client's LoginAsync, and ensure that the App Service allows that scheme to be emitted as a callback. I managed to thus get the app to open my browser, which showed me a permission granting screen, and on clicking "yes", the focus switched to my app.

Success? Well, not quite... The LoginAsync method never returns. The thread that was running it disappears after the callback uri triggers the App.OnActivated method. How can a whole call stack just disappear? None of my breakpoints following the call to LoginAsync get hit, no exceptions surface, app keeps running. If I try to trigger the login process a second time, the call to LoginAsync throws the InvalidOperationException "Authentication is already in progress".

Now, the Android instructions have some other steps that look like they could wire the callback URI directly into the mobile service client somehow, but I don't see how to do that with a UWP app.

**Comment by BioTurboNick** [comment]
Following up: switching to useSingleSignOn = true (which is mutually exclusive with uriScheme) causes my above app to revert to the original issue: in-app popup window which fails to resolve the authentication request.

**Comment by myokeeh** [comment]
Can you briefly explain what you did to get the "permission granting screen"?

**Comment by BioTurboNick** [comment]
You probably already saw it once, it only shows up the first time for your app and account. When I repeat the login, it opens a blank browser window and immediately returns focus to the app via the URI scheme without interaction. So the real problems are:

1) Using Single Sign On with the native UI, it doesn't return a result to the MobileServiceClient.
2) Using a custom URI scheme, there isn't a way to return a result to the MobileServiceClient (that I know of).

**Comment by BioTurboNick** [comment]
Though since I've gotten it working, let me try to return the favor.

Here's what I did, in order:
1. Associated my app with the Windows Store so that it got an app package name etc.
2. Followed instructions for Microsoft Account Developer Center and Azure App Service: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-how-to-configure-microsoft-authentication?toc=%2fazure%2fapp-service%2ftoc.json
    a. Exceptions: I also set the Target Domain in the listing to the app service domain (unsure if necessary). I don't think "Generate New Password" is necessary because it shows a password, though I did it anyway.
3. Loosely followed the instructions for Android here: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-android-get-started-users. Setting in the App Service "Allowed External Redirect URLs" may be critical.

**Comment by dhei** [comment]
Sorry for the delay of response.

Azure Mobile Apps .NET client SDK [v4.0.0](https://github.com/Azure/azure-mobile-apps-net-client/releases/tag/4.0.0) made an API breaking change of server authentication flow. We updated the Azure documentation for the SDK today. 

The `LoginAsync()` API in v3.1.0 for server authentication flow only requires parameter `MobileServiceAuthenticationProvider`. For example, `user = await MobileServiceClient.LoginAsync("Facebook");` should login your user. Starting from v4.0.0, `LoginAsync()` API requires an additional parameter `uriScheme`. Secure authentication requires you define a URL scheme for your app. This allows authentication backend to redirect back to your app once the authentication process is complete. In order for redirect to work, there is a one time extra setup you will need to do on azure portal. On [azure portal](https://portal.azure.com) select your Mobile App, click the *Authentication / Authorization* menu option, enter `url_scheme_of_your_app://easyauth.callback` in the *Allowed External Redirect URLs*. Then you can call `user = await MobileServiceClient.LoginAsync("Facebook", "url_scheme_of_your_app");` to login your user. 

Here are the links for each platform:
(1) [**UWP** server authentication flow documentation](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-windows-store-dotnet-get-started-users#a-nameadd-authenticationaadd-authentication-to-the-app)
(2) [**Xamarin.Android** server authentication flow documentation](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-android-get-started-users#a-nameadd-authenticationaadd-authentication-to-the-app)
(3) [**Xamarin.iOS** server authentication flow documentation](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-ios-get-started-users#add-authentication-to-the-app)
(4) We are working on updating **Xamarin.Forms** server authentication flow documentation. In the meanwhile, you may refer to a Xamarin.Forms PCL sample app [here](https://github.com/dhei/azure-mobile-apps-xamarinforms-login-sample) that works with v4.0.0 of the SDK.

**Comment by Quico20** [comment]
wow thanks I was able to solve it!!! using template 10. now I can move on!!

**Comment by asierpn** [comment]
This procedure is not working with v4.0.2, please, can you give us instructions of how to login with server flow using this version?
