### ISSUE TITLE
VS2017 Xamarin.Forms: CurrentPlatform is internal class in v.4.0.0

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#352]
Hi,

Recently I updated my XF solution to utilize .NET Standard instead of PCL and updated the Client to v.4.0.0. Now I get a compiler error in my MainActivity where I call  

`Microsoft.WindowsAzure.MobileServices.CurrentPlatform.Init();`

Installed packages in .NET Standard lib which targets **.NET Standard 1.4**:

![image](https://user-images.githubusercontent.com/6480047/27800352-4e63e3ee-6019-11e7-88a6-9500fe063a9f.png)

**Microsoft.Azure.Mobile.Client v.4.0.0:**
![image](https://user-images.githubusercontent.com/6480047/27800407-8d1d6fa6-6019-11e7-82e7-5c09427a6289.png)

**Microsoft.Azure.Mobile.Client.SQLiteStore v.4.0.0:**
![image](https://user-images.githubusercontent.com/6480047/27800435-a629cdf0-6019-11e7-9a0d-fd66fe458724.png)

**Compiler Error:**
![image](https://user-images.githubusercontent.com/6480047/27800309-1db82fa2-6019-11e7-93af-fb0fc4fe8194.png)

For reference I put the Droid [.csproj](https://gist.github.com/ericbrunner/4f709da1894d6fdfa082b736759cdaab) an [packages.config](https://gist.github.com/ericbrunner/b2026626179433d66a8d9ea33fb10f26) on gist

and the .NET Standard library [.csproj](https://gist.github.com/ericbrunner/ecabecbd30573d7a3cc6f33a0431cdbd) , too.

Quite interesting the the XF iOS project is compile and runnable with the same v.4.0.0 without any issue:
![image](https://user-images.githubusercontent.com/6480047/27800932-d6fc9762-601b-11e7-9d80-4404063a945e.png)

Further more I hit decompile on CurrentPlatform in MainActivity and AppDelegate and can see that 
![image](https://user-images.githubusercontent.com/6480047/27801149-c21cdc16-601c-11e7-9a96-21526d2e3c9e.png)

If you need more info please get back, i will provide as much I can.

best

Eric

**Comment by ericbrunner** [comment]
After targeting my XF Droid .csproj to Android 7.1 I could compile but I don't know if that is the solution 
![image](https://user-images.githubusercontent.com/6480047/27801876-b831a926-6020-11e7-82ed-4d142f973054.png)

**Comment by MatkovIvan** [comment]
Hi @ericbrunner 

Library `Microsoft.Azure.Mobile.Client v.4.0.0` depends on `MonoAndroid v7.1` and won't work with versions lower than. But since we have `.NETStandard` support in the library, NuGet fallback to it on resolving dependencies and wrong assembly (not for Android) was included to your project.
So, your solution is absolutely right.
FYI: We downgraded `MonoAndroid` dependency version to `v7.0` in `Microsoft.Azure.Mobile.Client v4.0.1`.
