### ISSUE TITLE
LoginAsync:  cannot convert from 'System.Collections.Generic.IDictionary<string, string>' to 'Newtonsoft.Json.Linq.JObject'

### ISSUE THREAD

**Issue by Goldstrike** [Azure/azure-mobile-apps-net-client#353]
Hello,

I try to use the latest version (v4.0.0) in a Xamarin.Forms project.

In a Class Library, I do this:
```
public Task<MobileServiceUser> LoginAsync(IMobileServiceClient client, MobileServiceAuthenticationProvider provider, IDictionary<string, string> parameters = null)
{
    try
    {
        return client.LoginAsync(provider, parameters);
    }
    catch { }

    return null;
}
```

I get the following error:

> cannot convert from 'System.Collections.Generic.IDictionary<string, string>' to 'Newtonsoft.Json.Linq.JObject'

Is it normal?

**Comment by BioTurboNick** [comment]
LoginAsync expects a JObject, not an IDictionary, which is documented here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.mobileservices.mobileserviceclient.loginasync?view=azure-dotnet

**Comment by Goldstrike** [comment]
Is this a change since version 3.0.2?
I try to adapt a Xamarin.Forms sample (https://github.com/jamesmontemagno/app-coffeecups) to understand how Azure works (Authentication, Easy tables,...). In this sample,  LoginAsync is called like this, but it is based on the 3.0.2 package.

I didn't find yet a more recent sample: would you have one to suggest me?

**Comment by BioTurboNick** [comment]
You might try doing the LoginAsync calls from the UWP app rather than from the PCL. The PCL interface supports fewer methods, and the UWP one has methods that takes an IDictionary.

**Comment by Goldstrike** [comment]
Thanks for your feedback. So there are 2 ways to use it:
- through a Shared Project
- through a PCL or a .Net Standard Library Class, by implementing the interface in the dedicated project (iOS, Android, UWP)
Is this correct?

**Comment by BioTurboNick** [comment]
Yeah. I don't know if this is the best way to do it, but I've got most of the MobileServiceClient code in my .Net Standard library, and I pass the client into a DependencyService interface method so that the platform-specific MobileServiceClient methods can be used.
