### ISSUE TITLE
LoginAsync works in 3.1, not in 4.0

### ISSUE THREAD

**Issue by RobbyRobbyRobby** [Azure/azure-mobile-apps-net-client#354]
I had this working in V3.1 of the client, but upgrading to V4.0 it no longer works.

In V3.1 the MobileServiceClient.LoginAsync method accepts a single parameter, the Provider.  This works great.

On V4.1 there is no single param method.  The closest is a two param version which takes the Provider and a bool for SingleSignOn.  The problem is it doesn't work.

Setting SingleSignOn to false (basically using it the old fashioned way) gives an error that the method "is depreciated", and setting it to true doesn't work (the dialog accepts your sign on credentials but rather than returning it displays a webpage and returns nothing.  Closing the dialog returns a cancel.

This is C# in UWP.

Any work around or fix in progress?

**Comment by BioTurboNick** [comment]
I suggest closing this, sounds same as #351, and your solution might be there.

**Comment by dhei** [comment]
Sorry for the confusion and inconvenience. Please see my response at https://github.com/Azure/azure-mobile-apps-net-client/issues/351#issuecomment-313758238
