### ISSUE TITLE
Typo: Deprecated LoginAsync api directs user to "LoginSync"

### ISSUE THREAD

**Issue by BioTurboNick** [Azure/azure-mobile-apps-net-client#356]
If attempting to call LoginAsync(provider, false);

System.InvalidOperationException: 'This api is deprecated. Please use LoginSync method with uriScheme parameter.'

**Comment by AndreyBespamyatnov** [comment]
The same issue

**Comment by dhei** [comment]
Please see https://github.com/Azure/azure-mobile-apps-net-client/issues/351#issuecomment-313758238. Thanks.

**Comment by AndreyBespamyatnov** [comment]
@BioTurboNick maybe we have found some solution, it will be fixed at next release, please see this  [comment and my thread](https://github.com/Azure/azure-mobile-apps-net-client/issues/341#issuecomment-313700033)

**Comment by BioTurboNick** [comment]
I disagree, the issue I'm reporting is that the deprecation notice is directing people to the wrong function. "LoginSync" doesn't exist.

**Comment by BioTurboNick** [comment]
See here, line 115: https://github.com/Azure/azure-mobile-apps-net-client/blob/0283f2f6b23c3b4aeabc267bf04ad01a4475e827/src/Microsoft.Azure.Mobile.Client/Platforms/uwp/Extensions/SingleSignOnExtensions.cs
