### ISSUE TITLE
PurgeAsync with force = true and Query.Filter fails to purge data [Question] [Possible Bug]

### ISSUE THREAD

**Issue by NickPolyder** [Azure/azure-mobile-apps-net-client#357]
Hello. I am trying to use the PurgeAsync with the force flag with a table query and even with the force =true it will throw the exception _"The table cannot be purged because it has pending operations."_.
As i understand this is because i supply  a table query  and on the line 37 of the [PurgeAction.cs](https://github.com/Azure/azure-mobile-apps-net-client/blob/8f0fc245f29c5b3245ce27e8428b0f4a90b948bc/src/Microsoft.Azure.Mobile.Client/Table/Sync/Queue/Actions/PurgeAction.cs#L37): it states that if the Query.Filter is not null throw the Invalid operation Exception. Is this correct ? It eliminates the use of the TableQuery parameter on the PurgeAsync.

Thanks for your time. If you need more information please ping me.

**Comment by ericbrunner** [comment]
Maybe helpful: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter3/client/#purging-records-from-the-offline-cache

**Comment by NickPolyder** [comment]
Hello this is what i am using as a guideline.   
The call that gives me this exception is this   
```
var id = "Some Id";
var syncTable = mobileServiceClient.GetSyncTable<Entity>();
var tableQuery = syncTable.CreateQuery().Where(tt=> tt.Id == id);
await syncTable.PurgeAsync("purge_Entity", tableQuery, true, CancellationToken.None);

```

The entity has pending operations. But with the force parameter to true. It must revoke them right ?

**Comment by ericbrunner** [comment]
Right! But a Purge before a Pull makes no sense. I use it the same way and it works. What happens when you do a PullAsync with that query and afterwards do a PullAsync with same query and force=true as you wrote? In that case there are no pending operations. Force=true always bypasses the pending operations check and purges(clears content) of local db (sqlite on droid, core data on ios)

**Comment by NickPolyder** [comment]
The data are not created by the mobile app only retrieved and updated. So there is always a pull before the purge. Also the problem lies only when i supply TableQuery with `.Where( expression )`. If the purge is for all the entities then with the force = true the purge is successful. Now if you go and look at the [PurgeAction.cs line 37](https://github.com/Azure/azure-mobile-apps-net-client/blob/8f0fc245f29c5b3245ce27e8428b0f4a90b948bc/src/Microsoft.Azure.Mobile.Client/Table/Sync/Queue/Actions/PurgeAction.cs#L37) there is this if statement.

```
   if (this.Query.Filter != null || !this.force)
   {
                throw new InvalidOperationException("The table cannot be purged because it has pending operations.");
   }
```

This states that if the Query (TableQuery) has a where statement ($filter) then throw the InvalidOperationException.

**Comment by ericbrunner** [comment]
Well you are right. That is a curious code statement, because IMO it doesn't check if there are pending operations. Moreover a reason why I don't use the sync table query. Maybe the author @onovotny can help. I am a api user like you.

**Comment by elamalani** [comment]
@NickPolyder Thanks for using Azure Mobile Apps. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps).  At this point, we are not fixing any bugs in the product unless it's a critical issue.

I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!
