### ISSUE TITLE
How-to: DeleteAsync AFTER final UpdateAsync has succeed

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#358]
Hi,

I want to `UpdateAsync `a record in the remote database and afterwards I want to set the `Deleted `column to `true`. After some investigation with offline sync tables I found out that I can't directly set the `Deleted `property on the record inside an app and invoke the `UpdateAsync `method. It doen't work because the `Deleted `property is not sent to the remote database which is what I guess intented by design.

So I tried to invoked` UpdateAsync(record)`, then `PushAsync()` after that` DeleteAsync(record)` and again `PushAsync()`. Well that works in connected mode (phone has web access). But it doesn't work in disconnected mode(no web access), because the Updates added before the DeleteAsync is invoked are lost of that record.

My current attempt is to add an additional field in my remote database tables called `Completed `and put an UPDATE Trigger on the tables. Whenever I set the `Completed ` then in the app to **true** , the trigger will set the `Deleted `column of that records to **true**, too. That works in connected in disconnected mode of the app.

Is there a better option available from the SDK?

best
Eric

**Comment by elamalani** [comment]
@ericbrunner Thanks for using Azure Mobile Apps. This looks like a new feature request that the product doesn't support. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). 

I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!
