### ISSUE TITLE
After updating to 4.0.1 Android crashes

### ISSUE THREAD

**Issue by aj-ja** [Azure/azure-mobile-apps-net-client#364]
After I updated to 4.0.1 I cannot sign in in Android anymore. It crashes without providing any error message and stack trace. The only thing that I get in VS is "An unhandled exception occured."

I'm also using Mobile Center crash report and this crash is not reported. 

Tested that UWP works ok, have not tested iOS yet.

Current workaround: downgrade back to 4.0.0.

**Comment by BioTurboNick** [comment]
See #361, linked issue. Dependencies and method calls are scrambled around.

**Comment by BioTurboNick** [comment]
Tip: If you press Continue one time after an exception, the exception details will be printed to the Debug output. (May also be a debug logging setting to change to Detailed, but I forget which one).

**Comment by 12michel34** [comment]
Same problem here. LoginAsync() fails with "Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found."

**Comment by oreyg** [comment]
I think this is somehow related to my issue. Im getting 

`Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.App.Activity,Android.Net.Uri)' (defined in assembly 'Microsoft.Azure.Mobile.Client, Version=4.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35') with scope 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.App.Activity,Android.Net.Uri)`

during build.  
Im using Xamarin.Android.Support 25.3.1

**Comment by ComplexVariable** [comment]
Facing same issue as above when compiling in release mode. Debug mode is working fine.  Xamarin.Android.Support.CustomTabs is at v25.4.0.1.

How do i fix it ?

**Comment by BioTurboNick** [comment]
Use the client library 4.0.0 until 4.0.2 is released.

**Comment by elamalani** [comment]
@aj-ja  We released the latest version of Zumo .NET client SDK v4.0.2 today which includes the fix of this issue, please find more information [here](https://github.com/Azure/azure-mobile-apps-net-client/releases/tag/4.0.2).

**Comment by aj-ja** [comment]
great news, updated and no errors on Android anymore. Thanks!
