### ISSUE TITLE
Default Browser stays open after LoginAsync on UWP

### ISSUE THREAD

**Issue by KlausLoeffelmann** [Azure/azure-mobile-apps-net-client#365]
Hey guys,

I do not at all like the way how you did the transition from V3.x to V4.

- First of all, the Refs for Android are completely messed up, as stated in #364 and #361 already.
- Secondly, the communication of the breaking changes you introduced was extremely bad. There was NO documentation when you guys released the updates, and the docu is still in pretty bad shape.
- Thirdly - my actual issue - on Windows (UWP) now, the Edge Browser opens and it stays open on Login. This is pretty ugly behavior and absolutely not acceptable.

I really hope, you guys care, and there will be an updated version coming up, which fixes all these issues?

Klaus Loeffelmann
  Microsoft MVP

**Comment by bmourat** [comment]
Hi @KlausLoeffelmann 

Thanks for your feedback and we do care! I would like to comment on your third issue. First of all i would like to make sure, that i understand you right, and your issue is that after login procedure is complete in your app, the tab in your edge browser stays open in background while your app is in foreground. If that is the case, then I agree that it is ugly behaviour, it bothers me too, but this is the only behaviour which is possible. And i think it is rather reasonable, cause we are starting completely different app, we don't know what application will be launched to handle uri, and we can not just close something in other app because we want to. The OS and especially UWP platform wouldn't allow us to do that. At least that what i found during my investigation, and if you happen to know some way to do this, we will be glad to make necessary changes.

Thanks,
Murat

**Comment by KlausLoeffelmann** [comment]
Hey Murat,

thanks for your reply. Why isn't it possible - as it seems to be in Android and in iOS - to pass a View/Windows where the Web-UI gets hosted in?

This was also possible before in the 3.X Version of the Client. In that context: What was the reason you guys changed the behavior so drastically?

Thanks,

Klaus

**Comment by myokeeh** [comment]
Yeah, I feel this is a step backwards from UX perspective.

See #326 for some explanation.

**Comment by bmourat** [comment]
The main reason was change in google oauth authentication policies, they no longer allowed using web views for authentication. And i think it is just a matter of time until all oauth providers will incorporate this behaviour. Please see article [Modernizing OAuth interactions in Native Apps for Better Usability and Security](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html). And the reasons why it is working on Android and iOS are Chrome Custom Tabs on Android and SFSafariViewController on iOS, while there is nothing similar in UWP. So we had to use system default browser to perform authentication to the detriment of usability and user experience.

**Comment by KlausLoeffelmann** [comment]
I see. But would there be a way to use another UI flow based on the provider? So, when the dev goes for Live Account, AAD, Facebook and Twitter then to use a WebView, otherwise to use the browser? And then to switch to browser login as it becomes necessary? Probably by then Microsoft has reacted and comes up with a WebView which Google (and then the others) are accepting?

**Comment by KlausLoeffelmann** [comment]
And: will this cause a problem for Store Certification from your point of view?

**Comment by myokeeh** [comment]
Curious if there's communication between the Microsoft teams to get this sorted out.

As a customer wanting to start that conversation, who do I even contact? Edge team? Windows Insider team? Azure team? Where do I start?

**Comment by clarkezone** [comment]
Yea this totally sucks and is an experiential regression.  Not only that single sign on doesn't work with MSA on WIndows.

**Comment by BioTurboNick** [comment]
You can cache the credential and refresh it without UI. This "bad experience" only has to happen once per app unless data gets cleared or token has been long expired.

**Comment by Quico20** [comment]
When are you guys gonna fix this issue on UWP?
This isnt an issue for edge browser.  It happens to any default browser (Google chrome, opera, edge, firefox).
Its been weeks since it has been reported and o dont see any changes.
Should we stick With 3.1.0 for now?

**Comment by KlausLoeffelmann** [comment]
@BioTurboNick : not entirely true, but I may be wrong.
The refresh token for Microsoft Live Account is only good for 24h, or is it not? After that, you'd need to go over the webpage again. Or did I miss something in that workflow:

* I Login, store the token
* The next Time I Login, I use that token to Refresh-Login
* I store they Refresh token as base for the next login.

Correct?

**Comment by BioTurboNick** [comment]
https://azure.microsoft.com/en-us/blog/mobile-apps-easy-authentication-refresh-token-support
Refresh can work up to 72 hours after token expiration. So if your app only gets used ~1/week, then yeah, login needed every time.

**Comment by mnmilner** [comment]
It's now May 2018 and I haven't seen any action on this issue since last August. Is anyone working on a resolution? If this is in fact going to be an issue with a lot of oauth providers, one would assume that someone at Microsoft is working on a way to manage this much like you can on Android and iOS devices. Can we get some action or tell us where else we should be going to see development in this area?

**Comment by myokeeh** [comment]
@mnmilner I'm starting to move to this for the auth flow: https://stackoverflow.com/questions/46464234/microsoft-graph-api-and-azure-mobile-apps

There's no coherent authentication flow guidance I see from Microsoft. If it's there--it's very hard to find.

**Comment by adrianhall** [comment]
My recommendation (as always) is to integrate the provider specific SDK and use the token - the providers are generally able to do other things (like pop up custom forms) and it isolates the problem to the provider.

When you don't use the provider SDK, then you are using a web broker connection, which spins up an appropriate web browser and does the authentication throguh that.  iOS and Android have in-built capabilities to deal with this; Windows does not, so we are at the mercy of the WebAuthenticationBroker.

If WebAuthenticationBroker improves in a uap10.0 project, we'll pick up the changes.  I'll keep an eye on this, but it's unlikely to change.
