### ISSUE TITLE
Support for upload files to ApiController

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps-net-client#367]
Hello,

I don't know if this is the correct place to request this feature, but I can't access the "Mobile Apps" section of Azure Feedback. 

I need to upload a file to an ApiController and process the file on the server and the MobileServiceClient doesn't expose any method to accomplish that.

Thanks,

**Comment by elamalani** [comment]
@asierpn Thanks for the suggestion but we have no plans to support the feature in Mobile Apps.

**Comment by elamalani** [comment]
@asierpn Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us to prioritize this work in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
