### ISSUE TITLE
Integrate Xamarin.Auth (native login) with AppService?

### ISSUE THREAD

**Issue by hardcodet** [Azure/azure-mobile-apps-net-client#369]
Hi all

I'm trying to integrate my native login (in this case Google) I do through Xamarin.Auth with my Azure AppService. A posting on the Xamarin blog showed (partially) the use of the `LoginAsync `method with a custom token, but as far as Google is concerned: Is this even possible?

This ends up with an Unauthorized error (the `auth` object contains the data I got form the Xamarin.Auth login:

                var jObject =  new JObject(
                    new JProperty("access_token", auth.AccessToken),
                    new JProperty("id_token", auth.IdToken));

                await ServiceClient.LoginAsync(MobileServiceAuthenticationProvider.Google, jObject);

Some context: I used to do server-side flow before, which works fine because I register _web application_ OAUTH credentials with a client ID and client secret on Azure. With native login, I'm getting a token for _Android_ OAUTH credentials, and AppService doesn't seem to know what to do with that.

As an alternative, I could generate a custom token on Azure (I'm doing that for manual logins with email/password anyway), but I guess it would be quite a hassle to verify that the data (token) I receive is legit?

Thanks,
Philipp

**Comment by hardcodet** [comment]
I posted this on S/O and got some feedback. Turns out I can just register my Android Client ID with Azure AppService and a fake secret and it "magically" works. I'm not sure though whether I just exposed a gaping security hole there, or Azure falls back to verifying the token according to https://developers.google.com/identity/sign-in/web/backend-auth#verify-the-integrity-of-the-id-token. In any case, it's weird that it doesn't complain about a secret that obviously doesn't match.

Also, this approach would mean that I can only authenticate Android or iOS users given that an app client ID should be restricted to a given Android or iOS app for security reasons (so I have two client IDs).

I'm keeping this open for now, and will also post back here if I learn more about this.

**Comment by kpronz** [comment]
Any progress on this?  I have been searching for something like this for weeks and I finally came across this post.  Same scenario here with the bogus client secret in Azure.

**Comment by elamalani** [comment]
@hardcodet We dont plan to support this scenario in Azure Mobile Apps SDK.

**Comment by kpronz** [comment]
Hi elamalani,

Thank you for that clarification, however, could you point us to a resource to tell us how to use Google OAuth via Xamarin Forms, Azure App Service, and client authentication?

Thanks,
Kenon

**Comment by elamalani** [comment]
@kpronz Please use the documentation link below: 
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#clientflow

**Comment by kpronz** [comment]
HI @elamalani ,

Thank you for that link, unfortunately, the Google implementation seems to be out of date.  When I only send the access_token in the token argument I get an error back from the call to LoginAsync saying that id_token is required.  Then, when I send the id_token, I get an error back saying "Unauthorized".  I am using an "Android" Google OAuth client in the Android app and have configured the Azure App Service to use a "Web" Google OAuth client, in the same Google project.  What all do I need to pass in the token to LoginAsync so that Azure App Proxy will authenticate correctly?

As an aside, as stated above by @hardcodet , if I set the Azure App Proxy to use the "Android" Google OAuth client id and put in a bogus client secret, then the authentication works.  However, I'm planning on writing an iOS app for this project as well so that's not going to work for me as iOS will have a separate Google OAuth client id.

Thanks,
Kenon

**Comment by kpronz** [comment]
Hi @elamalani ,

Any updates on the documentation?

Thanks,
Kenon

**Comment by kpronz** [comment]
Hello,

I checked the documentation link above and the content hasn't changed and it's two and a half months later.  Could you all either please update the documentation to state that Google native login is not supported or update the documentation with a working Google example?  This is really frustrating that you are advertising a feature, and actually recommend using that feature in Production apps in other places in your documentation, but it doesn't work like your documentation states.  

Thanks,
Kenon

**Comment by kpronz** [comment]
Hello,

After thinking about this a bit more, I think this is a feature request:  My request is that the Google Authentication via Azure App Service be able to take more than one authentication key, and work properly with both "native" keys and "web" keys.  The use case is building an application that has three interfaces:  web, Android, and iOS using Azure app service as the back-end.  All three interfaces, I believe, will need separate authentication keys from Google to work.  This may be true of the other oAuth platforms provided through App Service as well, but I haven't looked into those.

Thank you for your consideration.

Kenon

**Comment by taimila** [comment]
I'm trying to get Google login client-flow to work with Azure Mobile App backend with no luck.

I run into same issues as @kpronz. First got "id_token required" and after providing that calling `client.LoginAsync()` just returns Unauthorized.

Please, let us know if this is something that should work or is it something I should give up trying to do.

**Comment by taimila** [comment]
I figured out what the issue was in my app. I didn't set the `ServerClientID` before doing the login with google.

**Comment by kpronz** [comment]
Hi @taimila , could you explain what "ServerClientID" you had to set?  Also, in the Azure App Service authorization configuration, did you put the Google "Android" or "iOS" clientID in that blank or did you put the Google "Web" clientID and client secret in that dialog?

**Comment by taimila** [comment]
First some background: I use *Xamarin.Forms* and implemented client-flow for Google on iOS and Android. I found [this blog post](https://causerexception.com/2017/12/03/google-native-login-with-xamarin-forms/) very helpful.

I configured app as instructed for server-flow login when using Azure Mobile App backend. So, on Google platform I registered the app as *Web-application* and then used created `client_id` and `client_sercret` in Azure Portal where Google Authentication is configured.

Using the code from linked blog post lead to same issues you had. However, when I changed the `GoogleManager` class a bit, it started to work. 

On iOS before calling `SignIn.SharedInstance.SignInUser();` I just set the `client_id` (same as in Azure portal) to Shared instance of SignIn like this `SignIn.SharedInstance.ServerClientID = "client id here";`.

On Android I had to add the same `client_id` to `GoogleSignInOptions` builder. I did it by adding the request for token id:

`GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DefaultSignIn)
                                                             .RequestIdToken("client id here")
                                                             .RequestEmail()
                                                             .Build();`

I hope this helps you get forward. I am by no means expert on this subject, just lucky.

**Comment by kpronz** [comment]
@taimila Thank you, thank you, thank you!  It's working!  Awesome job figuring that out!  I was lost for months!  If you're ever in Phoenix, AZ, I'll buy you a beer  :-).

**Comment by elamalani** [comment]
@hardcodet Thanks for using Azure Mobile Apps. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). Since this is a feature request in the product, I'll close this issue for now as we are not adding new features, but feel free to ask us questions if you have any. Thanks!

**Comment by EmilAlipiev** [comment]
@taimila why would you register as web-application in the firebase console if you are doing native android login like in the post you shared? I am registering in azure backend as below accessToken parameter below is the one i provide from        ```
GoogleSignInAccount account = result.SignInAccount;
account.IdToken
``` like you mentioned but I am still getting IdToken required error. I use the same clientid in the azure backend, firebase console and in the code. can you please tell me what else need to be done here?

```
  var zumoPayload = new Newtonsoft.Json.Linq.JObject();
                    zumoPayload.Add("access_token", accessToken);

                    var result = await App.Client.LoginAsync(provider, zumoPayload);

```

**Comment by EmilAlipiev** [comment]
ok I found the problem. code should be as below. Facebook SDK returns accesstoken while google sdk only returns idtoken. you should make it optional. I wonder if that is really hard to document somewhere. 

```
var zumoPayload = new Newtonsoft.Json.Linq.JObject();
                    if(provider== MobileServiceAuthenticationProvider.Facebook)
                    zumoPayload.Add("access_token", accessToken);

                    if (provider == MobileServiceAuthenticationProvider.Google)
                        zumoPayload.Add("id_token", accessToken);

                    var result = await App.Client.LoginAsync(provider, zumoPayload);
```
