### ISSUE TITLE
LoginAsync Method with parameter useSingleSignOn and default browser stays open using uriScheme [UWP]

### ISSUE THREAD

**Issue by Quico20** [Azure/azure-mobile-apps-net-client#370]
@dhei Man I saw you tutorial at comment #351, let me tell you that using uriScheme works for me, but still I cant make it work using the overload method with useSingleSignOn it send me to this place:

![singlesignon2](https://user-images.githubusercontent.com/13721058/28488396-c656b580-6e6e-11e7-817e-c4a5c4499833.png)

I'm using as a provider facebook authentication, an even though i had made it work with uriScheme, how can i set my azure mobile app or my client to make this work with useSingleSignOn boolean.

because If i go back to v3.1.0 it works great, but I think its important to update always to last version, so hopefully you guys can show me a tutorial or explain me if this still on development, because I cant find any sense to that overloaded method.

It feels like a regression in UX to me honestly. also if I use uriScheme and I'm refreshing my token or login in for the very first time it open default browser after loginasync and stays open, what happened there??

I'm using UWP, thats the actual ugly experience there. this v4.0.0 or v4.0.1 i think was to hasty, we werent rdy to it yet.

**Comment by artemious7** [comment]
I have the same problem.
UWP app (targeting 1703 Creators update, Windows 10.0.15063). Upgraded the package to v4.0.1 (v3.1.0 worked great). Now the LoginAsync extension method with useSingleSignOn = true leaves the login window open. If I close it, the method throws exception (HTTP code 403) - because it thinks I have cancelled the authentication.

I'm using this extensions method with Microsoft account provider:

> Microsoft.WindowsAzure.MobileServices.SingleSignOnExtensions.LoginAsync(this IMobileServiceClient client, MobileServiceAuthenticationProvider provider, bool useSingleSignOn)

**Comment by denmarksdev** [comment]
Same problem hear too.

**Comment by denmarksdev** [comment]
With this steps works for me:
example : https://workplace.azurewebsites.net

{url_scheme_of_your_app}  => workplace

**1 Azure > .Authentication / Authorization >>  ALLOWED EXTERNAL REDIRECT URLS**
{url_scheme_of_your_app}://easyauth.callback

2. replace the OnNavigatedTo()  the YourPage.Xml
protected override async void OnNavigatedTo(NavigationEventArgs e)
 {
     if (e.Parameter is Uri)
     {
         App.MobileService.ResumeWithURL(e.Parameter as Uri);
     }
 }

3 Add the following code snippet to the App.xaml.cs

protected override void OnActivated(IActivatedEventArgs args)
 {
     if (args.Kind == ActivationKind.Protocol)
     {
         ProtocolActivatedEventArgs protocolArgs = args as ProtocolActivatedEventArgs;
         Frame content = Window.Current.Content as Frame;
         if (content.Content.GetType() == typeof(**YourPage**))
         {
             content.Navigate(typeof(**YourPage**), protocolArgs.Uri);
         }
     }
     Window.Current.Activate();
     base.OnActivated(args);
 }

4.  Method AuthenticateAsync

user = await App.MobileService
             .LoginAsync(MobileServiceAuthenticationProvider.Facebook, **{url_scheme_of_your_app}**.);

5. Package.appxmanifest file

Navigate to Declarations, in Available Declarations dropdown list, **select Protocol and click Add button**. Now configure the Properties of the Protocol declaration. In Display name, add the name you wish to display to users of your application. In Name, **{url_scheme_of_your_app}.**

![image](https://user-images.githubusercontent.com/31458051/36348752-907b2544-1455-11e8-9cd7-e8dce2ca90c3.png)
![image](https://user-images.githubusercontent.com/31458051/36348756-9c8315c2-1455-11e8-9f67-88a441915271.png)

**Comment by elamalani** [comment]
@Quico20 Thanks for using Azure Mobile Apps. Were you able to resolve this issue based on the discussion above? Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!
