### ISSUE TITLE
Call signature of Client.LoginAsync() has changed please provide example code

### ISSUE THREAD

**Issue by JPhilC** [Azure/azure-mobile-apps-net-client#375]
I have been working through Adrian Halls [book](https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/) to develop a cross platform app with an Azure mobile service API backend. It appears that between V3 and V4 of this Nuget package the call signatures for MobileServiceClient.LoginAsync changed.

Please could you provide, or let me know where I could find, sample code for the client flow for social provider authentication and authorisation using the new Client.LoginAsync call signature that needs a  MobileServiceAuthenticationProvider and a JToken object. Ideally using MicrosoftAccount authentication as an example.

Thank you.

Phil Crompton

**Comment by BioTurboNick** [comment]
This is caused by having the old Android SDKs installed when you install the Azure Client SDK Nuget. It causes the Android project to reference the common NetStandard DLL rather than the Android-specific DLL.

**Comment by JPhilC** [comment]
So what should I do to fix it? Uninstall the android SDK and the reinstall the Nuget?

**Comment by BioTurboNick** [comment]
I think you just need to update the Android SDK, make sure it's targeting the latest in the project properties, and then reinstall the Nuget.

**Comment by LuisPignataro** [comment]
Hi, I have same problem here. I updated VS2017 to 15.3.2.
Xamarin 4.6.0.299
Xamarin.Android SDK 7.4.0.21

How I can verify if the installed dll is correct?

I spended a lot of time migrating PCL to NetStandar 1.4 only for re-enable google login!

Thank you.

**Comment by MatkovIvan** [comment]
Hi @JPhilC 
I wrote a small instruction for v4 [here](https://github.com/Azure/azure-mobile-apps-net-client/issues/341#issuecomment-308337440)
Also, there is sample project by @dhei : https://github.com/dhei/azure-mobile-apps-xamarinforms-login-sample

**Comment by JPhilC** [comment]
Thank you,

It is very much appreciated.

Phil
