### ISSUE TITLE
How can I switch from a facebook account to another account within the same app?

### ISSUE THREAD

**Issue by Quico20** [Azure/azure-mobile-apps-net-client#377]
When I was using Azure V3.1.0 whenever I logged out and then try to login I used to prompt the facebook login page.

but now If I log out and the try to log in, it doesnt prompt me the facebook login page.

So this is my issue, what If, what i'm looking is an app that enables me to be able to login with another user account within the same pc, tablet or phone in UWP or Xamarin? (actually in developing on UWP).

this is my logic for login:

I do have a class name AzureCloudService.cs: and it contains this method:

          ` public async Task<MobileServiceUser> LoginAsync()
           {
              ILoginUWPProvider UwpProvider = new LoginUWPProvider();

            client.CurrentUser = UwpProvider.RetrieveTokenFromSecureStore();
            if (client.CurrentUser != null)
            {
                // User has previously been authenticated - try to Refresh the token
                try
                {
                    var refreshedUser = await client.RefreshUserAsync();
                    if (refreshedUser != null)
                    {
                        UwpProvider.StoreTokenInSecureStore(refreshedUser);
                        return refreshedUser;
                    }
                }
                catch (Exception refreshedException)
                {
                    Debug.WriteLine($"Could not refreshed token: {refreshedException.Message}");
                }
            }

            if (client.CurrentUser != null && !IsTokenExpired(client.CurrentUser.MobileServiceAuthenticationToken))
            {
                //User has previously been authenticated, no refresh is required
                return client.CurrentUser;
            }

            // We need to ask for credentials at this point
            await UwpProvider.LoginAsync(client);

            if(client.CurrentUser !=null)
            {
                // We were able to successfully log in
                UwpProvider.StoreTokenInSecureStore(client.CurrentUser);
            }

            return client.CurrentUser;
        }`

UWPLoginProvider.cs class contains this method:

`public async Task<MobileServiceUser> LoginAsync(MobileServiceClient client)
        {
            return await client.LoginAsync(MobileServiceAuthenticationProvider.Facebook, "uriSchema");
        }`

also contain a LogoutAsync() method:

      `public async Task LogOutAsync()
        {
            if (client.CurrentUser == null || client.CurrentUser.MobileServiceAuthenticationToken == null)
                return;

            //Invalidating token on the mobile backend
            var authUri = new Uri($"{client.MobileAppUri}/.auth/logout");
            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("X-ZUMO-AUTH", client.CurrentUser.MobileServiceAuthenticationToken);
                await httpClient.GetAsync(authUri);
            }

            //Remove token from the cache
            var UwpProvider = new LoginUWPProvider();
            UwpProvider.RemoveTokenFromSecureStore();

            //Remove the token from the mobile service client.
            await client.LogoutAsync();
        }`

now if I try to logout it logs me out but whenever I try to login it automatically log my account, what if I want to have the chance to switch from one facebook account to another??? how can I achieve that using SDK 4.0.1??

This was easily achievable with SDK V3.1.0

**Comment by Quico20** [comment]
I know now that if I logout directly from my facebook account I'll be able to make my app to prompt the facebook login page. I see now that security had been increased with this 4.0.1 version.
but it isnt something I like at all.

**Comment by artemious7** [comment]
I have the same problem, but with Microsoft account auth provider. I have logged in using my personal account, but I cannot log out, and I do not want to use my personal account while debugging the app!
Any solution/workaround?

**Comment by elamalani** [comment]
@Quico20 Is your issue fixed? Please refer to #397 if you are looking for a workaround. I'll close it for now but feel free to ask us questions if you have any. Also, please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps).
