### ISSUE TITLE
After updating to v4 authentication to Google no longer caching on UWP

### ISSUE THREAD

**Issue by JeffDalby** [Azure/azure-mobile-apps-net-client#380]
Every since we updated to UWP authentication no longer seems to be cached against our App service.  Any time that the app is killed (intentionally or via the device closing it for whatever reason) we have to manually re-authenticate the user.  We check for auth the same way it's been done from back in the first guides to add auth to your mobile app (before it was app service) by requesting an essentially blank api url that requires auth, if it comes back with an unauthorized error we then bring up the login prompt. The auth token is cached the same as we always have, and matches the current documentation.

In the past that meant if a person didn't use our app for 30 days they had to log in again..which we like.  Now they have to re-authenticate sometimes more than once a day, depending on how they use their device.

Did something change so we now have to set the token expiration time somewhere?  Is it no longer automatic and we'll have to refresh the token manually somehow first?

**Comment by MatkovIvan** [comment]
Hi @JeffDalby 
Sorry for the long delay.

Unfortunately, I cannot reproduce that issue. `PasswordVault` worked fine during my tests.
Make sure that you followed steps in this tutorial: [Caching the authentication token](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#caching)
If the problem is still actual, could you please clarify reproduction steps or give a code sample?

**Comment by JeffDalby** [comment]
No worries, the good news is we don't have that many Windows users compared to other platforms, and so far at least we haven't gotten any complaints (outside myself because I'm one of the rare people who actually still have a Windows Phone).  Now that I know it at least can work I'll go through this in the next week or so and update you.  Thanks for making sure it works for you.

**Comment by elamalani** [comment]
@JeffDalby Any update on this issue? Were you able to fix this?

**Comment by elamalani** [comment]
@JeffDalby We haven't heard back from you. I'm closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
