### ISSUE TITLE
V4.0.0 is no longer useful for Xamarin.Forms apps

### ISSUE THREAD

**Issue by stefanov-stefan** [Azure/azure-mobile-apps-net-client#381]
Hey guys,

maybe it is not a bad idea to make sure that when upgrading the dependancies, we would not turn down some of the technologies that could be utilizing the Azure Client. v4 made it unable for Xamarin.Forms apps to be using it by the introduced .NET Standard dependency.

Package Microsoft.Azure.Mobile.Client 4.0.0 is not compatible with portable45-net45+win8+wpa81 (.NETPortable,Version=v4.5,Profile=Profile111).

More info here: https://forums.xamarin.com/discussion/comment/282126/#Comment_282126

**Comment by dansiegel** [comment]
PCL is being deprecated, and as such you shouldn't expect libraries to be maintaining PCL backwards compatibility. Ultimately your best bet is to update your project to .NET Standard 1.4 or later. You can easily maintain backwards compatibility with libraries that haven't updated to .NET Standard as shown below.

```cs
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>NETSTANDARD_LIBRARY_VERSION</TargetFramework>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wpa81+wp8</PackageTargetFallback>
    <DebugType>full</DebugType>
  </PropertyGroup>

</Project>
```

**Comment by artemious7** [comment]
@dansiegel, what do you mean by this?

> You can easily maintain backwards compatibility with libraries that haven't updated to .NET Standard as shown below.

I tried to add my .NET Standard 1.4 Library to a PCL (for Windows 8.1, Windows Phone 8.1 and Windows 10 UWP as well), but it did not allow me to, even with the `PackageTargetFallback` directive in the .NET Standard Library project file, as you advised.

**Comment by elamalani** [comment]
@stefanov-stefan We are going to support PCL in .NET SDK for Mobile Apps. I don't have a timeline yet but it will take us a few weeks to release the new SDK.

**Comment by dansiegel** [comment]
@artemious7 you can't force netstandard into a PCL, but you can maintain compatibility by updating your project to netstandard1.4 and following my guidance. This will allow you to continue using PCL dependencies your project may have while taking advantage of netstandard. It really is the better way to go as netstandard1.4 gives you much more API surface to work with in your Apps. PCL has always been very limiting as the lowest common denominator. You may notice the sample I gave you showed using netstandard for the target framework not PCL.

**Comment by elamalani** [comment]
@stefanov-stefan We released the latest version of Zumo .NET client SDK v4.0.2 today where we support PCL based Xamarin.Forms project, please find more information [here](https://github.com/Azure/azure-mobile-apps-net-client/releases/tag/4.0.2).
