### ISSUE TITLE
New Android project not compatible when Xamarin Forms nuget is added

### ISSUE THREAD

**Issue by SpiegelSoft** [Azure/azure-mobile-apps-net-client#384]
There is a repro at https://github.com/SpiegelSoft/IssueRepro

Create a new Android blank page.

Add the nuget packages Microsoft.Azure.Mobile.Client, Newtonsoft.Json and Xamarin.Forms.

The resulting project will not build.

The first errors in the output are as follows:

1>    Processing: C:\GitHub\IssueRepro\ReproClient\obj\Debug\__library_projects__\Xamarin.Android.Support.Transition\library_project_imports\res\values\values.xml
1>  obj\Debug\android\src\android\support\customtabs\CustomTabsClient_CustomTabsCallbackImpl.java:5: error: cannot find symbol
1>  	extends android.support.customtabs.CustomTabsCallback
1>  	                                  ^
1>    symbol:   class CustomTabsCallback
1>    location: package android.support.customtabs
1>  obj\Debug\android\src\android\support\v7\widget\Toolbar_NavigationOnClickEventDispatcher.java:27: error: cannot find symbol
1>  	public Toolbar_NavigationOnClickEventDispatcher (android.support.v7.widget.Toolbar p0) throws java.lang.Throwable
1>  	                                                                          ^
1>    symbol:   class Toolbar
1>    location: package android.support.v7.widget
1>  obj\Debug\android\src\md57018357d52b54713cd814fbd5262dd1f\FrameRenderer.java:5: error: cannot find symbol
1>  	extends android.support.v7.widget.CardView

**Comment by SpiegelSoft** [comment]
Some of these errors can be mitigated by adding Xamarin.Android.Support.CustomTabs, but this results in java.lang.IllegalArgumentException: already added :  Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat

**Comment by SpiegelSoft** [comment]
I also have a fork at https://github.com/SpiegelSoft/azure-mobile-apps-net-client/tree/xamarin-forms, which contains a Xamarin Forms Android project.

Any help getting this to build would be very much appreciated.

**Comment by MatkovIvan** [comment]
Hi @SpiegelSoft 
This is known issue that I've fixed some time ago. 
Workaround for `4.0.1`: use `Xamarin.Android.Support.CustomTabs 23.3.0`. Or you can temporary downgrade `Microsoft.Azure.Mobile.Client` to `4.0.0`
Detailed description: https://github.com/Azure/azure-mobile-apps-net-client/issues/361#issuecomment-315353068

Version with fix will be soon.

**Comment by elamalani** [comment]
@SpiegelSoft We released the latest version of Zumo .NET client SDK v4.0.2 today which includes the fix of this issue, please find more information [here](https://github.com/Azure/azure-mobile-apps-net-client/releases/tag/4.0.2).

**Comment by elamalani** [comment]
Closing this issue as we have released the SDK with a fix.
