### ISSUE TITLE
MSA Token retrieved from UWP WebAccountManager rejected by Azure App Service

### ISSUE THREAD

**Issue by BioTurboNick** [Azure/azure-mobile-apps-net-client#392]
Flow:
1. Use WebAccountManager to obtain an MSA authentication token as described here: https://docs.microsoft.com/en-us/windows/uwp/security/web-account-manager
2. Pass token to client.LoginWithMicrosoftAccountAsync();

Result is 401 unauthorized.

**Comment by MatkovIvan** [comment]
Hi Nicholas,

You can see a reason for errors in your application logs in the Azure Portal. It's very helpful to diagnose issues.
For example in your case that is:
```
JWT validation failed: IDX10708: 'System.IdentityModel.Tokens.JwtSecurityTokenHandler' cannot read this string.
The string needs to be in compact JSON format, which is of the form: '<Base64UrlEncodedHeader>.<Base64UrlEndcodedPayload>.<OPTIONAL, Base64UrlEncodedSignature>'..
```
this means you pass token in incorrect format.

Here is documentation for correct usage of `LoginWithMicrosoftAccountAsync` method: [Single Sign On using Microsoft Account with the Live SDK](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#client-livesdk)

Best,
Ivan

**Comment by BioTurboNick** [comment]
Thank you. I believe that documentation is newer than my issue here. It looks like it may have the details I need now. Closing.
