### ISSUE TITLE
After updating records from SQL on server - incremental sync becomes always full

### ISSUE THREAD

**Issue by vhnatss** [Azure/azure-mobile-apps-net-client#395]
Hi! Very weird issue - 
After I update lets say 1000 records on server with raw SQL - sync always downloads those 1000 records, no matter query is incremental:(  - 
  __config table has query id and deltaToken date so for example

"deltaToken|CptCode|CptCode_"	"2017-11-07T02:04:03.7040000+00:00"

and query is 

...tables/CptCode?$filter=(updatedAt%20ge%20datetimeoffset'2017-11-07T01%3A59%3A38.1790000%2B00%3A00')&$orderby=updatedAt&$skip=0&$top=20000&__includeDeleted=true

It always downloads those records:( But when I update records with EF or (what's makes it even more strange !!) from table editor in SQL Management Studio - then sync becomes incremental again!!!!

But we create models with EF and code-first approach - so **EF creates triggers for UpdatedAt - seems it shouldn't matter where update/insert comes from** - **anyway it ends up with trigger setting UpdatedAt.**

Yet turns out - it somehow matters:((

It's client version 3.1.0, server 2.0.0 - we can't switch to latest due to DataSet legacy support - and we rely on moving data from legacy db to our staging with SQL - so that's why it's crucial to have incremental sync working while merging data to staging with raw SQL not EF (mainly for reuse of legacy SPs and performance)

Thanx in advance!!

**Comment by vhnatss** [comment]
Ok - 

after mind-blowing debugging session - it's not a bug - it's a feature, at least sort of:)

filter of incremental sync has 'ge' - greater or equal - **so if you do with SQL - trigger does it so fast to the point that value of UpdatedAt is equal for all the records!!  So it does what is supposed to - ge - brings all the records.** I believe it's a bug though - condition should be 'greater' - so it won't be bringing same records all over again and again. For a big table and big batch - it can be significant overhead! I doubt Azure team was expecting that tables would be modified only with EF that does insert/update record by record.

**Comment by elamalani** [comment]
@vhnatss Thanks for using Azure Mobile Apps. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). Since this is a feature request in the product, I'll close this issue for now as we are not adding new features, but feel free to ask us questions if you have any. Thanks!
