### ISSUE TITLE
Cannot switch accounts in iOS11

### ISSUE THREAD

**Issue by aj-ja** [Azure/azure-mobile-apps-net-client#397]
Since some changes in iOS 11 cannot switch accounts. 

In case of Google in previous versions and other platforms it is possible to bypass the limitation where cannot switch accounts (see #377) and use mobile's main browser to go to accounts.google.com and log in with several accounts at the same time. 
Then when logging out of the app, it asked to choose account in the next login step. 

It appears that iOS 11 made some changes and it is not sharing session with the main browser anymore. This way user has to enter username and password when loging in in the app. And in the end it is not possible to switch accounts, because after that user is logged in automatically and there is no way to setup more accounts upfront. 

Looks like the only way around this is to uninstall the app.

Is there a solution to this? Is there a way to force browser clear login for app?

**Comment by MatkovIvan** [comment]
Hi @aj-ja,

Thanks for getting in touch!
Unfortunately, the SDK doesn't deal with it at the moment.
I found the workaround for your specific case (iOS+Google):
```C#
class iOSGoogleLogoutHelper : SFSafariViewControllerDelegate
{
    public static void Logout(UIViewController controller)
    {
        var url = new NSUrl("https://www.google.com/accounts/Logout");
        var safari = new SFSafariViewController(url, false);
        safari.Delegate = new iOSGoogleLogoutHelper();
        controller.PresentViewController(safari, true, null);
    }

    public override void DidCompleteInitialLoad(SFSafariViewController controller, bool didLoadSuccessfully)
    {
        controller.DismissViewControllerAsync(true);
    }
}
```
We'll look for a common solution to provide it out-of-the-box.

Best,
Ivan

**Comment by aj-ja** [comment]
Hi @MatkovIvan, 
thanks. How do I plug this into Xamarin Forms app? My current authentication is implemented as described here - https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users#add-authentication-to-the-ios-app (except using Google, not FB).
How do I attach this delegate?

**Comment by MatkovIvan** [comment]
Just call `iOSGoogleLogoutHelper.Logout(<your_controller>)` on your logout action. This tutorial doesn't describe log out so, place it where you do that. If you want to call it from the shared code you can add another method like `Logout()` in `IAuthenticate` interface.
You might use root controller as a parameter which can be got like that: `UIApplication.SharedApplication.KeyWindow.RootViewController`.

**Comment by aj-ja** [comment]
I added this to my Logout implementation in iOS project: `iOSGoogleLogoutHelper.Logout(UIApplication.SharedApplication.KeyWindow.RootViewController)` but it did not fix the issue. Instead I get the totally blank page on top of sign out page and I can't do anything on the screen because there are no navigation buttons.
Also I noticed that `DidCompleteInitialLoad` is not called. 
I'll try to figure out what's happening, but even if I restart the app after calling `iOSGoogleLogoutHelper.Logout` it still uses the previous account and does not ask for new login in Google.

**Comment by MatkovIvan** [comment]
Are there any errors in the log?

**Comment by elamalani** [comment]
@aj-ja I am checking back on this issue. Were you able to resolve it?

**Comment by aj-ja** [comment]
sorry for late reply, there were no errors in the log and I could not resolve the issue. I will check again and provide more information.

**Comment by elamalani** [comment]
Sounds good. I am closing this issue for now. Thanks!

**Comment by aj-ja** [comment]
I took another look and it still does not work, by implementing the solution I get a blank screen when pressing logout and I cannot navigate anywhere: 
![screen shot 2018-03-27 at 19 20 19](https://user-images.githubusercontent.com/29518231/37986135-6419252a-3203-11e8-9789-af06692cc7d7.png)

To narrow it down, I have implemented the suggestion for TodoAuthAzure sample and the issue persists. The repo is at https://github.com/aj-ja/xam-issues/tree/master/Issue397_TodoAzureAuth

The changes made is the new file: https://github.com/aj-ja/xam-issues/blob/master/Issue397_TodoAzureAuth/iOS/iOSGoogleLogoutHelper.cs
and added to call `iOSGoogleLogoutHelper.Logout(UIApplication.SharedApplication.KeyWindow.RootViewController);` at `AppDelegate.cs` in `LogoutAsync`.

If possible working sample would be nice, thanks.

**Comment by MatkovIvan** [comment]
@aj-ja 
This is because you are changing `Application.Current.MainPage` at the same time.
Commenting on the change of the main page right after the call will fix your problem.
To get it usable in your case I suggest waiting for the closure of this web page to change pages after that.
```C#
public class iOSGoogleLogoutHelper : SFSafariViewControllerDelegate
{
    private readonly TaskCompletionSource<bool> source = new TaskCompletionSource<bool>();

    public static Task LogoutAsync(UIViewController controller)
    {
        var url = new NSUrl("https://www.google.com/accounts/Logout");
        var safari = new SFSafariViewController(url, false);
        var helper = new iOSGoogleLogoutHelper();
        safari.Delegate = helper;
        controller.PresentViewController(safari, true, null);
        return helper.source.Task;
    }

    public override async void DidCompleteInitialLoad(SFSafariViewController controller, bool didLoadSuccessfully)
    {
        await controller.DismissViewControllerAsync(true);
        source.SetResult(true);
    }
}
```

**Comment by aj-ja** [comment]
@MatkovIvan thanks! It has solved the issue and now it is possible to pick an account next time after logout.
