### ISSUE TITLE
System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by mistryhardik** [Azure/azure-mobile-apps-net-client#398]
Trying to do a very simple **Xamarin.Android UnitTest app**

> We are able to successfully use the **same PCL** from an actual **Xamarin.Android** project, this issue appears only when referencing and using it from a **Xamarin.Android UnitTest app**

**Enviornment**
- Visual Studio for Mac (Community Edition v 7.3.2 build 12)

**Following is the project structure:**
- Project.PCL (PCL4.5 - Profile 111)
- Project.Droid (Xamarin.Android)
- Project.iOS (Xamarin.iOS)
- Project.Common (PCL4.5 - Profile 111)
- Project.Service (PCL4.5 - Profile 111)
- Project.Tests.Droid (Xamarin.Android UnitTest app)

**Steps tried to be able to fix this:**
- Ensure **Microsoft.Azure.Mobile.Client** is referenced to platform-specific projects as well
- Ensure version of **Microsoft.Azure.Mobile.Client** package is same across all the projects
- Delete /bin and /obj folder from the project and Rebuild
- Restart Visual Studio

Any advice to be able to fix this for the UnitTest app?

**Comment by MatkovIvan** [comment]
Hi @mistryhardik 

Simple unit test with SDK works for me, so could you provide a sample project to follow your reproduction steps?
Also, I have additional questions to identify a problem.
(1) What version of SDK do you use?
(2) It happens only on your main project or do you able to reproduce it on sample project?
(3) The exception happens in build time or runtime?

If it happens at runtime:
(4) Do you have stacktrace for it?
(5) What code causes this issue?

Best,
Ivan

**Comment by mistryhardik** [comment]
@MatkovIvan Sorry for the delay.

- Mobile Client SDK version with me was 4.0.2 (did you mean something else?).
- I was able to reproduce when using an alternate project as well.
- The exception occurred at runtime.

However, in the interest of time, we moved to writing our own way to handle HTTP requests.

**Comment by MatkovIvan** [comment]
No worries. What about (4) and (5)?
Also, as I wrote before, I cannot reproduce your case. So, could you please share reproduction sample?

**Comment by elamalani** [comment]
@mistryhardik Any update on this? Do you still see this exception?

**Comment by mistryhardik** [comment]
@elamalani We have switched our implementation by writing our own HttpClient handler instead of using Azure Mobile SDK provided for now. Sorry for late reply

**Comment by elamalani** [comment]
Thanks for an update @mistryhardik
