### ISSUE TITLE
Xamarin.iOS : IMobileServiceClientLoginAsync doesn't redirect back into the app with Safari

### ISSUE THREAD

**Issue by kewinremy** [Azure/azure-mobile-apps-net-client#404]
Dear Azure Team & especially Mister @dhei ,

**Context** : 
I am willing to authenticate my user with the MobileServiceClient from azure with the lastest version (4.0.2).

Here is my signature :  
var user = await Client.LoginAsync(GetController(), provider, uriScheme);

When I want to login my users with any of the standard IdP (Facebook, Google or Microsoft), I can get to the web view of the identity provider and submit the required information. 

**Problem:** 
Finally, the user is not redirected to my app. I get the following error:  "Safari cannot open the page because the address is invalid".

**Tests**
As suggested in this old post #351, I updated the following URI Scheme in azure portal under Authentication / Authorization > ALLOWED EXTERNAL REDIRECT URLS as such : 

Uri Scheme: xyz (alias mine)
xyz://easyauth.callback
https://xyz.azurewebsites.net

Indeed, I registered xyz in my info.plist file as defined by the documentation : 
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users. 

Finally I check my apps settings with the Resource Explorer : under Mobile App -> Development Tools -> Resource Explorer  but there is no "allowedExternalRedirectUrls" property ! I try to add it manually but the system removes it.

https://github.com/Azure/azure-mobile-apps-ios-client/issues/123

What else shall I do ? Did someone has a solution ? Thanks a lot for your support.

**Comment by MatkovIvan** [comment]
Hi Kewin,

Probably, you missed this point from [the documentation](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users#add-authentication-to-the-ios-app):

6. Update the AppDelegate class by adding the `OpenUrl` method overload, as follows:
    ```C#
    public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
    {
         return TodoItemManager.DefaultManager.CurrentClient.ResumeWithURL(url);
    }
    ```

Let me know if it doesn't help.

Best,
Ivan

**Comment by kewinremy** [comment]
Hi MatkovIvan, thanks a lot ! I added the OpenUrl method and it now works ! I can get my user credentials with id and token. 

Best regards

**Comment by mdizzy** [comment]
Where does the ItemManager/DefaultManager class come from? I was using the MobileServiceClient directly. to call ResumeWithURL but don't get the redirect.

**Comment by mdizzy** [comment]
NVM, I thought from an earlier thread that I had to use the full redirect url for the LoginAsync call but only needed the URLScheme.

**Comment by elamalani** [comment]
Closing this issue as the redirection works fine for @kewinremy.

**Comment by GUOLDEV** [comment]
Hi all,
I know this is a closed issue, but I am having the same issue as @kewinremy reported but with Microsoft.Azure.Mobile.Client 4.2.0, works fine on Android, but not for iOS.

![IMG_EC1A8847AE23-1](https://user-images.githubusercontent.com/22019245/108141492-8c772a00-710f-11eb-8f8b-121dbf7fe0be.jpeg)

**Comment by stefffdev** [comment]
Did you try what Ivan suggested?
https://github.com/Azure/azure-mobile-apps-net-client/issues/404#issuecomment-357951748

**Comment by GUOLDEV** [comment]
Hi @stefffdev, thanks for the prompt reply and yes I tried what Ivan suggested, but in the 4.2.0 version, ResumeWithURL changed a little bit as you can see below:

`
public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
{
     return TodoItemManager.DefaultManager.CurrentClient.ResumeWithURL(app, url, options);
}
`

Here is my info.plist URL Types setting, not sure if I am missing something.

<img width="1030" alt="Screen Shot 2021-02-17 at 5 14 45 pm" src="https://user-images.githubusercontent.com/22019245/108169078-f9a4b280-7143-11eb-84b3-9ef264517af6.png">

**Comment by stefffdev** [comment]
Check the documentation (https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users#add-authentication-to-the-ios-app), it seems you have to use base.OpenUrl now:

 ```csharp
 public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
 {
     if (TodoItemManager.DefaultManager.CurrentClient.ResumeWithURL(app, url, options))
         return true;
     return base.OpenUrl(app, url, options);
 }
 ```

**Comment by GUOLDEV** [comment]
Hi @stefffdev, I tried that as well, I ended up modifying all structure and got it working, it is good that it is working now, but I am still investigating the reason it was not working with the previous structure. Once I find the reason I will post it here. Thanks for your suggestions.
