### ISSUE TITLE
Question: PullAsync POST Request instead of GET

### ISSUE THREAD

**Issue by OPunktSchmidt** [Azure/azure-mobile-apps-net-client#405]
Hey,

as described in the article (https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library) an IMobileServiceTableQuery object is first converted to a URL (OData Query) and then back to SQL server-side.

> You can view the URI of the request sent to the backend by using message inspection software, as well as browser developer tools or Fiddler. If you look at the request URI, notice that the query string is modified:
> 
> GET / tables / todoitem? $ Filter = (complete + eq + false) HTTP / 1.1
> This OData request is in SQL query by the Server SDK:
> 
> SELECT *
>     FROM TodoItem
>     WHERE ISNULL (complete, 0) = 0

... our SQL queries usually look like:

**SELECT *
FROM tbl_Appointment
WHERE (APM_ID = xyz OR APM_ID = abc OR APM_ID = ghf ....)**

APM_ID (data type = Guid) is the primary key of the table. Overall, this results in a very long chain for the Where condition which then has to be converted to a URL. This leads to a bad request because the URL is too long (https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/requestlimits/). Currently we proceed in such a way that we query maximally 5 PrimaryKey Ids in the Where condition. If, for example, 1000 Ids are to be queried, this alone leads to 200 HTTP requests by our code (irrespective of the fact that the PullAsync makes further internal queries because of the 50s PageSize). We would like to minimize the HTTP requests that we generate directly.

I had asked that question to Stackoverflow nearly a year ago. Unfortunately, there was little response from other developers here: https://stackoverflow.com/questions/43539199/azure-appservice-imobileservicetablequery-query-with-much-ids

A developer made the suggestion to pass the Where condition in the HTTP request body and not to attach it to the URL but I did not find out how it would be possible with the Azure SDK.

Is it possible to pass queries with such large and long Where conditions to the Azure backend? A Custom API Function is out of the question. It must continue to run in the offline sync context.

Thanks.

**Comment by NickPolyder** [comment]
Hello. Your issue title is a little bit misleading.
I do not think that this is possible without a lot of customization on the Mobile Service pipeline. 
While using the TableController you can use post only for content creation. 
I see you are using OR on your WHERE statement. You maybe could use some other function that would make the same result ?

**Comment by OPunktSchmidt** [comment]
I had contact with the Microsoft Azure tech support. It is not possible. So you are absolutely right.
