### ISSUE TITLE
Azure Mobile Services Push 10,000 records takes more than 30 minutes

### ISSUE THREAD

**Issue by rodineyhm** [Azure/azure-mobile-apps-net-client#406]
In the application I enter 10K records (coming from a txt file) with InsertAsync in the local SQLLite base and only then use PushAsync to synchronize these new records in Azure's SQL.
Everything works fine, however, this takes just over 30 minutes to complete.

Task SyncOfflineCacheAsync():
Client = new MobileServiceClient( AppServiceUrl, new AuthenticationDelegatingHandler());
Client.SyncContext.PendingOperations
= 10.000
Using:
Microsoft.WindowsAzure.MobileServices.MobileServicesClient
public IMobileServiceSyncContext SyncContext { get; }
Microsoft.WindowsAzure.MobileServices.MobileServicesSyncContextExtensions
public static Task PushAsync(this IMobileServiceSyncContext context);
await Client.SyncContext.PushAsync();
= await for 30 minutes

After completing the insertion a call to PullAsync quickly gives the ok of the synchronized bases.
Clearing local data and calling PullAsync takes 3.5 minutes to bring the 10K records to the local base. Much less than Push but still unacceptable for the purpose of the application.

Task PullAsync():
string queryName = $"incsync:r:{typeof(T).Name}";
string Tabela_Processando = typeof(T).Name;
var query = table.CreateQuery()
await table.PullAsync(queryName, query);
= await fast after sync
= await for 3,5 minutes after local data base clear

Although there are 10K records the base has the physical size of less than 4MB.
During this time I see the records being added to the one-by-one database, and I realize that the local network traffic coming in or out is 100Kbps, well below the available bandwidth, and in Azure I see the SQL database at 20% DTU and Mobile Service with 300 to 500KB input / output data, 200 to 400 requests and response time from 0.4 to 1mms.

This is not normal, right?
Why do not I see all the available network band being used?
If I'm waiting for Push to be completed where can the bottleneck be, in the application or in Azure?
I'm using PCL and the Android application and UWP have the same behavior.

**Comment by rodineyhm** [comment]
At least for the upload I got as outline to use pagination of 1K lines, popular the data directly in the local base reading online, and only after starting the synchronization. I now have the 10K synchronized from Azure to the location in 20 seconds.
Thank you friends!

**Comment by gonzobrains** [comment]
@rodineyhm  Could you please clarify your solution?  I'm interested in how you did it. Thanks.

**Comment by rodineyhm** [comment]
> @rodineyhm Could you please clarify your solution? I'm interested in how you did it. Thanks.

In the TableController in GetAllItems() add [EnableQuery (PageSize = 1000)], or the number of records that you want to be retrieve per page.
