### ISSUE TITLE
Xamarin.Forms: CurrentPlatform is inaccessible in Android project

### ISSUE THREAD

**Issue by juarezasjunior** [Azure/azure-mobile-apps-net-client#408]
Hi,

I'm trying to use Azure Mobile Client with Android. But, when I add the line 
**Microsoft.WindowsAzure.MobileServices.CurrentPlatform.Init();**
in the MainActivity, it says that CurrentPlatform is inaccessible. It's funny, because in the same solution I have this line in iOS project.

![image](https://user-images.githubusercontent.com/36205387/35877608-f7acda98-0b5c-11e8-9323-d2b83baaffa0.png)

![image](https://user-images.githubusercontent.com/36205387/35877650-161535d4-0b5d-11e8-8a10-99005f84c276.png)

![image](https://user-images.githubusercontent.com/36205387/35877687-2f48ab6c-0b5d-11e8-91a7-382e737303dd.png)

![image](https://user-images.githubusercontent.com/36205387/35877721-5143abe0-0b5d-11e8-813f-b9392f7654a8.png)

Please, could you help me with this issue?

**Comment by MatkovIvan** [comment]
Hi,

It looks like the Android project uses the PCL library instead of platform specific one. Could you please share NuGet packages file and NuGet restore log to be able to say more specifically what is wrong.

Best,
Ivan

**Comment by juarezasjunior** [comment]
Hi,

Yes, it's a PCL project.

Well, I've removed the packages Microsoft.Azure.Mobile.Client.SQLLiteStore and Microsoft.Azure.Mobile.Client from the android project. Then, I changed the compilation target from 7.1 to 6.0. I installed again those packages mentioned above. After this, I compiled the solution and it worked, because the MonoAndroid version became 6.0. But, it's funny that I removed again the packages, change again the compilation target to 7.1 and added the packages. Now, it's working, although with MonoAndroid 7.1 and the last version from the packages.

It should be wrong, shouldn't? Because the requirement from Microsoft.Azure.Mobile.Client is MonoAndroid 7.0 and not 7.1. But, it's working now.

I'll send you the previous package file and the new one (that is working).

[packages.zip](https://github.com/Azure/azure-mobile-apps-net-client/files/1700600/packages.zip)

Thank you,
Juarez Júnior

**Comment by MatkovIvan** [comment]
@juarezasjunior 

In your old file mono android version is **6.0**. See `targetFramework` attribute:
`<package id="Microsoft.Azure.Mobile.Client" version="4.0.2" targetFramework="monoandroid60" />`

This is why it happened. Anyway, I'm glad that the problem is solved :smiley:

Best,
Ivan

**Comment by juarezasjunior** [comment]
Thank you @MatkovIvan for your help! :)
