### ISSUE TITLE
Building the SDK fails - Xamarin.Auth dependency issue

### ISSUE THREAD

**Issue by ltaljaard** [Azure/azure-mobile-apps-net-client#411]
After downloading the azure-mobile-apps-net-client solution and restoring the NuGet packages I get build errors like this: Error	CS0234	The type or namespace name '_MobileServices' does not exist in the namespace 'Xamarin.Auth' (are you missing an assembly reference?)	Microsoft.Azure.Mobile.Client(uap10.0)	C:\Users\Administrator1\Documents\source\repos\azure-mobile-apps-net-client-master\src\Microsoft.Azure.Mobile.Client\Platforms\android\Authentication\MobileServiceUIAuthentication.cs	6	Active

It turns out Xamarin.Auth is not included in the solution. Please look into that, it should be possible to build the solution when one follows the Readme instructions on the Azure/azure-mobile-apps-net-client github site.

In the interim, I have dug a bit deeper and tried to add the Xamarin.Auth NuGet package to the Microsoft.Azure.Mobile.Client project. When I then try to build it still gives the same error i.e. the build fails on line 6 of MobileServiceUIAuthentication.cs: "using Xamarin.Auth._MobileServices;". It can't find _MobileServices. I have had a look into the source of Xamarin.Auth on Github and found the following in file https://github.com/xamarin/Xamarin.Auth/blob/820c0388beae316e2750de823f2084c5a845de4c/source/Core/Xamarin.Auth.Common.LinkSource/UINativeNonIntegratedBrowsers/AuthenticationUIType.cs:

`3 | #if ! AZURE_MOBILE_SERVICES
4 | namespace Xamarin.Auth
5 | #else
6 | namespace Xamarin.Auth._MobileServices
7 | #endif`

What is this AZURE_MOBILE_SERVICES define about? I can't find any usable hits on that with Google. As a temporary workaround to get the azure-mobile-apps-net-client solution to compile, can I just change all the occurrences of "using Xamarin.Auth._MobileServices;" to "using Xamarin.Auth;" in the azure-mobile-apps-net-client solution after including the Zamarin.Auth NuGet package? (Note: I'm just asking whether I can do this in the interim - you should still be fixing this problem with the azure-mobile-apps-net-client solution so that it can be built out of the box when following the Reame instructions).

**Comment by MatkovIvan** [comment]
Hi @ltaljaard 

We are using our fork of Xamarin.Auth that included to project as git submodule and project refer it as sources files. You can see it [here](https://github.com/Azure/azure-mobile-apps-net-client/blob/4.0.2/src/Microsoft.Azure.Mobile.Client/Microsoft.Azure.Mobile.Client.csproj#L105-L106).
Please check out that you have `Xamarin.Auth` in the `src/External` folder.

Best,
Ivan

**Comment by ltaljaard** [comment]
Hi @MatkovIvan thank you for the explanation. But please update the readme doc on the azure-mobile-apps-net-client github page because it explains there how to build the project but there is no mention of the requirement for the external Xamarin.Auth project. Just include proper steps in the readme then it will save many people a lot of time and frustration.

**Comment by MatkovIvan** [comment]
The readme already has
```
git submodule init
git submodule update
```

Did you run these commands?

**Comment by ltaljaard** [comment]
@MatkovIvan I downloaded the zp file, I didn't use git clone as described in the readme. Is that why Xamarin.Auth didn't come with? I'll try the git clone option now. Either way, maybe you can then just put a comment there to say the Download Zip option should not be used.

**Comment by MatkovIvan** [comment]
Yes. Unfortunately, GitHub doesn't include submodules into the archive.

**Comment by ltaljaard** [comment]
@MatkovIvan It is going a lot better now, but now getting build errors like the following, it seems it can't find namespace 'GCM': Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Gcm' could not be found (are you missing a using directive or an assembly reference?)	Android.E2ETest	C:\GitSrc\azure-mobile-apps-net-client\e2etest\Android.E2ETest\LoginActivity.cs	10	Active

Also getting some build errors of this kind: Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'Constants' does not exist in the current context	Android.E2ETest	C:\GitSrc\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmBroadcastReceiver.cs	11	Active

**Comment by MatkovIvan** [comment]
It related to our test application, but not the SDK itself. If you don't need test applications you can freely unload projects in `e2etests` folder. If you really want to look at this, you can see that this project uses Xamarin Component "Google Cloud Messaging Client" that requires Xamarin account to download. I know VS doesn't show the original error in this case. Even more, Xamarin Components system is deprecated and replaced by NuGet. We'll update the test applications on occasion. PRs are welcome :wink:

**Comment by ltaljaard** [comment]
@MatkovIvan thank you, I have unloaded all the e2etests projects and left the unittest ones loaded. The solution now builds. One last question pretty please, what would be the best way to now get the code in azure-mobile-apps-net-server to run inside my own app? I'd like to have full access to the source code (not just symbol sources). Is there a way to reference this whole solution from my own solution, or must I manually copy some bits (projects I guess) over into my solution, or must I manually copy my stuff (projects) into the azure-mobile-apps-net-server solution? I have tried to google it but not been able to come up with any guidance for this. My solution have quite a lot of stuff in it so it will be painful to have to do it manually in either direction.

**Comment by MatkovIvan** [comment]
You can add SDK project (not the solution) to the existing solution. Use "Existing Project" menu item.
See [How to: Add Projects to a Solution](https://msdn.microsoft.com/en-us/library/ff460187.aspx)

**Comment by ltaljaard** [comment]
Ok thank you, that's how I did it the previous time but it was a bit of a struggle to get it to compile (it worked eventually). Shall we close this issue seeing that you logged #412 for updating the documentation?
