### ISSUE TITLE
When will the SDK support iOS 11 and Android Oreo?

### ISSUE THREAD

**Issue by rachael-ross** [Azure/azure-mobile-apps-net-client#415]
Hi, I have an app that is using the client sdk and now need to support iOS 11 and up to Android 8. Is there an ETA on when support will be added?

**Comment by elamalani** [comment]
@rachael-ross We support iOS 11 and Android 8 on native SDK but not on .net client SDK. This is in our backlog but there is no ETA yet.

**Comment by rachael-ross** [comment]
Native SDK? I'm not sure what you're referring to. Is there another? I'm pulling this into a Xamarin project with .NET Standard

**Comment by elamalani** [comment]
By native SDK, I mean the Azure Mobile Apps [iOS SDK](https://github.com/azure/azure-mobile-apps-ios-client) and [Android SDK](https://github.com/azure/azure-mobile-apps-android-client).

We don't support this in .NET SDK yet and as I said, it's in our backlog.

**Comment by rachael-ross** [comment]
Ah. I see. Thank you very much.

**Comment by Quico20** [comment]
Holy damn!!! when are you adding support to .Net Client for Xamarin.Forms, I cant believe that SDK doesnt supportr Oreo. at all YET!!! by the end of 2019, then how am i suppose to login using Mobile Apps in an Xamarin.Forms Project?? in and Android Oreo Enviroment!!!

**Comment by rachael-ross** [comment]
@Quico20  We're still using the SDK successfully on Oreo, Pie and are currently evaluating for Android 10.

**Comment by Quico20** [comment]
I'm having this Issue, I login using Azure Mobile Apps and authenticating with Facebook account, facebook authentication is successful, but as soon as my code make this call: await platformProvider.LoginAsync(client).ConfigureAwait(false);

it remains in the authentication page in an Android Oreo 8.1 emulator.
at UWP it works fine, but in UWP I used native code. in my Android project I'm using Xamarin.Forms.

Is there a way to fix this issue?? All I need I to get me back to the register page if there isnt an account register or to the app navigation main page.

**Comment by MatkovIvan** [comment]
Hi @Quico20 ,

Please open a separate issue with your problem. Also, please add details like used versions of SDK and support libs, repro steps and how the SDK is initialized (or just sample app), so the team can reproduce this problem and help you to solve it.

Thanks

**Comment by Bamptrp** [comment]
Good

**Comment by adrianhall** [comment]
We have just merged a big change into master which will be released in the next couple of weeks as v4.2.0 - this supports the latest iOS and Android builds.
