### ISSUE TITLE
Is there a non-platform-specific way to use Azure Mobile Apps?

### ISSUE THREAD

**Issue by charlesroddie** [Azure/azure-mobile-apps-net-client#416]
Is it possible Azure Mobile Apps be used entirely from a .Net Standard 2.0 project without any platform specific code or dependencies? So that it will work on any .Net Standard 2.0 platform (assuming SQLite works there)? (Assuming of course we build our own UIs.) 

Http requests to get data and interaction with local SQLite databases don't require platform-specific code. So it would seem logical to me, although I don't know the details of authentication.

This would give support for [Xamarin.Mac](https://github.com/Azure/azure-mobile-apps-net-client/issues/322) as well as WPF (direct or via Xamarin.Forms).

Is there anything that requires platform-specific code in Azure Mobile Apps?

**Comment by MatkovIvan** [comment]
Hi @charlesroddie 

This SDK is available for `.NETStandard 1.4` and higher. You can use the common features in your `.NETStandard 2.0` project, but for authentication and push functions, platform-specific things are required.

Best,
Ivan

**Comment by charlesroddie** [comment]
Thanks! That makes sense.
