### ISSUE TITLE
MobileServiceClient - LoginAsync error

### ISSUE THREAD

**Issue by viniciusmaia** [Azure/azure-mobile-apps-net-client#417]
I'm trying to use the LoginAsync method from MobileServiceClient class and always I had an exception

Java.Lang.NoSuchMethodError: No static method startActivity(Landroid/app/Activity;Landroid/content/Intent;Landroid/os/Bundle;)V in class Landroid/support/v4/app/ActivityCompat; or its super classes (declaration of 'android.support.v4.app.ActivityCompat' appears in /data/app/com.lssistemas.odontowaypaciente-1/base.apk)

I saw this topic https://github.com/Azure/azure-mobile-apps-net-client/issues/401 that recommends the use of same version for all supports packages in Android, but I'm using same version for all support packages and the errors continues. I tried many differents versions too, but doesn't work.

Here is my code:

> public class LoginClientServiceAndroid : ILoginClientService
    {
        public async Task<MobileServiceUser> LoginAsync(MobileServiceClient client, MobileServiceAuthenticationProvider provider, string uriScheme)
        {
            var user = await client.LoginAsync(CrossCurrentActivity.Current.Activity, provider, uriScheme);
            return user;
        }
    }

**Comment by MatkovIvan** [comment]
Hi @viniciusmaia 

Thanks for getting in touch.
Could you please share your nuget config?

Best,
Ivan

**Comment by elamalani** [comment]
@viniciusmaia Since we did not hear back from you, I will close this issue for now, but feel free to ask us questions if you have any. Thanks!
