### ISSUE TITLE
PullAsync offline

### ISSUE THREAD

**Issue by CarmineScala92** [Azure/azure-mobile-apps-net-client#420]
Hi
When the pullasync is performed offline, when the device is back connected, does the data download?

I also noticed that when the device comes back online, not even pushAsync automatically syncs. I noticed that the changed offline data is updated at the next online pushasync. Is it possible to have clarifications on this aspect?

Thank you for the support

**Comment by CarmineScala92** [comment]
I also noticed that when the device comes back online, not even pushAsync automatically syncs. I noticed that the changed offline data is updated at the next online pushasync. Is it possible to have clarifications on this aspect?

**Comment by MatkovIvan** [comment]
Hi @CarmineScala92 

This is by design. It just gives you more control and allows to avoid various conflicts and inconsistency. In addition, not all applications that use this SDK need this behavior.
You can perform the necessary actions when the device came back to online on your own.

Best,
Ivan

**Comment by CarmineScala92** [comment]
As I had imagined. Thanks for the support
