### ISSUE TITLE
JsonReaderException when PullAsync with image field

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps-net-client#422]
Unterminated string. Expected delimiter: ". Path '[13].imagen', line 1, position 1635736.

This issue is being registered in our HockeyApp - AppCenter only in Xamarin Android and only sometimes, always when doing a PullAsync of a table containing an image field. The same code is executed from Xamarin iOS and UWP and I have never received this exception on this platforms.

**Comment by MatkovIvan** [comment]
Hi @asierpn 

Thanks for getting in touch.
Could you please share full error message with stack trace and reproduction steps if possible?
Any additional information would be helpful (an example of problematic response etc).

Best,
Ivan

**Comment by MatkovIvan** [comment]
It looks like something went wrong outside this SDK. We can catch this internally, but without a valid response, we should re-throw with just another type. So, it makes little sense to me.
I guess would be better to add try/catch block around the call of `PullAsync` in your application.
As in [the documentation](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-offline-data#update-the-sync-behavior-of-the-client-app):
```C#
catch (Exception ex)
{
    Console.Error.WriteLine(@"Exception: {0}", ex.Message);
}
```

**Comment by asierpn** [comment]
The logs I've send you are from a try/catch block surronding the whole LoadNextItems method, the app is not crashing, but this collection does not load properly when this issue happens, because the first I do is to sync it, I can surround only the PullAsync line into a try/catch to disable the offline sync if this issue occurs and at least load the cached items. 

On the server side there is a default tablecontroller. This code is in production since January, and I get this exception two or three times each month on Android, but never on iOS or UWP, so if this bug is not related with this SDK, could it be related with the HttpClient implementation of Mono Android?

**Comment by asierpn** [comment]
No, for the last exception which I have logged I can see the request in App Insights and it returned HTTP 200 in 3 secs, the request returned 14 items with an image of 20-40Kb each one.

![serverrequest](https://user-images.githubusercontent.com/9281751/39142797-f6c006ae-472b-11e8-97fd-804ee18887b2.png)

**Comment by asierpn** [comment]
I'm still getting this exception sometimes on Xamarin iOS and Xamarin Android also on regular LookUpAsync operations when a field of the Json payload is a binary, seems that fragmentation is not working correctly on this platforms. I didn't get this exception on UWP platform.

**Comment by bmourat** [comment]
@asierpn 
As I understand, it is parsing server response which is throwing these exceptions. So we need to find out what is being parsed and why it fails. When sending binary payload SDK will automatically convert it to base64 encoding, so there shouldn't be any symbols that can break parsing process. Can you confirm that all your binary payloads are in encoded on the server side?

Best,
Murat

**Comment by asierpn** [comment]
@bmourat 
I use regular Table Controller to retrieve the data, the Data Model property is defined as a byte array, the context where the error occurs is very simple.

`public byte[] Image { get; set; }`

**Comment by bmourat** [comment]
Yes, I understand this. And I've just experimented with this myself, and everything seems to be working. So my assumption is that server is returning something unparsable. Maybe this is happening with some specific image? I think we need to investigate what is stored in this column on the server.

**Comment by asierpn** [comment]
The table is storing a list of news, all news have an image and are retrieved by all users of the app from UWP, Xamarin iOS and Xamarin Android. It cannot be something related with some specific value because I only get the exception from iOS and Android sometimes. Initially I thought that it was something related with HTTP and network, but my attempts to reproduce the issue under bad network conditions were not successful.

**Comment by bmourat** [comment]
I wonder if it would be possible to get the content of the server response when this is happening? Maybe LoggingHandler will help. See [here.](https://github.com/Azure/azure-mobile-apps/wiki/Help,-my-app-isn't-working!)

**Comment by asierpn** [comment]
I will try to get that info when the bug happens again, thanks for the link. I will update this ticket when I have more info.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
