### ISSUE TITLE
No refresh tokens were found in the token store - token refresh fails

### ISSUE THREAD

**Issue by aj-ja** [Azure/azure-mobile-apps-net-client#424]
Hi, authentication token refresh with Google fails. The error in server log stream: 

```
Received request: GET https://mysite.azurewebsites.net/.auth/refresh
JWT validation succeeded. Subject: 'sid:3dc87fa73828e752e474d5c206c0b61a', Issuer: 'https://mysite.azurewebsites.net/'.
The refresh request issued by sid:3dc87fa73828e752e474d5c206c0b61a (SID: b9aced1d070cc99085d6e87645c036fb) failed because no refresh tokens were found in the token store.
Sending response: 403.80 Forbidden
```

I run some tests and it happens shortly after successfully logging in also.
I'm passing access_type=offline when logging in. 
In Azure Portal, in Authentication&Authorization section Token Store is On.

What else could be wrong?

As the result users have to login after an hour and if they are in the middle of using the app, it starts failing without being able to refresh the token for users seamlessly.

**Comment by bmourat** [comment]
Hi @aj-ja !

Please try adding parameter
```prompt="consent"```
during your login call. I've checked it works for me!

Best,
Murat

**Comment by aj-ja** [comment]
@bmourat thanks! Now I'm getting "refreshed google tokens successfully".
