### ISSUE TITLE
Is there any way to open login page without showing url?  #Question

### ISSUE THREAD

**Issue by abenedykt** [Azure/azure-mobile-apps-net-client#427]
I'm using Microsoft/Facebook/Google authentication. It works fine. 

`await _mobileClient.LoginAsync(Context, selectedProvider, "appName", parameters);`

AndroidManifest.xml looks like this...

```
<activity android:name="com.microsoft.windowsazure.mobileservices.authentication.RedirectUrlActivity" android:launchMode="singleTop" android:noHistory="true">
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="shemeName" android:host="easyauth.callback" />
			</intent-filter>
		</activity>
```

It pops out the browser, logs in and goes back. The thing is that I would like to hide the navigation toolbar in the browser to hide the url and everything that is not needed at this point. 

Any ideas how can I achieve that?

**Comment by ltaljaard** [comment]
Hello 4rchie, if you ever achieve this could you kindly post the how-to on this thread? I’d like to do the same.

On 25 May 2018, at 10:51, 4rchie <notifications@github.com> wrote:

I'm using Microsoft/Facebook/Google authentication. It works fine.

await _mobileClient.LoginAsync(Context, selectedProvider, "appName", parameters);

AndroidManifest.xml looks like this...

```
```
It pops out the browser, logs in and goes back. The thing is that I would like to hide the navigation toolbar in the browser to hide the url and everything that is not needed at this point.

Any ideas how can I achieve that?

**Comment by bmourat** [comment]
Hi @abenedykt 
I don't think that this is possible. First of all, that depends on the default browser that is installed on the system. It should be able to do this, but I don't know any major mobile browser that has such setting. And second, this would be wrong from a security point of view. It is critically important for the user to be able to tell which authority they are talking to when they are visiting a website, in particular when they are authenticating.

**Comment by abenedykt** [comment]
@bmourat it sounds fair for me. However hiding that url would greatly improve user experience. I was thinking about using webview but also didn't managed to make it work. So i'm looking for any alternatives.

**Comment by bmourat** [comment]
@abenedykt So you want the call to sdk ```LoginAsync``` method to show window without the address bar? Since sdk uses Xamarin.Auth underhood i don't think this is possible. Maybe there is some way to do this manually outside of the sdk, but i can't be sure!

**Comment by ltaljaard** [comment]
I read somewhere that they now route the login through the browser, citing various security benefits. But I think they should dream up something better, something that gives the app a native look & feel. It looks very unprofessional when your app switches out to a browser window to handle the login UI part. In my opinion that would raise a lot of eyebrows with users. I’m not sure that I would trust a popup login screen going through a browser myself. @elamalani


On 29 May 2018, at 09:45, Murat Baysangurov <notifications@github.com> wrote:

@abenedykt <https://github.com/abenedykt> So you want the call to sdk LoginAsync method to show window without the address bar? Since sdk uses Xamarin.Auth underhood i don't think this is possible. Maybe there is some way to do this manually outside of the sdk, but i can't be sure!

**Comment by ltaljaard** [comment]
@elamalani I mean for your planned next version, I do understand that you won't be changing the existing Mobile Apps.

**Comment by adrianhall** [comment]
The proper way to do this is to implement the provider SDK (e.g. Facebook SDK, Google SDK, MSAL) and pass the token into the LoginAsync() method.  This way, you control (or at least the SDK controls) how the pop-up happens.  

As others have commented, if you don't do this, you are at the mercy of Xamarin.Auth - which, as others have pointed out, uses the installed browser with little to no control.
