### ISSUE TITLE
Client not sending changes to server

### ISSUE THREAD

**Issue by JCpoz123** [Azure/azure-mobile-apps-net-client#428]
I'm using the latest client with offline sync enabled along with optimistic concurrency.  After calling the UpdateAsync method, before the request is sent I can see my record was updated in my local SQLite databse, but after the request is sent the row is reset to the original values.  Looking at the request on the server, the Id of the record is received but none of my object's data is sent (the delta shows no changes).  InsertAsync works fine so I don't think it's a serialization issue with my classes.  I have the Version field in my object(s) and it is getting populated locally on the PullAsync.

I can provide more details if necessary.  I've been debugging/tracing/fiddler-ing this and can't figure out what the issue is.

**Comment by bmourat** [comment]
Hi @JCpoz123 

It would be super helpful to get some sample project to be able to reproduce this. If it is not possible, could you please provide additional info:
- how do you set up your sync context
- how do you perform synchronization
- what response do you receive from the server 
- what is your table structure

Thanks,
Murat

**Comment by JCpoz123** [comment]
I will see if I can put together a sample project that recreates the issue.
In the meantime:
- The mobile service sync context is instantiated using a local SQLite store and a sync handler.  We use the handler to perform extra processing on certain tables.  The issue happens on all tables.  Our service is running on Azure.
- We use the Azure.MobileServices.MobileServiceClient to handle synchronization.  Our app works on/offline.
- 200.  After the response is received on the client the row is returned to it's original state, but breaking just before the request is sent the row in the local DB has the updated values.
- There are 20+ tables, none of which are updating.  The only commonality are the system property columns, which are named differently but the app service uses Fluent API in the dbContext.OnModelCReating to map the fields (createdAt, updatedAt, deleted, version) to their actual column names.

I was wondering if the issue is related to how the version field is handled.  POST/insert works (as does delete) but maybe the PATCH/updating is having an issue with the mapping.

**Comment by JCpoz123** [comment]
I have figured out the issue.  My controllers were annotated with [MobileAppController] which apparently causes issues.
https://github.com/Azure/azure-mobile-apps-net-server/issues/123
