### ISSUE TITLE
PullAsync with more than 50 records

### ISSUE THREAD

**Issue by CarmineScala92** [Azure/azure-mobile-apps-net-client#429]
Hello,
I have the following problem:
pullasync does not work properly when I have to read more than 50 records. It happens that only 5 records are left to me.

How can I solve?

Thanks for the support

**Comment by CarmineScala92** [comment]
I solved the problem was my mistake. Pulling makes more calls when there are more than 50 records. But is it not possible to intercept the different calls? Example:

the pull reads the first 50 records, "I do some things" then I read another 50 records etc.

**Comment by bmourat** [comment]
Hi @CarmineScala92 
I don't think there is such mechanism, but you can control page size with ```PullOptions``` parameter

**Comment by ltaljaard** [comment]
Not sure exactly what your original problem was, but if you do a PullAsync specifying your own query it could run out of "nodes" (an odata thing). You can extend the amount of allowed nodes by adding this tag to your GetAllXXX() method in your table controller in the backend app:      [EnableQuery(MaxNodeCount = 1000)] (or the limit you choose).

For more on this topic see [https://stackoverflow.com/questions/48972334/azure-offline-sync-how-to-use-contains?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa%20and%20http://odata.github.io/RESTier/v0.6/#02-08-Customize-Query](url)

**Comment by CarmineScala92** [comment]
Thank you so much ltaljaard  for the support. I solved the problem.
