### ISSUE TITLE
Xamarin android apps need the Custom Tabs NuGet for auth to work

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/azure-mobile-apps-net-client#430]
When using the mobile client SDK in a Xamarin Android app to handle server-flow authentication, you get a crash in the app unless you install an additional NuGet package.

*To reproduce*

* Create a brand new Xamarin Forms Multiplatform app using either Visual Studio 2017 or Visual Studio for Mac.
* Add the "Microsoft.Azure.Mobile.Client" NuGet package.
* Configure authentication in an app service using Facebook/Twitter etc. in the Azure Portal
* Add authentication to your app as shown here - https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users
* Run the app on Android. When you try to authenticate it will crash:
    > Java.Lang.NoSuchMethodError: No static method startActivity(Landroid/app/Activity;Landroid/content/Intent;Landroid/os/Bundle;)V in class Landroid/support/v4/app/ActivityCompat; or its super classes (declaration of 'android.support.v4.app.ActivityCompat' appears in /data/app/com.companyname.HappyXamDevs--Ccazm6xzwYR9Eq7TOFMkQ==/base.apk)

To fix this - you have to install the Xamarin.Android.Support.CustomTabs NuGet package into your Android app.

**Comment by MatkovIvan** [comment]
Hi.

The custom tab package is listed in the dependencies for [SDK NuGet package](https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client/). So, it's required and should be added automatically.
It can be related to https://github.com/Azure/azure-mobile-apps-net-client/issues/401#issuecomment-356277594 If it isn't your case could you please share the nuget config or the sample app?

Best,
Ivan

**Comment by ltaljaard** [comment]
@MatkovIvan I had the same issue a while back and had to install CustomTabs manually (or update the installed version manually). So I'd suggest you test this for yourself with a new project to confirm whether this is still a problem.

**Comment by jimbobbennett** [comment]
@ltaljaard It is a problem - just been trying this with the Xamarin Forms templates in VS 15.7.3 and latest Mobile Client.

The templates are on v27 of the support libraries, and this seems to be the way forward for new apps so @MatkovIvan as a suggestion can the dependency be bumped to Android 8.1/SDK27 and associated support libs?

**Comment by MatkovIvan** [comment]
@jimbobbennett Thanks for the suggestion. We'll consider and test this when preparing the next version.

**Comment by theotherpotter** [comment]
I've been fighting with this for the best part of 2 days and it's taken a lot of digging to finally come across a solution that works.  I'm working through the samples provided on the microsoft site as per the original post using the samples downloaded from the Xamarin Samples github (so it should work out of the box, but doesn't).  As someone new to Xamarin it's not a particularly welcoming experience and needs to be resolved IMO.

**Comment by kickstart750** [comment]
@jimbobbennett - Thank you, thank you, thank you!

I'm just learning Xamarin and this was a huge roadblock for me... installing the CustomTabs NuGet, as you suggested, allowed me to get the TodoAzureAuth (sample) working.

Very frustrating the microsoft sample does not work out of the box.  I spent many hours trying to solve for this until I finally found your post.

**Comment by MatkovIvan** [comment]
Hi there,

We've added note about this in the documentation, so I'm closing the issue.

We are considering introducing additional NuGet's target framework dependency groups for newer `Xamarin.Android` versions. It should cover most cases but not all of them. So until the fix is released or if it doesn't cover your case, please use this workaround - install the required version of the `Xamarin.Android.Support.CustomTabs` NuGet package directly into your project.

Thanks,
Ivan
