### ISSUE TITLE
How to ignore a model property

### ISSUE THREAD

**Issue by rachael-ross** [Azure/azure-mobile-apps-net-client#432]
We're using the Mobile Apps SDK and have a class that is stored as table data. We want to add a calculated field property to this class, but not store/sync the value. Is there an attribute we can use to instruct the SDK/SqlLite to ignore it? We've tried [JsonIgnore], but that doesn't work. Is there some special setting we can use on the MobileServiceJsonSerializerSettings() where decorated members will be ignored?

**Comment by ltaljaard** [comment]
[JsonIgnore] should do the trick for a client side table.

Btw, you can make an entire table client-side only by implementing your own Azure Sync Handler class (inherits from IMobileServiceSyncHandler). Then in method ExecuteTableOperationAsync you return a null value for the "local only table" and then the pending operation in that table is considered to be successfully processed - so it ends up never sending the data in that table to the backend.

Anyway, in that method you also have control over which fields are sent over to the server, you can do this: operation.Item.Remove("...your local-only field name..."); That's kindof another way you can suppress specific fields from being sent, so you could have a table that stores some additional fields only on the client without ever syncing those fields to the server-side table. Maybe you can hack it for your requirements given these options.
