### ISSUE TITLE
URGENT: "Download Source Code" steps on the main Readme.md guide does not work anymore

### ISSUE THREAD

**Issue by ltaljaard** [Azure/azure-mobile-apps-net-client#434]
Around three months ago the steps you gave in the Readme.md file worked fine to get the azure-mobile-apps-net-client solution running locally in Visual Studio 2017 on Windows (latest patched release):

git clone https://github.com/Azure/azure-mobile-apps-net-client.git
cd ./azure-mobile-apps-net-client/
git submodule init
git submodule update

And then: 

Building and Referencing the SDK

Open the Microsoft.Azure.Mobile.Client.sln solution file in Visual Studio 2017.
Ensure you have connected an iOS Build Agent prior to building
Use Solution -> Restore NuGet Packages...
Press F6 to build the solution.

I tried doing this again today and it's failing straight away when opening the .sln file. A popup box comes up with the title  "Time to update" and message body "We've detected your solution is currently using Xamarin Components, which is no longer supported. Please remove the used Components manually and reopen the solution."

Please update the downloadable solution for azure-mobile-apps-net-client urgently.

Trying to build the solution as it stand now results in the below 15 errors:

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | CS0246 | The type or namespace name 'Gcm' could not be found (are you missing a using directive or an assembly reference?) | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\LoginActivity.cs | 10 | Active
Error | CS0246 | The type or namespace name 'Gcm' could not be found (are you missing a using directive or an assembly reference?) | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmBroadcastReceiver.cs | 7 | Active
Error | CS0103 | The name 'Constants' does not exist in the current context | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmBroadcastReceiver.cs | 11 | Active
Error | CS0103 | The name 'Constants' does not exist in the current context | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmBroadcastReceiver.cs | 12 | Active
Error | CS0103 | The name 'Constants' does not exist in the current context | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmBroadcastReceiver.cs | 13 | Active
Error | CS0103 | The name 'Constants' does not exist in the current context | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmBroadcastReceiver.cs | 14 | Active
Error | CS0246 | The type or namespace name 'GcmBroadcastReceiverBase<>' could not be found (are you missing a using directive or an assembly reference?) | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmBroadcastReceiver.cs | 15 | Active
Error | CS0246 | The type or namespace name 'Gcm' could not be found (are you missing a using directive or an assembly reference?) | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmService.cs | 8 | Active
Error | CS0246 | The type or namespace name 'GcmServiceBase' could not be found (are you missing a using directive or an assembly reference?) | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmService.cs | 13 | Active
Error | CS0115 | 'GcmService.OnError(Context, string)': no suitable method found to override | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmService.cs | 23 | Active
Error | CS0115 | 'GcmService.OnMessage(Context, Intent)': no suitable method found to override | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmService.cs | 27 | Active
Error | CS0115 | 'GcmService.OnRegistered(Context, string)': no suitable method found to override | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmService.cs | 38 | Active
Error | CS0115 | 'GcmService.OnUnRegistered(Context, string)': no suitable method found to override | Android.E2ETest | C:\Users\Administrator1\Documents\Azure\azure-mobile-apps-net-client\e2etest\Android.E2ETest\Services\GcmService.cs | 43 | Active
Error |   | The "CreateAdditionalLibraryResourceCache" task failed unexpectedly.System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.   at System.IO.Path.NewNormalizePathLimitedChecks(String path, Int32 maxPathLength, Boolean expandShortPaths)   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)   at System.IO.Path.InternalGetDirectoryName(String path)   at Xamarin.Android.Tools.Files.CopyIfChanged(String source, String destination)   at Xamarin.Android.Tasks.CreateAdditionalLibraryResourceCache.Execute()   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() | Microsoft.WindowsAzure.Mobile.SQLiteStore.Android.Test |   |   |  
Error |   | One or more errors occurred. | E2ETest | C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Windows.After.targets | 93 |

**Comment by MatkovIvan** [comment]
Hi @ltaljaard 

Thanks for getting in touch and pointing it out.
As a workaround, I suggest гunloading or removing our test projects from the solution, as it isn't related to the SDK, but only to the test applications.

Best,
Ivan

**Comment by MatkovIvan** [comment]
Hi @ltaljaard 

Thanks for getting in touch and pointing it out.
As a workaround, I suggest unloading or removing our test applications from the solution, as it is not related to the SDK, but only for the test applications.

Best,
Ivan

**Comment by ltaljaard** [comment]
Hi @MatkovIvan 

Unloading or removing the tests (E2E and Unit) might have been ok I guess as a temporary workaround, but the other problem is that the two core projects in the main Solution, i.e.

1. Microsoft.Azure.Mobile.Client

2.Microsoft.Azure.Mobile.Client.SQLiteStore

are still using the .NET Standard 1.4 Target Framework. They should be updated to use the .NET Standard 2.0 target framework (to get away from the PCL world and so that the latest Nuget packages can be loaded into the project). At the moment these projects won't compile under Visual Studio for Mac due to this. If I simply change the target framework to 2.0 for these projects then a bunch of other errors come up (to do with the ore recent and incompatible Nuget packages). More work is needed to do this properly (not too much but still). And then the changes should be merged here so that everybody can simply pull the latest version and get on with writing their apps rather than having to waste time on all of this just to get the basic source code solution working.

**Comment by dhei** [comment]
Closing as the test application from `Microsoft.Azure.Mobile.Client.sln` is fixed by #435
