### ISSUE TITLE
How to use a proxy to sniff traffic?

### ISSUE THREAD

**Issue by gonzobrains** [Azure/azure-mobile-apps-net-client#436]
I have attempted to use Fiddler along with my Android device to diagnose an issue I have with certain requests being sent as Updates rather than Inserts.  However, it doesn't appear that the Android proxy settings work with this client library.  I can see traffic in Fiddler through the device's browser but not my own application.  

I even went as far as creating my own custom ProxySelector.  I can see traffic for the Microsoft login and my own HockeyApp-based logging, but I don't see any Azure sync-related data.  Does the app not honor ProxySelector or the Wi-Fi access point's proxy settings?  If not, is there any way to either get my app to use proxy settings or use another method by which I can sniff traffic?  Thanks.

**Comment by MatkovIvan** [comment]
Hi @gonzobrains 

Thanks for getting in touch!
You can use the same approach that we use in our test application:
https://github.com/Azure/azure-mobile-apps-net-client/blob/f3acf8ae87cb585203d9ffaf30f19f257cdeb0fb/e2etest/E2ETest/FunctionalTests/FunctionalTestBase.cs#L34-L41

Feel free to reopen the issue if it doesn't work for you.

Best,
Ivan

**Comment by gonzobrains** [comment]
Does this require me having to compile the mobile services client from
source?  Is there any particular reason why this isn't exposed through the
compiled library available through NuGet?

**Comment by gonzobrains** [comment]
Oh, and lastly, is there any way to just get the mobile client to use the
Android proxy defined in one's Wi-Fi access point settings as used by a
device's web browser?  That would be the easiest solution that could be
used in production as well as test.

**Comment by MatkovIvan** [comment]
This part of the code is in a test application, not in SDK. So, this doesn't require to recompile library from source, just use similar parameters to initialize mobile client.
See [HttpClientHandler.Proxy documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.proxy?view=netframework-4.7.2#System_Net_Http_HttpClientHandler_Proxy) for details or use code above as example.

**Comment by MatkovIvan** [comment]
Yes

**Comment by gonzobrains** [comment]
Thank you.  Do you know of a way to simply pass in the proxy configured on
the currently active Wi-Fi access point?

**Comment by MatkovIvan** [comment]
Since you just need to "replace proxyUri with your Android device IP address", I guess ip address can be obtained as described [here](https://forums.xamarin.com/discussion/2260/get-current-ip-address) for example.

**Comment by gonzobrains** [comment]
Ivan,  that's not quite what I meant.  What I mean is that you can go into
your device's Wi-Fi settings and long-press on an access point to configure
advanced settings.  There you can specify a manual proxy.  The browser
always honors this but other apps do not.  I was wondering if there is a
programmatic way to obtain the manual proxy defined here.  Thanks again.

**Comment by MatkovIvan** [comment]
@gonzobrains Probably [this](https://stackoverflow.com/a/38475243) can help you. Also look at [an article](https://shellmonger.com/2016/06/23/using-modernhttpclient-with-azure-mobile-apps/) that describes how to use platform-specific network libraries.

**Comment by gonzobrains** [comment]
Do you use Fiddler when testing in this manner?  I'd like to intercept traffic from my Android device but when I set the proxy and port the way you describe I get certificate issues.

**Comment by jwallra** [comment]
Fiddler has a guide on how to set up capture from your android device [here](https://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForAndroid), hopefully that helps.

**Comment by gonzobrains** [comment]
I was following the guide but couldn't get it to work.  I think it's
actually failing on the auth part and not with requests through the Azure
client.  An added issue is that I don't think Android 7 accepts
certificates from Fiddler.

**Comment by jwallra** [comment]
@gonzobrains You usually have to install a trusted fiddler root cert on your device for your HTTPS traffic to show up.  There's a tutorial for how to do this on desktop [here](https://docs.telerik.com/platform/knowledge-base/how-to/how-to-trust-fiddler-root-certificate), but I wasn't able to find one for Android.  I have done this in the past to get around this problem, but realize that you install trusted root certs at your own risk.  

Unfortunately I've also just found out that the platform is [no longer supported](https://docs.telerik.com/platform/), so getting further support will be difficult.  You can use [PostMan](https://www.getpostman.com/) as an alternative to Fiddler.  They have a tutorial [here](https://www.getpostman.com/docs/v6/postman/sending_api_requests/capturing_http_requests) for capturing HTTP traffic.

**Comment by ElektrojungeMS** [comment]
In case you have a mac you can use [Charles Proxy](http://charlesproxy.com) for this. It works really well.

**Comment by gonzobrains** [comment]
I will look at your suggested solutions.  Thanks.
