### ISSUE TITLE
Crash generated in Microsoft.Azure.Mobile.Client.SQLiteStore

### ISSUE THREAD

**Issue by ivanicin** [Azure/azure-mobile-apps-net-client#439]
Here is the crash report from the App Center - it could be that it is some malformed data, but the exception should be raised much before in that case, so it is still a bug:

JToken.FromObjectInternal (System.Object o, Newtonsoft.Json.JsonSerializer jsonSerializer)
System.ArgumentNullException: Value cannot be null. Parameter name: o

JToken.FromObjectInternal (System.Object o, Newtonsoft.Json.JsonSerializer jsonSerializer)
JToken.FromObject (System.Object o, Newtonsoft.Json.JsonSerializer jsonSerializer)
MobileServiceSerializer.Serialize (System.Object instance)
MobileServiceSyncTable`1[T].DeleteAsync (T instance)
DataTable`1+<DeleteAsync>d__8[T].MoveNext ()
ExceptionDispatchInfo.Throw ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
TaskAwaiter.GetResult ()
VModel+<>c__DisplayClass542_0+<<DeleteComment>b__0>d.MoveNext ()
ExceptionDispatchInfo.Throw ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
CommentViewController+<DeleteButton_Clicked>d__7.MoveNext ()
ExceptionDispatchInfo.Throw ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
UIKitSynchronizationContext+<Post>c__AnonStorey0.<>m__0 ()
NSAsyncActionDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)

**Comment by MatkovIvan** [comment]
Hi @ivanicin,

Thanks for getting in touch!
It's caused by passing `null` into `DeleteAsync` method.
Thanks for pointing out the lack of validation here. I've added it in #440.

Best,
Ivan
