### ISSUE TITLE
Decimal DataTypes in SqlLite

### ISSUE THREAD

**Issue by rachael-ross** [Azure/azure-mobile-apps-net-client#441]
I'm using offline sync (and I have a table entity with a decimal type property. On the backend (.NET), SQL Server is set to allow 38 precision with 8 scale. If a value that exceeds 8 digits in scale is assigned and saved, SqlServer automatically truncates the value to 8 digits for scale... no exceptions thrown. Great....

However, when a value that exceeds 8 digits in scale gets saved to SqlLite on the mobile client side, I'm getting an error:  "The value 40.23452345234523452345234576 for member Value is outside the valid range for numeric columns.",  although it's a valid .NET decimal value.

We've thought about programmatically truncating to 8-digit scale before saving to SqlLite OR changing the affinity of that column data type. What are the ramfications/side effects of changing the affinity to type text and how do we go about doing so? I'm not seeing any documentation on how to specify affinity.

**Comment by myokeeh** [comment]
Just use TEXT. That's what I had to do. I can't find the source of that answer.

**Comment by rachael-ross** [comment]
@myokeeh Thanks for the input. However, I'm asking for an answer that's a bit more comprehensive. 

I'd like to know: What are the ramfications/side effects of changing the affinity to type text and how do we go about doing so?  Would you happen to know?

**Comment by myokeeh** [comment]
You'll have to change type to `string` both in your model on the client and azure app. I believe the offline SQLite database just stores those as TEXT.

I use Migrations to make changes to the backend/azure app. I think there are limitations that won't allow just changing the type/affinity in place. 

From my experience, I believe you'll have to rename the existing column to something else and adding a new migration (Add-Migration) and execute the changes (Update-Database).

Create a new column with the correct type in your model and do another Add-Migration, and Update-Database.

Of course, this also means you'll have to parse strings to decimals and vice versa in your client.

**Comment by bmourat** [comment]
Hey @rachael-ross 

Does @myokeeh comment answers your question? Should I close this issue?

Best,
Murat

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
