### ISSUE TITLE
Backend Failover Scenario with Azure Traffic Manager

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#445]
Hi
Recently I configured Azure Traffic Manager to a primary Mobile Backend (mobile) and a secondary Mobile Backend (mobile-failover)

In my Xamarin.Forms App I use a DelegationHandler and capture the response.
In case of a failover scenario I get a 403 which is ok.
It takes a few seconds until the traffic manager routes the request to the secondary mobile backend.
But still after minutes I still get in DelegationHandlers PostAsync and MobileServiceClient's LoginAsync a 403.
When I hit refresh in chrome browser on the traffic manager url the request is a 200 and the secondary is visible.

What am I doing wrong?

Can I recreate the whole MobileServiceClient instance to overcome maybe any caching issues?

Thanks
Eric
.

**Comment by MatkovIvan** [comment]
Hi @ericbrunner,

Thanks for getting in touch!
Since I unable to reproduce your entire environment, here are just suggestions to clarify the issue.
1. Use a debug proxy (such as fiddler) to ensure that requests are cached on the client or not.
2. Look at the server logs to find out why the error is returned.
3. Yes, you can recreate client. By the way, what happens on just restart the app?

Best,
Ivan

**Comment by ericbrunner** [comment]
Hi @MatkovIvan 

Thanks for getting back that quick. When I restart the app I get still the same. That experience leaded my to do it much simplier.

In the DelegatingHandler I just return on 503 or 403.

Because my app is Offline Sync enabled the pending changes remain in Localstore.

So the user is not disturbed in app usage.

With the next 5-10 minutes when the failover process is done the base.PostAsync will return a 401 because the JWT token is invalid. That's fine. Then I do a MobileSeviceClient.LoginAsync again on the traffic manager url which now routes the request to the secondary mobile backend. That backend issues a new valid token and the pending changes can be persisted in the backend.

Thanks again
Best
Eric
