### ISSUE TITLE
Unhandled Exception:  No 'id' member found on type 'ModelName'. occurred

### ISSUE THREAD

**Issue by hindertsi** [Azure/azure-mobile-apps-net-client#446]
Hello everyone!

I have developped a Xamarin mobile application with a shared class library and an android project (iOS part will be added later) using the Azure offline synchronization. After developping the application in "debug" mode and testing(everything works perfect) on a physical device (Android v7.0), I have now tried to run the application in "release" mode, which produces the following error just after running the application:
"Unhandled Exception:
System.InvalidOperationException: No 'id' member found on type 'ModelName'. occurred"
So I have checked multiple times if there is an ID or not and it is there (see code section below).

I found some similar issues on the internet, but they have already been resolved back in 2013 and the problem was only linked with the use of inheritence (which is not used in my small project). 

I use the following system:
- Windows 10 (x64)
- Visual Studio Enterprise 2017 (Version 4.7.03056)
- Xamarin (Version 4.10.10.2)

..the following targets:
- Android 7.0 (already tried different ones)
- .NET Standard 2.0 (can not downgrade because of other NuGets I have to use)

..and the following NuGets (same for class library and android project):
- Microsoft.Azure.Mobile.Client (v4.0.2)
- Microsoft.Azure.Mobile.Client.SQLiteStore (v4.0.2)
- Newtonsoft.Json (v11.0.2)
- Microsoft.Bcl (v1.1.10)
- Microsoft.Bcl.Build (v1.1.10)
- Microsoft.Net.Http (v1.1.10)
- SQLitePCLRaw.bundle_green (v1.1.11)
- SQLitePCLRaw.core (v1.1.11)
- SQLitePCLRaw.lib.e_sqlite3.android (v1.1.11)
- SQLitePCLRaw.provider.e_sqlite3.android (v1.1.11)

I have already tried do downgrade the NuGets to differnet versions but still getting the same error.

Here is the part of the code causing the error (see comment):
```csharp
IMobileServiceSyncTable<ModelName> modelNameTable;
MobileServiceClient client = new MobileServiceClient(Constants.SERVER_ADDR);
var store = new MobileServiceSQLiteStore(Constants.LOCAL_DB_FILENAME);
store.DefineTable<ModelName>(); // <---- this line is causing the error
client.SyncContext.InitializeAsync(store);
modelNameTable = client.GetSyncTable<ModelName>();
```

This is the class:
```csharp
public class ModelName
{
    [JsonProperty(PropertyName = "id")]
    public string Id { get; set; }

    [JsonProperty(PropertyName = "name")]
    public string Name { get; set; }

    [JsonProperty(PropertyName = "prename")]
    public string Prename { get; set; }
}
```

..and the stack trace:
```
System.InvalidOperationException: No 'id' member found on type 'ModelName'.

07-10 08:36:39.769 I/MonoDroid(22593): UNHANDLED EXCEPTION:
07-10 08:36:39.830 I/MonoDroid(22593): System.InvalidOperationException: No 'id' member found on type 'ModelName'.
07-10 08:36:39.830 I/MonoDroid(22593):   at Microsoft.WindowsAzure.MobileServices.MobileServiceContractResolver.DetermineIdProperty (System.Type type, System.Collections.Generic.IEnumerable`1[T] properties) [0x00089] in <8549de33fcfc43fdbf87d857d68bab4e>:0 
07-10 08:36:39.830 I/MonoDroid(22593):   at Microsoft.WindowsAzure.MobileServices.MobileServiceContractResolver.CreateProperties (System.Type type, Newtonsoft.Json.MemberSerialization memberSerialization) [0x00075] in <8549de33fcfc43fdbf87d857d68bab4e>:0 
07-10 08:36:39.830 I/MonoDroid(22593):   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract (System.Type objectType) [0x00035] in <de13b324ffcf4cbda8e49adb26333875>:0 
07-10 08:36:39.830 I/MonoDroid(22593):   at Microsoft.WindowsAzure.MobileServices.MobileServiceContractResolver.CreateObjectContract (System.Type type) [0x00000] in <8549de33fcfc43fdbf87d857d68bab4e>:0 
07-10 08:36:39.830 I/MonoDroid(22593):   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract (System.Type objectType) [0x000bf] in <de13b324ffcf4cbda8e49adb26333875>:0 
07-10 08:36:39.830 I/MonoDroid(22593):   at Microsoft.WindowsAzure.MobileServices.MobileServiceContractResolver.ResolveTableName (System.Type type) [0x000ea] in <8549de33fcfc43fdbf87d857d68bab4e>:0 
07-10 08:36:39.830 I/MonoDroid(22593):   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStoreExtensions.DefineTable[T] (Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore store, Microsoft.WindowsAzure.MobileServices.MobileServiceJsonSerializerSettings settings) [0x00006] in <f6f6ac1573ac49b4aa9ef131cbe51557>:0 
07-10 08:36:39.830 I/MonoDroid(22593):   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStoreExtensions.DefineTable[T] (Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore store) [0x00006] in <f6f6ac1573ac49b4aa9ef131cbe51557>:0 
07-10 08:36:39.830 I/MonoDroid(22593):   at BaseManager..ctor () [0x00026] in C:\Users\..\BaseManager.cs:30 
07-10 08:36:39.830 I/MonoDroid(22593):   at BaseManager.get_Instance () [0x00007] in C:\Users\..\BaseManager.cs:139 
07-10 08:36:39.830 I/MonoDroid(22593):   at SplashActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0002f] in C:\Users\..\SplashActivity.cs:33 
07-10 08:36:39.830 I/MonoDroid(22593):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <50c5e353fbab471e9ac01da68289d985>:0 
07-10 08:36:39.830 I/MonoDroid(22593):   at (wrapper dynamic-method) System.Object.1be58e08-8c7e-43c1-8801-7b0a1c0b8094(intptr,intptr,intptr)
07-10 08:36:39.855 W/art     (22593): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
An unhandled exception occured.
```

Thanks for every second of investigation!

**Comment by MatkovIvan** [comment]
Hi @hindertsi,

Thanks for getting in touch!
It looks like the default behavior of the linker optimization. This allows you to reduce the size of the application, but sometimes (often this related to serialization) it can cut off some of the right things.
Please check out [this article](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker) for details and ways to solve this issue.

Best,
Ivan

**Comment by hindertsi** [comment]
Thanks @MatkovIvan !

Your solution works perfectly! Just needed to add one line.

```csharp
[Preserve(AllMembers = true)] // <--- this line solves the problem
public class ModelName
{
    [JsonProperty(PropertyName = "id")]
    public string Id { get; set; }

    [JsonProperty(PropertyName = "name")]
    public string Name { get; set; }

    [JsonProperty(PropertyName = "prename")]
    public string Prename { get; set; }
}
```

Thank you! After hours of debugging I can finally continue developping.

Best,
Hindertsi
