### ISSUE TITLE
Query sync information

### ISSUE THREAD

**Issue by LarsNymand** [Azure/azure-mobile-apps-net-client#450]
Is it possible to get sync information based on queryid or something similar.

The reason why I am looking for is, to be able to use local storage as cache, where I can purge data not being used for a period of time.

If I could get last_pull_time for a specific queryid, then I could purge the data if expired.

I know I could probably handle it myself and store the information somewhere else. But the data needed - I believe (updatedAt?) - is already stored and we just need an easy way see/query the sync information.

Can this be done? I haven't found a solution anywhere.
or could it be a feature request?

**Comment by MatkovIvan** [comment]
Hi @LarsNymand,

Thanks for getting in touch!
There is no public API for that. The SDK uses regular tables in SQLite storage for storing this, so you can read any data you want from there.

PS Please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features.

Best,
Ivan

**Comment by LarsNymand** [comment]
Hi @MatkovIvan thank you for your quick reply.

I will have a look at how to read the data directly.

Thank you
