### ISSUE TITLE
Apply Dependency Injection With MobileServiceClient class  

### ISSUE THREAD

**Issue by minaairsupport** [Azure/azure-mobile-apps-net-client#451]
I am trying to apply DI in this sample project with Autofac but I am cant as it have depend on AuthHandler that has depend on IAzureClient  could you help me 

```
public class AuthHandler : DelegatingHandler , IAuthHandler
    {

        readonly IAzureClient AzureClient;
        readonly IAuthentication Authentication;
        IMobileServiceClient Client;
        static readonly SemaphoreSlim semaphore = new SemaphoreSlim(1);
        static bool isReauthenticating = false;

        public AuthHandler(IAzureClient azureClient , IAuthentication authentication)
        {
            AzureClient = azureClient;
            Authentication = authentication;
            Client = AzureClient.Client;
        }
}


public class AzureClient : IAzureClient
    {
        const string DefaultMobileServiceUrl = "https://mydriving.azurewebsites.net";
        static IMobileServiceClient client;

        public IMobileServiceClient Client => client ?? (client = CreateClient());

        IMobileServiceClient CreateClient()
        {
            client = new MobileServiceClient(DefaultMobileServiceUrl, new AuthHandler())
            {
                SerializerSettings = new MobileServiceJsonSerializerSettings()
                {
                    ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore,
                    CamelCasePropertyNames = true
                }
            };
            return client;
        }
}
```

https://github.com/Azure-Samples/MyDriving/blob/master/src/MobileApps/MyDriving/MyDriving.AzureClient/AzureClient.cs

**Comment by bmourat** [comment]
Hi @minaairsupport !

Could you please clarify what is that you do not understand? If you need an instance of `IAzureClient` you need to instantiate `AzureClient` class, as it has default constructor, this won't be a problem. Also i don't see any constructor in AuthHandler class, did you added it?

Best
Murat

**Comment by InquisitorJax** [comment]
Hi @minaairsupport - try resolving the IAzureClient at runtime in the SendAsync method instead of as a constructor argument?
Then you shouldn't run into the chicken and egg problem.

**Comment by minaairsupport** [comment]
MobileServiceClient  don't have an empty constructor at least  it should have a URL, and in this sample, it passes many params like an instance of AuthHandler, that class inherit from DelegatingHandler plus some MobileServiceJsonSerializerSettings this violates DI , its not easy to create instance from MobileServiceClient

**Comment by InquisitorJax** [comment]
@minaairsupport for the mobile service client and autofac - use the instance registration:
Here's how mine looks like:

```
var mobileService = new MobileServiceClient(baseUrl, new AuthHttpMessageHandler(), new InjectNetworkMessageParametersHandler(), nativeMessageHandler);

builder.RegisterInstance<IMobileServiceClient>(mobileService);

```

**Comment by bmourat** [comment]
@minaairsupport does previous @InquisitorJax  comment answers your question?

**Comment by minafaw** [comment]
yea its ok with me you can close the issue I think
