### ISSUE TITLE
UWP MobileServiceClient.InvokeAsync exception "Instance already started"

### ISSUE THREAD

**Issue by InquisitorJax** [Azure/azure-mobile-apps-net-client#453]
UWP project: Whenever an attempt to call InvokeAsync() method, exception is thrown

Exception thrown: 'System.InvalidOperationException' in System.Net.Http.dll
This instance has already started one or more requests. Properties can only be modified before sending the first request.

The MobileServiceClient is registered as a single instance, but whenever I call InvokeApiAsync(), I get this message.

Android project works fine.

Any ideas?

**Comment by dhei** [comment]
Hi @InquisitorJax,

Thanks for getting in touch. 
Looks like an issue with how you're calling HttpClient. Can you share the code how you are calling `MobileServiceClient` and `InvokeApiAsync`?

Thanks.

**Comment by InquisitorJax** [comment]
@dhei - the MobileServiceClient is registered as a singleton with Autofac.
Pretty much any InvokeApiAsync causes the above failure.
Sample calls:

`return await _mobileService.InvokeApiAsync<T>(context.AlternateOnlineServiceRoute, HttpMethod.Get, null).ConfigureAwait(false);`

`HttpResponseMessage response = await _mobileService.InvokeApiAsync("auth/token", content,HttpMethod.Post, null, null);`

pretty standard stuff - and works just fine in Android.

**Comment by InquisitorJax** [comment]
Found the issue.
I was using the NativeMessageHandler, and when debugging locally, would set the property:

`nativeMessageHandler.EnableUntrustedCertificates = true;`

to get around SLL to localhost.
Guess I should just not include the handler when in debug mode :|

.... now I just need to log an issue for that massive Android memory leak when executing sync, so murphy will help me find the solution :P
