### ISSUE TITLE
Memory leak when executing offline sync - Xamarin.Android

### ISSUE THREAD

**Issue by InquisitorJax** [Azure/azure-mobile-apps-net-client#454]
There seems to be quite a memory leak when executing offline sync on Android.
Running the same sync on UWP works just fine, but Android increments 200 - 300 Meg every time a sync is executed.

I have a sample source project for anyone that can help out.

Thanks in advance.

**Comment by MatkovIvan** [comment]
Hi @InquisitorJax,

Thanks for getting in touch!
I didn't see so large allocations during my tests, so sharing the sample project would be awesome.

Duplicate of #423

Best,
Ivan

**Comment by InquisitorJax** [comment]
Hi Ivan - thanks for reaching out.
The sample project has credentials in it I'd rather not share on the public web. Do you have an email that you can send, so I can add you to the cloud share of the project?
You can send it to inquisitorjax (at) gmail

**Comment by MatkovIvan** [comment]
I see that total memory usage increases only by 15-20MB and comes down after garbage collection.
Are there any specific steps to reproduce it (I used Xamarin Profiler to test)?

PS Frankly, there is no platform-dependent code in that part of SDK

**Comment by InquisitorJax** [comment]
Interesting... memory allocation isn't nearly as bad as it was a week or 2 ago :|

Jeesh - I honestly don't know what's changed. Sync was taking well over a minute, and now it's about half that, although still slower than Windows)

Thanks for taking the time Ivan - I think I'll close this until I can more accurately reproduce what I was seeing :(
