### ISSUE TITLE
401 Error on LoginAsync with microsoft account on mobile with MSAL

### ISSUE THREAD

**Issue by mojobec** [Azure/azure-mobile-apps-net-client#455]
I have configured my app service to use a Microsoft account for authentication,
it works great on the web but on mobile, I'm getting a 401 error when calling `MobileServiceClient.LoginAsync` or `MobileServiceClient.LoginWithMicrosoftAccountAsync` with an access token from MSAL
(the app is configured to use a Native Application in https://apps.dev.microsoft.com)

the code we tried to use:
```csharp
var pca = new PublicClientApplication("Id");             
var result = await pca.AcquireTokenAsync(new []{"User.Read"}); //tried wl.login
var payload = new JObject();
payload["access_token"] = result.AccessToken; //tried payload["authenticationToken"]
var user = await mobileServiceClient.LoginAsync(MobileServiceAuthenticationProvider.MicrosoftAccount, payload);
//or this same result
var user = await mobileServiceClient.LoginWithMicrosoftAccountAsync(result.AccessToken);
```

**Comment by clpolet** [comment]
Hi @mojobec. Thanks for reaching out. The client authentication flow only supports MSA using Live SDK. There is currently no plan on supporting MSA using the MSAL SDK.

**Comment by myokeeh** [comment]
@clpolet So there's no way to have a converged app in Application Registration Portal to support apps using Azure Apps with MSA auth? I'm currently in a situation that my app is down because I can't recreate the right entry in Application Registration Portal tied to my UWP app in Dev Center. It's been 2 weeks+ without resolution from support.

Also, does this ultimately mean that any effort from the MSAL.NET team will not work because Azure Apps only use Live SDK?

Why does all this seem so incompatible?

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/599

**Comment by brunokc** [comment]
The Live SDK does not seem to support Xamarin. 

```
Error	NU1202	Package LiveSDK 5.6.3 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win. Package LiveSDK 5.6.3 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - win8 (Windows,Version=v8.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - wp81 (WindowsPhone,Version=v8.1)
```

I'm not sure what is being suggested going forward as the solution for MSA authentication (Live SDK vs. MSAL), but as of right now there is a gap in coverage where it's hard to use MSA authentication with Azure Mobile Apps and client flow authentication on Xamarin apps. Facebook authentication and Google authentication on the other hand are super easy.

**Comment by jwallra** [comment]
As @clpolet and @ElektrojungeMS have already stated, we don't have plans to support the MSAL library.  Sorry for the inconvenience.

**Comment by myokeeh** [comment]
@jwallra, thanks for fielding these questions. Does this mean MSA login for Azure App Services will eventually stop working then? If Live SDK is being phased out. We can't jump onto MSAL to keep our apps working?

**Comment by jwallra** [comment]
@myokeeh Unfortunately, yes.  Unless our plans for investment into this SDK change we aren't planning to fix our MSA story.  Sorry to be the bearer of bad news.

**Comment by brunokc** [comment]
FWIW, I looked into this a bit more and it seems that the part that's not working with MSAL belongs to the server SDK, not the client (for client directed auth, the client is just sending the token to the server). The token returned by MSAL seems to use the RS256 algorithm (rsa-sha256) (Facebook and Google seem to use HS256 -- hmac-sha256) and the server does not seem to handle it well. 

Not that it matters if MSA is not going to be supported going forward...

**Comment by FlxGen** [comment]
> 
> 
> @myokeeh Unfortunately, yes. Unless our plans for investment into this SDK change we aren't planning to fix our MSA story. Sorry to be the bearer of bad news.

Given the recent updates, has this position changed?
