### ISSUE TITLE
Managed client should add token query string parameter to login request

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-mobile-apps-net-client#46]
?session_mode=token

**Comment by adrianhall** [comment]
@mattchenderson - which query string are we talking here?  I understand it's the "auth" one, but a specific URI?

**Comment by elamalani** [comment]
Please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK.

Hope this helps.
