### ISSUE TITLE
SyncTable.PullAsync is sending requests to the wrong URI

### ISSUE THREAD

**Issue by xhanix** [Azure/azure-mobile-apps-net-client#460]
I have a IMobileServiceSyncTable called "TasksTable".  I'm calling PullAsync like so:

await TasksTable.PullAsync("allTasks", tasksTable.CreateQuery());

I am logging the http requests and responses from the DelegatingHandler's SendAsync method. I see two requests being sent when calling the above PullAsync. The uri for these two requests are:

1.  https://XXXX.azurewebsites.net/tables/Tasks?$filter=...
2. http://XXXX.azurewebsites.net/?%24filter=

The second request is causing problems as it is not to the correct table's uri and is not returning anything meaningful.

(I'm running a Node.js app for handling the requests and the route "/?%24filter=" will render the home page html)

**Comment by MatkovIvan** [comment]
Hi @xhanix,

Thanks for getting in touch!
On which platform are you seeing the issue?
Currently, I'm unable to reproduce the issue. Could you please provide full reproduction steps or minimal reproduction sample?

Best,
Ivan

**Comment by xhanix** [comment]
Hi Ivan

Thanks for looking into this. I'm testing on iOS (both device and emulator). The issue occurs specifically under these two conditions (both conditions must be met):

Condition 1- Number of rows in the azure sql table must be around 80 or more. I understand that several calls must be made until all records are pulled but some of these calls are to the wrong "http" uri as described in my original post.



And condition 2- The "first-time" PullAsync is causing the problem. Subsequent PullAsync calls are all okay. To reproduce I have to delete the app and re-run.

Let me know if you're unable to reproduce and I will send you a minimal test project.

<img width="519" alt="screen shot 2018-09-07 at 8 03 39 am" src="https://user-images.githubusercontent.com/5132536/45218333-44ccf280-b275-11e8-9bc9-c987262a830f.png">

**Comment by MatkovIvan** [comment]
Thanks for details.
Still can't reproduce, but currently I have a few thoughts.
The main version is the invalid url was sent by a server as [NextLink](https://github.com/Azure/azure-mobile-apps-net-client/blob/f3acf8ae87cb585203d9ffaf30f19f257cdeb0fb/src/Microsoft.Azure.Mobile.Client/Table/Query/QueryResult.cs#L48-L51). Could you please check this by logging headers too?

**Comment by xhanix** [comment]
Yes, here's the response header with the link (not all responses have this link in the header):

Cache-Control: no-cache
Pragma: no-cache
ETag: W/"7780-f4DqhP1BmXbspaIMNYBbusUompA"
Vary: Accept-Encoding
Server: Microsoft-IIS/10.0
X-Powered-By: Express, ASP.NET
Link: http://xxxx.azurewebsites.net/?%24filter=(updatedAt%20ge%20datetimeoffset'1970-01-01T00%3A00%3A00.0000000%2B00%3A00')&%24orderby=updatedAt&%24skip=50&%24top=50&__includeDeleted=true; rel=next
Date: Fri, 07 Sep 2018 13:33:26 GMT

**Comment by xhanix** [comment]
Thanks for the help Ivan. There is a [pull request](https://github.com/Azure/azure-mobile-apps-node/pull/551) to fix the server SDK. Closing as this is not related to the client SDK.
