### ISSUE TITLE
Not able to execute the sqllite join query on sqlite store.

### ISSUE THREAD

**Issue by rajeshangappan** [Azure/azure-mobile-apps-net-client#461]
Hi , I am trying to read the data from more then one table using join. but i can't.

Please return the value of "ExecuteNonQueryInternal" result.

For insert and update u can track by synctable.. but read should be from more than one table?

Thanks,
Rajesh.A

**Comment by guperrot** [comment]
Hi, unfortunately our SDK does not support this operation.

**Comment by jwallra** [comment]
You can see the operations we support in our documentation [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.mobileservices.sync.imobileservicesynctable-1?redirectedfrom=MSDN&view=azure-dotnet).
