### ISSUE TITLE
[Question/Doubt] Handling Server Error using custom IMobileServiceSyncHandler - Xamarin Forms

### ISSUE THREAD

**Issue by stezma** [Azure/azure-mobile-apps-net-client#463]
I have implemented the Azure - Offline Sync based on the documentation / Sample provided by Microsoft [https://github.com/Azure/azure-mobile-apps-quickstarts/blob/master/client/xamarin.forms/ZUMOAPPNAME/TodoItemManager.cs](sample) in my Xamarin Forms Application.

In the sample / documentation provided, they are using the default Service Handler.

**// Simple error/conflict handling. A real application would handle the various errors like network conditions,server conflicts and others via the IMobileServiceSyncHandler.**

Since I need to implement a **retry logic for 3 times** **if the Pull / Push fails**. As per the documentation I have created a custom Service Handler(IMobileServiceSyncHandler).

Please find my code logic here.

```
public class CustomSyncHandler : IMobileServiceSyncHandler
{
    public async Task<JObject> ExecuteTableOperationAsync(IMobileServiceTableOperation operation)
    {
        MobileServiceInvalidOperationException error = null;
        Func<Task<JObject>> tryExecuteAsync = operation.ExecuteAsync;

        int retryCount = 3;
        for (int i = 0; i < retryCount; i++)
        {
            try
            {
                error = null;
                var result = await tryExecuteAsync();
                return result;
            }
            catch (MobileServiceConflictException e)
            {
                error = e;
            }
            catch (MobileServicePreconditionFailedException e)
            {
                error = e;
            }
            catch (MobileServiceInvalidOperationException e)
            {
                error = e;
            }
            catch (Exception e)
            {
                throw e;
            }

            if (error != null)
            {
                if(retryCount <=3) continue;
                else
                {
                     //Need to implement
                     //Update failed, reverting to server's copy.
                }
            }
        }
        return null;
    }

    public Task OnPushCompleteAsync(MobileServicePushCompletionResult result)
    {
        return Task.FromResult(0);
    }
}
```

But I am not sure how to handle / revert **server copy in case all the 3 retry failed.**

In the TODO sample they where **reverting** it based on the **MobileServicePushFailedException**. But which is available when we implement **IMobileServiceSyncHandler**. More over if we include custom IMobileServiceSyncHandler it wont execute the code after **PushAsync / PullAsync**. Even the try catch wont fire in case any exception.

```
try
        {
            await this.client.SyncContext.PushAsync();

            await this.todoTable.PullAsync(
                //The first parameter is a query name that is used internally by the client SDK to implement incremental sync.
                //Use a different query name for each unique query in your program
                "allTodoItems",
                this.todoTable.CreateQuery());
        }
        catch (MobileServicePushFailedException exc)
        {
            if (exc.PushResult != null)
            {
                syncErrors = exc.PushResult.Errors;
            }
        }

        // Simple error/conflict handling. A real application would handle the various errors like network conditions,
        // server conflicts and others via the IMobileServiceSyncHandler.
        if (syncErrors != null)
        {
            foreach (var error in syncErrors)
            {
                if (error.OperationKind == MobileServiceTableOperationKind.Update && error.Result != null)
                {
                    //Update failed, reverting to server's copy.
                    await error.CancelAndUpdateItemAsync(error.Result);
                }
                else
                {
                    // Discard local change.
                    await error.CancelAndDiscardItemAsync();
                }

                Debug.WriteLine(@"Error executing sync operation. Item: {0} ({1}). Operation discarded.", error.TableName, error.Item["id"]);
            }
        }
    }
```

**Note**

In my application I am only trying to achieve retry for 3 time in case any server error. I am not looking for to resolve conflicts. Thant is the reason I haven't added the code for the same.

If someone came across similar issues and resolved it please help.

Stez.

**Comment by bmourat** [comment]
Hi @stezma !

If I understand you right, you can access push context results, including errors in `OnPushCompleteAsync` callback. `MobileServicePushCompletionResult` has `Errors` property, so you can revert to server's copy. If you want to wait for 3 retries you can just sync through your `CustomSyncHandler` instance variables.

Best,
Murat

**Comment by stezma** [comment]
Sorry .. I didn't get the second point, you mentioned about the retry. What does it mean "**If you want to wait for 3 retries you can just sync through your CustomSyncHandler instance variables.**" could you please elaborate the point?

What change I need to make in my **CustomSyncHandler**  to make it work.?

**Comment by bmourat** [comment]
@stezma 
After reading [this article](https://www.nalashaa.com/windows-azure-mobile-services-offline-sync-alpha/), I think that is not a good solution, cause potentially `ExecuteTableOperationAsync` can be called concurrently for each row. But you can find how to revert to server copy in that article. Hope this helps!

**Comment by bmourat** [comment]
Hi @stezma 
Did you manage to implement the `retry` logic?

**Comment by bmourat** [comment]
Closing this issue, if you'll have any questions please feel free to reopen it.
