### ISSUE TITLE
The IPrincipal's Claims must contain an 'iss' Claim.

### ISSUE THREAD

**Issue by myokeeh** [Azure/azure-mobile-apps-net-client#464]
I have an Azure app service that at some point started failing on the code below. After looking at logs, it seems to fail with `Operation=ReflectedHttpActionDescriptor.ExecuteAsync, Exception=System.ArgumentOutOfRangeException: The IPrincipal's Claims must contain an 'iss' Claim.
` I'm unsure what has changed or why it started failing. How do I resolve this?

    [MobileAppController, Authorize]
    public class UserInfoController : ApiController
    {
        [HttpGet, Route("api/GetUserInfo")]
        public async Task<JToken> Get()
        {
            // fails on this next line
            var msCreds = await User.GetAppServiceIdentityAsync<MicrosoftAccountCredentials>(Request);             var result = new JObject();
            var accessToken = msCreds.AccessToken;
            return await GetProviderInfo("https://apis.live.net/v5.0/me/?method=GET&access_token=" + accessToken);
        }

        async Task<JToken> GetProviderInfo(string url)
        {
            var c = new HttpClient();
            var resp = await c.GetAsync(url);
            resp.EnsureSuccessStatusCode();
            return JToken.Parse(await resp.Content.ReadAsStringAsync());
        }
    }

**Comment by myokeeh** [comment]
@jwallra, I've double checked config on the Azure app and Application Registration portal--all correct. 

By the way, this is happening on an Azure app I setup for my personal use, and another one for work setup on a different Azure account. I really only noticed something wasn't right about 2-34 weeks ago. Not until now did I dig into it to find out that's where it's failing.

**Comment by dhei** [comment]
Hi @myokeeh, 
This appears to be an issue on the server side of Azure Mobile Apps. This repo is used to track bugs in .NET client SDK of Azure Mobile Apps. I recommend open a support ticket from Azure portal for this type of issue. Thank you.

**Comment by iamkaranvalecha** [comment]
@myokeeh Was this issue resolved after creating support ticket?

**Comment by adrianhall** [comment]
another ref - a couple of weeks ago, Azure App Service visually changed the Authentication section.  As part of that update, the "Microsoft Account" authentication mechanism was replaced with Azure Active Directory.  I suspect (but have nothing other than a suspicion) that the change is done at that level.

Since it's in App Service, there is little we can do here.  I'll take a look to see if there is a an easy code fix, but we are not developing this codebase any longer (since we are concentrating effort on the .NET Core edition).

**Comment by myokeeh** [comment]
> @myokeeh Was this issue resolved after creating support ticket?

@iamkaranvalecha I don't recall. Sorry. I also switched from MSA to AAD authentication, so this became irrelevant.

**Comment by iamkaranvalecha** [comment]
> another ref - a couple of weeks ago, Azure App Service visually changed the Authentication section. As part of that update, the "Microsoft Account" authentication mechanism was replaced with Azure Active Directory. I suspect (but have nothing other than a suspicion) that the change is done at that level.
> 
> Since it's in App Service, there is little we can do here. I'll take a look to see if there is a an easy code fix, but we are not developing this codebase any longer (since we are concentrating effort on the .NET Core edition).

Well, I did saw an upgrade button in the Authentication /Authorziation section in app service & our client has different environments where authentication is working fine but at pre prod & prod environment we are facing different issues related to Auth. I would like to share logs & will need help to resolved this as soon as I can.

Please let me know if anyone can help!

**Comment by iamkaranvalecha** [comment]
> > @myokeeh Was this issue resolved after creating support ticket?
> 
> @iamkaranvalecha I don't recall. Sorry. I also switched from MSA to AAD authentication, so this became irrelevant.

Will you be able to help? It's for a client & we desperately need it to resolve

I can share logs & will need help to resolve this as soon as we can.

Please let me know if you can help!

**Comment by adrianhall** [comment]
@iamkaranvalecha - this is a bug from 2018 and references MSA authentication, which is no longer supported by Azure App Service.  Azure App Service has switched over to using AAD authentication for supporting MSA accounts (i.e. outlook.com accounts).  

Since Azure App Service is no longer supporting MSA authentication, you need to update the Azure App Service side of things as well as the client.
