### ISSUE TITLE
PullAsync() WithParameters() generates incorrect URI

### ISSUE THREAD

**Issue by il-frans** [Azure/azure-mobile-apps-net-client#465]
In my scenario, I try to pull data which is only for the day. Say I have a field which store the expected arival time of an item , I would have an odata query as ($filter=ScheduledTimeOfArrival ge <yesterday midnight> and ScheduledTimeOfArrival lt <today midnight>)

I use the following parameter (query) to the PullAsync() (Hard coded values for simplicity)

.WithParameters(new Dictionary<string, string>
                {
                    {
                        "filter",
                        "scheduledTimeOfArrival gt DateTimeOffset'2018-07-01T00:00:00Z' and scheduledTimeOfArrival lt DateTimeOffset'2018-07-02T00:00:00Z'"
                    }
                });

Tracking the request being sent the generated request URI is the following. 

http://localhost/tables/ScheduleDetails?$filter=(updatedAt%20ge%20datetimeoffset'1970-01-01T00%3A00%3A00.0000000%2B00%3A00')&$orderby=updatedAt&$skip=0&$top=50&filter=scheduledTimeOfArrival%2520gt%2520DateTimeOffset%272018-07-01T00%3A00%3A00Z%27%2520and%2520scheduledTimeOfArrival%2520lt%2520DateTimeOffset%272018-07-02T00%3A00%3A00Z%27&__includeDeleted=true

Using postman, if I remove the first $filter part, the query works fine, which makes me suspect that the second $filter get's ignored by the WebApi since $filter is defined twice. 

I suspect that if a filter is passed as .WithParameters() it should be added to the first filter rather then a separate one

**Comment by bmourat** [comment]
Hi @il-frans,

Why are you trying to pass the filtering condition in `WithParameters` method, and not as a parameter to `PullAsync`?

Murat

**Comment by il-frans** [comment]
Hi Murat

Actually there is no particular reason, after reading your reply I tried to apply the `.Where` on the passed in query instead the `.WithParameters`. The generates the correct URI with just one $filter section. 

Although my issue is solved, the title of this issue is still valid. If passing $filter withParameters is not supported, I would suggest throwing an exception to the user, in the same way when a parameter name is passed by the user with a '$' in front. The user is told that names should not contain the '$'. Or else if a filter is passed, it should generate a working URI

**Comment by bmourat** [comment]
I agree that this may be very confusing, but judging from the [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.mobileservices.imobileservicetablequery-1.withparameters?view=azure-dotnet) `WithParameters` method was added to allow passing additional user-defined parameters to the query. Its behaviour is not to merge new parameters with existing ones, but to pass them along with the query as they are.
