### ISSUE TITLE
CurrentPlatform.Init() or . anything works when using the Microsoft.Azure.Mobile.Client this if for UWP App is inaccessable due to it's protection level

### ISSUE THREAD

**Issue by xtianus79** [Azure/azure-mobile-apps-net-client#469]
When using the package I get 
this error when tyring use CurrentPlatform.Init(); in the MainPage.Xaml.cs in the UWP project I get the following error. 

xxxxx is inaccessable due to it's protection level. 

this is for either version of the package 3.1.0 or the latest 4.+ version

**Comment by xtianus79** [comment]
this is the dll and it doesnt' even have init in it. 

`#region Assembly Microsoft.WindowsAzure.Mobile.Ext, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// C:\Users\choles\.nuget\packages\microsoft.azure.mobile.client\3.1.0\lib\netcore45\Microsoft.WindowsAzure.Mobile.Ext.dll
#endregion

namespace Microsoft.WindowsAzure.MobileServices
{
    internal class CurrentPlatform : IPlatform
    {
        public CurrentPlatform();

        //
        // Summary:
        //     Returns a platform-specific implemention of application storage.
        public IApplicationStorage ApplicationStorage { get; }
        //
        // Summary:
        //     Returns a platform-specific implemention of platform information.
        public IPlatformInformation PlatformInformation { get; }
        //
        // Summary:
        //     Returns a platform-specific implementation of a utility class that provides functionality
        //     for manipulating System.Linq.Expressions.Expression instances.
        public IExpressionUtility ExpressionUtility { get; }
        //
        // Summary:
        //     Returns a platform-specific implementation of a utility class that provides functionality
        //     for platform-specifc push capabilities.
        public IPushUtility PushUtility { get; }
        //
        // Summary:
        //     Returns a platform-specific path for storing offline databases that are not fully-qualified.
        public string DefaultDatabasePath { get; }

        //
        // Summary:
        //     Ensures that a file exists, creating it if necessary
        //
        // Parameters:
        //   path:
        //     The fully-qualified pathname to check
        public void EnsureFileExists(string path);
        //
        // Summary:
        //     Retrieves an ApplicationStorage where all items stored are segmented from other
        //     stored items
        //
        // Parameters:
        //   name:
        //     The name of the segemented area in application storage
        //
        // Returns:
        //     The specific instance of that segment
        public IApplicationStorage GetNamedApplicationStorage(string name);
    }
}`

**Comment by guperrot** [comment]
As per the quickstart of Xamarin.Forms and Windows you don't need to call CurrentPlatform.Init from a UWP application, this is an instruction specific to Xamarin.Android and Xamarin.iOS application files.

**Comment by xtianus79** [comment]
@guperrot ahhhhh that would make more sense. lol. I will say this... All of these instructions putting IOS and Android first and leaving UWP behind.  Nobody cares about Android except for phones.  For tablets it's all about Windows and IOS.  Trust me this is how the enterprise is going.  It's either Ios ipads or windows devices.
