### ISSUE TITLE
Xamarin.iOS ResumeWithUrl doesn't seem to finalizes the auth process

### ISSUE THREAD

**Issue by aventurella** [Azure/azure-mobile-apps-net-client#470]
The modal window just stays open and the `await` is never returned to from `LoginAsync`.

**Visual Representation of the Issue**
>You can see it's hitting all the right things. The url that's being redirected has the code that comes with it. It just stops with `ResumeWithUrl`. The modal is never dismissed and the await never continues.  The ViewController is never unloaded as well.  I have this set to trigger on `ViewDidAppear` for demo purposes.

![issue](https://user-images.githubusercontent.com/75315/47621295-f4bf1f00-dab2-11e8-9079-8bbab9bb3a06.gif)

My Setup:

**AppDelegate**

> This is successfully invoked when the `AuthService` below calls `LoginAsync` and the user successfully provides their credentials. I can see the auth code when I set the breakpoint here.
```
[Export("application:openURL:options:")]
public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
{
    // authService is a Singleton that
    // that hosts the MobileClient
    // This call just forwards the url to the 
    // `MobileClient.ResumeWithUrl`
    if (url.Scheme == "myapporders")
        authService.ResumeWithUrl(url);
}
```

**AuthService**
> This successfully displays the modal, and does the login and the redirect is returned to the  AppDelegate's `OpenUrl` defined above.

```
public void ResumeWithUrl(NSUrl url)
{
    var result = _client.ResumeWithURL(url);
}

public Task LoginAsync(UIViewController viewController)
{
    try
    {
        // Never returns from this await.
        var user = await _client.LoginAsync(
            viewController: viewController,
            provider: MobileServiceAuthenticationProvider.Google,
            uriScheme: "myapporders",
            parameters: new Dictionary<string, string>
            {
                ["access_type"] = "offline",
                ["post_login_redirect_uri"] = "myapporders://auth.callback.azure"
            });
    }
    catch(Exception e)
    {
        // log the exception for now
    }
}
```

**Comment by bmourat** [comment]
Hi @aventurella 

Why do you need `post_login_redirect_uri` parameter? To setup auth, you need to add your app url `myapporders://easyauth.callback` to Allowed External Redirect URLs like described [here](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-ios-get-started-users#add-your-app-to-the-allowed-external-redirect-urls). Then you just pass your scheme `myapporders` to `LoginAsync` method and handle `OpenUrl` method in `AppDelegate`

**Comment by aventurella** [comment]
Well, I'll be.. I didn't think it LITERALLY had to be <developer_scheme>://**easyauth.callback** but sure enough it DOES literally need to be **easyauth.callback** hahaha.

Thank you!
