### ISSUE TITLE
PullAsync throw TaskCancellationException

### ISSUE THREAD

**Issue by apy534** [Azure/azure-mobile-apps-net-client#471]
The table contains varbinary data for images.
Each record is having 2 images. The size of each image is between 1 and 2 MB.
If the table contains more than one record, the PullAsync throws TaskCancellationException.
Please help me out with the solution.

**Comment by MatkovIvan** [comment]
Hi @apy534,

Thanks for getting in touch!
`TaskCancellationException` means a timeout error here. I suggest you consider moving out storing images from a database to a blob storage with a URL to that blob being stored in your table.

Best,
Ivan

**Comment by apy534** [comment]
Hello @MatkovIvan,
Thanks for the response.
I've got a doubt. If the records are above 1000 the PullAsync works fine even its time taken for pulling is 8 mins. But for image its throwing error in just 1 minute.
Please help me to understand this.
Thanks in advance

**Comment by apy534** [comment]
Thank you @MatkovIvan
