### ISSUE TITLE
How to limit records retrieved by PullAsync() by date.

### ISSUE THREAD

**Issue by gonzobrains** [Azure/azure-mobile-apps-net-client#472]
@MatkovIvan  

I would like my app to only pull down data created within the last 30 days.  I have been trying to do the following:

```
const double DAYS_AGO = -30;

await myTable.PullAsync("myTable", myTable.CreateQuery().Where(x => x.CreatedAt > (DateTime.Today.AddDays(DAYS_AGO))));
```

However, my HTTP requests failed with the following:

message=The query specified in the URI is not valid. A binary operator with incompatible types was detected. Found operand types 'Edm.DateTimeOffset' and 'Edm.DateTime' for operator kind 'GreaterThan'.

I think this is because CreatedAt is defined in the client app as follows:

```
        [JsonProperty(PropertyName = "CreatedAt")]
		public DateTime CreatedAt { get; set; }
```

Whereas the SQL server table has it defined as datetimeoffset(7).  First off, should these fields not even be defined in the client code?  I notice they are not defined in our service, so perhaps I should remove them from the client side?  If I do that, doesn't that mean I no longer should manually update them before adding/updating the local store?  Are they only designed for use by the Azure client/server libraries?  Your "to-do" quickstart doesn't have them defined so I'm starting to think I should remove them.

Next, if I remove them how can I perform the query which limits by CreatedAt date if I no longer have it defined in my client-side model?

Thanks,
Jeff

**Comment by MatkovIvan** [comment]
Hi @gonzobrains,

> `[JsonProperty(PropertyName = "CreatedAt")]`

BTW, you can use `[CreatedAt]`

> First off, should these fields not even be defined in the client code? I notice they are not defined in our service, so perhaps I should remove them from the client side? If I do that, doesn't that mean I no longer should manually update them before adding/updating the local store? Are they only designed for use by the Azure client/server libraries?

You can not define system properties directly, if you don't have to work with it directly. In your case they needed for queries at least.

> `await myTable.PullAsync("myTable", myTable.CreateQuery().Where(x => x.CreatedAt > (DateTime.Today.AddDays(DAYS_AGO))));`

This works on my sample. As well as if I use `DateTimeOffset` on client app. Obviously, this issue depends on some server specific implementation. Try to use `DateTimeOffset` instead `DateTime` to avoid type diff:
``` C#
[CreatedAt]
public DateTimeOffset CreatedAt { get; set; }
```
```C#
DateTimeOffset offset = DateTime.Today.AddDays(DAYS_AGO);
await myTable.PullAsync("myTable", table.CreateQuery().Where(x => x.CreatedAt > offset));
```

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
