### ISSUE TITLE
Calling PullAsync() on three separate tables without await doesn't make all three pulls happen simultaneously.

### ISSUE THREAD

**Issue by gonzobrains** [Azure/azure-mobile-apps-net-client#473]
I am trying to call PullAsync() on three independent tables without awaits in hopes of getting all three tables to be processed concurrently:

```
_ = firstTable.PullAsync("firstTable" + Guid.NewGuid().ToString("N"), firstTable.CreateQuery(), new PullOptions { MaxPageSize = 200 });

_ = secondTable.PullAsync("secondTable" + Guid.NewGuid().ToString("N"), secondTable.CreateQuery(), new PullOptions { MaxPageSize = 200 });

_ = thirdTable.PullAsync("thirdTable" + Guid.NewGuid().ToString("N"), thirdTable.CreateQuery(), new PullOptions { MaxPageSize = 200 });

```

However, when I inspect the traffic through Fiddler I see all GET requests happen from the first table before any from the second are initiated.  Then I see all the GET requests from the second table happen before the third.  Since I am not using the await keyword, I was expecting requests from all three tables to be interspersed to indicate they are all being concurrently updated.

What am I doing wrong?  Is there a better way to improve performance?  The goal is to just get these tables to update faster.  Maybe I can retrieve more records per request somehow?  Thanks.

**Comment by MatkovIvan** [comment]
Hi @gonzobrains,

This is by design. If you are interested for details, see usages of:
https://github.com/Azure/azure-mobile-apps-net-client/blob/3e42acee8d955dcdd45923c829e8654ac6b28dff/src/Microsoft.Azure.Mobile.Client/Table/Sync/MobileServiceSyncContext.cs#L33-L36

> Maybe I can retrieve more records per request somehow? 

You can customize page size, but as I see, you already do it. Please note that maximum page size can by limited by server side too.

**Comment by gonzobrains** [comment]
I think I need to increase the page size on the server as well.  It
defaults to 50, right?  What is the design reason for making pulls
sequentially?  In this case, does it matter if I use await or not?

**Comment by gonzobrains** [comment]
Okay, thanks.  What is the recommended maximum?  I'd like to pull as many
as possible for certain tables that will return thousands of records.  I
can customize this on a controller-by-controller basis, right?

How do I get authorization to make PRs?  Do I need an account?

**Comment by MatkovIvan** [comment]
> What is the recommended maximum?

You can experiment with it, but I guess it shouldn't be larger than 1000.

> I can customize this on a controller-by-controller basis, right?

Yes

> How do I get authorization to make PRs?  Do I need an account?

Just use forks https://guides.github.com/activities/forking/
