### ISSUE TITLE
Working disconnected updated local database but leave 'null' for 'Deleted' column (bool type) which fails to return records

### ISSUE THREAD

**Issue by Tuytje** [Azure/azure-mobile-apps-net-client#475]
Everything is working fine when working connected, but in disconnected mode the local database update leaves some fields 'null' even though I have set them. Fields that are left null are CreatedAt (DateTime), UpdatedAt (DateTime), Deleted (bool). This is a problem when trying to use this field in a Where clause, which I do for the deleted. I only want to use the non deleted items (obviously :)). Since the field is set to null this becomes an issue (no errors btw) and it isn't returning those newly added records which in turn looks like the local database isn't updated.

Why are those fields left to 'null' and not the value I have set for them?

**Comment by MatkovIvan** [comment]
Hi @Tuytje,

This is expected behavior. System fields are populated only by the server.

See related questions for details:
* https://github.com/Azure/azure-mobile-apps-net-client/issues/74
* https://stackoverflow.com/questions/39578143

You can use nullable values to filter locally:
```C#
[Deleted]
public bool? Deleted { get; set; }
```
```C#
.Where(i => i.Deleted == false || i.Deleted == null)
```

**Comment by Tuytje** [comment]
I see. 

thank you for the fast response time!
