### ISSUE TITLE
Roadmap for next release

### ISSUE THREAD

**Issue by michaelwda** [Azure/azure-mobile-apps-net-client#476]
Is there a roadmap or timeframe for the next release? I just ran into issue #442 in production and had to build from source and patch so he wasn't stuck unable to sync. Would love to see some of these great fixes make their way to an official release.

Nightly/Beta builds would be interesting too. Maybe something with Azure DevOps?

**Comment by elamalani** [comment]
@michaelwda Unfortunately, we don't plan to release the SDK in the coming weeks. My recommendation would be to fork and build the SDK for now.

**Comment by dhei** [comment]
Hi @michaelwda, 

Sorry for the delay.
We recently released [v4.1.1](https://github.com/Azure/azure-mobile-apps-net-client/releases/tag/4.1.1) which includes a fix to issue #442. Please give it a try.
