### ISSUE TITLE
No way to exclude soft deleted records on initial table sync

### ISSUE THREAD

**Issue by oleksandrmykhaylyshyn** [Azure/azure-mobile-apps-net-client#485]
From performance perspective it makes sense to skip soft deleted records on initial data load since processing of those takes time on the client regardless there is no local data yet (nothing to delete locally). In other words it would be nice to have a mechanism to remove __includeDeleted parameter from url.

**Comment by MatkovIvan** [comment]
Hi @oleksandrmykhaylyshyn,

Adding a new method to configure it is a "feature request" for the SDK. Please refer to the SDK readme that highlights the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). We are not adding new features to the product. I will close this issue for now but feel free to fork the repository and make the changes that you'd like.
Thanks!
