### ISSUE TITLE
Is Azure Mobile App correct for multi app scenario 

### ISSUE THREAD

**Issue by WinInsider** [Azure/azure-mobile-apps-net-client#487]
Conditions:
- Many Native Client apps: UWP, using SSO via OnlineIdAuthenticator class (JWT).
- UWP's app ClientID obtained via apps.dev.microsoft.com
- One Azure Mobile App with *many* "Easy Tables" 

Question
Can *same user* access data stores in Azure "Easy Tables" via Mobile Apps SDK from *different* UWP Client Apps?

**Comment by myokeeh** [comment]
I think the answer is generally "Yes." I use it in a very similar way--Multiple UWP apps with a single Azure Mobile Service (App Service). I have SSO setup initially using MS accounts, then recently switched to Azure AD auth.
