### ISSUE TITLE
use custom sqlite3 build

### ISSUE THREAD

**Issue by mojobec** [Azure/azure-mobile-apps-net-client#489]
i'm trying to integrate a custom build of sqlite3 with [SQLite Encryption Extension](https://www.sqlite.org/see/doc/trunk/www/index.wiki) without success. 
any idea how that can be achieved?

**Comment by MatkovIvan** [comment]
Hi @mojobec,

First of all, could you please give us a little bit more detail about what you are trying to achieve?
It would also be great if you specify what steps you already tried to integrate **Sqlite Encryption Extension.**
Have you tried following [this instruction](https://azure.microsoft.com/en-us/resources/samples/app-service-mobile-dotnet-offline-encryption/)?

Thanks!

**Comment by ericsink** [comment]
In general, using SEE (or any other custom SQLite build) with SQLitePCL.raw is not easy.  Currently, the path is something like: "Look inside SQLitePCL.raw to see how it deals with packing sqlite builds and do something similar."

And the approach is very different on various platforms.  Which platform(s) are you targeting?

**Comment by mojobec** [comment]
@MatkovIvan I tried following that example. 
looks like that example is referencing an earlier version of mobile client before it was updated to use SQLitePCL.raw.

@ericsink I am using [Uno platform](https://github.com/nventive/Uno) that targets iOS, Android,
UWP and Wasm.

@ericsink would you say it's much easier to use sqlcipher instead? (found this [issue](https://github.com/ericsink/SQLitePCL.raw/issues/168) about that)

**Comment by ericsink** [comment]
Wasm?  Hmmm.  I wonder how that's going to work with SQLite.  :-)

Anyway, yes, for SQLitePCL.raw scenarios, sqlcipher is currently easier than SEE.  You can use the nuget package `SQLitePCLRaw.bundle_zetetic` with the actual sqlcipher builds from Zetetic.  I also provide unofficial sqlcipher builds in the package `SQLitePCLRaw.bundle_sqlcipher`.

**Comment by mojobec** [comment]
I only know it works. but how is a mystery for me. 
I'm sure @jeromelaban can help with that if you're interested.

**Comment by mojobec** [comment]
@MatkovIvan I ended up using sqlcipher, closing this issue. 
@ericsink thanks for helping out on this one and in general for all your work in SQLitePCL.raw

**Comment by mojobec** [comment]
@MatkovIvan would you accept a PR removing the reference to `SQLitePCLRaw.bundle_green` that way the users can decide what db to use? 
right now to use sqlcipher i will need to build and maintain my own nuget package for `Microsoft.Azure.Mobile.Client.SQLiteStore` without the bundle_green ref.

**Comment by ericsink** [comment]
Actually, adding something like the following to your app project will probably work:

    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="whatever" ExcludeAssets="All" />
    <PackageReference Include="SQLitePCLRaw.bundle_sqlcipher" Version="whatever" />

The key point is ExcludeAssets.

**Comment by pooran** [comment]
Does this means, SQLCipher works for iOS, Android & UWP @mottibec  ?

**Comment by pooran** [comment]
If you have steps, please share

**Comment by mottibec** [comment]
@pooran yes it does. 
Are you trying to integrate it with the mobile apps client?
If so look at @ericsink comment 
> Actually, adding something like the following to your app project will probably work:
> 
> ```
> <PackageReference Include="SQLitePCLRaw.bundle_green" Version="whatever" ExcludeAssets="All" />
> <PackageReference Include="SQLitePCLRaw.bundle_sqlcipher" Version="whatever" />
> ```
> 
> The key point is ExcludeAssets.

**Comment by myokeeh** [comment]
@mottibec do you also pass the password via querystring or is it different for SQLCipher? I'm getting an invalid format exception for the path.

```
string testDb = uri.AbsoluteUri + "?hexkey=" + ToHexString("password");
store = new MobileServiceSQLiteStore(testDb);
````

**Comment by mottibec** [comment]
@myokeeh no, you pass the password with the following SQL command `PRAGMA key = '{PASSWORD}';`
I had to do some hacking with reflection to get the `sqlite3 connection` object and use it to execute the command

**Comment by myokeeh** [comment]
@mottibec, that's a bit beyond my current knowledge. Any chance you can show me how? Searching to see if I can figure it out in the mean time.

**Comment by mottibec** [comment]
I'm afraid I can't help with that, I no longer have access to the project where I worked on this issue, 
but a good place to start is https://github.com/ericsink/SQLitePCL.raw
