### ISSUE TITLE
Incremental sync uses the ">=" operator for the UpdatedAt field

### ISSUE THREAD

**Issue by FlxGen** [Azure/azure-mobile-apps-net-client#491]
Say I have a table of 1000 customers and I do a bulk update of some field and also set the UpdatedAt field to the current date and time.   I sync a client to get the new updates.

The client stores the last date time of the newest UpdatedAt of the result set to the __config table.  If the server table doesn't change then the client will keep syncing the customer records because the query it creates is "updatedat >= (UpdatedAt record for table stored in __config)".

The question.  Why does the query use >= rather than >?

I'm aware that this question has been asked before but I feel the answers weren't satisfactory.  Given that a large portions of clients are mobile it seems like wasting time (and battery) on needless operations will create negative user experiences.  

I created a method to manually override the values in the config table after a sync and I haven't found any issues yet.  

Please don't mark this as a feature request because I believe this is a bug.  If it's not a bug I'd like to understand the reasoning.  Thanks

**Comment by FlxGen** [comment]
I considered concurrency issues resulting from using greater than.  The client already has all the updates with the greatest UpdatedAt so unless you are sloppy setting the UpdatedAt field, then you shouldn't need to get those records again. 

Since there are no plans to change this behavior, I have developed a work around but there is one issue I can't seem to figure out.  My logic is as follows:

1.  Create QueryId.
2.  PullAsync on table.
3.  Get existing delta token using QueryId from the __config table.
4.  Increase value by one millisecond.

However, this does not work when executing PullAsync back to back.  If you quit the app and then run PullAsync a second time then it works.  Are the __config values handled in memory?  I've been reviewing the source but I can't seem to figure out why this would happen.  

When the above logic does work it drastically reduces sync times, by more than 50%.  If there are no updates to tables the sync time is reduced by more than 80% in my tests.  Assuming concurrency isn't an issue and given those kind of performance increases...I don't see how this isn't a bug.

**Comment by MatkovIvan** [comment]
> The client already has all the updates with the greatest UpdatedAt

When I wrote about "concurrency issues", I meant backend/db, but not just local threads on the client. So, I questioned that statement.

> Are the __config values handled in memory?

[Yes](https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.Azure.Mobile.Client/Table/Sync/MobileServiceSyncSettingsManager.cs#L21)

**Comment by FlxGen** [comment]
That particular class is private when its instantiated so there is no way to flush the cache.  Looks like the only way to get the updates I make the the config table is to re-initialize the store, which is hacky.  

Unless you know of another way I don't think it's possible to work around the >= issue with the existing sdk.

**Comment by FlxGen** [comment]
Can you point me to where the query is created?

**Comment by MatkovIvan** [comment]
The application calls `CreateQuery` method to pass the query to the `PullAsync` method - [Syncing an Offline Table](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#syncoffline)

If you asked about converting this object to an OData string, here:

https://github.com/Azure/azure-mobile-apps-net-client/blob/6ecc4185b3a7c366881dc805ae4b6187a26850df/src/Microsoft.Azure.Mobile.Client/Table/Sync/Queue/Actions/PullAction.cs#L74

**Comment by FlxGen** [comment]
I did end up finding a real bug related to this.  There seems to be a precision issue related to datetime in sqlite.  See the attached image.  All of the values in the table after the 3rd digit in milliseconds are zero. 

Take the two records below.  The top is an UpdatedAt value in my DB.  The other is the value the sdk creates from the deltaToken.  As a result the sdk will unnecessarily update this record. 

2019-02-21 00:27:48.9677333 +00:00

2019-02-21 00:27:48.9670000 +00:00

![untitled](https://user-images.githubusercontent.com/22063606/53136096-49dfde80-3543-11e9-9105-d41692ee92a0.png)

**Comment by MatkovIvan** [comment]
@FlxGen This is a known behavior. It plays fine with ">=" operator. See #466

**Comment by adrianhall** [comment]
Based on discussion, it doesn't look like we have any open issue.  The protocol (while less than ideal) is working as intended.
