### ISSUE TITLE
Is it possible to apply multiple authentication providers?

### ISSUE THREAD

**Issue by Quico20** [Azure/azure-mobile-apps-net-client#492]
I'm new using authentication in fact I'm following Adrian Hall [Social Authentication Tutorial](https://adrianhall.gitlab.io/develop-mobile-apps-with-csharp-and-azure/chapter2/social/) but my question is the following one.

I wish to authenticate with a Facebook, Microsoft, twitter or Google account and acknowledge me as one unique user. I already achive authentication but if I try to authenticate with a different provider I wont be able to see the data stored at my database. I wish to be able to get one unique UserId for the four of them.

Can it be achieve? I would appreciate to point me in the right direction to build a practice app achieving that goal, I dont not work for any company I just code for fun. So I dont know anyone who can help me with this doubt.

**Comment by MatkovIvan** [comment]
Hi @Quico20,

Thanks for getting in touch! Azure Mobile Apps doesn't support this scenario out-of-box. You need to manually create a unique user id and maintain mapping table on the backend to keep track of things.

Thanks,
Ivan

**Comment by Quico20** [comment]
Ok, i dont have no idea how to create a userid manually i suppose it must be at backend project since unique userid is created there, i also read that claims arent supported in custom authentication.
What approach do you guys recommend me?
Should i create custom authentication and then merged it with social authentication, is it posible just to use social authentication and merged all account in one?
And finally is there any book or blog that cover this type of scenario, i really have no idea how to or where to begin?
Anyways i appreciate your answer at least you clear me of that doubt.

**Comment by MatkovIvan** [comment]
> i suppose it must be at backend project

Yes, it should be done on the server side

> is it posible just to use social authentication and merged all account in one?

You can rely on email equality for example. Unfortunately, there are not many docs about it. You can find some piece of information [here](https://github.com/Azure/azure-mobile-apps-net-server/wiki/Understanding-User-Ids). It and provider-specific authentification docs should give you the right direction.

**Comment by Quico20** [comment]
@MatkovIvan I really appreciate your help, I found the documentation very useful, I'll begin to dig more on claims before coming up with the architecture to modify my backend project.
