### ISSUE TITLE
How to handle Done button tap or close authenticator tap of google or facebook authenticator? 

### ISSUE THREAD

**Issue by fazil1979** [Azure/azure-mobile-apps-net-client#495]
Hello,
I need to handle Done or Close button tap in microsoft azure authentication webview.
Actually If I want to complete authentication process by done clicking or want to close the process of login through facebook or google by close tap then there isn't any event to handle this.

MobileServiceClient _client; 
await _client.LoginAsync(UIApplication.SharedApplication.KeyWindow.RootViewController, provider, "uri scheme");

This actually returns MobileServiceClient as result. But If I handle webview by Done or close tapping then there is no event I am getting there. Anyone knows how to handle this ?

![done_handling_issue](https://user-images.githubusercontent.com/2875281/53719161-51787f00-3e83-11e9-8957-08180848ea43.gif)

**Comment by roland-chernov-akvelon** [comment]
Hi @fazil1979,

Sorry for the delay in replying. It's possible to handle done/close tap events using try/catch block. Please take a look at this example: https://github.com/Azure/azure-mobile-apps-net-client/blob/899294bd9bfee1b67dcfc6d703845449733830c7/e2etest/iOS.E2ETest/UI/LoginViewController.cs#L97-L105

When done/close button is tapped then the exception will be thrown saying that login was canceled.

Please let me know if you have any questions.

**Comment by roland-chernov-akvelon** [comment]
@fazil1979, I'm closing this issue as we haven't heard from you for a while. Please feel free to reopen it if you have any questions.
