### ISSUE TITLE
Transaction Support?

### ISSUE THREAD

**Issue by mraswinc** [Azure/azure-mobile-apps-net-client#496]
Hi, 

Would there be any support for transaction in the SDK? The last thread was in 2017 so thought of checking in

Thanks

**Comment by MatkovIvan** [comment]
Hi @mraswinc 

We are not adding new features to the product. Please refer to the SDK readme that highlights the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). I will close this issue for now but feel free to fork the repository and make the changes that you'd like.

Thanks,
Ivan
