### ISSUE TITLE
[Question] Using Certificate  Along with the SDK

### ISSUE THREAD

**Issue by stezma** [Azure/azure-mobile-apps-net-client#498]
![Screenshot 2019-04-05 at 15 31 14](https://user-images.githubusercontent.com/38653526/55631409-3ec1d480-57b8-11e9-9fc8-cf254efe337a.png)

I am using Xamarin Forms along with **microsoft.azure.mobile.client** for implementing offline sync. Recently we have made additional factor (Certificate based validation ) to our Azure mobile app. And I would like to integrate the same to our mobile app.

Could you please let me know how I can share the certificate information using the **microsoft.azure.mobile.client** library

**Comment by annakocheshkova** [comment]
Hi there @stezma. I believe this question is not related to SDK. You can ask on Xamarin forum or Stackoverflow. If this UI is from Azure portal, you can ask for help there.
Thanks!

**Comment by stezma** [comment]
its related to the authentication part of sdk. My question is more specific like, how I can enable Self signed certificate along with login.

**Comment by annakocheshkova** [comment]
@stezma What is the self signed cert used for?
Do you use this certificate for testing purposes? I'm not sure it is safe to use self signed cert for production android app.

**Comment by stezma** [comment]
@annakocheshkova Sorry!!! My bad. It was not self signed certificate. It is certificate provided by some Authority

**Comment by dhei** [comment]
Hi @stezma, 

This repository is used primarily to track issues specifically on Azure Mobile Apps client SDK. The "Protocol Settings" is a feature provided by App Service backend. To get better assistance on this, you may want to post it on azure forum or Stackoverflow.

Thanks.

**Comment by stezma** [comment]
@dhei 
You are crazy,

What is your SDK? 
SDK to consume Azure Mobile Service.

Based on the description in the GitHub page. 

With Azure Mobile Apps you can add a scalable backend to your connected client applications in minutes.

And what was my question. 

The same Azure Mobile Service providing provision for accepting secured certificate.

Being a Xamarin application developer, what I am looking for is. The provision to authenticate Azure Mobile Service using your library with secured certificate.

You are asking me to put question on Azure forum. To implement certificate based auth using the SDK why I need to put question on Azure forum?

You please let me know how I cans send certificate along with Client.

**Comment by annakocheshkova** [comment]
@stezma it is not possible to implement certificate based auth using the Zumo SDK. Sorry for the confusion.

**Comment by rkshnair** [comment]
@annakocheshkova Is there any plan to support Certificate for Zumo SDK in future?

**Comment by MatkovIvan** [comment]
Hi @rkshnair

We are not adding new features to the product. Please refer to the SDK readme that highlights the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps).

Thanks,
Ivan
