### ISSUE TITLE
Microsoft.Azure.Mobile.Client not changing the UpdatedAt value present in the EntityData of Microsoft.Azure.Mobile.Server on enableSoftDelete: true.

### ISSUE THREAD

**Issue by vishwajitshep0815** [Azure/azure-mobile-apps-net-client#499]
I am facing an issue while using Microsoft.Azure.Mobile.Client in my Xamarin.Forms application on below operations.

When I delete a record through the mobile app for a table it performs soft delete and the record gets updated in the SQL Server Table(Hosted on Azure Cloud). But in this scenario, the soft-deleted record does not get it's "UpdatedAt" column value changed. So, when the same record is present on different devices, it is not being deleted from there local storage as the MobileServices is not able to compare the changes in the "UpdatedAt" column because we are using incremental sync for multiple devices. This is hindering the syncing process on multiple devices for my application.
Following are the package details that I have in my project:

Microsoft.Azure.Mobile.Client.SQLiteStore: 4.1.1
Xamarin.Forms: 3.1.0.583944
Further, there is no exception thrown in the sync code written for the mobile sync which using the following steps:
var table = ApplicationSession.CurrentMobileContext.MobileService.GetSyncTable();
await table.PullAsync(tabName, table.CreateQuery(), pushOtherTables: false,
cancellationToken: CancellationToken.None,
pullOptions:new PullOptions{ MaxPageSize =100 }
);
On the server side, we have implemented soft delete using the following steps in the controllers:
protected override void Initialize(HttpControllerContext controllerContext)
{
base.Initialize(controllerContext);
//string databaseName = controllerContext.Request.Headers.GetValues("x-dbname").SingleOrDefault();
//Change 6 Feb 2019
string databaseName = ContextHelper.ConnRequestHandler(controllerContext);
string connectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString.Replace("dbName", databaseName);
ProjectContext context = new ProjectContext(connectionString);
DomainManager = new EntityDomainManager(context, Request, enableSoftDelete: true);
}
We also tried implementing hard delete by setting the "enableSoftDelete" false. This also does not seem to work.
For the workaround, we have added a trigger from backend service to change the "UpdatedAt" values which do not seem to be a proper way to handle the situation as the Microsoft.Azure.Mobile.Client should internal handle this on it own.
If anyone can provide an update or solution for the same as soon as possible that would be really great.

**Comment by annakocheshkova** [comment]
Hi @vishwajitshep0815, I understand your problem, but this seems to me more like backend issue. Could you open a ticket with Azure support?
Meanwhile, updating the record before soft-delete seems fine as a workaround.

**Comment by Jamminroot** [comment]
Hey @vishwajitshep0815, we haven't heard anything from you for quite a while now, so we are going to close the issue. 
Have you any questions, feel free to reopen issue back again.
