### ISSUE TITLE
[QUESTION] Saving to existing offline DB without offline sync

### ISSUE THREAD

**Issue by soooraj** [Azure/azure-mobile-apps-net-client#500]
Is it possible to use the same offline sync db for saving non syn / local table data. In our app we have sync tables and other local tables, I think using two different sqlite tables in the same app is going to be a performance hit. So I there any way we can use the sync table to save local table which doesn't have any relation with server table.

**Comment by annakocheshkova** [comment]
Hi @soooraj, no I don't think it will be possible. Of course you can store local tables using SyncTable, but PushAsync operation will push all the changes in one database to the server. 
If you want to use Azure Client API for storing tables, you can create a separate SyncContext for storing local tables and never push it. But this seems no better solution than just create local db on your own.

**Comment by Jamminroot** [comment]
Hey @sooraj, we haven't heard anything from you for quite a while now, so we are going to close the issue.
Have you any questions, feel free to reopen issue back again.
