### ISSUE TITLE
Possible to give user a choice to change `TableRouteSeparatorName` from `'/tables'` to `'/api'`

### ISSUE THREAD

**Issue by SunnySoldier357** [Azure/azure-mobile-apps-net-client#501]
I want to use my ASP.NET Core project as it is without chaging all the controllers's routes. The controllers use the `'api'` endpoint while the `MobileServiceTable` uses the `'/table'` endpoint. There is a property on the `MobileServiceTable` that defines this separator so would it be possible for this to be changed by the user from either the constructor of the `MobileServiceTable` or the `MobileServiceClient`?

**Comment by MatkovIvan** [comment]
Hi @SunnySoldier357

We are not adding new features to the product. Please refer to the SDK readme that highlights the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). I will close this issue for now but feel free to fork the repository and make the changes that you'd like.

Thanks,
Ivan
