### ISSUE TITLE
[Question] Future of Azure Mobile App Client.

### ISSUE THREAD

**Issue by rkshnair** [Azure/azure-mobile-apps-net-client#502]
I have noticed that, there is a new feature called **App Center Data** [https://docs.microsoft.com/en-us/appcenter/data/](url)has been introduced recently with app center. 

While reading the documentation, I am getting a feel that the new sdk is doing the exactly same functionalities with some additional features that Azure Mobile App SDK provides. 

What is the future plan about **Azure Mobile App Client**?
Is it going to replace by **App Center Data**?
Is there any way we can easily migrate the existing feature that we already developed on top of Azure Mobile App?

And finally, what will be the future of Azure Mobile Apps.

Thanks,
Rakesh

**Comment by fileman** [comment]
hi, not the same functionalities because there are some limitations in the current preview #https://github.com/microsoft/appcenter/issues/400#issuecomment-493787938

**Comment by elamalani** [comment]
@rkshnair We haven't been making any new investment in Azure Mobile Apps. This [link](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps) shares the future of the product. We recently launched Data and Auth services in App Center and those are the next generation mobile backend services for developers to use. We don't have a concrete plan for transition but we would share more details once the plan is finalized.

**Comment by Martin-Stein** [comment]
> @rkshnair We haven't been making any new investment in Azure Mobile Apps. This link shares the future of the product. We recently launched Data and Auth services in App Center and those are the next generation mobile backend services for developers to use. We don't have a concrete plan for transition but we would share more details once the plan is finalized.

is there any documentation how to use it?

Thanks,
Martin
