### ISSUE TITLE
LoginAsync with {"code":401,"message":"IDX10205: Issuer validation failed. Issuer: '[PII is hidden]'. Did not match: validationParameters.ValidIssuer: '[PII is hidden]' or validationParameters.ValidIssuers: '[PII is hidden]'."}

### ISSUE THREAD

**Issue by leeVictor** [Azure/azure-mobile-apps-net-client#507]
Hello 
I got the following error when I calling MobileServiceClient.LoginAsync. 

Error Message:
{"code":401,"message":"IDX10205: Issuer validation failed. Issuer: '[PII is hidden]'. Did not match: validationParameters.ValidIssuer: '[PII is hidden]' or validationParameters.ValidIssuers: '[PII is hidden]'."}

My auth code and configuration of azure are totally same with [Integrating Azure Active Directory B2C with Azure Mobile Apps](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app#client-managed-authentication).

Code as following. I can get the token to build payload. But an error occurred when calling LoginAsync.

				if (User == null)
				{
					var payload = new JObject();
					if (authenticationResult != null && !string.IsNullOrWhiteSpace(authenticationResult.IdToken))
					{
						payload["access_token"] = authenticationResult.IdToken;
					}

					User = await App.DbContext.Connection.LoginAsync(
						MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory,
						payload);
					ObjectId = authenticationResult.UniqueId;
					success = true;
				}

How can I fix this issue? Thank you.

**Comment by MatkovIvan** [comment]
Hi @leeVictor!

It looks like the code sample is incorrect on this page. `AccessToken` should be used instead of `IdToken`.

Please follow the steps from this page instead: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#adal

We'll fix this piece, sorry for the inconvenience.

Thanks,
Ivan

**Comment by leeVictor** [comment]
> Hi @leeVictor!
> 
> It looks like the code sample is incorrect on this page. `AccessToken` should be used instead of `IdToken`.
> 
> Please follow the steps from this page instead: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#adal
> 
> We'll fix this piece, sorry for the inconvenience.
> 
> Thanks,
> Ivan

Thank you for your reply, Ivan.

I need to integrating ADB2C to APP service. And need to use client managed authentication. So the AccessToken always null on my side.

I was referred to this sample to build my code. [TodoAzureAuthADB2CClientFlow](https://developer.xamarin.com/samples/xamarin-forms/WebServices/TodoAzureAuthADB2CClientFlow/)

And referred this documentation to config my Azure. [Integrating Azure Active Directory B2C with Azure Mobile Apps](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app)

As you can see they are both used IdToken. I'm not sure whether use IdToken depends on if integrating ADB2C?

My full of code as follows:
The executed result is thrown a MobileServiceInvalidOperationException. The error message which like I posted before.
```
public async Task<bool> LoginAsync(bool useSilent = false)
		{
			bool success = false;
			try
			{
				AuthenticationResult authenticationResult;
				var accounts = await ADB2CClient.GetAccountsAsync();
				if (useSilent)
				{
					authenticationResult = await ADB2CClient.AcquireTokenSilentAsync(
						App.Scopes,
						GetUserByPolicy(accounts, App.PolicySignUpSignIn),
						App.Authority,
						false);
				}
				else
				{
					authenticationResult = await ADB2CClient.AcquireTokenAsync(
						App.Scopes,
						GetUserByPolicy(accounts, App.PolicySignUpSignIn),
						App.UiParent);
				}
				if (User == null)
				{
					var payload = new JObject();
					if (authenticationResult != null && !string.IsNullOrWhiteSpace(authenticationResult.IdToken))
					{
						payload["access_token"] = authenticationResult.IdToken;
					}

					User = await App.DbContext.Connection.LoginAsync(
						MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory,
						payload);
					ObjectId = authenticationResult.UniqueId;
					success = true;
				}
			}
			catch (MobileServiceInvalidOperationException moe)
			{
				var message = await moe.Response.Content.ReadAsStringAsync();
			}
			catch (Exception ex)
			{
				Console.WriteLine($"Authentication failed! {ex.Message}{ex.StackTrace}{ex.InnerException?.Message}{ex.InnerException?.StackTrace}");
			}

			return success;
		}

```

Looking forward you reply.
Thanks

**Comment by leeVictor** [comment]
> > Hi @leeVictor!
> > It looks like the code sample is incorrect on this page. `AccessToken` should be used instead of `IdToken`.
> > Please follow the steps from this page instead: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#adal
> > We'll fix this piece, sorry for the inconvenience.
> > Thanks,
> > Ivan
> 
> Thank you for your reply, Ivan.
> 
> I need to integrating ADB2C to APP service. And need to use client managed authentication. So the AccessToken always null on my side.
> 
> I was referred to this sample to build my code. [TodoAzureAuthADB2CClientFlow](https://developer.xamarin.com/samples/xamarin-forms/WebServices/TodoAzureAuthADB2CClientFlow/)
> 
> And referred this documentation to config my Azure. [Integrating Azure Active Directory B2C with Azure Mobile Apps](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app)
> 
> As you can see they are both used IdToken. I'm not sure whether use IdToken depends on if integrating ADB2C?
> 
> My full of code as follows:
> The executed result is thrown a MobileServiceInvalidOperationException. The error message which like I posted before.
> 
> ```
> public async Task<bool> LoginAsync(bool useSilent = false)
> 		{
> 			bool success = false;
> 			try
> 			{
> 				AuthenticationResult authenticationResult;
> 				var accounts = await ADB2CClient.GetAccountsAsync();
> 				if (useSilent)
> 				{
> 					authenticationResult = await ADB2CClient.AcquireTokenSilentAsync(
> 						App.Scopes,
> 						GetUserByPolicy(accounts, App.PolicySignUpSignIn),
> 						App.Authority,
> 						false);
> 				}
> 				else
> 				{
> 					authenticationResult = await ADB2CClient.AcquireTokenAsync(
> 						App.Scopes,
> 						GetUserByPolicy(accounts, App.PolicySignUpSignIn),
> 						App.UiParent);
> 				}
> 				if (User == null)
> 				{
> 					var payload = new JObject();
> 					if (authenticationResult != null && !string.IsNullOrWhiteSpace(authenticationResult.IdToken))
> 					{
> 						payload["access_token"] = authenticationResult.IdToken;
> 					}
> 
> 					User = await App.DbContext.Connection.LoginAsync(
> 						MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory,
> 						payload);
> 					ObjectId = authenticationResult.UniqueId;
> 					success = true;
> 				}
> 			}
> 			catch (MobileServiceInvalidOperationException moe)
> 			{
> 				var message = await moe.Response.Content.ReadAsStringAsync();
> 			}
> 			catch (Exception ex)
> 			{
> 				Console.WriteLine($"Authentication failed! {ex.Message}{ex.StackTrace}{ex.InnerException?.Message}{ex.InnerException?.StackTrace}");
> 			}
> 
> 			return success;
> 		}
> ```
> 
> Looking forward you reply.
> Thanks

Hi @MatkovIvan 

Sorry Ivan, After I updated my Azure settings the error became 403.
I think it much like a configuration issue. I'll investigate what config is wrong of azure.

Thank you for your help.

{Microsoft.WindowsAzure.MobileServices.MobileServiceInvalidOperationException: The request could not be completed.  (Forbidden)
  at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient+<ThrowInvalidResponse>d__24.MoveNext () [0x001d2] in <14b3925606b5475b8c7d9d3d44eaca5c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient+<SendRequestAsync>d__26.MoveNext () [0x00121] in <14b3925606b5475b8c7d9d3d44eaca5c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient+<RequestAsync>d__18.MoveNext () [0x000f0] in <14b3925606b5475b8c7d9d3d44eaca5c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient+<RequestWithoutHandlersAsync>d__16.MoveNext () [0x00097] in <14b3925606b5475b8c7d9d3d44eaca5c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.WindowsAzure.MobileServices.MobileServiceAuthentication+<LoginAsync>d__25.MoveNext () [0x00068] in <14b3925606b5475b8c7d9d3d44eaca5c>:0

**Comment by leeVictor** [comment]
> > > Hi @leeVictor!
> > > It looks like the code sample is incorrect on this page. `AccessToken` should be used instead of `IdToken`.
> > > Please follow the steps from this page instead: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#adal
> > > We'll fix this piece, sorry for the inconvenience.
> > > Thanks,
> > > Ivan
> > 
> > 
> > Thank you for your reply, Ivan.
> > I need to integrating ADB2C to APP service. And need to use client managed authentication. So the AccessToken always null on my side.
> > I was referred to this sample to build my code. [TodoAzureAuthADB2CClientFlow](https://developer.xamarin.com/samples/xamarin-forms/WebServices/TodoAzureAuthADB2CClientFlow/)
> > And referred this documentation to config my Azure. [Integrating Azure Active Directory B2C with Azure Mobile Apps](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app)
> > As you can see they are both used IdToken. I'm not sure whether use IdToken depends on if integrating ADB2C?
> > My full of code as follows:
> > The executed result is thrown a MobileServiceInvalidOperationException. The error message which like I posted before.
> > ```
> > public async Task<bool> LoginAsync(bool useSilent = false)
> > 		{
> > 			bool success = false;
> > 			try
> > 			{
> > 				AuthenticationResult authenticationResult;
> > 				var accounts = await ADB2CClient.GetAccountsAsync();
> > 				if (useSilent)
> > 				{
> > 					authenticationResult = await ADB2CClient.AcquireTokenSilentAsync(
> > 						App.Scopes,
> > 						GetUserByPolicy(accounts, App.PolicySignUpSignIn),
> > 						App.Authority,
> > 						false);
> > 				}
> > 				else
> > 				{
> > 					authenticationResult = await ADB2CClient.AcquireTokenAsync(
> > 						App.Scopes,
> > 						GetUserByPolicy(accounts, App.PolicySignUpSignIn),
> > 						App.UiParent);
> > 				}
> > 				if (User == null)
> > 				{
> > 					var payload = new JObject();
> > 					if (authenticationResult != null && !string.IsNullOrWhiteSpace(authenticationResult.IdToken))
> > 					{
> > 						payload["access_token"] = authenticationResult.IdToken;
> > 					}
> > 
> > 					User = await App.DbContext.Connection.LoginAsync(
> > 						MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory,
> > 						payload);
> > 					ObjectId = authenticationResult.UniqueId;
> > 					success = true;
> > 				}
> > 			}
> > 			catch (MobileServiceInvalidOperationException moe)
> > 			{
> > 				var message = await moe.Response.Content.ReadAsStringAsync();
> > 			}
> > 			catch (Exception ex)
> > 			{
> > 				Console.WriteLine($"Authentication failed! {ex.Message}{ex.StackTrace}{ex.InnerException?.Message}{ex.InnerException?.StackTrace}");
> > 			}
> > 
> > 			return success;
> > 		}
> > ```
> > 
> > 
> > Looking forward you reply.
> > Thanks
> 
> Hi @MatkovIvan
> 
> Sorry Ivan, After I updated my Azure settings the error became 403.
> I think it much like a configuration issue. I'll investigate what config is wrong of azure.
> 
> Thank you for your help.
> 
> {Microsoft.WindowsAzure.MobileServices.MobileServiceInvalidOperationException: The request could not be completed. (Forbidden)
> at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient+d__24.MoveNext () [0x001d2] in <14b3925606b5475b8c7d9d3d44eaca5c>:0
> --- End of stack trace from previous location where exception was thrown ---
> at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient+d__26.MoveNext () [0x00121] in <14b3925606b5475b8c7d9d3d44eaca5c>:0
> --- End of stack trace from previous location where exception was thrown ---
> at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient+d__18.MoveNext () [0x000f0] in <14b3925606b5475b8c7d9d3d44eaca5c>:0
> --- End of stack trace from previous location where exception was thrown ---
> at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient+d__16.MoveNext () [0x00097] in <14b3925606b5475b8c7d9d3d44eaca5c>:0
> --- End of stack trace from previous location where exception was thrown ---
> at Microsoft.WindowsAzure.MobileServices.MobileServiceAuthentication+d__25.MoveNext () [0x00068] in <14b3925606b5475b8c7d9d3d44eaca5c>:0

Hi @MatkovIvan 
Please close the issue. This is an azure issue. The solution please see the below:
https://stackoverflow.com/questions/56743496/receiving-403-error-when-accessing-azure-function-app-locked-down-by-azure-ad-b2.

Sorry for waste your time and thank you for your help. Appreciate it.

Thanks

Victor.
