### ISSUE TITLE
Incremental Sync: Avoid redundant requests

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-mobile-apps-net-client#51]
Ported from Azure/azure-mobile-services#680.

The current incremental sync implementation will end up making multiple requests because it uses greater-or-equal on updatedAt. If we update the incremental sync query to use Id as a secondary sort value we can avoid these redundant requests. See Android client for an example implementation.

**Comment by lindydonna** [comment]
This will probably be won't-fix since we are going to change the protocol anyway. @paulbatum Do you agree?

**Comment by adrianhall** [comment]
Tagging Won't Fix since we are looking at protocol changes that will make this moot.
