### ISSUE TITLE
Build does not work in VS 2019

### ISSUE THREAD

**Issue by MichaelStgt** [Azure/azure-mobile-apps-net-client#511]
To get a better understanding of how the code works, I followed the instructions on the Main Project Page to clone the project via git.
After doing the 4 steps described I open up the Microsoft.Azure.Mobile.Client Solution File and try to compile the solution/project.
I get about 1600 error messages saying: "The type or namespace xxx could not be found.
In the dependencies Folder, most of the dependencies for all of the target frameworks are there,  but with an error symbol.
Loading the solution also gives multiple errors telling there is not enough information to restore the nuget packages.
What am I doing wrong?

**Comment by russelarms** [comment]
Hi, thanks for reaching out! Our team will look into this and get back to you soon.

**Comment by artemious7** [comment]
Still can't build in VS 2019

**Comment by MichaelStgt** [comment]
Still cant build in VS 2019 Community Edition, even after following the recommended way

**Comment by ht20200101** [comment]
Still can't build in VS 2019. Followed directions on main page.

**Comment by stefffdev** [comment]
There is a branch that builds in VS2019 https://github.com/Azure/azure-mobile-apps-net-client/tree/fix/vs2019
Just make sure you have the rights SDK's installed.

**Comment by ht20200101** [comment]
Hi ,
  I cloned the branch using the git clone https://github.com/Azure/azure-mobile-apps-net-client.git command as mentioned in the instructions, however it seems to be cloning the non VS2019 version and I am still get thousands of errors on compile. Please send instructions to clone and compile this version.

Thanks.

**Comment by adrianhall** [comment]
We've just merged the VS 2019 work into the master branch - you should be able to build and test with VS 2019 now.  Let us know if that is still not possible and we can work through specific issues.
