### ISSUE TITLE
System.IO.FIleStream is not disposed during file creation

### ISSUE THREAD

**Issue by Artem-Marakhovskyi** [Azure/azure-mobile-apps-net-client#512]
Implementations of `IPlatform` are in charge of ensuring file exists. 
They use `File.Create(String)` method [https://docs.microsoft.com/en-us/dotnet/api/system.io.file.create?view=netframework-4.8#System_IO_File_Create_System_String_](url) for creating file which returns `System.IO.FileStream` and do not call `.Dispose()` method either implicitly or explicitly. 

Android: [https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.Azure.Mobile.Client/Platforms/android/CurrentPlatform.cs#L81](url)
IOS: [https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.Azure.Mobile.Client/Platforms/ios/CurrentPlatform.cs#L81](url)
net45: [https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.Azure.Mobile.Client/Platforms/net45/CurrentPlatform.cs#L61](url)
netstandard 1.4: [https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.Azure.Mobile.Client/Platforms/netstandard14/CurrentPlatform.cs#L62](url)
Not sure about UWP platform (whether it causes any issues).

We've got trapped into the `System.IO.Exception` with "Sharing violation on path ..." after accessing DB file as a simple file into `InitializeAsync()` method of `Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore`. My assumption is that GC didn't collect instance of `System.IO.FileStream` in the memory at that time. Moreover that instance has full access and restricts access to the file.
Reproducability is about 10% as we do not manage GC.

Anyway, I suggest creating file in a following manner: 
`using (File.Create(path)) {}`

**Comment by achocron** [comment]
Hey thanks for pointing this out! I think you are right and I've raised a pull request to address it.
