### ISSUE TITLE
Push Notifications on iOS 13

### ISSUE THREAD

**Issue by MattCrees** [Azure/azure-mobile-apps-net-client#519]
Notifications are broken on iOS 13 using Microsoft.WindowsAzure.MobileServices.Push

I believe the issue is due to the device token passed into RegisterASync(NSData deviceToken) has had its format changed as below:
iOS 12: <124686a5 556a72ca d808f572 00c323b9 3eff9285 92445590 3225757d b83997ba>
iOS13: {length = 32, bytes = 0xd3d997af 967d1f43 b405374a 13394d2f ... 28f10282 14af515f }

Looking at the source in Microsoft.Azure.Mobile.Client.Platforms.ios.Push.Push.cs we have ParseDeviceToken(NSData deviceToken) which returns  
"deviceToken.Description.Trim('<', '>').Replace(" ", string.Empty).ToUpperInvariant();" (line 111)
The above is fine of iOS12 but the new format in iOS means this will not return as expected.

I am unsure if any other changes would be required.

Thanks

**Comment by pauloortins** [comment]
It's happening to me too. Any news about it? @jwallra @dhei

**Comment by jwallra** [comment]
Hi folks, we're planning to release this fix as a part of a release in December.

**Comment by MattCrees** [comment]
Thanks for the update @jwallra

**Comment by MatkovIvan** [comment]
The release of client SDK (4.1.2) with the fix for it is available now.

**Comment by MattCrees** [comment]
Thanks

After calling UIApplication.SharedApplication.RegisterForRemoteNotifications();

public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken) is not called on iOS 13, it is working on iOS 12

Thanks
