### ISSUE TITLE
Azure changed my UserId.

### ISSUE THREAD

**Issue by Quico20** [Azure/azure-mobile-apps-net-client#529]
I've created an app and published it, like 4 years ago.
today when I logged into my app, my userid was for example like this: sid:a4210a7eda89e60251a8cf802f423c78

but now whenever I try to login into my app, it doesnt find my user ID and then prompt me to create a new account for my app, so I create it, and my app stores this info in an azure sql database.

to find out that my new userid is now something like this:
10155645027668686

Ok, so what happened??? why is my mobileapp service at azure dumping my old userid and why has the sid:############# changed?

does anyone know what could have happened?

**Comment by russelarms** [comment]
Hi, @Quico20! Thanks for reaching out, we are looking into it.

**Comment by russelarms** [comment]
What identity provider do you use?

It looks like a backend issue as the SDK does not care about the format of the user id.
I'd suggest opening an azure support ticket with App Service team.

**Comment by ktsakas** [comment]
Could you also provide your tenant and policy id? That would help us correlate with our logs.

**Comment by Quico20** [comment]
> 
> 
> What identity provider do you use?
> 
> It looks like a backend issue as the SDK does not care about the format of the user id.
> I'd suggest opening an azure support ticket with App Service team.

Facebook Identity provider!!

**Comment by adrianhall** [comment]
Closing as this is not an issue with the library (auth and auth user IDs are handled by App Service)
