### ISSUE TITLE
Windows: Support WAB UseCorporateNetwork

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-mobile-apps-net-client#53]
Particularly for AAD->ADFS federations (with server flow), the developer should be able to specify that they want to allow the WAB to interact with ADFS. This requires their app to specify a manifest permission, and the UseCorporateNetwork WebAuthenticationOptions flag must be set. This is currently hidden within LoginAsync().

Workaround is to use ADAL client flow.

**Comment by elamalani** [comment]
Please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK.

Hope this helps. Thanks!
