### ISSUE TITLE
Sniff Login Request to Debug

### ISSUE THREAD

**Issue by rachael-ross** [Azure/azure-mobile-apps-net-client#530]
Hi there, I've seen this post (https://github.com/Azure/azure-mobile-apps-net-client/issues/436), but it only works for "With Handler" requests and not login requests. Is there a way I can capture the request/header values/body to debug an issue we're seeing with Facebook login?

I've installed Charles Proxy on the iPhone device and can see <unknown> web sockets requests, but no readable data pertaining to the request, nor header values. The body is encrypted, of course, so I tried using a non-SSL AlternateLoginHost just to debug my issue. The SDK won't allow that saying it must be SSL. I need a way to isolate the request to determine where our issue lies.

**Comment by russelarms** [comment]
Hi, thanks for getting in touch! 

What error do you get with the Facebook login?

It seems to me that to properly handle that case it would require something like inner logging API inside the library, but we are not currently [investing in any new feature work for Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps).

**Comment by rachael-ross** [comment]
![image](https://user-images.githubusercontent.com/17603150/71425431-927b9300-2651-11ea-8413-bf54bc976b32.png)

**Comment by ktsakas** [comment]
Could you provide us with your tenant and policy id? That would help us correlate without logs.
Feel free to email me at kotsakas@microsoft.com.

**Comment by adrianhall** [comment]
TO DO: Add a mechanism whereby the developer can add DelegatingHandler to the Login Http client, probably by specifying the base HttpClient to use.

**Comment by adrianhall** [comment]
We are updating the client to have a separate authentication flow (you can see the work in azure/azure-mobile-apps).  We will not be fixing this bug in THIS library; rather it will be in the rewrite.
