### ISSUE TITLE
Intermittently getting MobileServicePushStatus.CancelledByAuthenticationError

### ISSUE THREAD

**Issue by myokeeh** [Azure/azure-mobile-apps-net-client#531]
I've got clients that have been getting `CancelledByAuthenticationError` intermittently recently. It seems after some time after the machine being off. Logging off the client and logging back in fixes it. Is there more reason to `CancelledByAuthenticationError`?

This is through AzureAD authentication.

**Comment by russelarms** [comment]
Hi @myokeeh! What is the token TTL configured on the portal?

**Comment by myokeeh** [comment]
@russelarms Sorry, where can I check that in the portal? Also, with MSAL, the client does attempt to refresh the token silently at app startup, and it doesn't seem to fail there.

**Comment by russelarms** [comment]
@myokeeh Are you using AAD or AAD B2C?

You can check it here if you're using aad b2c:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-tokens

We checked but did not encounter this error when we waited offline for about 2 hours.

**Comment by myokeeh** [comment]
@russelarms AAD--not B2C.

I can't figure out what's wrong. It's repeatable on a 4 laptops I have at home.

**Comment by myokeeh** [comment]
Looking at the azure app service, it's logging `401.0 - Unauthorized` whenever this error occurs.

Detailed Error Info:

Module | __DynamicModule_Microsoft.Owin.Host.SystemWeb.OwinHttpModule, Microsoft.Owin.Host.SystemWeb, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35_012a0b12-0fc3-4cca-9cc7-ed9d7bf21b09
-- | --
Notification | PreExecuteRequestHandler
-- | --
Handler | ExtensionlessUrlHandler-Integrated-4.0
-- | --
Logon Method | Anonymous
-- | --
Logon User | Anonymous
-- | --

**Comment by myokeeh** [comment]
It appears requests are getting sent by the client without a token. `mobileServiceClient.CurrentUser` is not `null` (assumed authenticated). Why would a command like below not send the request below with an appropriate header with the token?

```
    await App.syncTableDocumentItem.PullAsync("test",
        App.syncTableDocumentItem4.CreateQuery(),
        false, new CancellationToken(), new PullOptions());

```

**Comment by russelarms** [comment]
@myokeeh Can you check if `mobileServiceClient.CurrentUser.MobileServiceAuthenticationToken` is also not null at that moment?
I've looked through the code and I can't figure out the way it can be null, especially if it worked for a while.

**Comment by myokeeh** [comment]
Correct `MobileServiceAuthenticationToken` also has a value (an unexpired token).

**Comment by myokeeh** [comment]
I've found the culprit. Apparently, the token being used here isn't always valid. Not sure how this has been working, but only failing now.

```
mobileServiceClient.CurrentUser = new MobileServiceUser(passwordCredential.UserName)
    {
        MobileServiceAuthenticationToken = passwordCredential.Password
    };

```
