### ISSUE TITLE
Update packages to be in sync with AppCenter 3.0

### ISSUE THREAD

**Issue by norton287** [Azure/azure-mobile-apps-net-client#533]
The SQLite packages:

SQLite-net-pcl version 1.7.302 and QLitePCLRaw.bundle_green v2

are now used by AppCenter and cause a crash in mobile service sdk on Xamarin.Forms UWP app for me and it seems to be affecting other platforms for other users.

If you are trying to migrate towards using AppCenter like Microsoft wants it would great if we could sample the features of AppCenter like Analytics and Crash reporting on our Mobile Service Client Net apps.

Is it possible to upgrade Apps Net Client to these new SQLite packages so we have some consistancy between where we are now and where we are supposed to be migrating.

Here is the thread on AppCenter:  https://github.com/microsoft/appcenter-sdk-dotnet/issues/1340

**Comment by Jamminroot** [comment]
Thanks for reopening the ticket in a different repo.
I'm closing original issue in dotnet repo now, and I'll let our PM team look at this feature request.

**Comment by myokeeh** [comment]
I would really like this as well. With AppCenter recently canceling their Data solution, those of us still using SQLiteStore are again in search of a new path forward. Until then, I hope Sqlite gets updated on this.

**Comment by myokeeh** [comment]
Please consider this. Thanks!

**Comment by ninaada** [comment]
Is this going to happen? Existing app doesn't seem to build at all, since we have appcenter also, which depends on SQLitePCLRaw v2

**Comment by norton287** [comment]
This should definately happen as Microsoft pushed App Center as the future of mobile development.  Stop stalling and just do  it so we can update App Center and move on.

**Comment by norton287** [comment]
This needs to happen to take advantage of new app center distribution features.  Please move this from feature request to assign to someone to fix.

MAUI is far off and we need this fix now to have our apps take advantage of app center features.

**Comment by adrianhall** [comment]
I've just merged PR #554 which updates all the libraries to the latest versions.  Once released (as v4.2.0 - next couple of weeks), this should be solved.

**Comment by norton287** [comment]
@adrianhall Thank You!
