### ISSUE TITLE
LoginAsync signature changed

### ISSUE THREAD

**Issue by jedicoder88** [Azure/azure-mobile-apps-net-client#535]
Good day,

I have been struggling for 2 days now trying to get authentication working. There is no more 3 parameter constructor, only 2 parameters, with no documentation indicating use:

https://docs.microsoft.com/en-us/previous-versions/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users (completely outdated)

Even worse your documentation as indicated here, show LoginAsync working with 1 paramenter:

https://docs.microsoft.com/en-us/previous-versions/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#serverflow

Please indicate where I can find documentation in using it

**Comment by stefffdev** [comment]
You should have a look at the "zumobook", which is the de-facto documentation for the Azure Mobile Client: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/

Also covers "social authentication".

**Comment by jedicoder88** [comment]
Hi @stefffdev,

Thank you very much!
