### ISSUE TITLE
MobileServiceSQLiteStore failure with encrypted database

### ISSUE THREAD

**Issue by youchen-zhou** [Azure/azure-mobile-apps-net-client#537]
When you create a MobileServiceSQLiteStore, you have to specify the database path.
To access an encrypted database, you have to specify an URI with the password inside the path. An error occurs with the following code, when the constructor of MobileServiceSQLiteStore transforms the path: 

        MobileServiceSQLiteStore(string fileName)
        {
            if (fileName == null)
            {
                throw new ArgumentNullException("fileName");
            }

            if (this.connection == null)
            {
                // Fully qualify the path
                var dbPath = fileName.StartsWith("/") ? fileName : Path.Combine(MobileServiceClient.DefaultDatabasePath, fileName);
                MobileServiceClient.EnsureFileExists(dbPath);

                this.connection = SQLitePCLRawHelpers.GetSqliteConnection(dbPath);
            }
        }

Afterwards, if you specify a file name like so "file:///C:/MyDBPath/test.db?hexkey=passwordinhex", the above code will transform it to "C:\\DefaultBatabasePath\\file:///C:/MyDBPath/test.db?hexkey=passwordinhex", which causes the exception.

Exception: "System.ArgumentException"
Message: "Illegal characters in path."
StackTrace:
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.WindowsAzure.MobileServices.CurrentPlatform.EnsureFileExists(String path)
   at Microsoft.WindowsAzure.MobileServices.MobileServiceClient.EnsureFileExists(String path)
   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore..ctor(String fileName)

**Comment by AnastasiaKubova** [comment]
Hi, @youchen-zhou ! Thanks for getting in touch with us! 
Could you please clarify on the what platform it's happened and what the version of SDK are you use? Also please make sure that you follow to this [guide](https://docs.microsoft.com/en-us/previous-versions/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#work-with-offline-tables) for using our SDK.

**Comment by youchen-zhou** [comment]
Hi, @AnastasiaKubova !
I'm using MobileServiceSQLiteStore 4.1.2, which is executed in .net framework 4.6.1 and built in .net standard 2.0 project. The execution environment is Windows 10.

The guide you are refering to does not use encryption, which is what i need. So I followed this two guides. They essentially instantiate the store in the same way.
[Implementing Client-side Encryption with Azure Mobile Apps](https://azure.github.io/AppService/2016/07/15/Implementing-Client-side-Encryption-with-Azure-Mobile-Apps.html) and [How to use SQLite Encryption Extension with Azure Mobile Apps](https://github.com/Azure-Samples/app-service-mobile-dotnet-offline-encryption)

`var uri = new System.Uri(Path.Combine(ApplicationData.Current.LocalFolder.Path,"testSee.db"));
                string testDb = uri.AbsoluteUri + "?hexkey=" + Utils.ToHexString("Hello");
                var store = new MobileServiceSQLiteStore(testDb);`

**Comment by annakocheshkova** [comment]
@youchen-zhou can you try passing `\MyDBPath\test.db?hexkey=passwordinhex` instead of `file:///C:/MyDBPath/test.db?hexkey=passwordinhex` and see what happens?

**Comment by Jamminroot** [comment]
We haven't heard from you for a while, @youchen-zhou, so I'm closing this issue. Have you any new updates or need you any further assistance, feel free to reopen this ticket.
