### ISSUE TITLE
[Question] Alternative to Azure Mobile App

### ISSUE THREAD

**Issue by rkshnair** [Azure/azure-mobile-apps-net-client#538]
This is related to my previous [Question](https://github.com/Azure/azure-mobile-apps-net-client/issues/502). **Future of Azure Mobile App Client**
During that time, Microsoft was advised to use [App Center Data](https://docs.microsoft.com/en-us/appcenter/migration/data/) as an alternative to **Azure Mobile App**

We kind of planned for the migration end of May, and now I get to know that, **App Center Data** also retired.

![image](https://user-images.githubusercontent.com/3647522/81001433-03288c80-8e48-11ea-9a82-9928fcb7fef0.png)

[Retrial Announcement](https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/)

So what is going to be the replacement for

- Future of Azure Mobile App Client

- App Center Data 

**Also**
Is there any way (Direct or Indirect way) I can create **Mobile App Service** in Azure portal to add few additional feature to my existing app, that is already in production.

We cannot afford multiple different implementation to  achieve the same feature with different logic.

Please advice.

**Comment by Jamminroot** [comment]
Hey!
Thanks for getting in touch. As for the first part - I'll ping our PM team.
As for the second - can you elaborate a bit to make it clearer to me?

**Comment by rkshnair** [comment]
@Jamminroot Thanks for your response.

[As described in this blog](https://www.c-sharpcorner.com/article/create-azure-mobile-apps-service/) is there any way I can create a Mobile App Service through Portal / CLI?

If my understanding is correct MS removed the option to create **Mobile APP Service** - The question was is there any way we can enable this feature again.

**Comment by elamalani** [comment]
@rkshnair App Center Data is retired and there is no replacement to Azure Mobile Apps. We are working on a forward-looking strategy and will share updates once finalized.

**Comment by Jamminroot** [comment]
@rkshnair I'd suggest you reaching out Microsoft Azure support for that case then, might be there is something they can do.

**Comment by rkshnair** [comment]
@elamalani 
What would be your suggestion to the customers, who is already using Azure Mobile Apps in their application (In Production).

We came into situation like we need to create another mobile app service for implementing a new set of features to the existing app. And here is the challenges in terms of app development.

- Few services are already running on existing mobile app service.
- And which is using the SQLite db of the SDK. And we cannot reuse the existing DB (API restriction)
- Since it is an additional feature we don't have the time and bandwidth to introduce something completely new from the scratch.
- Introducing something completely new with existing logic will double the effort, complexity and maintainability of the code.

So what is the advice from MS to existing customers who is facing similar issues.

Please advise us, otherwise we will end up with big trouble.

**Comment by myokeeh** [comment]
I'm also in the same boat of having LOB apps in production and in limbo. I've heard recommendations to use CosmosDB, but there's the missing piece of offline syncing with SQLiteStore. I wish the team would take all that is good in this SDK and use it on top of CosmosDB.

**Comment by ninaada** [comment]
Even we are facing the same issue. We have an app on the stores running for 3 years now. Now, we wanted to create new servers for different locations, but the project doesn't work when deployed fresh to a new server and database. The database remains empty and seed method also doesn't run. Is there any alternative for this SDK ? Even AppCenter Data seems to be retired.

**Comment by pooran** [comment]
@MatkovIvan Please give us some inkling on how to create a live sync server on SQL Azure. 
@yorek was going through your post on data change tracking on SQL Azure. Is it in line with Azure Mobile App Service?

Even if you give us a script to run on normal SQL Azure as part of this repo, to make it compatible with Azure Mobile App SDK, it would be great. There must be some scripts that surely would have run while creating a Azure Mobile App - SQL Azure instance. Please share those scripts.

**Comment by yorek** [comment]
@pooran I need your help here as I really don't know what Azure Mobile App Service is/was doing. Maybe someone from the Azure Mobile App Service can connect with me to see what can be done?

**Comment by myokeeh** [comment]
@yorek's [post](https://medium.com/microsoftazure/an-amazingly-simple-solution-for-mobile-apps-to-sync-with-the-cloud-c1801189f61b) also piqued my interest when I saw it.

@yorek, I think Azure Mobile App Service overlapped what you discussed in that post except, for one, it doesn't make use of the change tracking in SQL Azure and it can have other backends (MySQL, PostgreSQL(?)). For me, one thing it simplified is the offline sync capability with SQLite.

**Comment by sameertotey** [comment]
> @pooran I need your help here as I really don't know what Azure Mobile App Service is/was doing. Maybe someone from the Azure Mobile App Service can connect with me to see what can be done?

Azure Mobile App Service was a flavor of Azure Web API app with SDK to help mobile apps.  We had database sync functionality built-in very similar to what you have explained in the Azure SQL Change Tracking sample.  Please refer to this book from Adrian Hall, we build our LOB app using this book at the reference https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/

**Comment by yorek** [comment]
Thanks @sameertotey. I noticed you used the past tense...Is the Azure Mobile App Service not available anymore? Would make sense to create a (maybe community) effort to have an SDK that take advantage of Azure SQL Change Tracking and that also help on the offline side?

**Comment by sameertotey** [comment]
@yorek Azure Mobile App Service is still out there, but is not being invested in by Microsoft. Like people on this thread have been saying, Microsoft has removed the templates to create a Azure Mobile Service from Azure, templates from Visual Studio 2019 are gone as well. We have to keep Visual Studio 2017 around to debug Azure Mobile App services, so tooling to support this eco-system is falling behind.
So existing services work fine, but it is a hassle to create a new Azure Mobile App Service, my guess is the abstractions that mobile apps provided were nice but were starting to get hard to support and bug prone.

There are alternate options available now to do what Azure Mobile Apps used to do:
- We can use Azure notifications hub for sending Push notifications
-We can use CosmosDB for data storage needs for certain mobile apps where it makes sense.

Azure SQL Change Tracking as you explained in your sample is very useful for syncing mobile devices, if we apply some additional conventions like using GUID as the primary key and develop procedures for syncing client changes and develop conventions for handling conflicts, we can also add the ability to create data on mobile devices when offline.  I think it might be more beneficial initially to create samples of this pattern.

**Comment by stefffdev** [comment]
We are in the same boat, have some Azure Mobile Apps in production and some in the pipeline.

Under massive customer pressure we created our own database sync framework for our apps and open-sourced it lately.
There is a blog post if anyone's interested: [https://www.lakedice.com/?p=14](https://www.lakedice.com/?p=14)

**Comment by ltaljaard** [comment]
Well done @stefffdev. I can't believe MS leaves a gaping hole like this in their cloud offering. We have moved on to AWS Datastore: [https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js](url)

**Comment by OPunktSchmidt** [comment]
The discontinued development of Azure Mobile apps causes us headaches. We are a small development team and have an app that uses mobile apps. We cannot afford to migrate to another solution within the next 2 years.

All other solutions we have found often cannot be connected to existing SQL databases. Many solutions are also especially suitable for NoSQL only. However, we have an existing SQL - database. We cannot simply create an extra database just for the app.

If anyone else has found an alternative to the Azure Mobile apps that can communicate with an existing SQL database, we would be very grateful!

@stefffdev That sounds promising! However, we are also concerned about the long-term support. Do you plan to support your solution for the next years?

**Comment by stefffdev** [comment]
We are still in early development but will use this framework for apps with a lifespan of 10+ years, so maintenance of the sync framework is necessary anyway.

But keep in mind that transitioning to a different sync framework is never trivial, especially if you want to avoid a hard break for your users and support also older versions of the mobile app!

**Comment by OPunktSchmidt** [comment]
> But keep in mind that transitioning to a different sync framework is never trivial, especially if you want to avoid a hard break for your users and support also older versions of the mobile app!

Yes, this is a decision that requires careful consideration. However, we have to prepare for the scenario that Microsoft Azure Mobile apps will shut down or fail to fix a critical bug in new Android and iOs versions.

**Comment by adrianhall** [comment]
We are committed to supporting this library, and are just about to release an updated version - v4.2.0 - (which we just checked into master as PR #554) - that updates library support to .NET Standard 2.0, and the latest iOS and Android releases.

In addition, all our code is open source.  This allows you to fork and get your own copy of the sync framework.
