### ISSUE TITLE
Problem with UIWebView

### ISSUE THREAD

**Issue by douglasilva** [Azure/azure-mobile-apps-net-client#539]
There is a problem regarding a dependency on this package with UIWebView. Someone managed to solve?

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted.

**Comment by russelarms** [comment]
Hi! It seems to be related to https://developer.apple.com/news/?id=12232019b
I'll notify the team about the problem.

**Comment by crm-graeme** [comment]
Are there any updates on this?  Or a work around?  I am unable to get any builds approved by Apple, and the only reference to UIWebView seems to come from this package.

**Comment by Bejasc** [comment]
@russelarms is there any update on this? 
December is quickly approaching and so far it seems that this package has not been updated to accommodate for these changes. 
This is a serious issue and there is so far no response.

### Relevant Links
https://docs.microsoft.com/en-us/xamarin/ios/release-notes/13/13.16#help-with-uiwebview-deprecation
https://github.com/xamarin/Xamarin.Forms/issues/9823
https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/


@crm-graeme @dougsilva1 have you had any luck getting around this issue on any of your recent publishes?

**Comment by adrianhall** [comment]
I've just merged PR #554 which updates the auth view to use Xamarin.Essentials.  This fixes this issue (or rather, it delegates it to the Xamarin.Essentials library, which is included in all new Xamarin projects).  We will be releasing the new library as v4.2.0 in the next couple of weeks.
