### ISSUE TITLE
Is this project still developed?

### ISSUE THREAD

**Issue by Mikilll94** [Azure/azure-mobile-apps-net-client#540]
Is this project still developed?

On the main page, it is written:

> Supported platforms
> .NET Standard 1.4
> Xamarin Android for API 19 through 24 (KitKat through Nougat)
> Xamarin iOS for iOS versions 8.0 through 10.0
> Xamarin.Forms (Android, iOS and UWP)
> Universal Windows Platform
> Other versions may work. We do not test them and thus cannot support them.

So what about newer versions of Android and iOS? What is the future of this project? I want to implement an offline sync functionality for my Xamarin.Forms app but I can't find any reasonable solutions.

**Comment by MatkovIvan** [comment]
Hi @Mikilll94,

> So what about newer versions of Android and iOS?

They should work, please file an issue if you're facing with the issues.

> What is the future of this project?

The answer is right in the readme:

> ### Future of Azure Mobile Apps
>
> Microsoft is committed to fully supporting Azure Mobile Apps, including support for the latest OS release, bug fixes, documentation improvements, and community PR reviews. Please note that the product team is not currently investing in any new feature work for Azure Mobile Apps. We highly appreciate community contributions to all areas of Azure Mobile Apps.

I'm closing this issue, but feel free to reopen/reply if you have more questions.

**Comment by Mikilll94** [comment]
@MatkovIvan 
Ok. So if newer versions of Android and iOS are working then you should update README file.

Because when someone reads:

> Supported platforms
> .NET Standard 1.4
> Xamarin Android for API 19 through 24 (KitKat through Nougat)
> Xamarin iOS for iOS versions 8.0 through 10.0
> Xamarin.Forms (Android, iOS and UWP)
> Universal Windows Platform
> Other versions may work. We do not test them and thus cannot support them. 

then they think that this project is no longer supported.
