### ISSUE TITLE
SQLitePCLRaw Updated with Breaking Changes

### ISSUE THREAD

**Issue by tomeverin** [Azure/azure-mobile-apps-net-client#542]
Azure.Mobile.Client.SQLiteStore needs to be updated for compatibility with SQLitePCLRaw.bundle_green > 2.0

https://github.com/ericsink/SQLitePCL.raw/blob/master/v2.md#source-level-breaking-changes

**Comment by MatkovIvan** [comment]
Duplicate of #533
