### ISSUE TITLE
Microsoft.Azure.Mobile.Client v. 4.2.0 crashes on Android when canceling login

### ISSUE THREAD

**Issue by DA-VDCT** [Azure/azure-mobile-apps-net-client#563]
As reported here on Xamarin forum [(link)](https://docs.microsoft.com/en-us/answers/questions/422025/android-app-crashes-when-user-cancels-login-with-a.html), the LoginAsync() method crashes when user cancels a login on Android, and chooses to login again.
This worked fine on v. 4.1.2 though an exception was caught upon canceling each login, but now on 4.2.0 the whole app just shuts down.

 ```
   try
                         {
                             MobileServiceUser user = await MyApp.App.Client.LoginAsync(this, MobileServiceAuthenticationProvider.Facebook, "myApp");
                         }catch(InvalidOperationException e)
                         {
                             //doesnt hit the exception when canceling
                             return false;
                         }
```

**Comment by adrianhall** [comment]
Closing as it has been > 30 days without an update.
