### ISSUE TITLE
Quickstart Link Broken

### ISSUE THREAD

**Issue by adamhill** [Azure/azure-mobile-apps-net-client#565]
The Quickstart link at the bottom of the Readme.md is broken. It points to:

[Quickstarts](https://github.com/Azure/azure-mobile-apps-quickstarts)

**Comment by adrianhall** [comment]
Thanks Adam.  Will fix. 

In the interim, you can check out the new quickstarts in our new combined repo azure/azure-mobile-apps

**Comment by adrianhall** [comment]
Fixed via PR.
