### ISSUE TITLE
Duplicate updateAt for many records (more than 1 page) causes issues on initial Pull

### ISSUE THREAD

**Issue by tomysaw** [Azure/azure-mobile-apps-net-client#567]
Hi! On the server-side, we're setting updatedAt for some table within a batch action so sometimes it happens that many records get the same value. Our pageSize option is 800 and as updatedAt is the only sort parameter, obviously paged pull doesn't work well as db doesn't guarantee the same sorting each time. Unfortunately, we can't quickly update to the latest versions both client and server and I'm not sure if this issue has been ever resolved. But can you think of any workaround we can come up with? UpdatedAt is basically not unique by its nature and we have no easy way to include additional sorting parameters like "id" which would solve an issue... 

Thanks!

**Comment by adrianhall** [comment]
Per our offline conversation, the expectation is that updatedAt is set by the server, not a client application.  The current client does not expect multiple records to have the same updatedAt field, let alone hundreds.  You will have to update your methodology (as you verified) to compensate.

Future builds will be happening on the azure/azure-mobile-apps repository, where we have discussion boards for questions.  Please direct future discussions there.

Thanks!
