### ISSUE TITLE
DefaultContractResolver.CreateObjectContract System.InvalidOperationException with properties of base class

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps-net-client#569]
We have found that the issue described in ticket https://github.com/Azure/azure-mobile-apps-net-client/issues/546 appears when the types used to query concurrently against the backend have the same base class. We have a base class in the client side with all common properties (Id, CreatedAt, UpdatedAt, Version, etc.), and all our DataModel classes derive from this base class. The exception always occurs in this line with the properties defined in the base class:

`var memberInfo = relevantProperties.Single(x => x.Value == property).Key;`

The relevantProperties dictionary has a property with the same name, but the JsonProperty instance is not the same returned by CreateProperties so the where clause is not true and it returns null. We have changed the instance comparison with a property name comparison and this has solved the issue:

`var memberInfo = relevantProperties.Single(x => x.Value.PropertyName == property.PropertyName).Key;`

[stacktrace.txt](https://github.com/Azure/azure-mobile-apps-net-client/files/8155488/stacktrace.txt)

**Comment by adrianhall** [comment]
Funnily enough, when I was working on the new client (which is over at azure/azure-mobile-apps) - I put in this exact modification.  So you should be set once the 5.x client gets released.

**Comment by asierpn** [comment]
It's good to know that the issue has beed fixed in the new client and that the release date is closer.
