### ISSUE TITLE
Strong Name Microsoft.Azure.Mobile.Client

### ISSUE THREAD

**Issue by jmecosta** [Azure/azure-mobile-apps-net-client#570]
hi,

Cant use this library
1>CSC : error CS8002: Referenced assembly 'Microsoft.Azure.Mobile.Client, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
1>CSC : error CS8002: Referenced assembly 'Microsoft.WindowsAzure.Mobile.Files, Version=2.0.0.352, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Since this is library code, the expected is that all those are strong name to facilitate its use accross more deployment scenarios (ours, enterprise app that requires strong name all stuff)

thanks in advance
jorge costa

**Comment by adrianhall** [comment]
We are not developing this library any further.  All future development is done over on azure/azure-mobile-apps.  There, the new libraries have Microsoft.Datasync.Client and Microsoft.AspNetCore.Datasync (depending on whether you are dealing with the client or server).
