### ISSUE TITLE
IMobileServiceTable leaks concrete implementation

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-mobile-apps-net-client#58]
IMobileServiceTable.MobileServiceClient should be of type IMobileServiceClient, otherwise mocking client SDK calls is very painful.

See:
https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices/Table/IMobileServiceTable.cs#L20

This was an unfortunate oversight that is now a breaking change to fix.

**Comment by pragnagopa** [comment]
Concrete implementation of MobileServiceClient has following internal members:
 internal MobileServiceHttpClient HttpClient { get; private set; }
 internal MobileServiceSerializer Serializer { get; set; }
which are used in multiple places. 

For example, see
https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices/Table/MobileServiceTable.cs#L374
https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices/Table/Query/Linq/MobileServiceTableQueryProvider.cs#L100

Changing IMobileServiceTable.MobileServiceClient to IMobileServiceClient will require adding additional interfaces for MobileServiceHttpClient and MobileServiceSerializer . As these are internal classes right now, adding interfaces will expose them as public APIs.

**Comment by elamalani** [comment]
Please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK. Thanks!
