### ISSUE TITLE
Does it support Azure Active Directory B2C Authentication now?

### ISSUE THREAD

**Issue by amanoharan** [Azure/azure-mobile-apps-net-client#61]
We started to move our website to Azure AD B2C only to realize that 2.0.0-beta-3 did not support that method. Does this version support it now? If not, is it possible to extend this library to custom implement AAD B2C authentication?

Our mobile application uses AAD, but that results in login ids requiring an unnatural "@mydomain.com" suffix, counter intuitive for the user since it looks like an email address but its not.

Is there a timeline for that to be available?
https://azure.microsoft.com/en-us/documentation/articles/active-directory-b2c-overview/

**Comment by adrianhall** [comment]
Thanks for the feature request.  This is already posted on our UserVoice - feedback.azure.com - so I'm closing it here.  The UserVoice will be updated when the feature is complete.  Please feel free to vote on the UserVoice.  Link is here: https://feedback.azure.com/forums/216254-mobile-apps/suggestions/11355411-add-support-for-aad-b2c
