### ISSUE TITLE
Remove resources file

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-mobile-apps-net-client#67]
We stopped using a resource file in the SDK a while ago (I believe it was due to some obscure windows phone bug but forget the details). However the resource file was never removed completely and so usages of it keep creeping back in to the code base.

We need to remove the resource file completely and fix any instances where strings from the resource file are used in the code base.

**Comment by pvyhlas** [comment]
I think this causes crash after calling Client.Login(MicrosoftAccountProvider); on Win mobile 10
this exception is thrown
'System.IO.FileNotFoundException' in mscorlib.ni.dll

**Comment by elamalani** [comment]
Please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK. Thanks!
