### ISSUE TITLE
LookupAsync() with ID containing colon is not URL encoded as expected

### ISSUE THREAD

**Issue by gc435** [Azure/azure-mobile-apps-net-client#94]
Calling `LookupAsync()` with an ID containing a colon does not behave as expected.  For example:

```
string id = "abc:xyz";
var item = await table.LookupAsync(id);
```

This appears to result in a call to a URI like this:

https://example.azurewebsites.net/tables/TodoItem/abc:xyz

This results in a 400 error: Bad Request.

If I urlencode `id` before passing it to `LookupAsync()`, the argument gets urlencoded again when `LookupAsync()` calls `GetUri()` in the SDK source.  This results in the wrong ID being queried.

Should IDs with colons be handled properly by `LookupAsync()`?

**Comment by gc435** [comment]
By the way, in the above example `table` is an `IMobileServiceTable<TodoItem>`, not an `IMobileServiceSyncTable<TodoItem>`.  A colon seems to be parsed correctly when using the latter, but not the former, at least in my code.

**Comment by shrishrirang** [comment]
The ID passed to MobileServiceTable::LookupAsync() should be URL encoded. The URL value in the debugger watch window can be URL encoded or decoded depending on what property of Uri you are looking at. Try checking the URL in Fiddler instead. 

If the ID value in Fiddler is not URL encoded, can you try calling ID values with other special characters and share what URLs you see? Also it would be useful to know the version of the Azure Mobile Client you are using.

**Comment by csotomon** [comment]
Hi, I have the same issue. whit the 2.1.0 version.

**Comment by csotomon** [comment]
I tryed with another URL encoded special characteres and they works perferct, the unique problem is with the **:** (%3A encoded) character

**Comment by lindydonna** [comment]
@shrishrirang @dihei or @pragnagopa Could you see if the issue should be reopened?

**Comment by csotomon** [comment]
Hi, any news about this issue?

**Comment by dhei** [comment]
@csotomon Which backend do you use, .NET or Node? I couldn't repo this with my .NET backend.

**Comment by csotomon** [comment]
.net

**Comment by dhei** [comment]
@csotomon I am not able to repo this, would you mind sharing a code snippet for repo purpose?

**Comment by csotomon** [comment]
Ok, i'll share my private repo with U at night.

Enviado desde mi Windows Phone
________________________________
De: Di Hei<mailto:notifications@github.com>
Enviado el: ‎07/‎09/‎2016 12:48 p. m.
Para: Azure/azure-mobile-apps-net-client<mailto:azure-mobile-apps-net-client@noreply.github.com>
CC: Camilo Soto Montoya<mailto:csotomon@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [Azure/azure-mobile-apps-net-client] LookupAsync() with ID containing colon is not URL encoded as expected (#94)


@csotomon<https://github.com/csotomon> I am not able to repo this, would you mind sharing a code snippet for repo purpose?
