### ISSUE TITLE
Confusing - SID Claim missmatch on Client and Server for Push Notification

### ISSUE THREAD

**Issue by brisebois** [Azure/azure-mobile-apps-net-client#96]
On the client 'MobileService.CurrentUser.UserId` is returning the "**stable_sid**" claim value after authentication.

When we register a user for PushNotifiaction, the "**http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier**" is used as the _UserId tag.

This was confusing for me as I was expecting to use the same sid on both client and servicer. To trouble shoot why I was not able to send Push Notifications to specific users I had to dive deep into the code to finally find the miss match.

**Comment by dhei** [comment]
@soninaren, can you help answer this question?

**Comment by adrianhall** [comment]
If we have an answer that needs to be documented, please add the documentation tag and assign to me after commenting with the answer.  I'll update the docs.

**Comment by shrishrirang** [comment]
@brisebois https://github.com/Azure/azure-mobile-services/issues/883 has details of this bug and a possible resolution.

@adrianhall WEBSITE_AUTH_HIDE_DEPRECATED_SID isn't documented currently. Check with @brettsam if we are ready for documenting it.
